import { useCallback } from 'react';
import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arCmsSupplement: PhraseMap = {
  'Referenced by': 'مُشار إليه من', 'Collection settings': 'إعدادات المجموعة', 'Collection slug': 'مسار المجموعة', 'Entry slug field': 'حقل مسار الإدخال', 'Referenced collection': 'المجموعة المرتبطة', 'Duplicate entry': 'نسخ الإدخال', 'This entry is referenced by other CMS content': 'هذا الإدخال مرتبط بمحتوى CMS آخر', 'Matching published entries': 'الإدخالات المنشورة المطابقة', 'Remove filter': 'إزالة الفلتر', 'Add filter': 'إضافة فلتر',
  'Import / Export': 'استيراد / تصدير', 'Import collection': 'استيراد مجموعة', 'Export collection': 'تصدير المجموعة', 'Export JSON': 'تصدير JSON', 'Export CSV': 'تصدير CSV', 'Import JSON': 'استيراد JSON', 'Import CSV': 'استيراد CSV', 'JSON · CSV': 'JSON · CSV', 'Import preview': 'معاينة الاستيراد', 'Replace collection': 'استبدال المجموعة', 'Append entries': 'إضافة الإدخالات', 'Field mapping': 'ربط الحقول', 'Duplicate handling': 'معالجة التكرار', 'Skip duplicates': 'تخطي المكررات', 'Update duplicates': 'تحديث المكررات', 'Import validation failed': 'فشل التحقق من الاستيراد', 'Import complete': 'اكتمل الاستيراد', 'Preview and validate imported content before changing the project.': 'عاين المحتوى المستورد وتحقق منه قبل تغيير المشروع.', 'Import file is too large': 'ملف الاستيراد كبير جدًا', 'Imported collection': 'مجموعة مستوردة', 'Import as new collection': 'استيراد كمجموعة جديدة', 'Apply import': 'تطبيق الاستيراد', 'Import file does not contain a CMS collection.': 'ملف الاستيراد لا يحتوي على مجموعة CMS.', 'Imported collection has no valid fields.': 'المجموعة المستوردة لا تحتوي على حقول صالحة.', 'Some fields were skipped because the collection field limit was reached.': 'تم تخطي بعض الحقول بسبب بلوغ الحد الأقصى لحقول المجموعة.', 'Some entries were skipped because the collection entry limit was reached.': 'تم تخطي بعض الإدخالات بسبب بلوغ الحد الأقصى لإدخالات المجموعة.', 'Some columns were skipped because the collection field limit was reached.': 'تم تخطي بعض الأعمدة بسبب بلوغ الحد الأقصى لحقول المجموعة.', 'CSV file is empty.': 'ملف CSV فارغ.', 'CSV file has no usable field columns.': 'ملف CSV لا يحتوي على أعمدة حقول قابلة للاستخدام.', 'CSV contains an unterminated quoted value.': 'يحتوي ملف CSV على قيمة مقتبسة غير مغلقة.', 'CMS collection limit reached.': 'تم بلوغ الحد الأقصى لمجموعات CMS.',
  'Multilingual CMS content': 'محتوى CMS متعدد اللغات', 'Add language-specific values and slugs. Missing translations automatically use the default CMS value.': 'أضف قيمًا ومسارات خاصة بكل لغة. تستخدم الترجمات الناقصة قيمة CMS الافتراضية تلقائيًا.', 'CMS collection': 'مجموعة CMS', 'CMS entry': 'إدخال CMS', 'Content language': 'لغة المحتوى', 'Add an entry before creating translations.': 'أضف إدخالًا قبل إنشاء الترجمات.', 'Copy default values': 'نسخ القيم الافتراضية', 'Use default fallback for every field': 'استخدام القيم الافتراضية لكل الحقول', 'Use fallback': 'استخدام القيمة الافتراضية', 'Fallback': 'القيمة الاحتياطية', 'Empty': 'فارغ', 'This collection has no localizable fields.': 'لا تحتوي هذه المجموعة على حقول قابلة للترجمة.',
  'AI CMS assistant': 'مساعد CMS بالذكاء الاصطناعي', 'Review first': 'مراجعة أولًا', 'AI plans CMS changes for review. New entries stay drafts and CMS content is never deleted automatically.': 'يخطط الذكاء الاصطناعي لتغييرات CMS كي تراجعها أولًا. تبقى الإدخالات الجديدة كمسودات ولا يُحذف محتوى CMS تلقائيًا.', 'Describe CMS changes, entries, views, or translations…': 'صف تغييرات CMS أو الإدخالات أو العروض أو الترجمات…', 'Plan with AI': 'خطط بالذكاء الاصطناعي', 'Planning…': 'جارٍ التخطيط…', 'Review AI CMS plan': 'راجع خطة CMS بالذكاء الاصطناعي', 'Operations': 'العمليات', 'Cancel plan': 'إلغاء الخطة', 'Apply reviewed plan': 'تطبيق الخطة المراجعة', 'Applied CMS operations': 'عمليات CMS المطبقة', 'warnings': 'تحذيرات', 'No safe CMS operations were returned.': 'لم يُرجع الذكاء الاصطناعي عمليات CMS آمنة.', 'Describe the CMS changes you want first.': 'صف أولًا تغييرات CMS التي تريدها.', 'AI returned an invalid CMS plan.': 'أعاد الذكاء الاصطناعي خطة CMS غير صالحة.', 'CMS AI planning failed.': 'فشل تخطيط CMS بالذكاء الاصطناعي.', 'CMS AI plan could not be applied.': 'تعذر تطبيق خطة CMS بالذكاء الاصطناعي.',
  'Live collaborators': 'المتعاونون المباشرون', 'Live cursor': 'المؤشر المباشر', 'Editing this element': 'يحرر هذا العنصر', 'Editing conflict': 'تعارض في التحرير', 'Another collaborator is editing this element': 'متعاون آخر يحرر هذا العنصر', 'Version comparison': 'مقارنة الإصدارات', 'Selective restore': 'استعادة انتقائية', 'Added': 'مضاف', 'Removed': 'محذوف', 'Changed': 'معدّل',
  'Manage multilingual content, routes, SEO, RTL and locale domains.': 'إدارة المحتوى متعدد اللغات والمسارات وتحسين محركات البحث واتجاه RTL ونطاقات اللغات.', 'Editing language': 'لغة التحرير', 'Direction': 'اتجاه الكتابة', 'Fallback language': 'اللغة الاحتياطية', 'Locale path prefix': 'بادئة مسار اللغة', 'Subdomain': 'النطاق الفرعي', 'Localized page name': 'اسم الصفحة المترجم', 'Localized slug': 'المسار المترجم', 'Translating…': 'جارٍ الترجمة…', 'Translate page with AI': 'ترجمة الصفحة بالذكاء الاصطناعي',
  'Integrations': 'التكاملات', 'Connect analytics, payments, email, CRM, APIs and signed webhooks.': 'اربط التحليلات والمدفوعات والبريد الإلكتروني وإدارة علاقات العملاء وواجهات API وخطافات الويب الموقعة.', 'Provider': 'المزوّد', 'Add integration': 'إضافة تكامل', 'active': 'نشط', 'configuration issue': 'مشكلة في الإعداد', 'configuration issues': 'مشكلات في الإعداد', 'Enabled': 'مفعّل', 'Name': 'الاسم', 'Environments': 'البيئات', 'Events': 'الأحداث', 'Configured — enter to replace': 'تم الإعداد — أدخل قيمة للاستبدال', 'Testing…': 'جارٍ الاختبار…', 'Test connection': 'اختبار الاتصال', 'Remove': 'إزالة',
};

export const svCmsSupplement: PhraseMap = {
  'Referenced by': 'Refereras av', 'Collection settings': 'Samlingsinställningar', 'Collection slug': 'Samlingsslug', 'Entry slug field': 'Slugfält för post', 'Referenced collection': 'Refererad samling', 'Duplicate entry': 'Duplicera post', 'This entry is referenced by other CMS content': 'Den här posten refereras av annat CMS-innehåll', 'Matching published entries': 'Matchande publicerade poster', 'Remove filter': 'Ta bort filter', 'Add filter': 'Lägg till filter',
  'Import / Export': 'Import / Export', 'Import collection': 'Importera samling', 'Export collection': 'Exportera samling', 'Export JSON': 'Exportera JSON', 'Export CSV': 'Exportera CSV', 'Import JSON': 'Importera JSON', 'Import CSV': 'Importera CSV', 'JSON · CSV': 'JSON · CSV', 'Import preview': 'Förhandsgranska import', 'Replace collection': 'Ersätt samling', 'Append entries': 'Lägg till poster', 'Field mapping': 'Fältmappning', 'Duplicate handling': 'Dubbletthantering', 'Skip duplicates': 'Hoppa över dubbletter', 'Update duplicates': 'Uppdatera dubbletter', 'Import validation failed': 'Importvalideringen misslyckades', 'Import complete': 'Importen är klar', 'Preview and validate imported content before changing the project.': 'Förhandsgranska och validera importerat innehåll innan projektet ändras.', 'Import file is too large': 'Importfilen är för stor', 'Imported collection': 'Importerad samling', 'Import as new collection': 'Importera som ny samling', 'Apply import': 'Tillämpa import', 'Import file does not contain a CMS collection.': 'Importfilen innehåller ingen CMS-samling.', 'Imported collection has no valid fields.': 'Den importerade samlingen har inga giltiga fält.', 'Some fields were skipped because the collection field limit was reached.': 'Vissa fält hoppades över eftersom fältgränsen för samlingen nåddes.', 'Some entries were skipped because the collection entry limit was reached.': 'Vissa poster hoppades över eftersom postgränsen för samlingen nåddes.', 'Some columns were skipped because the collection field limit was reached.': 'Vissa kolumner hoppades över eftersom fältgränsen för samlingen nåddes.', 'CSV file is empty.': 'CSV-filen är tom.', 'CSV file has no usable field columns.': 'CSV-filen har inga användbara fältkolumner.', 'CSV contains an unterminated quoted value.': 'CSV-filen innehåller ett citerat värde som inte avslutats.', 'CMS collection limit reached.': 'Gränsen för CMS-samlingar har nåtts.',
  'Multilingual CMS content': 'Flerspråkigt CMS-innehåll', 'Add language-specific values and slugs. Missing translations automatically use the default CMS value.': 'Lägg till språkspecifika värden och sluggar. Saknade översättningar använder automatiskt CMS-standardvärdet.', 'CMS collection': 'CMS-samling', 'CMS entry': 'CMS-post', 'Content language': 'Innehållsspråk', 'Add an entry before creating translations.': 'Lägg till en post innan du skapar översättningar.', 'Copy default values': 'Kopiera standardvärden', 'Use default fallback for every field': 'Använd standardvärden för alla fält', 'Use fallback': 'Använd reservvärde', 'Fallback': 'Reservvärde', 'Empty': 'Tomt', 'This collection has no localizable fields.': 'Den här samlingen har inga lokaliserbara fält.',
  'AI CMS assistant': 'AI-assistent för CMS', 'Review first': 'Granska först', 'AI plans CMS changes for review. New entries stay drafts and CMS content is never deleted automatically.': 'AI planerar CMS-ändringar för granskning. Nya poster förblir utkast och CMS-innehåll raderas aldrig automatiskt.', 'Describe CMS changes, entries, views, or translations…': 'Beskriv CMS-ändringar, poster, vyer eller översättningar…', 'Plan with AI': 'Planera med AI', 'Planning…': 'Planerar…', 'Review AI CMS plan': 'Granska AI-plan för CMS', 'Operations': 'Åtgärder', 'Cancel plan': 'Avbryt plan', 'Apply reviewed plan': 'Tillämpa granskad plan', 'Applied CMS operations': 'Tillämpade CMS-åtgärder', 'warnings': 'varningar', 'No safe CMS operations were returned.': 'Inga säkra CMS-åtgärder returnerades.', 'Describe the CMS changes you want first.': 'Beskriv först de CMS-ändringar du vill göra.', 'AI returned an invalid CMS plan.': 'AI returnerade en ogiltig CMS-plan.', 'CMS AI planning failed.': 'AI-planeringen för CMS misslyckades.', 'CMS AI plan could not be applied.': 'CMS-planen från AI kunde inte tillämpas.',
  'Live collaborators': 'Aktiva medarbetare', 'Live cursor': 'Livepekare', 'Editing this element': 'Redigerar detta element', 'Editing conflict': 'Redigeringskonflikt', 'Another collaborator is editing this element': 'En annan medarbetare redigerar detta element', 'Version comparison': 'Versionsjämförelse', 'Selective restore': 'Selektiv återställning', 'Added': 'Tillagt', 'Removed': 'Borttaget', 'Changed': 'Ändrat',
  'Manage multilingual content, routes, SEO, RTL and locale domains.': 'Hantera flerspråkigt innehåll, rutter, SEO, RTL och språkdomäner.', 'Editing language': 'Redigeringsspråk', 'Direction': 'Skrivriktning', 'Fallback language': 'Reservspråk', 'Locale path prefix': 'Sökvägsprefix för språk', 'Subdomain': 'Underdomän', 'Localized page name': 'Lokaliserat sidnamn', 'Localized slug': 'Lokaliserad slug', 'Translating…': 'Översätter…', 'Translate page with AI': 'Översätt sidan med AI',
  'Integrations': 'Integrationer', 'Connect analytics, payments, email, CRM, APIs and signed webhooks.': 'Anslut analys, betalningar, e-post, CRM, API:er och signerade webhooks.', 'Provider': 'Leverantör', 'Add integration': 'Lägg till integration', 'active': 'aktiva', 'configuration issue': 'konfigurationsproblem', 'configuration issues': 'konfigurationsproblem', 'Enabled': 'Aktiverad', 'Name': 'Namn', 'Environments': 'Miljöer', 'Events': 'Händelser', 'Configured — enter to replace': 'Konfigurerad — ange ett värde för att ersätta', 'Testing…': 'Testar…', 'Test connection': 'Testa anslutning', 'Remove': 'Ta bort',
};

const cmsMaps: Record<Language, PhraseMap> = { en: {}, ar: arCmsSupplement, sv: svCmsSupplement };
export function localizeUi(text: string, language: Language): string { if (language === 'en') return text; return cmsMaps[language][text] ?? localizeBaseUi(text, language); }
export function useLocalizer() { const { prefs } = usePreferences(); const language = prefs.language; return useCallback((text: string) => localizeUi(text, language), [language]); }
