import { useCallback } from 'react';
import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arReleaseSupplement: PhraseMap = {
  'Account and Data Deletion': 'حذف الحساب والبيانات',
  'Tayar provides permanent account deletion from the mobile app and signed-in web workspace.': 'يوفّر Tayar حذفًا دائمًا للحساب من تطبيق الهاتف ومن مساحة العمل على الويب بعد تسجيل الدخول.',
  'Delete your account now': 'احذف حسابك الآن',
  'Mobile app: open Profile, choose Delete account permanently, then confirm the destructive action.': 'تطبيق الهاتف: افتح الملف الشخصي، واختر حذف الحساب نهائيًا، ثم أكّد الإجراء النهائي.',
  'Web: sign in, open Workspace → Settings → Privacy → Delete Account, then type DELETE to confirm.': 'الويب: سجّل الدخول، ثم افتح مساحة العمل ← الإعدادات ← الخصوصية ← حذف الحساب، واكتب DELETE للتأكيد.',
  'Sign in to Tayar': 'تسجيل الدخول إلى Tayar',
  'If you cannot sign in': 'إذا تعذر عليك تسجيل الدخول',
  'Send an account deletion request from the email address associated with your Tayar account. Include only the information needed to identify the account. Never send your password.': 'أرسل طلب حذف الحساب من عنوان البريد المرتبط بحساب Tayar. أرسل فقط المعلومات اللازمة لتحديد الحساب، ولا ترسل كلمة المرور مطلقًا.',
  'Request deletion by email': 'طلب الحذف عبر البريد الإلكتروني',
  'Use the legal and privacy contact shown on the Privacy Policy page to request deletion assistance.': 'استخدم جهة الاتصال القانونية والخصوصية الموضحة في صفحة سياسة الخصوصية لطلب المساعدة في الحذف.',
  'What deletion does': 'ما الذي يفعله الحذف',
  'Tayar cancels an active Tayar subscription first, removes the active account, deletes owned project records, and removes user-owned Tayar storage that is covered by the deletion flow.': 'يلغي Tayar أولًا أي اشتراك Tayar نشط، ثم يزيل الحساب النشط ويحذف سجلات المشاريع المملوكة والتخزين المملوك للمستخدم الذي يشمله مسار الحذف.',
  'Limited billing, security, fraud-prevention, dispute, or audit records may remain only where required by law or needed for legitimate service protection, as described in the Privacy Policy.': 'قد تبقى سجلات محدودة للفوترة أو الأمان أو منع الاحتيال أو النزاعات أو التدقيق فقط عندما يفرض القانون ذلك أو عند الحاجة لحماية مشروعة للخدمة، كما هو موضح في سياسة الخصوصية.',
  'Important': 'مهم',
  'Account deletion is permanent and cannot be undone. If you need a copy of your account records first, use the Account Data Export in Workspace → Settings → Privacy before deleting the account.': 'حذف الحساب نهائي ولا يمكن التراجع عنه. إذا كنت تحتاج إلى نسخة من سجلات حسابك أولًا، فاستخدم تصدير بيانات الحساب من مساحة العمل ← الإعدادات ← الخصوصية قبل حذف الحساب.',

  'Remove image backgrounds privately with AI running directly in your browser.': 'أزل خلفيات الصور بخصوصية باستخدام ذكاء اصطناعي يعمل مباشرة داخل متصفحك.',
  'Local processing': 'معالجة محلية',
  'Your image stays on this device. The browser downloads a small AI model on first use, then removes the background locally. No image is sent to fal.ai, Gemini or Tayar servers.': 'تبقى صورتك على هذا الجهاز. ينزّل المتصفح نموذج ذكاء اصطناعي صغيرًا عند أول استخدام، ثم يزيل الخلفية محليًا. لا تُرسل أي صورة إلى fal.ai أو Gemini أو خوادم Tayar.',
  'Trim transparent space around the detected subject': 'قص المساحة الشفافة حول العنصر المكتشف',

  'Could not read this dataset.': 'تعذرت قراءة مجموعة البيانات هذه.',
  'Choose a CSV, TSV or delimited text file first.': 'اختر أولًا ملف CSV أو TSV أو ملفًا نصيًا محدد الفواصل.',
  'Enter the question you want AI to answer about the data.': 'أدخل السؤال الذي تريد من الذكاء الاصطناعي الإجابة عنه حول البيانات.',
  'Analyzing data...': 'جارٍ تحليل البيانات...',
  'Analysis ready': 'التحليل جاهز',
  'Could not analyze this dataset.': 'تعذر تحليل مجموعة البيانات هذه.',
  'Could not copy the result.': 'تعذر نسخ النتيجة.',
  'AI Data Analytics': 'تحليلات البيانات بالذكاء الاصطناعي',
  'Profile CSV data locally, then turn statistics into clear AI insights.': 'حلّل بنية بيانات CSV محليًا ثم حوّل الإحصاءات إلى رؤى واضحة بالذكاء الاصطناعي.',
  'Privacy-aware analysis': 'تحليل يراعي الخصوصية',
  'The full file is parsed in your browser. AI receives computed column statistics plus up to 12 rows distributed across the dataset (max 30 columns), not the complete dataset.': 'يُحلَّل الملف كاملًا داخل متصفحك. يستقبل الذكاء الاصطناعي إحصاءات الأعمدة المحسوبة وما يصل إلى 12 صفًا موزعًا من مجموعة البيانات، بحد أقصى 30 عمودًا، وليس مجموعة البيانات كاملة.',
  'Up to 10 MB · parsed locally': 'حتى 10 MB · يُحلّل محليًا',
  'Rows': 'الصفوف',
  'Columns': 'الأعمدة',
  'Numeric': 'رقمي',
  'Analysis Type': 'نوع التحليل',
  'Executive insights': 'رؤى تنفيذية',
  'Trends & patterns': 'الاتجاهات والأنماط',
  'Data quality audit': 'تدقيق جودة البيانات',
  'KPI & dashboard ideas': 'أفكار لمؤشرات الأداء ولوحات المعلومات',
  'Ask a custom question': 'اطرح سؤالًا مخصصًا',
  'Question / Business Context': 'السؤال / سياق العمل',
  'Optional: What drives revenue? Which columns look problematic? What KPIs should I track?': 'اختياري: ما الذي يحرك الإيرادات؟ أي الأعمدة تبدو إشكالية؟ ما مؤشرات الأداء التي ينبغي تتبعها؟',
  'Local data profile': 'ملف تعريف البيانات المحلي',
  'Column': 'العمود',
  'Unique': 'فريد',
  'Mean': 'المتوسط',
  'Min / Max': 'الحد الأدنى / الأقصى',
  'more columns profiled locally': 'أعمدة إضافية تم تحليلها محليًا',
  'mean': 'المتوسط',
  'values': 'القيم',
  'AI analysis': 'تحليل الذكاء الاصطناعي',
  'Validate important decisions against the source data.': 'تحقق من القرارات المهمة بالرجوع إلى البيانات الأصلية.',

  'Describe the key terms you want in the agreement.': 'صف الشروط الأساسية التي تريدها في الاتفاقية.',
  'Paste the contract or clause you want to review.': 'الصق العقد أو البند الذي تريد مراجعته.',
  'Could not process the contract.': 'تعذرت معالجة العقد.',
  'AI Contract Writer': 'كاتب العقود بالذكاء الاصطناعي',
  'Draft agreements, review contract risks, and improve clauses with AI.': 'أنشئ مسودات اتفاقيات وراجع مخاطر العقود وحسّن البنود باستخدام الذكاء الاصطناعي.',
  'Drafting assistant — not legal advice': 'مساعد صياغة — وليس استشارة قانونية',
  'Review important contracts with a qualified lawyer in the relevant jurisdiction before signing or relying on them.': 'راجع العقود المهمة مع محامٍ مؤهل في الولاية القضائية المعنية قبل توقيعها أو الاعتماد عليها.',
  'Risk Style': 'أسلوب توزيع المخاطر',
  'Balanced / mutual': 'متوازن / متبادل',
  'Protect my side': 'حماية جانبي',
  'Collaborative / light': 'تعاوني / مرن',
  'Contract Type': 'نوع العقد',
  'Parties': 'الأطراف',
  'Who are the parties and what are their roles?': 'من هم الأطراف وما أدوارهم؟',
  'Key Terms': 'الشروط الأساسية',
  'Scope, price/payment, dates, deliverables, termination, confidentiality, ownership, special conditions...': 'النطاق، السعر/الدفع، التواريخ، التسليمات، الإنهاء، السرية، الملكية، الشروط الخاصة...',
  'Paste the text here...': 'الصق النص هنا...',
  'Jurisdiction / Country': 'الولاية القضائية / البلد',
  'e.g. Sweden — optional': 'مثال: السويد — اختياري',
  'Optional: payment risk, termination, liability, make it more balanced...': 'اختياري: مخاطر الدفع، الإنهاء، المسؤولية، جعله أكثر توازنًا...',
  'Your contract draft or review will appear here.': 'ستظهر مسودة العقد أو المراجعة هنا.',
  'Verify names, numbers, dates, obligations, and local-law requirements before use.': 'تحقق من الأسماء والأرقام والتواريخ والالتزامات ومتطلبات القانون المحلي قبل الاستخدام.',

  'Writing email...': 'جارٍ كتابة البريد الإلكتروني...',
  'Email ready': 'البريد الإلكتروني جاهز',
  'Could not generate the email.': 'تعذر إنشاء البريد الإلكتروني.',
  'Compose, reply to, and improve professional emails with AI.': 'أنشئ رسائل بريد احترافية ورد عليها وحسّنها باستخدام الذكاء الاصطناعي.',
  'Same as input': 'نفس لغة النص الأصلي',
  'Formal': 'رسمي',
  'Concise': 'موجز',
  'Warm': 'ودود ودافئ',
  'Creative': 'إبداعي',
  'Recipient / Name': 'المستلم / الاسم',
  'e.g. Maria, Hiring Manager, Customer': 'مثال: ماريا، مدير التوظيف، العميل',
  'Subject / Topic': 'الموضوع / العنوان',
  'Optional subject or topic': 'موضوع أو عنوان اختياري',
  'Paste the email here...': 'الصق البريد الإلكتروني هنا...',
  'Detailed': 'مفصل',
  'Your finished email will appear here.': 'سيظهر البريد الإلكتروني النهائي هنا.',
  'Ready to send': 'جاهز للإرسال',
  'Review names, dates and commitments before sending.': 'راجع الأسماء والتواريخ والالتزامات قبل الإرسال.',

  'English': 'الإنجليزية',
  'Swedish': 'السويدية',
  'Arabic': 'العربية',
  'German': 'الألمانية',
  'French': 'الفرنسية',
  'Spanish': 'الإسبانية',
  'Service Agreement': 'اتفاقية خدمات',
  'Freelance Agreement': 'اتفاقية عمل حر',
  'Non-Disclosure Agreement (NDA)': 'اتفاقية عدم إفشاء (NDA)',
  'Consulting Agreement': 'اتفاقية استشارات',
  'Sales Agreement': 'اتفاقية بيع',
  'Loan Agreement': 'اتفاقية قرض',
  'Employment Agreement': 'اتفاقية توظيف',
  'Lease / Rental Agreement': 'اتفاقية إيجار',
  'Partnership / Collaboration Agreement': 'اتفاقية شراكة / تعاون',
  'Custom Agreement': 'اتفاقية مخصصة',
};

export const svReleaseSupplement: PhraseMap = {
  'Account and Data Deletion': 'Radering av konto och data',
  'Tayar provides permanent account deletion from the mobile app and signed-in web workspace.': 'Tayar erbjuder permanent kontoradering från mobilappen och från den inloggade webbarbetsytan.',
  'Delete your account now': 'Radera ditt konto nu',
  'Mobile app: open Profile, choose Delete account permanently, then confirm the destructive action.': 'Mobilapp: öppna Profil, välj Radera konto permanent och bekräfta sedan den definitiva åtgärden.',
  'Web: sign in, open Workspace → Settings → Privacy → Delete Account, then type DELETE to confirm.': 'Webb: logga in, öppna Arbetsyta → Inställningar → Integritet → Radera konto och skriv sedan DELETE för att bekräfta.',
  'Sign in to Tayar': 'Logga in på Tayar',
  'If you cannot sign in': 'Om du inte kan logga in',
  'Send an account deletion request from the email address associated with your Tayar account. Include only the information needed to identify the account. Never send your password.': 'Skicka en begäran om kontoradering från e-postadressen som är kopplad till ditt Tayar-konto. Ta bara med information som behövs för att identifiera kontot. Skicka aldrig ditt lösenord.',
  'Request deletion by email': 'Begär radering via e-post',
  'Use the legal and privacy contact shown on the Privacy Policy page to request deletion assistance.': 'Använd kontaktuppgifterna för juridik och integritet på sidan Integritetspolicy för att få hjälp med radering.',
  'What deletion does': 'Vad raderingen innebär',
  'Tayar cancels an active Tayar subscription first, removes the active account, deletes owned project records, and removes user-owned Tayar storage that is covered by the deletion flow.': 'Tayar avslutar först en aktiv Tayar-prenumeration, tar bort det aktiva kontot, raderar ägda projektposter och tar bort användarägd Tayar-lagring som omfattas av raderingsflödet.',
  'Limited billing, security, fraud-prevention, dispute, or audit records may remain only where required by law or needed for legitimate service protection, as described in the Privacy Policy.': 'Begränsade poster för fakturering, säkerhet, bedrägeriförebyggande, tvister eller revision kan finnas kvar endast när lagen kräver det eller när det behövs för legitimt skydd av tjänsten, enligt Integritetspolicyn.',
  'Important': 'Viktigt',
  'Account deletion is permanent and cannot be undone. If you need a copy of your account records first, use the Account Data Export in Workspace → Settings → Privacy before deleting the account.': 'Kontoradering är permanent och kan inte ångras. Om du först behöver en kopia av dina kontoposter använder du Export av kontodata under Arbetsyta → Inställningar → Integritet innan du raderar kontot.',

  'Remove image backgrounds privately with AI running directly in your browser.': 'Ta bort bildbakgrunder privat med AI som körs direkt i webbläsaren.',
  'Local processing': 'Lokal bearbetning',
  'Your image stays on this device. The browser downloads a small AI model on first use, then removes the background locally. No image is sent to fal.ai, Gemini or Tayar servers.': 'Din bild stannar på den här enheten. Webbläsaren laddar ned en liten AI-modell vid första användningen och tar sedan bort bakgrunden lokalt. Ingen bild skickas till fal.ai, Gemini eller Tayars servrar.',
  'Trim transparent space around the detected subject': 'Beskär genomskinligt utrymme runt det identifierade motivet',

  'Could not read this dataset.': 'Kunde inte läsa den här datamängden.',
  'Choose a CSV, TSV or delimited text file first.': 'Välj först en CSV-, TSV- eller avgränsad textfil.',
  'Enter the question you want AI to answer about the data.': 'Ange frågan som du vill att AI ska besvara om datan.',
  'Analyzing data...': 'Analyserar data...',
  'Analysis ready': 'Analysen är klar',
  'Could not analyze this dataset.': 'Kunde inte analysera den här datamängden.',
  'Could not copy the result.': 'Kunde inte kopiera resultatet.',
  'AI Data Analytics': 'AI-dataanalys',
  'Profile CSV data locally, then turn statistics into clear AI insights.': 'Profilera CSV-data lokalt och omvandla sedan statistiken till tydliga AI-insikter.',
  'Privacy-aware analysis': 'Integritetsmedveten analys',
  'The full file is parsed in your browser. AI receives computed column statistics plus up to 12 rows distributed across the dataset (max 30 columns), not the complete dataset.': 'Hela filen tolkas i webbläsaren. AI får beräknad kolumnstatistik samt upp till 12 rader fördelade över datamängden, högst 30 kolumner, inte hela datamängden.',
  'Up to 10 MB · parsed locally': 'Upp till 10 MB · tolkas lokalt',
  'Rows': 'Rader',
  'Columns': 'Kolumner',
  'Numeric': 'Numeriska',
  'Analysis Type': 'Analystyp',
  'Executive insights': 'Ledningsinsikter',
  'Trends & patterns': 'Trender och mönster',
  'Data quality audit': 'Granskning av datakvalitet',
  'KPI & dashboard ideas': 'Idéer för KPI:er och dashboards',
  'Ask a custom question': 'Ställ en egen fråga',
  'Question / Business Context': 'Fråga / affärskontext',
  'Optional: What drives revenue? Which columns look problematic? What KPIs should I track?': 'Valfritt: Vad driver intäkterna? Vilka kolumner ser problematiska ut? Vilka KPI:er bör jag följa?',
  'Local data profile': 'Lokal dataprofil',
  'Column': 'Kolumn',
  'Unique': 'Unika',
  'Mean': 'Medelvärde',
  'Min / Max': 'Min / Max',
  'more columns profiled locally': 'fler kolumner profilerade lokalt',
  'mean': 'medelvärde',
  'values': 'värden',
  'AI analysis': 'AI-analys',
  'Validate important decisions against the source data.': 'Verifiera viktiga beslut mot källdatan.',

  'Describe the key terms you want in the agreement.': 'Beskriv de viktigaste villkoren du vill ha i avtalet.',
  'Paste the contract or clause you want to review.': 'Klistra in avtalet eller klausulen som du vill granska.',
  'Could not process the contract.': 'Kunde inte behandla avtalet.',
  'AI Contract Writer': 'AI-avtalsskrivare',
  'Draft agreements, review contract risks, and improve clauses with AI.': 'Skapa avtalsutkast, granska avtalsrisker och förbättra klausuler med AI.',
  'Drafting assistant — not legal advice': 'Skrivassistent — inte juridisk rådgivning',
  'Review important contracts with a qualified lawyer in the relevant jurisdiction before signing or relying on them.': 'Granska viktiga avtal med en kvalificerad jurist i relevant jurisdiktion innan du undertecknar eller förlitar dig på dem.',
  'Risk Style': 'Riskprofil',
  'Balanced / mutual': 'Balanserad / ömsesidig',
  'Protect my side': 'Skydda min sida',
  'Collaborative / light': 'Samarbetsinriktad / lätt',
  'Contract Type': 'Avtalstyp',
  'Parties': 'Parter',
  'Who are the parties and what are their roles?': 'Vilka är parterna och vilka roller har de?',
  'Key Terms': 'Viktiga villkor',
  'Scope, price/payment, dates, deliverables, termination, confidentiality, ownership, special conditions...': 'Omfattning, pris/betalning, datum, leveranser, uppsägning, sekretess, ägande, särskilda villkor...',
  'Paste the text here...': 'Klistra in texten här...',
  'Jurisdiction / Country': 'Jurisdiktion / land',
  'e.g. Sweden — optional': 't.ex. Sverige — valfritt',
  'Optional: payment risk, termination, liability, make it more balanced...': 'Valfritt: betalningsrisk, uppsägning, ansvar, gör det mer balanserat...',
  'Your contract draft or review will appear here.': 'Ditt avtalsutkast eller din granskning visas här.',
  'Verify names, numbers, dates, obligations, and local-law requirements before use.': 'Kontrollera namn, siffror, datum, skyldigheter och krav enligt lokal lag före användning.',

  'Writing email...': 'Skriver e-post...',
  'Email ready': 'E-postmeddelandet är klart',
  'Could not generate the email.': 'Kunde inte skapa e-postmeddelandet.',
  'Compose, reply to, and improve professional emails with AI.': 'Skriv, besvara och förbättra professionella e-postmeddelanden med AI.',
  'Same as input': 'Samma som indata',
  'Formal': 'Formell',
  'Concise': 'Kortfattad',
  'Warm': 'Varm',
  'Creative': 'Kreativ',
  'Recipient / Name': 'Mottagare / namn',
  'e.g. Maria, Hiring Manager, Customer': 't.ex. Maria, rekryteringschef, kund',
  'Subject / Topic': 'Ämne / tema',
  'Optional subject or topic': 'Valfritt ämne eller tema',
  'Paste the email here...': 'Klistra in e-postmeddelandet här...',
  'Detailed': 'Detaljerad',
  'Your finished email will appear here.': 'Ditt färdiga e-postmeddelande visas här.',
  'Ready to send': 'Redo att skickas',
  'Review names, dates and commitments before sending.': 'Granska namn, datum och åtaganden innan du skickar.',

  'English': 'Engelska',
  'Swedish': 'Svenska',
  'Arabic': 'Arabiska',
  'German': 'Tyska',
  'French': 'Franska',
  'Spanish': 'Spanska',
  'Service Agreement': 'Tjänsteavtal',
  'Freelance Agreement': 'Frilansavtal',
  'Non-Disclosure Agreement (NDA)': 'Sekretessavtal (NDA)',
  'Consulting Agreement': 'Konsultavtal',
  'Sales Agreement': 'Försäljningsavtal',
  'Loan Agreement': 'Låneavtal',
  'Employment Agreement': 'Anställningsavtal',
  'Lease / Rental Agreement': 'Hyresavtal',
  'Partnership / Collaboration Agreement': 'Partnerskaps- / samarbetsavtal',
  'Custom Agreement': 'Anpassat avtal',
};

const releaseMaps: Record<Language, PhraseMap> = {
  en: {},
  ar: arReleaseSupplement,
  sv: svReleaseSupplement,
};

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return releaseMaps[language][text] ?? localizeBaseUi(text, language);
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  const language = prefs.language;
  return useCallback((text: string) => localizeUi(text, language), [language]);
}
