import { useCallback } from 'react';
import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arCmsSupplement: PhraseMap = {
  "Atomic quantity adjustments": "تغييرات كمية ذرّية",
  "Use for stock, quotas or points. New records start at the minimum; changes use a protected adjustment.": "للمخزون والحصص والنقاط. تبدأ السجلات عند الحد الأدنى وتُغيّر الكمية بإجراء محمي.",
  "Quantity field": "حقل الكمية",
  "Minimum quantity": "الحد الأدنى للكمية",
  "Maximum quantity (optional)": "الحد الأعلى للكمية (اختياري)",
  "Whole numbers only": "أعداد صحيحة فقط",
  "Set the quantity field default to the minimum before saving.": "اجعل القيمة الافتراضية لحقل الكمية مساوية للحد الأدنى قبل الحفظ.",
  "Save quantity rule": "حفظ قاعدة الكمية",
  "Remove quantity rule": "إزالة قاعدة الكمية",
  "Adjust quantity": "تغيير الكمية",
  "Atomic multi-item transaction": "معاملة ذرّية متعددة العناصر",
  "Create one parent record and its line items while updating every selected quantity in one protected operation.": "أنشئ سجلاً رئيسياً وبنوده مع تحديث كل الكميات المحددة ضمن عملية محمية واحدة.",
  "Item table": "جدول العناصر", "Line table": "جدول البنود", "Parent reference field": "حقل مرجع السجل الرئيسي",
  "Item reference field": "حقل مرجع العنصر", "Line quantity field": "حقل كمية البند", "Quantity direction": "اتجاه الكمية",
  "Decrease": "إنقاص", "Increase": "زيادة", "Save transaction rule": "حفظ قاعدة المعاملة", "Remove transaction rule": "إزالة قاعدة المعاملة",
  "Create transaction": "إنشاء معاملة",

  "Booking conflict protection": "منع تعارض الحجوزات",
  "One resource cannot have overlapping bookings. Adjacent times are allowed. Cancelled states can release the time.": "لا يمكن حجز المورد نفسه بأوقات متداخلة. يُسمح بالأوقات المتجاورة ويمكن للحالات الملغاة تحرير الوقت.",
  "Booking resource": "مورد الحجز",
  "Booking start": "بداية الحجز",
  "Booking end": "نهاية الحجز",
  "Booking status": "حالة الحجز",
  "Every booking blocks time": "كل حجز يحجز الوقت",
  "States that block time": "الحالات التي تحجز الوقت",
  "Save booking rule": "حفظ قاعدة الحجز",
  "Remove booking rule": "إزالة قاعدة الحجز",

  'Application data view': 'عرض بيانات التطبيق',
  'Records load after secure application publishing and sign-in. Database permissions control every action.': 'تظهر السجلات بعد نشر التطبيق الآمن وتسجيل الدخول. تتحكم صلاحيات قاعدة البيانات بكل إجراء.',
  'Visible columns': 'الأعمدة الظاهرة', 'Allowed actions': 'الإجراءات المسموحة',
  'Add record': 'إضافة سجل', 'Edit record': 'تعديل سجل', 'Delete record': 'حذف سجل',
  'Search column': 'عمود البحث', 'Records per page': 'السجلات في الصفحة',
  'Save data view': 'حفظ عرض البيانات', 'Remove data view': 'إزالة عرض البيانات',
  'Select valid columns and actions permitted by the table.': 'اختر أعمدة صحيحة وإجراءات تسمح بها صلاحيات الجدول.',
  'Save the project before connecting your accounts.': 'احفظ المشروع قبل ربط حساباتك.',
  'Connect and verify your accounts before publishing.': 'اربط حساباتك وتحقق منها قبل النشر.',
  'Add application data and access settings before linking a backend.': 'أضف إعدادات بيانات التطبيق والدخول قبل ربط قاعدة البيانات.',
  'Publishing is blocked. Check your connections and application configuration, then retry. This project has not been verified as ready.': 'النشر متوقف. راجع الاتصالات وإعدادات التطبيق ثم حاول مجددًا. لم يتم التحقق من جاهزية هذا المشروع.',
  'Code, database and hosting remain in your accounts. Provider billing, backups and ongoing administration belong to you after handover.': 'يبقى الكود وقاعدة البيانات والاستضافة في حساباتك. بعد التسليم تتولى أنت فواتير المزودين والنسخ الاحتياطية والإدارة المستمرة.',
  'A verified release runs independently of Tayar. Keep its runtime credentials in your hosting account; remove Tayar setup permissions only after verifying the handover.': 'يعمل الإصدار المتحقق منه بشكل مستقل عن طيار. احتفظ ببيانات اعتماد تشغيله في حساب الاستضافة، وألغِ صلاحيات إعداد طيار بعد التحقق من التسليم.',
  'After handover, you manage these accounts and their billing. Tayar is used for project setup and future edits you request.': 'بعد التسليم تتولى أنت إدارة هذه الحسابات وفواتيرها. يُستخدم طيار لإعداد المشروع وللتعديلات المستقبلية التي تطلبها.',
  'Connection setup is not available yet. Tayar must activate this provider before you can connect your account.': 'إعداد الاتصال غير متاح بعد. يجب أن يفعّل طيار هذا المزود قبل أن تتمكن من ربط حسابك.',
  'Save the current project before publishing on your accounts.': 'احفظ المشروع الحالي قبل نشره على حساباتك.',
  'HTML': 'HTML',
  'Application form data': 'بيانات نموذج التطبيق',
  'Bound forms require secure application publishing before they can accept records.': 'تحتاج النماذج المرتبطة إلى نشر التطبيق الآمن قبل استقبال السجلات.',
  'Target table': 'الجدول المستهدف', 'Select a table': 'اختر جدولًا', 'Select a field': 'اختر حقلًا',
  'Calculated field': 'حقل محسوب', 'Calculation': 'الحساب', 'Source fields': 'الحقول المصدر',
  'Sum': 'جمع', 'Subtract': 'طرح', 'Multiply': 'ضرب',
  'Match every form field to a compatible application field.': 'اربط كل حقل في النموذج بحقل متوافق في التطبيق.',
  'Save data binding': 'حفظ ربط البيانات', 'Remove data binding': 'إزالة ربط البيانات',
  "Application backend connection": "ربط خلفية التطبيق",
  "Connect an existing dedicated backend with the matching application schema.": "اربط خلفية مستقلة موجودة تطابق بنية التطبيق.",
  "Save this project before linking a backend.": "احفظ هذا المشروع قبل ربط الخلفية.",
  "Checking backend…": "جارٍ التحقق من الخلفية…",
  "Backend linked": "تم ربط الخلفية",
  "No verified backend connection.": "لا يوجد ربط خلفية متحقق منه.",
  "Backend linked. Publishing still requires the remaining runtime checks.": "تم ربط الخلفية. ما زال النشر يتطلب استكمال فحوص التشغيل.",
  "Refresh backend status": "تحديث حالة الخلفية",
  "Dedicated backend URL": "رابط الخلفية المستقلة",
  "Backend public key": "المفتاح العام للخلفية",
  "Backend service key": "مفتاح الخدمة للخلفية",
  "The service key is encrypted on the server and cleared from this form after submission.": "يُشفّر مفتاح الخدمة على الخادم ويُمسح من هذا النموذج بعد الإرسال.",
  "Verify and link backend": "تحقق واربط الخلفية",
  "Backend status is unavailable. Save the project and try again.": "حالة الخلفية غير متاحة. احفظ المشروع وحاول مجدداً.",
  "Enter a valid backend service key.": "أدخل مفتاح خدمة صالحاً للخلفية.",
  "The project changed. Review the backend connection again.": "تغيّر المشروع. راجع ربط الخلفية مجدداً.",
  "Backend linking failed. Check the saved schema and connection settings, then enter the service key again.": "فشل ربط الخلفية. تحقق من البنية المحفوظة وإعدادات الاتصال ثم أدخل مفتاح الخدمة مجدداً.",
  'Plan application changes with AI': 'خطّط لتغييرات التطبيق باستخدام AI', 'Describe application changes': 'صف تغييرات التطبيق', 'The project changed while AI was planning. Create a new plan.': 'تغيّر المشروع أثناء تخطيط AI. أنشئ خطة جديدة.', 'Application AI planning failed.': 'فشل تخطيط التطبيق باستخدام AI.', 'AI returned an invalid application plan.': 'أعاد AI خطة تطبيق غير صالحة.', 'AI returned an unsupported application operation.': 'أعاد AI عملية تطبيق غير مدعومة.', 'Describe the application changes first.': 'صف تغييرات التطبيق أولاً.',
  'Application data and access': 'بيانات التطبيق والتحكم بالوصول', 'Database and authentication require secure backend provisioning before publishing.': 'قاعدة البيانات وتسجيل الدخول يحتاجان خلفية آمنة قبل النشر.', 'Data': 'البيانات', 'Enter a table name.': 'أدخل اسم الجدول.', 'Table name': 'اسم الجدول', 'Add table': 'إضافة جدول', 'Table key': 'مفتاح الجدول', 'Field': 'الحقل', 'Key': 'المفتاح', 'Type': 'النوع', 'Related table': 'الجدول المرتبط', 'Options (comma separated)': 'الخيارات (مفصولة بفواصل)', 'Required': 'مطلوب', 'Unique': 'فريد', 'Index for queries': 'فهرسة للاستعلامات', 'Default value': 'القيمة الافتراضية', 'No default': 'دون قيمة افتراضية', 'Remove field': 'حذف الحقل', 'Add field': 'إضافة حقل', 'Permissions': 'الصلاحيات', 'read': 'قراءة', 'create': 'إنشاء', 'update': 'تحديث', 'delete': 'حذف', 'No access': 'دون وصول', 'Public': 'عام', 'Authenticated': 'مستخدم مسجّل', 'Record owner': 'مالك السجل', 'Role': 'دور', 'Remove table': 'حذف الجدول', 'Remove this table and its definition?': 'حذف هذا الجدول وتعريفه؟', 'Auth and roles': 'تسجيل الدخول والأدوار', 'Enable authentication': 'تفعيل تسجيل الدخول', 'Allow sign up': 'السماح بالتسجيل', 'Require email verification': 'طلب تأكيد البريد الإلكتروني', 'Role name': 'اسم الدور', 'Add role': 'إضافة دور',

  'Referenced by': 'مُشار إليه من', 'Collection settings': 'إعدادات المجموعة', 'Collection slug': 'مسار المجموعة', 'Entry slug field': 'حقل مسار الإدخال', 'Referenced collection': 'المجموعة المرتبطة', 'Duplicate entry': 'نسخ الإدخال', 'This entry is referenced by other CMS content': 'هذا الإدخال مرتبط بمحتوى CMS آخر', 'Matching published entries': 'الإدخالات المنشورة المطابقة', 'Remove filter': 'إزالة الفلتر', 'Add filter': 'إضافة فلتر',
  'Import / Export': 'استيراد / تصدير', 'Import collection': 'استيراد مجموعة', 'Export collection': 'تصدير المجموعة', 'Export JSON': 'تصدير JSON', 'Export CSV': 'تصدير CSV', 'Import JSON': 'استيراد JSON', 'Import CSV': 'استيراد CSV', 'JSON · CSV': 'JSON · CSV', 'Import preview': 'معاينة الاستيراد', 'Replace collection': 'استبدال المجموعة', 'Append entries': 'إضافة الإدخالات', 'Field mapping': 'ربط الحقول', 'Duplicate handling': 'معالجة التكرار', 'Skip duplicates': 'تخطي المكررات', 'Update duplicates': 'تحديث المكررات', 'Import validation failed': 'فشل التحقق من الاستيراد', 'Import complete': 'اكتمل الاستيراد', 'Preview and validate imported content before changing the project.': 'عاين المحتوى المستورد وتحقق منه قبل تغيير المشروع.', 'Import file is too large': 'ملف الاستيراد كبير جدًا', 'Imported collection': 'مجموعة مستوردة', 'Import as new collection': 'استيراد كمجموعة جديدة', 'Apply import': 'تطبيق الاستيراد', 'Import file does not contain a CMS collection.': 'ملف الاستيراد لا يحتوي على مجموعة CMS.', 'Imported collection has no valid fields.': 'المجموعة المستوردة لا تحتوي على حقول صالحة.', 'Some fields were skipped because the collection field limit was reached.': 'تم تخطي بعض الحقول بسبب بلوغ الحد الأقصى لحقول المجموعة.', 'Some entries were skipped because the collection entry limit was reached.': 'تم تخطي بعض الإدخالات بسبب بلوغ الحد الأقصى لإدخالات المجموعة.', 'Some columns were skipped because the collection field limit was reached.': 'تم تخطي بعض الأعمدة بسبب بلوغ الحد الأقصى لحقول المجموعة.', 'CSV file is empty.': 'ملف CSV فارغ.', 'CSV file has no usable field columns.': 'ملف CSV لا يحتوي على أعمدة حقول قابلة للاستخدام.', 'CSV contains an unterminated quoted value.': 'يحتوي ملف CSV على قيمة مقتبسة غير مغلقة.', 'CMS collection limit reached.': 'تم بلوغ الحد الأقصى لمجموعات CMS.',
  'Multilingual CMS content': 'محتوى CMS متعدد اللغات', 'Add language-specific values and slugs. Missing translations automatically use the default CMS value.': 'أضف قيمًا ومسارات خاصة بكل لغة. تستخدم الترجمات الناقصة قيمة CMS الافتراضية تلقائيًا.', 'CMS collection': 'مجموعة CMS', 'CMS entry': 'إدخال CMS', 'Content language': 'لغة المحتوى', 'Add an entry before creating translations.': 'أضف إدخالًا قبل إنشاء الترجمات.', 'Copy default values': 'نسخ القيم الافتراضية', 'Use default fallback for every field': 'استخدام القيم الافتراضية لكل الحقول', 'Use fallback': 'استخدام القيمة الافتراضية', 'Fallback': 'القيمة الاحتياطية', 'Empty': 'فارغ', 'This collection has no localizable fields.': 'لا تحتوي هذه المجموعة على حقول قابلة للترجمة.',
  'AI CMS assistant': 'مساعد CMS بالذكاء الاصطناعي', 'Review first': 'مراجعة أولًا', 'AI plans CMS changes for review. New entries stay drafts and CMS content is never deleted automatically.': 'يخطط الذكاء الاصطناعي لتغييرات CMS كي تراجعها أولًا. تبقى الإدخالات الجديدة كمسودات ولا يُحذف محتوى CMS تلقائيًا.', 'Describe CMS changes, entries, views, or translations…': 'صف تغييرات CMS أو الإدخالات أو العروض أو الترجمات…', 'Plan with AI': 'خطط بالذكاء الاصطناعي', 'Planning…': 'جارٍ التخطيط…', 'Review AI CMS plan': 'راجع خطة CMS بالذكاء الاصطناعي', 'Operations': 'العمليات', 'Cancel plan': 'إلغاء الخطة', 'Apply reviewed plan': 'تطبيق الخطة المراجعة', 'Applied CMS operations': 'عمليات CMS المطبقة', 'warnings': 'تحذيرات', 'No safe CMS operations were returned.': 'لم يُرجع الذكاء الاصطناعي عمليات CMS آمنة.', 'Describe the CMS changes you want first.': 'صف أولًا تغييرات CMS التي تريدها.', 'AI returned an invalid CMS plan.': 'أعاد الذكاء الاصطناعي خطة CMS غير صالحة.', 'CMS AI planning failed.': 'فشل تخطيط CMS بالذكاء الاصطناعي.', 'CMS AI plan could not be applied.': 'تعذر تطبيق خطة CMS بالذكاء الاصطناعي.',
  'Live collaborators': 'المتعاونون المباشرون', 'Live cursor': 'المؤشر المباشر', 'Editing this element': 'يحرر هذا العنصر', 'Editing conflict': 'تعارض في التحرير', 'Another collaborator is editing this element': 'متعاون آخر يحرر هذا العنصر', 'Version comparison': 'مقارنة الإصدارات', 'Selective restore': 'استعادة انتقائية', 'Added': 'مضاف', 'Removed': 'محذوف', 'Changed': 'معدّل',
  'Manage multilingual content, routes, SEO, RTL and locale domains.': 'إدارة المحتوى متعدد اللغات والمسارات وتحسين محركات البحث واتجاه RTL ونطاقات اللغات.', 'Editing language': 'لغة التحرير', 'Direction': 'اتجاه الكتابة', 'Fallback language': 'اللغة الاحتياطية', 'Locale path prefix': 'بادئة مسار اللغة', 'Subdomain': 'النطاق الفرعي', 'Localized page name': 'اسم الصفحة المترجم', 'Localized slug': 'المسار المترجم', 'Translating…': 'جارٍ الترجمة…', 'Translate page with AI': 'ترجمة الصفحة بالذكاء الاصطناعي',
  'Secure secret storage is not connected yet.': 'خدمة الحفظ الآمن للمفاتيح غير موصولة بعد.', 'Infrastructure': 'البنية التشغيلية', 'Your accounts own the code, database and hosting. Tayar handles setup.': 'الكود وقاعدة البيانات والاستضافة على حساباتك. طيار يتولى الإعداد.', 'Infrastructure ready for publishing': 'البنية التشغيلية جاهزة للنشر', 'Connect your accounts after saving the project': 'اربط حساباتك بعد حفظ المشروع', 'Not required': 'غير مطلوب', 'Account': 'الحساب', 'Target': 'الوجهة', 'Connect account': 'وصل الحساب', 'Manage connection': 'إدارة الاتصال', 'Refresh connection status': 'تحديث حالة الاتصال', 'Connection setup is not available yet.': 'إعداد الاتصال غير متاح بعد.', 'Connection could not be completed. Try again.': 'تعذّر إكمال الاتصال. حاول مجدداً.', 'Connection status could not be refreshed.': 'تعذّر تحديث حالة الاتصال.', 'disconnected': 'غير متصل', 'connecting': 'جارٍ الاتصال', 'connected': 'متصل', 'permissions-missing': 'صلاحيات ناقصة', 'setup-incomplete': 'إعداد غير مكتمل', 'outdated-schema': 'مخطط قديم', 'deployment-failed': 'فشل النشر', 'credentials-revoked': 'أُلغيت الصلاحية', 'ready': 'جاهز', 'Secret could not be saved. Enter it again to retry.': 'تعذّر حفظ المفتاح. أدخله مجدداً لإعادة المحاولة.', 'Connection test failed. Check the configuration and try again.': 'فشل اختبار الاتصال. راجع الإعدادات وحاول مجدداً.', 'Choose exactly one environment before storing a credential.': 'اختر بيئة واحدة فقط قبل حفظ بيانات الاعتماد.', 'Checking credentials…': 'جارٍ التحقق من بيانات الاعتماد…', 'Check stored credentials': 'التحقق من بيانات الاعتماد المحفوظة', 'Stored credentials': 'بيانات اعتماد محفوظة', 'Missing references': 'مراجع مفقودة', 'Unlinked credentials': 'بيانات اعتماد غير مرتبطة', 'Credential check failed. Try again.': 'تعذّر التحقق من بيانات الاعتماد. حاول مجدداً.',
  'Stage': 'المرحلة', 'Open published website': 'فتح الموقع المنشور', 'Create and verify a preview first.': 'أنشئ نسخة معاينة وتحقق منها أولًا.', 'Publish on your infrastructure': 'انشر على بنيتك التشغيلية', 'Tayar prepares and verifies the release. Your connected accounts run it.': 'يُعد طيار الإصدار ويتحقق منه، ثم تشغّله حساباتك المتصلة.', 'Publishing endpoint is not available yet.': 'خدمة النشر غير متاحة بعد.',
  'Integrations': 'التكاملات', 'Connect analytics, payments, email, CRM, APIs and signed webhooks.': 'اربط التحليلات والمدفوعات والبريد الإلكتروني وإدارة علاقات العملاء وواجهات API وخطافات الويب الموقعة.', 'Provider': 'المزوّد', 'Add integration': 'إضافة تكامل', 'active': 'نشط', 'configuration issue': 'مشكلة في الإعداد', 'configuration issues': 'مشكلات في الإعداد', 'Enabled': 'مفعّل', 'Name': 'الاسم', 'Environments': 'البيئات', 'Events': 'الأحداث', 'Configured — enter to replace': 'تم الإعداد — أدخل قيمة للاستبدال', 'Testing…': 'جارٍ الاختبار…', 'Test connection': 'اختبار الاتصال', 'Remove': 'إزالة',
  'Choose GitHub repository': 'اختر مستودع GitHub',
  'Select the account and repository that will own your source code.': 'اختر الحساب والمستودع اللذين سيملكان كود مشروعك.',
  'Choose another account': 'اختر حساباً آخر',
  'Loading repositories...': 'جارٍ تحميل المستودعات...',
  'GitHub repositories are unavailable. Reconnect GitHub.': 'تعذّر عرض المستودعات. أعد ربط GitHub.',
  'Repository connection could not be verified. Try again.': 'تعذّر التحقق من ربط المستودع. حاول مجدداً.',
  'Repository connected. Publishing setup is still required.': 'تم ربط المستودع. ما زال إعداد النشر مطلوباً.',
  'Next page': 'الصفحة التالية',
  'Choose Vercel project': 'اختر مشروع Vercel',
  'Only projects linked to the selected GitHub repository are shown.': 'تظهر فقط المشاريع المرتبطة بمستودع GitHub المحدد.',
  'Loading Vercel projects...': 'جارٍ تحميل مشاريع Vercel...',
  'Vercel projects are unavailable. Reconnect Vercel.': 'تعذّر عرض مشاريع Vercel. أعد ربط Vercel.',
  'No matching Vercel project. Create or link one to the GitHub repository first.': 'لا يوجد مشروع Vercel مطابق. أنشئ مشروعاً أو اربطه بمستودع GitHub أولاً.',
  'Vercel project connection could not be verified. Try again.': 'تعذّر التحقق من ربط مشروع Vercel. حاول مجدداً.',
  'Vercel project connected. Deployment setup is still required.': 'تم ربط مشروع Vercel. ما زال إعداد النشر مطلوباً.',
  'Choose Supabase project': 'اختر مشروع Supabase',
  'Only active projects in organizations you own are shown. Tayar accounts are excluded.': 'تظهر فقط المشاريع النشطة في المؤسسات التي تملكها. تُستبعد حسابات طيار.',
  'Loading Supabase projects...': 'جارٍ تحميل مشاريع Supabase...',
  'Supabase projects are unavailable. Reconnect Supabase.': 'تعذّر عرض مشاريع Supabase. أعد ربط Supabase.',
  'No eligible Supabase project was found.': 'لم يُعثر على مشروع Supabase مؤهل.',
  'No eligible Supabase project was found. Use a project in a customer-owned Supabase organization that is separate from Tayar\'s platform organization, then reconnect Supabase.': 'لم يُعثر على مشروع Supabase مؤهل. استخدم مشروعًا في مؤسسة Supabase مملوكة للعميل ومنفصلة عن مؤسسة منصة طيار، ثم أعد ربط Supabase.',
  'No eligible Vercel project was found. Use a personal account or customer-owned team that is separate from Tayar\'s platform account, and link its project to this GitHub repository first.': 'لم يُعثر على مشروع Vercel مؤهل. استخدم حسابًا شخصيًا أو فريقًا مملوكًا للعميل ومنفصلًا عن حساب منصة طيار، واربط مشروعه بمستودع GitHub هذا أولًا.',
  'Supabase project connection could not be verified. Try again.': 'تعذّر التحقق من ربط مشروع Supabase. حاول مجدداً.',
  'Supabase project connected. Backend setup is still required.': 'تم ربط مشروع Supabase. ما زال إعداد الخلفية مطلوباً.',
  'Loading infrastructure status...': 'جارٍ تحميل حالة البنية التشغيلية...',
  'Infrastructure status is unavailable.': 'حالة البنية التشغيلية غير متاحة.',
};

export const svCmsSupplement: PhraseMap = {
  "Atomic quantity adjustments": "Atomära mängdändringar",
  "Use for stock, quotas or points. New records start at the minimum; changes use a protected adjustment.": "För lager, kvoter och poäng. Nya poster börjar vid minimum; ändringar använder en skyddad justering.",
  "Quantity field": "Mängdfält",
  "Minimum quantity": "Minsta mängd",
  "Maximum quantity (optional)": "Största mängd (valfritt)",
  "Whole numbers only": "Endast heltal",
  "Set the quantity field default to the minimum before saving.": "Sätt mängdfältets standardvärde till minimum innan du sparar.",
  "Save quantity rule": "Spara mängdregel",
  "Remove quantity rule": "Ta bort mängdregel",
  "Adjust quantity": "Ändra antal",
  "Atomic multi-item transaction": "Atomär transaktion med flera poster",
  "Create one parent record and its line items while updating every selected quantity in one protected operation.": "Skapa en huvudpost och dess rader medan alla valda antal uppdateras i en skyddad operation.",
  "Item table": "Posttabell", "Line table": "Radtabell", "Parent reference field": "Referensfält till huvudpost",
  "Item reference field": "Referensfält till post", "Line quantity field": "Radens antalsfält", "Quantity direction": "Antalsriktning",
  "Decrease": "Minska", "Increase": "Öka", "Save transaction rule": "Spara transaktionsregel", "Remove transaction rule": "Ta bort transaktionsregel",
  "Create transaction": "Skapa transaktion",

  "Booking conflict protection": "Skydd mot bokningskonflikter",
  "One resource cannot have overlapping bookings. Adjacent times are allowed. Cancelled states can release the time.": "En resurs kan inte ha överlappande bokningar. Angränsande tider tillåts. Avbokade tillstånd kan frigöra tiden.",
  "Booking resource": "Bokningsresurs",
  "Booking start": "Bokningens start",
  "Booking end": "Bokningens slut",
  "Booking status": "Bokningsstatus",
  "Every booking blocks time": "Varje bokning blockerar tiden",
  "States that block time": "Tillstånd som blockerar tiden",
  "Save booking rule": "Spara bokningsregel",
  "Remove booking rule": "Ta bort bokningsregel",

  'Application data view': 'Appens datavy',
  'Records load after secure application publishing and sign-in. Database permissions control every action.': 'Poster visas efter säker apppublicering och inloggning. Databasens behörigheter styr varje åtgärd.',
  'Visible columns': 'Synliga kolumner', 'Allowed actions': 'Tillåtna åtgärder',
  'Add record': 'Lägg till post', 'Edit record': 'Redigera post', 'Delete record': 'Ta bort post',
  'Search column': 'Sökkolumn', 'Records per page': 'Poster per sida',
  'Save data view': 'Spara datavy', 'Remove data view': 'Ta bort datavy',
  'Select valid columns and actions permitted by the table.': 'Välj giltiga kolumner och åtgärder som tabellen tillåter.',
  'Save the project before connecting your accounts.': 'Spara projektet innan du ansluter dina konton.',
  'Connect and verify your accounts before publishing.': 'Anslut och verifiera dina konton innan du publicerar.',
  'Add application data and access settings before linking a backend.': 'Lägg till appdata och åtkomstinställningar innan du ansluter en backend.',
  'Publishing is blocked. Check your connections and application configuration, then retry. This project has not been verified as ready.': 'Publiceringen är blockerad. Kontrollera anslutningarna och appens inställningar och försök igen. Projektets beredskap har inte verifierats.',
  'Code, database and hosting remain in your accounts. Provider billing, backups and ongoing administration belong to you after handover.': 'Kod, databas och drift finns kvar på dina konton. Efter överlämningen ansvarar du för leverantörernas fakturering, säkerhetskopior och löpande administration.',
  'A verified release runs independently of Tayar. Keep its runtime credentials in your hosting account; remove Tayar setup permissions only after verifying the handover.': 'En verifierad version körs oberoende av Tayar. Behåll dess driftuppgifter på ditt hostingkonto och ta bort Tayars inställningsbehörigheter först efter att överlämningen har verifierats.',
  'After handover, you manage these accounts and their billing. Tayar is used for project setup and future edits you request.': 'Efter överlämningen hanterar du dessa konton och deras fakturering. Tayar används för projektets inställningar och framtida ändringar som du begär.',
  'Connection setup is not available yet. Tayar must activate this provider before you can connect your account.': 'Anslutning är inte tillgänglig ännu. Tayar måste aktivera denna leverantör innan du kan ansluta ditt konto.',
  'Save the current project before publishing on your accounts.': 'Spara det aktuella projektet innan du publicerar på dina konton.',
  'HTML': 'HTML',
  'Application form data': 'Data för appformulär',
  'Bound forms require secure application publishing before they can accept records.': 'Kopplade formulär kräver säker apppublicering innan de kan ta emot poster.',
  'Target table': 'Måltabell', 'Select a table': 'Välj tabell', 'Select a field': 'Välj fält',
  'Calculated field': 'Beräknat fält', 'Calculation': 'Beräkning', 'Source fields': 'Källfält',
  'Sum': 'Summa', 'Subtract': 'Subtrahera', 'Multiply': 'Multiplicera',
  'Match every form field to a compatible application field.': 'Koppla varje formulärfält till ett kompatibelt appfält.',
  'Save data binding': 'Spara datakoppling', 'Remove data binding': 'Ta bort datakoppling',
  "Application backend connection": "Anslut appens backend",
  "Connect an existing dedicated backend with the matching application schema.": "Anslut en befintlig separat backend med matchande appschema.",
  "Save this project before linking a backend.": "Spara projektet innan du ansluter en backend.",
  "Checking backend…": "Kontrollerar backend…",
  "Backend linked": "Backend ansluten",
  "No verified backend connection.": "Ingen verifierad backendanslutning.",
  "Backend linked. Publishing still requires the remaining runtime checks.": "Backend är ansluten. Publicering kräver fortfarande återstående körningskontroller.",
  "Refresh backend status": "Uppdatera backendstatus",
  "Dedicated backend URL": "URL till separat backend",
  "Backend public key": "Backendens publika nyckel",
  "Backend service key": "Backendens tjänstenyckel",
  "The service key is encrypted on the server and cleared from this form after submission.": "Tjänstenyckeln krypteras på servern och rensas från formuläret efter att det skickats.",
  "Verify and link backend": "Verifiera och anslut backend",
  "Backend status is unavailable. Save the project and try again.": "Backendstatus är inte tillgänglig. Spara projektet och försök igen.",
  "Enter a valid backend service key.": "Ange en giltig tjänstenyckel för backend.",
  "The project changed. Review the backend connection again.": "Projektet har ändrats. Granska backendanslutningen igen.",
  "Backend linking failed. Check the saved schema and connection settings, then enter the service key again.": "Backendanslutningen misslyckades. Kontrollera det sparade schemat och anslutningsinställningarna och ange tjänstenyckeln igen.",
  'Plan application changes with AI': 'Planera appändringar med AI', 'Describe application changes': 'Beskriv appändringar', 'The project changed while AI was planning. Create a new plan.': 'Projektet ändrades medan AI planerade. Skapa en ny plan.', 'Application AI planning failed.': 'AI-planeringen av appen misslyckades.', 'AI returned an invalid application plan.': 'AI returnerade en ogiltig appplan.', 'AI returned an unsupported application operation.': 'AI returnerade en appåtgärd som inte stöds.', 'Describe the application changes first.': 'Beskriv appändringarna först.',
  'Application data and access': 'Appdata och åtkomst', 'Database and authentication require secure backend provisioning before publishing.': 'Databas och inloggning kräver säker backend innan publicering.', 'Data': 'Data', 'Enter a table name.': 'Ange ett tabellnamn.', 'Table name': 'Tabellnamn', 'Add table': 'Lägg till tabell', 'Table key': 'Tabellnyckel', 'Field': 'Fält', 'Key': 'Nyckel', 'Type': 'Typ', 'Related table': 'Relaterad tabell', 'Options (comma separated)': 'Alternativ (kommaseparerade)', 'Required': 'Obligatoriskt', 'Unique': 'Unikt', 'Index for queries': 'Indexera för sökningar', 'Default value': 'Standardvärde', 'No default': 'Inget standardvärde', 'Remove field': 'Ta bort fält', 'Add field': 'Lägg till fält', 'Permissions': 'Behörigheter', 'read': 'Läsa', 'create': 'Skapa', 'update': 'Uppdatera', 'delete': 'Ta bort', 'No access': 'Ingen åtkomst', 'Public': 'Offentlig', 'Authenticated': 'Inloggad', 'Record owner': 'Postens ägare', 'Role': 'Roll', 'Remove table': 'Ta bort tabell', 'Remove this table and its definition?': 'Ta bort tabellen och dess definition?', 'Auth and roles': 'Inloggning och roller', 'Enable authentication': 'Aktivera inloggning', 'Allow sign up': 'Tillåt registrering', 'Require email verification': 'Kräv e-postverifiering', 'Role name': 'Rollnamn', 'Add role': 'Lägg till roll',

  'Referenced by': 'Refereras av', 'Collection settings': 'Samlingsinställningar', 'Collection slug': 'Samlingsslug', 'Entry slug field': 'Slugfält för post', 'Referenced collection': 'Refererad samling', 'Duplicate entry': 'Duplicera post', 'This entry is referenced by other CMS content': 'Den här posten refereras av annat CMS-innehåll', 'Matching published entries': 'Matchande publicerade poster', 'Remove filter': 'Ta bort filter', 'Add filter': 'Lägg till filter',
  'Import / Export': 'Import / Export', 'Import collection': 'Importera samling', 'Export collection': 'Exportera samling', 'Export JSON': 'Exportera JSON', 'Export CSV': 'Exportera CSV', 'Import JSON': 'Importera JSON', 'Import CSV': 'Importera CSV', 'JSON · CSV': 'JSON · CSV', 'Import preview': 'Förhandsgranska import', 'Replace collection': 'Ersätt samling', 'Append entries': 'Lägg till poster', 'Field mapping': 'Fältmappning', 'Duplicate handling': 'Dubbletthantering', 'Skip duplicates': 'Hoppa över dubbletter', 'Update duplicates': 'Uppdatera dubbletter', 'Import validation failed': 'Importvalideringen misslyckades', 'Import complete': 'Importen är klar', 'Preview and validate imported content before changing the project.': 'Förhandsgranska och validera importerat innehåll innan projektet ändras.', 'Import file is too large': 'Importfilen är för stor', 'Imported collection': 'Importerad samling', 'Import as new collection': 'Importera som ny samling', 'Apply import': 'Tillämpa import', 'Import file does not contain a CMS collection.': 'Importfilen innehåller ingen CMS-samling.', 'Imported collection has no valid fields.': 'Den importerade samlingen har inga giltiga fält.', 'Some fields were skipped because the collection field limit was reached.': 'Vissa fält hoppades över eftersom fältgränsen för samlingen nåddes.', 'Some entries were skipped because the collection entry limit was reached.': 'Vissa poster hoppades över eftersom postgränsen för samlingen nåddes.', 'Some columns were skipped because the collection field limit was reached.': 'Vissa kolumner hoppades över eftersom fältgränsen för samlingen nåddes.', 'CSV file is empty.': 'CSV-filen är tom.', 'CSV file has no usable field columns.': 'CSV-filen har inga användbara fältkolumner.', 'CSV contains an unterminated quoted value.': 'CSV-filen innehåller ett citerat värde som inte avslutats.', 'CMS collection limit reached.': 'Gränsen för CMS-samlingar har nåtts.',
  'Multilingual CMS content': 'Flerspråkigt CMS-innehåll', 'Add language-specific values and slugs. Missing translations automatically use the default CMS value.': 'Lägg till språkspecifika värden och sluggar. Saknade översättningar använder automatiskt CMS-standardvärdet.', 'CMS collection': 'CMS-samling', 'CMS entry': 'CMS-post', 'Content language': 'Innehållsspråk', 'Add an entry before creating translations.': 'Lägg till en post innan du skapar översättningar.', 'Copy default values': 'Kopiera standardvärden', 'Use default fallback for every field': 'Använd standardvärden för alla fält', 'Use fallback': 'Använd reservvärde', 'Fallback': 'Reservvärde', 'Empty': 'Tomt', 'This collection has no localizable fields.': 'Den här samlingen har inga lokaliserbara fält.',
  'AI CMS assistant': 'AI-assistent för CMS', 'Review first': 'Granska först', 'AI plans CMS changes for review. New entries stay drafts and CMS content is never deleted automatically.': 'AI planerar CMS-ändringar för granskning. Nya poster förblir utkast och CMS-innehåll raderas aldrig automatiskt.', 'Describe CMS changes, entries, views, or translations…': 'Beskriv CMS-ändringar, poster, vyer eller översättningar…', 'Plan with AI': 'Planera med AI', 'Planning…': 'Planerar…', 'Review AI CMS plan': 'Granska AI-plan för CMS', 'Operations': 'Åtgärder', 'Cancel plan': 'Avbryt plan', 'Apply reviewed plan': 'Tillämpa granskad plan', 'Applied CMS operations': 'Tillämpade CMS-åtgärder', 'warnings': 'varningar', 'No safe CMS operations were returned.': 'Inga säkra CMS-åtgärder returnerades.', 'Describe the CMS changes you want first.': 'Beskriv först de CMS-ändringar du vill göra.', 'AI returned an invalid CMS plan.': 'AI returnerade en ogiltig CMS-plan.', 'CMS AI planning failed.': 'AI-planeringen för CMS misslyckades.', 'CMS AI plan could not be applied.': 'CMS-planen från AI kunde inte tillämpas.',
  'Live collaborators': 'Aktiva medarbetare', 'Live cursor': 'Livepekare', 'Editing this element': 'Redigerar detta element', 'Editing conflict': 'Redigeringskonflikt', 'Another collaborator is editing this element': 'En annan medarbetare redigerar detta element', 'Version comparison': 'Versionsjämförelse', 'Selective restore': 'Selektiv återställning', 'Added': 'Tillagt', 'Removed': 'Borttaget', 'Changed': 'Ändrat',
  'Manage multilingual content, routes, SEO, RTL and locale domains.': 'Hantera flerspråkigt innehåll, rutter, SEO, RTL och språkdomäner.', 'Editing language': 'Redigeringsspråk', 'Direction': 'Skrivriktning', 'Fallback language': 'Reservspråk', 'Locale path prefix': 'Sökvägsprefix för språk', 'Subdomain': 'Underdomän', 'Localized page name': 'Lokaliserat sidnamn', 'Localized slug': 'Lokaliserad slug', 'Translating…': 'Översätter…', 'Translate page with AI': 'Översätt sidan med AI',
  'Secure secret storage is not connected yet.': 'Säker lagring av hemligheter är inte ansluten ännu.', 'Infrastructure': 'Infrastruktur', 'Your accounts own the code, database and hosting. Tayar handles setup.': 'Dina konton äger koden, databasen och driften. Tayar sköter inställningen.', 'Infrastructure ready for publishing': 'Infrastrukturen är redo för publicering', 'Connect your accounts after saving the project': 'Anslut dina konton efter att projektet har sparats', 'Not required': 'Krävs inte', 'Account': 'Konto', 'Target': 'Mål', 'Connect account': 'Anslut konto', 'Manage connection': 'Hantera anslutning', 'Refresh connection status': 'Uppdatera anslutningsstatus', 'Connection setup is not available yet.': 'Anslutning är inte tillgänglig ännu.', 'Connection could not be completed. Try again.': 'Anslutningen kunde inte slutföras. Försök igen.', 'Connection status could not be refreshed.': 'Anslutningsstatus kunde inte uppdateras.', 'disconnected': 'Frånkopplad', 'connecting': 'Ansluter', 'connected': 'Ansluten', 'permissions-missing': 'Behörighet saknas', 'setup-incomplete': 'Inställningen är ofullständig', 'outdated-schema': 'Föråldrat schema', 'deployment-failed': 'Publiceringen misslyckades', 'credentials-revoked': 'Åtkomsten återkallad', 'ready': 'Redo', 'Secret could not be saved. Enter it again to retry.': 'Hemligheten kunde inte sparas. Ange den igen för att försöka på nytt.', 'Connection test failed. Check the configuration and try again.': 'Anslutningstestet misslyckades. Kontrollera inställningarna och försök igen.', 'Choose exactly one environment before storing a credential.': 'Välj exakt en miljö innan du sparar en autentiseringsuppgift.', 'Checking credentials…': 'Kontrollerar autentiseringsuppgifter…', 'Check stored credentials': 'Kontrollera sparade autentiseringsuppgifter', 'Stored credentials': 'Sparade autentiseringsuppgifter', 'Missing references': 'Saknade referenser', 'Unlinked credentials': 'Ej kopplade autentiseringsuppgifter', 'Credential check failed. Try again.': 'Det gick inte att kontrollera autentiseringsuppgifterna. Försök igen.',
  'Stage': 'Steg', 'Open published website': 'Öppna den publicerade webbplatsen', 'Create and verify a preview first.': 'Skapa och verifiera en förhandsversion först.', 'Publish on your infrastructure': 'Publicera på din infrastruktur', 'Tayar prepares and verifies the release. Your connected accounts run it.': 'Tayar förbereder och verifierar releasen. Dina anslutna konton kör den.', 'Publishing endpoint is not available yet.': 'Publiceringstjänsten är inte tillgänglig ännu.',
  'Integrations': 'Integrationer', 'Connect analytics, payments, email, CRM, APIs and signed webhooks.': 'Anslut analys, betalningar, e-post, CRM, API:er och signerade webhooks.', 'Provider': 'Leverantör', 'Add integration': 'Lägg till integration', 'active': 'aktiva', 'configuration issue': 'konfigurationsproblem', 'configuration issues': 'konfigurationsproblem', 'Enabled': 'Aktiverad', 'Name': 'Namn', 'Environments': 'Miljöer', 'Events': 'Händelser', 'Configured — enter to replace': 'Konfigurerad — ange ett värde för att ersätta', 'Testing…': 'Testar…', 'Test connection': 'Testa anslutning', 'Remove': 'Ta bort',
  'Choose Vercel project': 'Välj Vercel-projekt',
  'Only projects linked to the selected GitHub repository are shown.': 'Endast projekt som är kopplade till det valda GitHub-arkivet visas.',
  'Loading Vercel projects...': 'Läser in Vercel-projekt...',
  'Vercel projects are unavailable. Reconnect Vercel.': 'Vercel-projekten kan inte visas. Anslut Vercel igen.',
  'No matching Vercel project. Create or link one to the GitHub repository first.': 'Inget matchande Vercel-projekt. Skapa eller koppla ett till GitHub-arkivet först.',
  'Vercel project connection could not be verified. Try again.': 'Vercel-projektanslutningen kunde inte verifieras. Försök igen.',
  'Vercel project connected. Deployment setup is still required.': 'Vercel-projektet är anslutet. Publiceringen måste fortfarande konfigureras.',
  'Choose Supabase project': 'Välj Supabase-projekt',
  'Only active projects in organizations you own are shown. Tayar accounts are excluded.': 'Endast aktiva projekt i organisationer som du äger visas. Tayars konton undantas.',
  'Loading Supabase projects...': 'Läser in Supabase-projekt...',
  'Supabase projects are unavailable. Reconnect Supabase.': 'Supabase-projekten kan inte visas. Anslut Supabase igen.',
  'No eligible Supabase project was found.': 'Inget behörigt Supabase-projekt hittades.',
  'No eligible Supabase project was found. Use a project in a customer-owned Supabase organization that is separate from Tayar\'s platform organization, then reconnect Supabase.': 'Inget behörigt Supabase-projekt hittades. Använd ett projekt i en kundägd Supabase-organisation som är separat från Tayars plattformsorganisation och anslut sedan Supabase igen.',
  'No eligible Vercel project was found. Use a personal account or customer-owned team that is separate from Tayar\'s platform account, and link its project to this GitHub repository first.': 'Inget behörigt Vercel-projekt hittades. Använd ett personligt konto eller ett kundägt team som är separat från Tayars plattformskonto och koppla först dess projekt till det här GitHub-arkivet.',
  'Supabase project connection could not be verified. Try again.': 'Supabase-projektanslutningen kunde inte verifieras. Försök igen.',
  'Supabase project connected. Backend setup is still required.': 'Supabase-projektet är anslutet. Backend måste fortfarande konfigureras.',
  'Loading infrastructure status...': 'Läser in infrastrukturstatus...',
  'Infrastructure status is unavailable.': 'Infrastrukturstatus är inte tillgänglig.',
};

Object.assign(svCmsSupplement, {
  'Choose GitHub repository': 'Välj GitHub-arkiv',
  'Select the account and repository that will own your source code.': 'Välj kontot och arkivet som ska äga källkoden.',
  'Choose another account': 'Välj ett annat konto',
  'Loading repositories...': 'Läser in arkiv...',
  'GitHub repositories are unavailable. Reconnect GitHub.': 'Arkiven kan inte visas. Anslut GitHub igen.',
  'Repository connection could not be verified. Try again.': 'Arkivanslutningen kunde inte verifieras. Försök igen.',
  'Repository connected. Publishing setup is still required.': 'Arkivet är anslutet. Publicering måste fortfarande konfigureras.',
  'Next page': 'Nästa sida',
});
const cmsMaps: Record<Language, PhraseMap> = { en: {}, ar: arCmsSupplement, sv: svCmsSupplement };
export function localizeUi(text: string, language: Language): string { if (language === 'en') return text; return cmsMaps[language][text] ?? localizeBaseUi(text, language); }
export function useLocalizer() { const { prefs } = usePreferences(); const language = prefs.language; return useCallback((text: string) => localizeUi(text, language), [language]); }
