import { useCallback } from 'react';
import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arWorkspaceSupplement: PhraseMap = {
  'Search tools...': 'ابحث عن الأدوات...',
  'Clear search': 'مسح البحث',
  'Ungroup container': 'فك تجميع الحاوية',
  'Code Assistant': 'مساعد البرمجة',
  'Build, inspect, adapt, and reuse UI components with AI-assisted workflows.': 'أنشئ مكونات واجهة المستخدم وافحصها وكيّفها وأعد استخدامها عبر مسارات عمل مدعومة بالذكاء الاصطناعي.',
  'Remove image backgrounds privately with local in-browser AI. Image pixels stay on the user’s device.': 'أزل خلفيات الصور بخصوصية عبر ذكاء اصطناعي محلي داخل المتصفح؛ تبقى بكسلات الصورة على جهاز المستخدم.',
  'Profile CSV data locally and turn statistics into AI business insights.': 'حلّل بيانات CSV محلياً وحوّل الإحصاءات إلى رؤى أعمال بالذكاء الاصطناعي.',
  'Organize, edit, convert and optimize PDF files locally with 16 focused tools.': 'نظّم ملفات PDF وعدّلها وحوّلها وحسّنها محلياً باستخدام 16 أداة متخصصة.',
  'Invite teammates, manage roles and collaborate on shared projects.': 'ادعُ زملاء الفريق وأدر الأدوار وتعاون في المشاريع المشتركة.',
  'Build, operate, audit and publish production-ready websites.': 'أنشئ مواقع جاهزة للإنتاج وشغّلها ودقّقها وانشرها.',
  'Create a CV': 'إنشاء سيرة ذاتية',
  'Build a professional resume with AI assistance': 'أنشئ سيرة ذاتية احترافية بمساعدة الذكاء الاصطناعي',
  'Write a Cover Letter': 'كتابة خطاب تغطية',
  'Generate a tailored cover letter for any job': 'أنشئ خطاب تغطية مخصصاً لأي وظيفة',
  'Analyze a PDF': 'تحليل ملف PDF',
  'Upload and analyze any document with AI': 'ارفع أي مستند وحلّله بالذكاء الاصطناعي',
  'Translate Text': 'ترجمة نص',
  'Translate between any languages': 'ترجم بين أي لغات',
  'Write with AI': 'الكتابة بالذكاء الاصطناعي',
  'Generate any written content with AI': 'أنشئ أي محتوى مكتوب بالذكاء الاصطناعي',
  'Get help with study materials and notes': 'احصل على مساعدة في المواد الدراسية والملاحظات',
  'Improve My Resume': 'تحسين سيرتي الذاتية',
  'Optimize your CV for ATS and recruiters': 'حسّن سيرتك الذاتية لأنظمة ATS ومسؤولي التوظيف',
  'Summarize My Document': 'تلخيص مستندي',
  'Get a concise summary of any document': 'احصل على ملخص موجز لأي مستند',
  'Projects could not be loaded. Tool results are still available.': 'تعذر تحميل المشاريع، لكن نتائج الأدوات ما زالت متاحة.',
  'Open command palette': 'فتح لوحة الأوامر',
  'Show keyboard shortcuts': 'عرض اختصارات لوحة المفاتيح',
  'Toggle sidebar': 'إظهار أو إخفاء الشريط الجانبي',
  'Open settings': 'فتح الإعدادات',
  'Close dialogs / blur input': 'إغلاق النوافذ أو إلغاء تركيز حقل الإدخال',
  'Go to Dashboard': 'الانتقال إلى لوحة المعلومات',
  'Go to Files': 'الانتقال إلى الملفات',
  'Go to CV Builder': 'الانتقال إلى منشئ السيرة الذاتية',
  'Failed to delete': 'تعذر الحذف',
  'Moved to trash': 'نُقل إلى سلة المحذوفات',
  'Failed to update favorite': 'تعذر تحديث المفضلة',
  'Failed to update pin': 'تعذر تحديث التثبيت',
  'Failed to move': 'تعذر النقل',
  'Moved successfully': 'تم النقل بنجاح',
  'File type': 'نوع الملف',
  'Sort files': 'ترتيب الملفات',
  'Ascending': 'تصاعدي',
  'Descending': 'تنازلي',
  'Files could not be loaded.': 'تعذر تحميل الملفات.',
  'Try again': 'إعادة المحاولة',
  'Move file to Trash?': 'نقل الملف إلى سلة المحذوفات؟',
  'You can restore it later from Trash.': 'يمكنك استعادته لاحقًا من سلة المحذوفات.',
  'Move to Trash': 'نقل إلى سلة المحذوفات',
  'Notifications could not be updated.': 'تعذر تحديث الإشعارات.',
  'Delete notification': 'حذف الإشعار',
  'No supported source files were found in this folder.': 'لم يتم العثور على ملفات مصدر مدعومة في هذا المجلد.',
  'Could not create the code project.': 'تعذر إنشاء مشروع البرمجة.',
  'Code project imported: {count} source files{skipped}.': 'تم استيراد مشروع البرمجة: {count} من ملفات المصدر{skipped}.',
  ', {count} skipped': '، تم تخطي {count}',
  'Could not import this code folder.': 'تعذر استيراد مجلد البرمجة هذا.',
  'Code Project': 'مشروع برمجي',
  'Import a real project for Safe Apply': 'استورد مشروعًا حقيقيًا للتطبيق الآمن',
  'Choose a source folder. Tayar stores supported source files in My Files so Coding Assistance can review diffs, apply AI patches safely, and rollback changes.': 'اختر مجلد المصدر. يحفظ طيار ملفات المصدر المدعومة في ملفاتي لكي يتمكن مساعد البرمجة من مراجعة الفروقات وتطبيق تعديلات الذكاء الاصطناعي بأمان والتراجع عن التغييرات.',
  'Secrets, .env files, node_modules, build output, and unsupported binaries are skipped automatically.': 'يتم تلقائيًا تخطي الأسرار وملفات .env ومجلد node_modules ومخرجات البناء والملفات الثنائية غير المدعومة.',
  'Importing…': 'جارٍ الاستيراد…',
  'Import Code Folder': 'استيراد مجلد البرمجة',
};

export const svWorkspaceSupplement: PhraseMap = {
  'Search tools...': 'Sök verktyg...',
  'Clear search': 'Rensa sökning',
  'Ungroup container': 'Dela upp behållare',
  'Code Assistant': 'Kodassistent',
  'Build, inspect, adapt, and reuse UI components with AI-assisted workflows.': 'Bygg, granska, anpassa och återanvänd gränssnittskomponenter med AI-stödda arbetsflöden.',
  'Remove image backgrounds privately with local in-browser AI. Image pixels stay on the user’s device.': 'Ta bort bildbakgrunder privat med lokal AI i webbläsaren. Bildpixlarna stannar på användarens enhet.',
  'Profile CSV data locally and turn statistics into AI business insights.': 'Profilera CSV-data lokalt och omvandla statistik till affärsinsikter med AI.',
  'Organize, edit, convert and optimize PDF files locally with 16 focused tools.': 'Organisera, redigera, konvertera och optimera PDF-filer lokalt med 16 fokuserade verktyg.',
  'Invite teammates, manage roles and collaborate on shared projects.': 'Bjud in kollegor, hantera roller och samarbeta i delade projekt.',
  'Build, operate, audit and publish production-ready websites.': 'Bygg, hantera, granska och publicera produktionsklara webbplatser.',
  'Create a CV': 'Skapa ett CV',
  'Build a professional resume with AI assistance': 'Skapa ett professionellt CV med AI-hjälp',
  'Write a Cover Letter': 'Skriv ett personligt brev',
  'Generate a tailored cover letter for any job': 'Skapa ett anpassat personligt brev för valfritt jobb',
  'Analyze a PDF': 'Analysera en PDF',
  'Upload and analyze any document with AI': 'Ladda upp och analysera valfritt dokument med AI',
  'Translate Text': 'Översätt text',
  'Translate between any languages': 'Översätt mellan valfria språk',
  'Write with AI': 'Skriv med AI',
  'Generate any written content with AI': 'Skapa valfritt skriftligt innehåll med AI',
  'Get help with study materials and notes': 'Få hjälp med studiematerial och anteckningar',
  'Improve My Resume': 'Förbättra mitt CV',
  'Optimize your CV for ATS and recruiters': 'Optimera ditt CV för ATS och rekryterare',
  'Summarize My Document': 'Sammanfatta mitt dokument',
  'Get a concise summary of any document': 'Få en kort sammanfattning av valfritt dokument',
  'Projects could not be loaded. Tool results are still available.': 'Projekt kunde inte läsas in. Verktygsresultaten är fortfarande tillgängliga.',
  'Open command palette': 'Öppna kommandopaletten',
  'Show keyboard shortcuts': 'Visa kortkommandon',
  'Toggle sidebar': 'Visa eller dölj sidofältet',
  'Open settings': 'Öppna inställningar',
  'Close dialogs / blur input': 'Stäng dialoger eller lämna inmatningsfältet',
  'Go to Dashboard': 'Gå till instrumentpanelen',
  'Go to Files': 'Gå till filer',
  'Go to CV Builder': 'Gå till CV-byggaren',
  'Failed to delete': 'Det gick inte att ta bort',
  'Moved to trash': 'Flyttad till papperskorgen',
  'Failed to update favorite': 'Det gick inte att uppdatera favoriten',
  'Failed to update pin': 'Det gick inte att uppdatera fästmarkeringen',
  'Failed to move': 'Det gick inte att flytta',
  'Moved successfully': 'Flyttad',
  'File type': 'Filtyp',
  'Sort files': 'Sortera filer',
  'Ascending': 'Stigande',
  'Descending': 'Fallande',
  'Files could not be loaded.': 'Filerna kunde inte läsas in.',
  'Try again': 'Försök igen',
  'Move file to Trash?': 'Flytta filen till papperskorgen?',
  'You can restore it later from Trash.': 'Du kan återställa den senare från papperskorgen.',
  'Move to Trash': 'Flytta till papperskorgen',
  'Notifications could not be updated.': 'Aviseringarna kunde inte uppdateras.',
  'Delete notification': 'Ta bort avisering',
  'No supported source files were found in this folder.': 'Inga källfiler som stöds hittades i den här mappen.',
  'Could not create the code project.': 'Det gick inte att skapa kodprojektet.',
  'Code project imported: {count} source files{skipped}.': 'Kodprojekt importerat: {count} källfiler{skipped}.',
  ', {count} skipped': ', {count} hoppades över',
  'Could not import this code folder.': 'Det gick inte att importera den här kodmappen.',
  'Code Project': 'Kodprojekt',
  'Import a real project for Safe Apply': 'Importera ett riktigt projekt för säker tillämpning',
  'Choose a source folder. Tayar stores supported source files in My Files so Coding Assistance can review diffs, apply AI patches safely, and rollback changes.': 'Välj en källmapp. Tayar sparar källfiler som stöds i Mina filer så att Kodassistenten kan granska ändringar, tillämpa AI-patchar säkert och återställa ändringar.',
  'Secrets, .env files, node_modules, build output, and unsupported binaries are skipped automatically.': 'Hemligheter, .env-filer, node_modules, byggutdata och binärfiler som inte stöds hoppas över automatiskt.',
  'Importing…': 'Importerar…',
  'Import Code Folder': 'Importera kodmapp',
};

const workspaceMaps: Record<Language, PhraseMap> = {
  en: {},
  ar: arWorkspaceSupplement,
  sv: svWorkspaceSupplement,
};

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return workspaceMaps[language][text] ?? localizeBaseUi(text, language);
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  const language = prefs.language;
  return useCallback((text: string) => localizeUi(text, language), [language]);
}
