import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';
import { useCallback } from 'react';

type PhraseMap = Record<string, string>;

export const arSupplement: PhraseMap = {
  'configured': 'مُعدّ',
  'unconfigured': 'غير مُعدّ',
  'enabled': 'مفعّل',
  'needs attention': 'يحتاج إلى مراجعة',
  'missing': 'مفقود',
  'not verified': 'غير متحقق منه',
  'needs setup': 'يحتاج إلى إعداد',
  'test': 'اختبار',
  'live': 'فعلي',
  'APP_URL missing or invalid': 'قيمة APP_URL مفقودة أو غير صالحة',
  'Administrator accounts must be transferred and deleted by another administrator.': 'يجب نقل حسابات المسؤولين وحذفها بواسطة مسؤول آخر.',
  'Export Account Records': 'تصدير سجلات الحساب',
  'Help us improve by sharing optional product usage data': 'ساعدنا على التحسين بمشاركة بيانات استخدام المنتج الاختيارية',
  'Data uses encrypted network connections; storage security follows the configured providers and access controls.': 'تستخدم البيانات اتصالات شبكية مشفرة؛ ويتبع أمان التخزين المزوّدين المعدّين وضوابط الوصول.',
  'With your consent, product analytics and error monitoring may process page or action names, referrer, a session identifier linked to your signed-in account, browser or device data, network information and limited error diagnostics. Interaction autocapture and session replay are disabled, and project content is not intentionally included in analytics events.': 'بموافقتك، قد تعالج تحليلات المنتج ومراقبة الأخطاء أسماء الصفحات أو الإجراءات والمصدر ومعرّف جلسة مرتبطاً بحسابك المسجّل وبيانات المتصفح أو الجهاز ومعلومات الشبكة وتشخيصات محدودة للأخطاء. يكون الالتقاط التلقائي للتفاعلات وتسجيل الجلسات معطّلين، ولا يُضمّن محتوى المشاريع عمداً في أحداث التحليلات.',
  'Permanently delete your Tayar account, owned projects and stored files. An active subscription is canceled first. Limited billing, security and audit records may remain where legally required or needed to protect the service. This action cannot be undone.': 'احذف حساب Tayar والمشاريع التي تملكها والملفات المخزنة نهائياً. يُلغى الاشتراك النشط أولاً. قد تبقى سجلات محدودة للفوترة والأمان والتدقيق عندما يفرض القانون ذلك أو تكون لازمة لحماية الخدمة. لا يمكن التراجع عن هذا الإجراء.',
  'Deleting a user cancels any active Stripe subscription, removes owned storage and then permanently removes the account.': 'يلغي حذف المستخدم أي اشتراك Stripe نشط، ثم يزيل التخزين المملوك ويحذف الحساب نهائياً.',
  'Choose whether to also block this email from re-registering.': 'اختر ما إذا كنت تريد أيضاً منع هذا البريد من التسجيل مجدداً.',
  'We use necessary browser storage for sign-in and preferences. With your permission, we also record product analytics. See our': 'نستخدم تخزين المتصفح الضروري لتسجيل الدخول والتفضيلات. وبموافقتك، نسجل أيضاً تحليلات استخدام المنتج. راجع',
  'Operator identity details are incomplete. Public launch must remain blocked until they are configured.': 'بيانات هوية المشغّل غير مكتملة. يجب أن يبقى الإطلاق العام محظوراً حتى إعدادها.',
  'Required before launch': 'مطلوب قبل الإطلاق',
  'Legal name': 'الاسم القانوني',
  'Registration number': 'رقم التسجيل',
  'Postal address': 'العنوان البريدي',
  'Country': 'البلد',
  'Legal and privacy contact': 'جهة الاتصال القانونية والخصوصية',
  'Last updated:': 'آخر تحديث:',
  'year': 'سنة',
  'month': 'شهر',
  '1. Operator and scope': '1. المشغّل والنطاق',
  'This policy explains how the operator of Tayar Intelligence processes personal data when you use the workspace, public website features, support and billing flows.': 'توضح هذه السياسة كيف يعالج مشغّل Tayar Intelligence البيانات الشخصية عند استخدام مساحة العمل وميزات المواقع العامة والدعم وعمليات الفوترة.',
  '2. Data we process': '2. البيانات التي نعالجها',
  'Depending on the features you use, we process account and profile details, authentication identifiers, projects and files, AI conversations and usage records, preferences, support requests, subscription status, team activity, and security or operational events.': 'بحسب الميزات التي تستخدمها، نعالج بيانات الحساب والملف الشخصي ومعرّفات المصادقة والمشاريع والملفات ومحادثات الذكاء الاصطناعي وسجلات الاستخدام والتفضيلات وطلبات الدعم وحالة الاشتراك ونشاط الفريق والأحداث الأمنية أو التشغيلية.',
  'Website Builder may also store published pages and media, release history, form submissions, leads and privacy-limited analytics events for sites you operate.': 'قد يخزّن منشئ المواقع أيضاً الصفحات والوسائط المنشورة وسجل الإصدارات وإرسالات النماذج والعملاء المحتملين وأحداث تحليلات محدودة مراعية للخصوصية للمواقع التي تديرها.',
  '3. Purposes and legal grounds': '3. الأغراض والأسس القانونية',
  'We process data as needed to provide and secure the service, save your work, enforce permissions and plan limits, respond to support, and administer subscriptions. Depending on the context, the legal ground may be performance of a contract, legitimate interests in protecting and improving the service, consent for optional analytics, or compliance with a legal obligation.': 'نعالج البيانات بالقدر اللازم لتقديم الخدمة وتأمينها وحفظ عملك وفرض الصلاحيات وحدود الخطط والاستجابة للدعم وإدارة الاشتراكات. بحسب السياق، قد يكون الأساس القانوني تنفيذ عقد أو المصلحة المشروعة في حماية الخدمة وتحسينها أو الموافقة على التحليلات الاختيارية أو الامتثال لالتزام قانوني.',
  '4. AI and external processing': '4. الذكاء الاصطناعي والمعالجة الخارجية',
  'AI requests are sent only when you choose an AI-powered action. The prompt and content needed for that action may be sent to the AI or image provider configured by the operator. Do not submit sensitive data unless it is necessary and you are authorized to do so.': 'لا تُرسل طلبات الذكاء الاصطناعي إلا عندما تختار إجراءً يعتمد عليه. قد يُرسل الطلب والمحتوى اللازمان لذلك الإجراء إلى مزوّد الذكاء الاصطناعي أو الصور الذي أعدّه المشغّل. لا ترسل بيانات حساسة إلا عند الضرورة وإذا كنت مخولاً بذلك.',
  '5. Website visitors': '5. زوار المواقع',
  'If you publish a site with Tayar, you are responsible for the notices, permissions and lawful use of visitor information collected through your site. Tayar handles form submissions and configured analytics to provide those Website Builder features to your account.': 'إذا نشرت موقعاً عبر Tayar، فأنت مسؤول عن الإشعارات والأذونات والاستخدام القانوني لمعلومات الزوار التي يجمعها موقعك. يعالج Tayar إرسالات النماذج والتحليلات المعدّة لتوفير ميزات منشئ المواقع لحسابك.',
  '6. Providers, payments and transfers': '6. المزوّدون والمدفوعات وعمليات النقل',
  'Supabase provides authentication, database and storage capabilities. Stripe handles Checkout, payment methods, invoices and subscription management; Tayar stores billing identifiers and subscription status, not full payment-card details. Configured AI, email, monitoring or hosting providers process only the information needed for their service.': 'يوفّر Supabase المصادقة وقاعدة البيانات والتخزين. يتولى Stripe الدفع ووسائل الدفع والفواتير وإدارة الاشتراكات؛ ويخزّن Tayar معرّفات الفوترة وحالة الاشتراك، لا تفاصيل بطاقات الدفع الكاملة. يعالج مزوّدو الذكاء الاصطناعي أو البريد أو المراقبة أو الاستضافة المعدّون المعلومات اللازمة لخدماتهم فقط.',
  'Provider locations can vary. Where personal data is transferred internationally, the operator relies on the safeguards available under its provider agreements and applicable law. Contact us for the current provider list and transfer details.': 'قد تختلف مواقع المزوّدين. عند نقل البيانات الشخصية دولياً، يعتمد المشغّل على الضمانات المتاحة في اتفاقياته مع المزوّدين والقانون المعمول به. تواصل معنا للحصول على قائمة المزوّدين الحالية وتفاصيل النقل.',
  '7. Retention and deletion': '7. الاحتفاظ والحذف',
  'Account and project data is generally kept while your account is active. Account deletion cancels an active Tayar subscription and removes the active account, owned project records and owned storage controlled by Tayar. Limited billing, security, fraud-prevention, dispute and audit records may remain when needed for legal obligations or legitimate service protection.': 'تُحتفظ بيانات الحساب والمشاريع عموماً ما دام حسابك نشطاً. يؤدي حذف الحساب إلى إلغاء اشتراك Tayar النشط وإزالة الحساب النشط وسجلات المشاريع المملوكة والتخزين المملوك الذي يتحكم به Tayar. قد تبقى سجلات محدودة للفوترة والأمان ومنع الاحتيال والنزاعات والتدقيق عندما تلزم للامتثال القانوني أو الحماية المشروعة للخدمة.',
  '8. Security': '8. الأمان',
  'The application uses encrypted network connections, authenticated server functions and database access controls, including Row Level Security for user and workspace data. No online service can guarantee absolute security.': 'يستخدم التطبيق اتصالات شبكة مشفرة ووظائف خادم موثقة وضوابط وصول لقاعدة البيانات، بما فيها أمان مستوى الصف لبيانات المستخدم ومساحة العمل. لا يمكن لأي خدمة عبر الإنترنت ضمان الأمان المطلق.',
  '9. Browser storage and analytics': '9. تخزين المتصفح والتحليلات',
  'Necessary browser storage supports authentication sessions, interface preferences, recovery and consent choices. Product analytics is off until you consent and can be disabled later in Settings. Tayar does not currently activate a separate marketing-cookie category.': 'يدعم تخزين المتصفح الضروري جلسات المصادقة وتفضيلات الواجهة والاسترداد وخيارات الموافقة. تكون تحليلات المنتج متوقفة حتى توافق عليها ويمكن تعطيلها لاحقاً من الإعدادات. لا يفعّل Tayar حالياً فئة مستقلة لملفات ارتباط تسويقية.',
  '10. Your choices and rights': '10. خياراتك وحقوقك',
  'Settings provides account-data export, analytics consent controls and account deletion. Depending on applicable law, you may also request access, correction, restriction, portability or objection, withdraw consent, and complain to a competent data-protection authority. Use the account support flow or the legal contact above.': 'توفر الإعدادات تصدير بيانات الحساب والتحكم بالموافقة على التحليلات وحذف الحساب. بحسب القانون المعمول به، قد يحق لك أيضاً طلب الوصول أو التصحيح أو التقييد أو النقل أو الاعتراض وسحب الموافقة وتقديم شكوى إلى جهة مختصة بحماية البيانات. استخدم مسار دعم الحساب أو جهة الاتصال القانونية أعلاه.',
  'Settings provides account-data export, analytics consent controls and account deletion. Depending on applicable law, you may also request access, correction, restriction, portability or objection, withdraw consent, and complain to a competent data-protection authority. Use the in-product account support flow.': 'توفر الإعدادات تصدير بيانات الحساب والتحكم بالموافقة على التحليلات وحذف الحساب. بحسب القانون المعمول به، قد يحق لك أيضاً طلب الوصول أو التصحيح أو التقييد أو النقل أو الاعتراض وسحب الموافقة وتقديم شكوى إلى جهة مختصة بحماية البيانات. استخدم مسار دعم الحساب داخل المنتج.',
  '11. Changes': '11. التغييرات',
  'This policy may be updated as the product, providers or legal requirements change. Material changes should be communicated through the service when appropriate, and the revision date above will be updated.': 'قد تُحدّث هذه السياسة عند تغير المنتج أو المزوّدين أو المتطلبات القانونية. ستُبلّغ التغييرات الجوهرية عبر الخدمة عند الاقتضاء وسيُحدّث تاريخ المراجعة أعلاه.',
  'the operator country shown above': 'بلد المشغّل الموضح أعلاه',
  '1. Operator and agreement': '1. المشغّل والاتفاق',
  'These Terms govern your use of Tayar Intelligence. By creating an account or using the service, you agree to these Terms. If you use Tayar for an organization, you confirm that you are authorized to accept them for that organization.': 'تحكم هذه الشروط استخدامك لـTayar Intelligence. بإنشاء حساب أو استخدام الخدمة، فإنك توافق عليها. وإذا استخدمت Tayar لصالح مؤسسة، فأنت تؤكد أنك مخول بقبولها نيابة عنها.',
  '2. Accounts and access': '2. الحسابات والوصول',
  'You must provide accurate account information, protect your sign-in credentials and promptly report suspected unauthorized access. You are responsible for activity performed through your account and for choosing appropriate team permissions.': 'يجب أن تقدم معلومات حساب دقيقة وتحمي بيانات تسجيل الدخول وتبلغ فوراً عن أي وصول غير مصرح به مشتبه فيه. أنت مسؤول عن النشاط المنفذ عبر حسابك وعن اختيار صلاحيات الفريق المناسبة.',
  '3. Your content': '3. محتواك',
  'You keep ownership of content you submit or create. You give the operator a limited permission to host, copy, process and transmit that content only as needed to provide, secure and support the service. You must have the rights and permissions needed for content you upload, publish or share.': 'تحتفظ بملكية المحتوى الذي ترسله أو تنشئه. تمنح المشغّل إذناً محدوداً لاستضافة ذلك المحتوى ونسخه ومعالجته ونقله بالقدر اللازم فقط لتقديم الخدمة وتأمينها ودعمها. يجب أن تملك الحقوق والأذونات اللازمة للمحتوى الذي ترفعه أو تنشره أو تشاركه.',
  '4. AI-assisted output': '4. المخرجات المدعومة بالذكاء الاصطناعي',
  'AI output may be inaccurate, incomplete or unsuitable. You are responsible for reviewing output before relying on it, publishing it or using it for legal, medical, financial, employment or other consequential decisions.': 'قد تكون مخرجات الذكاء الاصطناعي غير دقيقة أو غير مكتملة أو غير مناسبة. أنت مسؤول عن مراجعتها قبل الاعتماد عليها أو نشرها أو استخدامها في قرارات قانونية أو طبية أو مالية أو وظيفية أو قرارات أخرى ذات أثر.',
  '5. Acceptable use': '5. الاستخدام المقبول',
  'You may not use the service to violate law or third-party rights, process data without authorization, distribute malicious or deceptive content, abuse forms or APIs, bypass limits or security controls, scrape other accounts, or disrupt the platform.': 'لا يجوز استخدام الخدمة لانتهاك القانون أو حقوق الغير أو معالجة البيانات دون تصريح أو توزيع محتوى ضار أو مضلل أو إساءة استخدام النماذج أو واجهات API أو تجاوز الحدود أو ضوابط الأمان أو جمع بيانات حسابات أخرى أو تعطيل المنصة.',
  '6. Published sites and visitor data': '6. المواقع المنشورة وبيانات الزوار',
  'You are responsible for sites you publish, including their content, domains, legal notices, accessibility, visitor consent and handling of leads or analytics. Remove or correct unlawful content promptly.': 'أنت مسؤول عن المواقع التي تنشرها، بما يشمل محتواها ونطاقاتها وإشعاراتها القانونية وإمكانية الوصول وموافقة الزوار ومعالجة العملاء المحتملين أو التحليلات. أزل المحتوى غير القانوني أو صححه فوراً.',
  '7. Plans, renewal and cancellation': '7. الخطط والتجديد والإلغاء',
  'The current features, usage limits, amount, currency and billing interval are shown in the product and Stripe Checkout. Paid subscriptions renew automatically until canceled. You can manage or cancel a subscription through the Stripe billing portal, with access continuing as shown there. Any taxes actually charged are shown in Checkout before purchase.': 'تظهر الميزات الحالية وحدود الاستخدام والمبلغ والعملة وفترة الفوترة في المنتج وعند الدفع عبر Stripe. تتجد الاشتراكات المدفوعة تلقائياً حتى إلغائها. يمكنك إدارة الاشتراك أو إلغاؤه عبر بوابة فوترة Stripe، ويستمر الوصول كما هو موضح هناك. وتظهر أي ضرائب تُفرض فعلياً في صفحة الدفع قبل الشراء.',
  'Nothing in these Terms removes mandatory consumer rights, including any applicable withdrawal, refund or digital-service remedies. Contact support promptly if you believe a charge is incorrect.': 'لا تلغي هذه الشروط حقوق المستهلك الإلزامية، بما فيها أي حقوق سحب أو استرداد أو تعويضات للخدمات الرقمية تنطبق عليك. تواصل مع الدعم فوراً إذا اعتقدت أن رسماً غير صحيح.',
  '8. Service changes and availability': '8. تغييرات الخدمة وتوفرها',
  'Tayar may change, add or retire features and may interrupt access for maintenance, security or circumstances outside reasonable control. Pilot and preview features may change more frequently and are not promised for uninterrupted production use.': 'قد يغيّر Tayar الميزات أو يضيفها أو يوقفها، وقد يقطع الوصول للصيانة أو الأمان أو لظروف خارجة عن السيطرة المعقولة. قد تتغير الميزات التجريبية والمعاينات بوتيرة أكبر ولا يُتعهد بتشغيلها الإنتاجي دون انقطاع.',
  '9. Suspension, termination and deletion': '9. التعليق والإنهاء والحذف',
  'Access may be limited or suspended when reasonably necessary to protect users, enforce these Terms, prevent abuse or comply with law. You may stop using the service at any time and can request account deletion in Settings. Subscription cancellation and account deletion are separate actions unless the deletion flow states otherwise.': 'قد يُقيّد الوصول أو يُعلّق عند الضرورة المعقولة لحماية المستخدمين أو تطبيق هذه الشروط أو منع الإساءة أو الامتثال للقانون. يمكنك التوقف عن استخدام الخدمة في أي وقت وطلب حذف الحساب من الإعدادات. إلغاء الاشتراك وحذف الحساب إجراءان منفصلان ما لم ينص مسار الحذف على خلاف ذلك.',
  '10. Disclaimers': '10. إخلاء المسؤولية',
  'Except for rights and guarantees that cannot legally be excluded, the service is provided as available without a promise that every feature or generated output will be error-free or fit for every purpose.': 'باستثناء الحقوق والضمانات التي لا يمكن استبعادها قانوناً، تُقدم الخدمة بحسب توفرها دون تعهد بأن كل ميزة أو مخرج منشأ سيكون خالياً من الأخطاء أو مناسباً لكل غرض.',
  '11. Liability': '11. المسؤولية',
  'Nothing limits liability that cannot legally be limited. Otherwise, each party is responsible for reasonably foreseeable direct loss caused by its breach, and the operator is not responsible for indirect loss or third-party services outside its control to the extent permitted by law.': 'لا يحد أي نص من مسؤولية لا يجوز قانوناً الحد منها. وفيما عدا ذلك، يتحمل كل طرف الخسارة المباشرة المتوقعة بصورة معقولة والناجمة عن إخلاله، ولا يكون المشغّل مسؤولاً عن الخسارة غير المباشرة أو خدمات الغير الخارجة عن سيطرته بالقدر الذي يسمح به القانون.',
  '12. Governing law and disputes': '12. القانون الحاكم والنزاعات',
  'These Terms are governed by the laws of': 'تخضع هذه الشروط لقوانين',
  'These Terms are governed by applicable law.': 'تخضع هذه الشروط للقانون المعمول به.',
  'This does not deprive consumers of mandatory protections available in their country of residence. Contact support first so the parties can try to resolve a concern informally.': 'لا يحرم ذلك المستهلكين من الحماية الإلزامية المتاحة في بلد إقامتهم. تواصل مع الدعم أولاً كي يحاول الطرفان حل المشكلة ودياً.',
  '13. Contact': '13. التواصل',
  'Questions about these Terms, billing or the service can be submitted through the in-product support flow or the legal contact listed above.': 'يمكن إرسال الأسئلة عن هذه الشروط أو الفوترة أو الخدمة عبر مسار الدعم داخل المنتج أو جهة الاتصال القانونية المذكورة أعلاه.',
  'Questions about these Terms, billing or the service can be submitted through the in-product support flow.': 'يمكن إرسال الأسئلة عن هذه الشروط أو الفوترة أو الخدمة عبر مسار الدعم داخل المنتج.',
  'Close menu': 'إغلاق القائمة',
  'Open menu': 'فتح القائمة',
  'unread': 'غير مقروء',
  'Current subscriptions by plan': 'الاشتراكات الحالية حسب الخطة',
  'Active · cancels at period end': 'نشط · يُلغى عند نهاية الفترة',
  'Billing / Access Date': 'تاريخ الفوترة / الوصول',
  'Only runtime-enforced platform settings are editable here.': 'يمكن هنا تعديل إعدادات المنصة التي تُطبَّق فعليًا أثناء التشغيل فقط.',
  'Authoritative controls': 'عناصر التحكم المعتمدة',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'تتم إدارة الوصول إلى الأدوات وحدود الاستخدام من قسم Tools، بينما تتم إدارة مزود الذكاء الاصطناعي والنماذج من AI Management. تم إخفاء الإعدادات القديمة التي لا تؤثر فعليًا في سلوك النظام.',
  'API key inventory only': 'قائمة مفاتيح API فقط',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'هذه الصفوف بيانات وصفية فقط ولا تفعّل أو تعطّل أسرار الإنتاج التي تستخدمها Edge Functions. دوّر الأسرار الحية أو احذفها من أسرار مشروع Supabase.',
  'Read-only service metadata': 'بيانات وصفية للخدمات للقراءة فقط',
  'Failed to toggle tool': 'فشل تغيير حالة الأداة',
  'disabled': 'معطّل',
  'Failed to update tool plan': 'فشل تحديث خطة الأداة',
  'Failed to update usage limits': 'فشل تحديث حدود الاستخدام',
  'usage limits updated': 'تم تحديث حدود الاستخدام',
  'Tool plan access & limits': 'الوصول وحدود الاستخدام حسب الخطة',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'اختر الخطة التي يمكنها الوصول إلى كل أداة وحدد عدد الاستخدامات الناجحة المتاحة لمستخدمي Free وPro وBusiness يوميًا أو شهريًا أو مدى الحياة. اترك الحد فارغًا للاستخدام غير المحدود.',
  'Minimum plan': 'الحد الأدنى للخطة',
  'Reset period': 'فترة إعادة التعيين',
  'Daily': 'يومي',
  'Monthly': 'شهري',
  'Lifetime': 'مدى الحياة',
  'Unlimited': 'غير محدود',
  'recorded uses': 'استخدامات مسجلة',
  'Save limits': 'حفظ الحدود',
  'live quota': 'حد الاستخدام المباشر',
  'Processing...': 'جارٍ المعالجة...',
  'Change sort direction': 'تغيير اتجاه الفرز',
  'Grid view': 'عرض شبكي',
  'List view': 'عرض قائمة',
  'File actions': 'إجراءات الملف',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'اكتملت عملية الدفع. نقوم الآن بمزامنة اشتراكك، وسيتم تحديث خطتك تلقائيًا.',
  'Checkout was canceled. No plan change was made.': 'تم إلغاء عملية الدفع. لم يتم تغيير خطتك.',
  'Account menu': 'قائمة الحساب',
  'Could not clean this file.': 'تعذر تنظيف هذا الملف.',
  'Could not create invoice output.': 'تعذر إنشاء مخرجات الفاتورة.',
  'Could not generate this letter.': 'تعذر إنشاء هذا الخطاب.',
  'Could not generate names.': 'تعذر إنشاء الأسماء.',
  'Checking access...': 'جارٍ التحقق من الوصول...',
  'Access check unavailable': 'تعذر التحقق من الوصول',
  'We could not safely verify your plan. Please retry in a moment.': 'تعذر التحقق من خطتك بأمان. يرجى المحاولة مرة أخرى بعد قليل.',
  'Tool temporarily unavailable': 'الأداة غير متاحة مؤقتًا',
  'This tool has been disabled by the administrator.': 'تم تعطيل هذه الأداة بواسطة المسؤول.',
  'Usage limit reached': 'تم بلوغ حد الاستخدام',
  'View plans': 'عرض الخطط',
  'Website published successfully. Release history was skipped:': 'تم نشر الموقع بنجاح. تم تخطي سجل الإصدارات:',
  'Continue with Google': 'المتابعة باستخدام Google',
  'Start free with your Tayar workspace, Website Builder and included tools.': 'ابدأ مجانًا مع مساحة عمل Tayar ومنشئ المواقع والأدوات المتضمنة.',
  '1 Website Builder project with up to 3 pages': 'مشروع Website Builder واحد حتى 3 صفحات',
  'Free-access tools with Free plan usage limits': 'أدوات الخطة المجانية ضمن حدود استخدام Free',
  'Sign in to continue to your Tayar workspace.': 'سجّل الدخول للمتابعة إلى مساحة عمل Tayar.',
  'Quick setup': 'إعداد سريع',
  'One workspace for websites, documents, AI tools and client work. Personalize your setup, or skip and explore right away.': 'مساحة واحدة للمواقع والمستندات وأدوات الذكاء الاصطناعي وأعمال العملاء. خصّص إعدادك أو تخطَّ الخطوات واستكشف مباشرة.',
  'Personalize my workspace': 'تخصيص مساحة عملي',
  'Skip for now': 'تخطي الآن',
  'You can change your language, profile and preferences later in Settings.': 'يمكنك تغيير اللغة والملف الشخصي والتفضيلات لاحقًا من الإعدادات.',
  'Build and publish a website': 'بناء ونشر موقع',
  'Study, write and organize work with focused tools': 'ادرس واكتب ونظّم عملك بأدوات مركزة',
  'Build CVs, cover letters and job-ready documents': 'أنشئ سيرًا ذاتية وخطابات تقديم ومستندات جاهزة للعمل',
  'Create documents and everyday work from one workspace': 'أنشئ المستندات وأنجز عملك اليومي من مساحة واحدة',
  'Build your web presence and manage business workflows': 'ابنِ حضورك على الويب وأدر سير عملك التجاري',
  'Build, write and deliver client work from one workspace': 'ابنِ واكتب وسلّم أعمال العملاء من مساحة واحدة',
  'Browse your tools, recommendations and recent activity from one place.': 'استعرض أدواتك وتوصياتك ونشاطك الأخير من مكان واحد.',
  'Your projects, files and everyday work stay together here.': 'تبقى مشاريعك وملفاتك وعملك اليومي مجتمعة هنا.',
  'Build and publish a responsive website with manual controls and guided workflows.': 'أنشئ وانشر موقعًا متجاوبًا مع تحكم يدوي وسير عمل موجّه.',
  'Find saved documents, exports and project files without hunting across tools.': 'اعثر على المستندات المحفوظة والصادرات وملفات المشاريع بدون البحث بين الأدوات.',
  'See your current plan, included limits and billing options in one place.': 'شاهد خطتك الحالية والحدود المتضمنة وخيارات الفوترة في مكان واحد.',
  'Your Tayar workspace is ready. Start with the recommendation below or explore everything at your own pace.': 'مساحة عمل Tayar جاهزة. ابدأ بالتوصية أدناه أو استكشف كل شيء بالسرعة التي تناسبك.',
  'Explore all tools': 'استكشف كل الأدوات',
  'Browse every available tool and choose what you need.': 'استعرض كل الأدوات المتاحة واختر ما تحتاجه.',
  'Take the product tour': 'ابدأ جولة المنتج',
  'See where projects, tools and plan controls live.': 'تعرّف على مكان المشاريع والأدوات والتحكم بالخطة.',
  'Start with your recommended tool': 'ابدأ بالأداة الموصى بها',
  'Review your plan and limits': 'راجع خطتك وحدودها',
  'project': 'مشروع',
  'projects': 'مشاريع',
  'No-code AI Provider Control': 'إدارة مزودي الذكاء الاصطناعي بدون كود',
  'Add a provider, Base URL, Model ID and API secret here. Secrets stay in Supabase Vault. After this control layer is installed, adding or changing providers does not require code changes or database changes.': 'أضف هنا المزود والرابط الأساسي ومعرّف النموذج وسر API. تبقى الأسرار محفوظة في Supabase Vault. بعد تفعيل طبقة التحكم هذه، لا يتطلب إضافة المزودين أو تغييرهم أي تعديل على الكود أو قاعدة البيانات.',
  'Current Gemini fallback active': 'إعداد Gemini الاحتياطي الحالي نشط',
  'Backend not enabled': 'الواجهة الخلفية غير مفعلة',
  'No managed provider has been added yet. Tayar continues using the current Gemini environment configuration until you add and activate one.': 'لم تتم إضافة مزود مُدار بعد. سيستمر Tayar باستخدام إعداد Gemini الحالي من متغيرات البيئة حتى تضيف مزودًا وتفعّله.',
  'Key': 'المفتاح',
  'Adapter': 'الموائم',
  'Base URL': 'الرابط الأساسي',
  'Model ID': 'معرّف النموذج',
  'Secret configured in Vault': 'السر محفوظ في Vault',
  'API secret missing': 'سر API مفقود',
  'Test': 'اختبار',
  'Make Default': 'تعيين كافتراضي',
  'Disable': 'تعطيل',
  'Enable': 'تفعيل',
  'Edit AI Provider': 'تعديل مزود الذكاء الاصطناعي',
  'Add AI Provider': 'إضافة مزود ذكاء اصطناعي',
  'Leave API Secret empty while editing to keep the existing secret.': 'اترك حقل سر API فارغًا أثناء التعديل للاحتفاظ بالسر الحالي.',
  'Provider Key': 'مفتاح المزود',
  'Display Name': 'اسم العرض',
  'API Secret': 'سر API',
  'Leave blank to keep current secret': 'اتركه فارغًا للاحتفاظ بالسر الحالي',
  'Save Provider': 'حفظ المزود',
  'Current Gemini fallback': 'إعداد Gemini الاحتياطي الحالي',
  'This keeps Tayar working exactly as it does today when no managed provider is active.': 'يحافظ هذا على عمل Tayar بالطريقة الحالية نفسها عندما لا يكون هناك مزود مُدار نشط.',
  'Save fallback': 'حفظ الإعداد الاحتياطي',
  'Configuration Center': 'مركز الإعدادات',
  'Manage AI providers, Stripe prices and coupons from the Admin Panel without editing application code. API secrets remain server-side and are never shown back in the browser.': 'أدر مزودي الذكاء الاصطناعي وأسعار Stripe والكوبونات من لوحة الإدارة بدون تعديل كود التطبيق. تبقى أسرار API على الخادم ولا يتم عرضها مرة أخرى في المتصفح.',
  'Refresh status': 'تحديث الحالة',
  'AI Providers': 'مزودو الذكاء الاصطناعي',
  'Add, test, enable and choose the default provider': 'أضف المزودين واختبرهم وفعّلهم واختر المزود الافتراضي',
  'Gemini fallback': 'Gemini الاحتياطي',
  'Secret': 'السر',
  'Configured securely': 'مُعدّ بأمان',
  'Manage AI Providers': 'إدارة مزودي الذكاء الاصطناعي',
  'Payments & Pricing': 'المدفوعات والتسعير',
  'Manage Stripe prices and promotion codes': 'إدارة أسعار Stripe ورموز الخصم',
  'Stripe': 'Stripe',
  'Not connected': 'غير متصل',
  'Checkout / Portal': 'الدفع / البوابة',
  'Ready': 'جاهز',
  'Manage Prices & Coupons': 'إدارة الأسعار والكوبونات',
  'Safe operating model: adding a compatible AI provider or changing the active Stripe price is done from Admin. Existing subscribers keep their historical Stripe price unless you explicitly migrate them later.': 'نموذج تشغيل آمن: تتم إضافة مزود ذكاء اصطناعي متوافق أو تغيير سعر Stripe النشط من لوحة الإدارة. يحتفظ المشتركون الحاليون بسعر Stripe التاريخي الخاص بهم ما لم تقم بترحيلهم صراحةً لاحقًا.',
  'Always': 'دائمًا',
  'Enter a valid price greater than zero.': 'أدخل سعرًا صالحًا أكبر من صفر.',
  'Create and activate a new Stripe price for': 'إنشاء وتفعيل سعر Stripe جديد لخطة',
  'new price created and activated for new checkouts.': 'تم إنشاء السعر الجديد وتفعيله لعمليات الدفع الجديدة.',
  'Coupon code is required.': 'رمز الكوبون مطلوب.',
  'Coupon created and activated.': 'تم إنشاء الكوبون وتفعيله.',
  'Disable this promotion code?': 'هل تريد تعطيل رمز الخصم هذا؟',
  'Coupon disabled.': 'تم تعطيل الكوبون.',
  'Price Control': 'إدارة الأسعار',
  'Changing a plan creates a new Stripe Price and activates it for new checkouts. Existing subscribers are not migrated automatically.': 'يؤدي تغيير سعر الخطة إلى إنشاء سعر Stripe جديد وتفعيله لعمليات الدفع الجديدة. لا يتم نقل المشتركين الحاليين تلقائيًا إلى السعر الجديد.',
  'Creating…': 'جارٍ الإنشاء…',
  'Create & Activate New Price': 'إنشاء وتفعيل سعر جديد',
  'Coupon Manager': 'إدارة الكوبونات',
  'Code, e.g. WELCOME20': 'الرمز، مثال: WELCOME20',
  'Percent discount': 'خصم بالنسبة المئوية',
  'Fixed amount': 'مبلغ ثابت',
  'Once': 'مرة واحدة',
  'Forever': 'دائمًا',
  'Max uses (optional)': 'الحد الأقصى للاستخدامات (اختياري)',
  'Working…': 'جارٍ التنفيذ…',
  'Create Coupon': 'إنشاء كوبون',
  'Loading…': 'جارٍ التحميل…',
  'Refresh Coupons': 'تحديث الكوبونات',
  'No promotion codes found.': 'لم يتم العثور على رموز خصم.',
  'PDF Studio': 'استوديو PDF',
  'Organize, edit, convert and optimize PDF files directly in your browser.': 'نظّم ملفات PDF وعدّلها وحوّلها وحسّنها مباشرة داخل متصفحك.',
  '16 local tools': '16 أداة محلية',
  'Private browser processing': 'معالجة خاصة داخل المتصفح',
  'Your PDF files stay on this device. Tayar does not upload them for these tools.': 'تبقى ملفات PDF على هذا الجهاز ولا يرفعها Tayar عند استخدام هذه الأدوات.',
  'PDF tool categories': 'فئات أدوات PDF',
  'Organize': 'تنظيم',
  'Edit & sign': 'تحرير وتوقيع',
  'Convert': 'تحويل',
  'Optimize': 'تحسين',
  'Merge PDF': 'دمج PDF',
  'Combine multiple PDF files in your chosen order.': 'ادمج عدة ملفات PDF بالترتيب الذي تختاره.',
  'Split PDF': 'تقسيم PDF',
  'Save every page as a separate PDF inside one ZIP.': 'احفظ كل صفحة كملف PDF منفصل داخل ملف ZIP واحد.',
  'Extract pages': 'استخراج الصفحات',
  'Create a new PDF from the pages you choose.': 'أنشئ ملف PDF جديدًا من الصفحات التي تختارها.',
  'Delete pages': 'حذف الصفحات',
  'Remove selected pages and keep the rest.': 'احذف الصفحات المحددة واحتفظ بالباقي.',
  'Reorder pages': 'إعادة ترتيب الصفحات',
  'Enter the exact new order for every page.': 'أدخل الترتيب الجديد الدقيق لكل صفحة.',
  'Rotate pages': 'تدوير الصفحات',
  'Rotate all pages or only a selected range.': 'دوّر كل الصفحات أو نطاقًا محددًا فقط.',
  'Crop PDF': 'قص PDF',
  'Trim page edges using precise millimetre margins.': 'اقصص حواف الصفحات باستخدام هوامش دقيقة بالمليمتر.',
  'Add page numbers': 'إضافة أرقام الصفحات',
  'Number all pages or a selected range.': 'رقّم كل الصفحات أو نطاقًا محددًا.',
  'Add watermark': 'إضافة علامة مائية',
  'Stamp custom text with position and opacity controls.': 'أضف نصًا مخصصًا مع التحكم بالموقع والشفافية.',
  'Add text': 'إضافة نص',
  'Place text on one page, a range, or the entire PDF.': 'ضع نصًا على صفحة واحدة أو نطاق أو كامل الملف.',
  'Sign PDF': 'توقيع PDF',
  'Place your PNG, JPEG, or WebP signature on selected pages.': 'ضع صورة توقيع PNG أو JPEG أو WebP على الصفحات المحددة.',
  'Create PDF': 'إنشاء PDF',
  'Create a clean blank PDF with your page size and orientation.': 'أنشئ ملف PDF فارغًا ونظيفًا بالحجم والاتجاه المطلوبين.',
  'PDF to images': 'PDF إلى صور',
  'Export every page as PNG or JPEG in one ZIP.': 'صدّر كل صفحة كصورة PNG أو JPEG داخل ملف ZIP واحد.',
  'PDF to text': 'PDF إلى نص',
  'Extract selectable text from every page into a TXT file.': 'استخرج النص القابل للتحديد من كل صفحة إلى ملف TXT.',
  'Compress PDF': 'ضغط PDF',
  'Reduce file size by rebuilding pages at a chosen quality.': 'قلّل حجم الملف بإعادة بناء الصفحات بالجودة التي تختارها.',
  'Flatten forms': 'تثبيت حقول النماذج',
  'Lock completed form fields into the PDF page content.': 'ثبّت حقول النماذج المكتملة ضمن محتوى صفحات PDF.',
  'Add PDF files': 'إضافة ملفات PDF',
  'Replace PDF file': 'استبدال ملف PDF',
  'Choose a PDF file': 'اختيار ملف PDF',
  'Up to 12 files · 120 MB combined': 'حتى 12 ملفًا · 120 MB بالمجموع',
  'Up to 50 MB · 150 pages': 'حتى 50 MB · 150 صفحة',
  'Remove file': 'إزالة الملف',
  'Pages': 'الصفحات',
  'Pages (optional)': 'الصفحات (اختياري)',
  'Example: 1-3,5,8': 'مثال: 1-3,5,8',
  'Leave empty for all pages': 'اتركه فارغًا لكل الصفحات',
  'pages in this PDF': 'صفحة في ملف PDF هذا',
  'New page order': 'ترتيب الصفحات الجديد',
  'Enter every page once, separated by commas. Example: 3,1,2,4': 'أدخل كل صفحة مرة واحدة وافصل بينها بفواصل. مثال: 3,1,2,4',
  'Rotation': 'زاوية التدوير',
  'Top': 'أعلى',
  'Right': 'يمين',
  'Bottom': 'أسفل',
  'Left': 'يسار',
  'Position': 'الموقع',
  'Top left': 'أعلى اليسار',
  'Top center': 'أعلى الوسط',
  'Top right': 'أعلى اليمين',
  'Center': 'الوسط',
  'Bottom left': 'أسفل اليسار',
  'Bottom center': 'أسفل الوسط',
  'Bottom right': 'أسفل اليمين',
  'Start number': 'رقم البداية',
  'Text size': 'حجم النص',
  'Text': 'النص',
  'CONFIDENTIAL': 'سري',
  'Enter text to place on the PDF': 'أدخل النص المراد وضعه على PDF',
  'Opacity': 'الشفافية',
  'Signature image': 'صورة التوقيع',
  'Choose signature image': 'اختيار صورة التوقيع',
  'Signature width': 'عرض التوقيع',
  'This places a visual signature. It does not create a certificate-based digital signature.': 'يضيف هذا توقيعًا مرئيًا ولا ينشئ توقيعًا رقميًا موثقًا بشهادة.',
  'Orientation': 'الاتجاه',
  'Portrait': 'عمودي',
  'Landscape': 'أفقي',
  'Page count': 'عدد الصفحات',
  'Letter': 'Letter',
  'Image format': 'صيغة الصورة',
  'Resolution': 'الدقة',
  'Standard': 'قياسية',
  'High': 'عالية',
  'Very high': 'عالية جدًا',
  'Compression level': 'مستوى الضغط',
  'Best quality': 'أفضل جودة',
  'Balanced': 'متوازن',
  'Smallest file': 'أصغر ملف',
  'Strong compression rebuilds each page as an image. Links and selectable text will be flattened.': 'يعيد الضغط القوي بناء كل صفحة كصورة، لذلك تصبح الروابط والنصوص القابلة للتحديد مسطحة.',
  'The ZIP will contain one PDF for each page.': 'سيحتوي ملف ZIP على ملف PDF مستقل لكل صفحة.',
  'Flattening makes completed form fields non-editable in the output copy.': 'يجعل التثبيت حقول النموذج المكتملة غير قابلة للتعديل في النسخة الناتجة.',
  'Processing PDF...': 'جارٍ معالجة PDF...',
  'Reading PDF...': 'جارٍ قراءة PDF...',
  'Choose a PDF tool and add your file.': 'اختر أداة PDF ثم أضف ملفك.',
  'Ready to download': 'جاهز للتنزيل',
  'PDF result preview': 'معاينة نتيجة PDF',
  'Extracted text': 'النص المستخرج',
  'ZIP package ready': 'ملف ZIP جاهز',
  'Download the ZIP to access every generated file.': 'نزّل ملف ZIP للوصول إلى كل الملفات الناتجة.',
  'Original PDF': 'ملف PDF الأصلي',
  'Original PDF preview': 'معاينة ملف PDF الأصلي',
  'Create a new PDF': 'إنشاء ملف PDF جديد',
  'Choose the page settings, then create and download your blank document.': 'اختر إعدادات الصفحات ثم أنشئ المستند الفارغ ونزّله.',
  'Page numbers must be within the document range.': 'يجب أن تكون أرقام الصفحات ضمن نطاق المستند.',
  'Enter every page exactly once in the new order.': 'أدخل كل صفحة مرة واحدة تمامًا ضمن الترتيب الجديد.',
  'PDF processing failed.': 'فشلت معالجة ملف PDF.',
  'Choose a PDF file first.': 'اختر ملف PDF أولًا.',
  'Choose one PDF file for this tool.': 'اختر ملف PDF واحدًا لهذه الأداة.',
  'Choose no more than 12 PDF files.': 'اختر 12 ملف PDF كحد أقصى.',
  'Choose at least two PDF files to merge.': 'اختر ملفي PDF على الأقل للدمج.',
  'The merged PDF cannot exceed 150 pages.': 'لا يمكن أن يتجاوز ملف PDF المدمج 150 صفحة.',
  'The selected PDF files exceed the 120 MB combined safety limit.': 'تتجاوز الملفات المحددة حد الأمان الإجمالي البالغ 120 MB.',
  'PDF files must be larger than 0 bytes and no more than 50 MB each.': 'يجب أن يكون حجم كل ملف PDF أكبر من صفر وألا يتجاوز 50 MB.',
  'This file is not a valid PDF document.': 'هذا الملف ليس مستند PDF صالحًا.',
  'PDF page count must be between 1 and 150 pages.': 'يجب أن يكون عدد صفحات PDF بين 1 و150 صفحة.',
  'This PDF is damaged or uses an unsupported format.': 'ملف PDF تالف أو يستخدم صيغة غير مدعومة.',
  'This PDF exceeded the safe decompression limit.': 'تجاوز ملف PDF حد فك الضغط الآمن.',
  'Password-protected PDFs must be unlocked before using this local tool.': 'يجب فك حماية ملف PDF بكلمة المرور قبل استخدام هذه الأداة المحلية.',
  'Password-protected PDFs must be unlocked before conversion.': 'يجب فك حماية ملف PDF بكلمة المرور قبل التحويل.',
  'Enter pages like 1-3,5,8.': 'أدخل الصفحات بهذا الشكل: 1-3,5,8.',
  'Enter at least one page number.': 'أدخل رقم صفحة واحدًا على الأقل.',
  'You cannot delete every page from the PDF.': 'لا يمكنك حذف كل صفحات ملف PDF.',
  'Crop margins must be between 0 and 100 millimetres.': 'يجب أن تكون هوامش القص بين 0 و100 مليمتر.',
  'Crop margins leave no usable page area.': 'هوامش القص لا تترك مساحة صالحة في الصفحة.',
  'Enter the text you want to add.': 'أدخل النص الذي تريد إضافته.',
  'Text size must be between 8 and 120 points.': 'يجب أن يكون حجم النص بين 8 و120 نقطة.',
  'Canvas processing is not available in this browser.': 'معالجة Canvas غير متاحة في هذا المتصفح.',
  'The browser could not create the text layer.': 'تعذر على المتصفح إنشاء طبقة النص.',
  'The browser could not encode this PDF page.': 'تعذر على المتصفح ترميز صفحة PDF هذه.',
  'Choose a signature image first.': 'اختر صورة توقيع أولًا.',
  'Use a PNG, JPEG, or WebP signature image.': 'استخدم صورة توقيع بصيغة PNG أو JPEG أو WebP.',
  'Signature images must be no more than 10 MB.': 'يجب ألا يتجاوز حجم صورة التوقيع 10 MB.',
  'Signature image dimensions are too large to process safely.': 'أبعاد صورة التوقيع كبيرة جدًا للمعالجة الآمنة.',
  'Blank PDFs can contain between 1 and 20 pages.': 'يمكن أن يحتوي ملف PDF الفارغ على 1 إلى 20 صفحة.',
  'Image and text conversion supports PDFs up to 60 pages.': 'يدعم تحويل الصور والنصوص ملفات PDF حتى 60 صفحة.',
  'Splitting supports PDFs up to 100 pages per ZIP.': 'يدعم التقسيم ملفات PDF حتى 100 صفحة لكل ملف ZIP.',
  'No selectable text was found. This PDF may require OCR.': 'لم يتم العثور على نص قابل للتحديد؛ قد يحتاج الملف إلى OCR.',
  'This PDF does not contain interactive form fields.': 'لا يحتوي ملف PDF على حقول نموذج تفاعلية.',
  'This PDF could not be rendered safely in the browser.': 'تعذر عرض ملف PDF بأمان داخل المتصفح.',
};

export const svSupplement: PhraseMap = {
  'configured': 'konfigurerad',
  'unconfigured': 'inte konfigurerad',
  'enabled': 'aktiverad',
  'needs attention': 'behöver granskas',
  'missing': 'saknas',
  'not verified': 'inte verifierad',
  'needs setup': 'behöver konfigureras',
  'test': 'test',
  'live': 'live',
  'APP_URL missing or invalid': 'APP_URL saknas eller är ogiltig',
  'Administrator accounts must be transferred and deleted by another administrator.': 'Administratörskonton måste överföras och raderas av en annan administratör.',
  'Export Account Records': 'Exportera kontoposter',
  'Help us improve by sharing optional product usage data': 'Hjälp oss att förbättra genom att dela valfria produktanvändningsdata',
  'Data uses encrypted network connections; storage security follows the configured providers and access controls.': 'Data använder krypterade nätverksanslutningar; lagringssäkerheten följer konfigurerade leverantörer och åtkomstkontroller.',
  'With your consent, product analytics and error monitoring may process page or action names, referrer, a session identifier linked to your signed-in account, browser or device data, network information and limited error diagnostics. Interaction autocapture and session replay are disabled, and project content is not intentionally included in analytics events.': 'Med ditt samtycke kan produktanalys och felövervakning behandla sid- eller åtgärdsnamn, hänvisningskälla, en sessionsidentifierare kopplad till ditt inloggade konto, webbläsar- eller enhetsdata, nätverksinformation och begränsad feldiagnostik. Automatisk interaktionsinsamling och sessionsinspelning är avstängda, och projektinnehåll inkluderas inte avsiktligt i analyshändelser.',
  'Permanently delete your Tayar account, owned projects and stored files. An active subscription is canceled first. Limited billing, security and audit records may remain where legally required or needed to protect the service. This action cannot be undone.': 'Radera permanent ditt Tayar-konto, projekt som du äger och lagrade filer. En aktiv prenumeration sägs upp först. Begränsade fakturerings-, säkerhets- och revisionsposter kan finnas kvar när lagen kräver det eller när det behövs för att skydda tjänsten. Åtgärden kan inte ångras.',
  'Deleting a user cancels any active Stripe subscription, removes owned storage and then permanently removes the account.': 'När en användare raderas sägs en eventuell aktiv Stripe-prenumeration upp, ägd lagring tas bort och därefter raderas kontot permanent.',
  'Choose whether to also block this email from re-registering.': 'Välj om du också vill hindra den här e-postadressen från att registrera sig igen.',
  'We use necessary browser storage for sign-in and preferences. With your permission, we also record product analytics. See our': 'Vi använder nödvändig webbläsarlagring för inloggning och inställningar. Med ditt samtycke registrerar vi även produktanalys. Se vår',
  'Operator identity details are incomplete. Public launch must remain blocked until they are configured.': 'Operatörens identitetsuppgifter är ofullständiga. Offentlig lansering måste förbli blockerad tills de har konfigurerats.',
  'Required before launch': 'Krävs före lansering',
  'Legal name': 'Juridiskt namn',
  'Registration number': 'Registreringsnummer',
  'Postal address': 'Postadress',
  'Country': 'Land',
  'Legal and privacy contact': 'Kontakt för juridik och integritet',
  'Last updated:': 'Senast uppdaterad:',
  'year': 'år',
  'month': 'månad',
  '1. Operator and scope': '1. Operatör och omfattning',
  'This policy explains how the operator of Tayar Intelligence processes personal data when you use the workspace, public website features, support and billing flows.': 'Denna policy förklarar hur operatören av Tayar Intelligence behandlar personuppgifter när du använder arbetsytan, offentliga webbplatsfunktioner, support och betalningsflöden.',
  '2. Data we process': '2. Uppgifter vi behandlar',
  'Depending on the features you use, we process account and profile details, authentication identifiers, projects and files, AI conversations and usage records, preferences, support requests, subscription status, team activity, and security or operational events.': 'Beroende på vilka funktioner du använder behandlar vi konto- och profiluppgifter, autentiseringsidentifierare, projekt och filer, AI-konversationer och användningsposter, inställningar, supportärenden, prenumerationsstatus, teamaktivitet samt säkerhets- eller drifthändelser.',
  'Website Builder may also store published pages and media, release history, form submissions, leads and privacy-limited analytics events for sites you operate.': 'Webbplatsbyggaren kan även lagra publicerade sidor och medier, versionshistorik, formulärinskick, leads och integritetsbegränsade analyshändelser för webbplatser du driver.',
  '3. Purposes and legal grounds': '3. Ändamål och rättsliga grunder',
  'We process data as needed to provide and secure the service, save your work, enforce permissions and plan limits, respond to support, and administer subscriptions. Depending on the context, the legal ground may be performance of a contract, legitimate interests in protecting and improving the service, consent for optional analytics, or compliance with a legal obligation.': 'Vi behandlar uppgifter i den utsträckning som behövs för att tillhandahålla och säkra tjänsten, spara ditt arbete, upprätthålla behörigheter och plangränser, svara på supportärenden och administrera prenumerationer. Beroende på sammanhanget kan den rättsliga grunden vara fullgörande av avtal, berättigat intresse av att skydda och förbättra tjänsten, samtycke till valfri analys eller en rättslig förpliktelse.',
  '4. AI and external processing': '4. AI och extern behandling',
  'AI requests are sent only when you choose an AI-powered action. The prompt and content needed for that action may be sent to the AI or image provider configured by the operator. Do not submit sensitive data unless it is necessary and you are authorized to do so.': 'AI-förfrågningar skickas endast när du väljer en AI-driven åtgärd. Prompten och innehållet som behövs kan skickas till den AI- eller bildleverantör som operatören har konfigurerat. Skicka inte känsliga uppgifter om det inte är nödvändigt och du har rätt att göra det.',
  '5. Website visitors': '5. Webbplatsbesökare',
  'If you publish a site with Tayar, you are responsible for the notices, permissions and lawful use of visitor information collected through your site. Tayar handles form submissions and configured analytics to provide those Website Builder features to your account.': 'Om du publicerar en webbplats med Tayar ansvarar du för information, tillstånd och laglig användning av besökaruppgifter som samlas in via webbplatsen. Tayar hanterar formulärinskick och konfigurerad analys för att tillhandahålla dessa funktioner i Webbplatsbyggaren till ditt konto.',
  '6. Providers, payments and transfers': '6. Leverantörer, betalningar och överföringar',
  'Supabase provides authentication, database and storage capabilities. Stripe handles Checkout, payment methods, invoices and subscription management; Tayar stores billing identifiers and subscription status, not full payment-card details. Configured AI, email, monitoring or hosting providers process only the information needed for their service.': 'Supabase tillhandahåller autentisering, databas och lagring. Stripe hanterar Checkout, betalningsmetoder, fakturor och prenumerationer; Tayar lagrar faktureringsidentifierare och prenumerationsstatus, inte fullständiga kortuppgifter. Konfigurerade leverantörer för AI, e-post, övervakning eller hosting behandlar endast uppgifter som behövs för deras tjänst.',
  'Provider locations can vary. Where personal data is transferred internationally, the operator relies on the safeguards available under its provider agreements and applicable law. Contact us for the current provider list and transfer details.': 'Leverantörernas platser kan variera. När personuppgifter överförs internationellt förlitar sig operatören på skyddsåtgärder i leverantörsavtal och tillämplig lag. Kontakta oss för aktuell leverantörslista och överföringsinformation.',
  '7. Retention and deletion': '7. Lagring och radering',
  'Account and project data is generally kept while your account is active. Account deletion cancels an active Tayar subscription and removes the active account, owned project records and owned storage controlled by Tayar. Limited billing, security, fraud-prevention, dispute and audit records may remain when needed for legal obligations or legitimate service protection.': 'Konto- och projektuppgifter behålls i allmänhet medan kontot är aktivt. Kontoradering avslutar en aktiv Tayar-prenumeration och tar bort det aktiva kontot, ägda projektposter och ägd lagring som Tayar kontrollerar. Begränsade poster för fakturering, säkerhet, bedrägeriförebyggande, tvister och revision kan finnas kvar när det behövs för rättsliga skyldigheter eller legitimt skydd av tjänsten.',
  '8. Security': '8. Säkerhet',
  'The application uses encrypted network connections, authenticated server functions and database access controls, including Row Level Security for user and workspace data. No online service can guarantee absolute security.': 'Applikationen använder krypterade nätverksanslutningar, autentiserade serverfunktioner och databasåtkomstkontroller, inklusive Row Level Security för användar- och arbetsytedata. Ingen onlinetjänst kan garantera absolut säkerhet.',
  '9. Browser storage and analytics': '9. Webbläsarlagring och analys',
  'Necessary browser storage supports authentication sessions, interface preferences, recovery and consent choices. Product analytics is off until you consent and can be disabled later in Settings. Tayar does not currently activate a separate marketing-cookie category.': 'Nödvändig webbläsarlagring stöder autentiseringssessioner, gränssnittsinställningar, återställning och samtyckesval. Produktanalys är avstängd tills du samtycker och kan senare stängas av i Inställningar. Tayar aktiverar för närvarande ingen separat kategori för marknadsföringscookies.',
  '10. Your choices and rights': '10. Dina val och rättigheter',
  'Settings provides account-data export, analytics consent controls and account deletion. Depending on applicable law, you may also request access, correction, restriction, portability or objection, withdraw consent, and complain to a competent data-protection authority. Use the account support flow or the legal contact above.': 'I Inställningar finns export av kontodata, samtyckeskontroller för analys och kontoradering. Beroende på tillämplig lag kan du även begära tillgång, rättelse, begränsning eller dataportabilitet, invända, återkalla samtycke och klaga hos behörig dataskyddsmyndighet. Använd kontosupporten eller den juridiska kontakten ovan.',
  'Settings provides account-data export, analytics consent controls and account deletion. Depending on applicable law, you may also request access, correction, restriction, portability or objection, withdraw consent, and complain to a competent data-protection authority. Use the in-product account support flow.': 'I Inställningar finns export av kontodata, samtyckeskontroller för analys och kontoradering. Beroende på tillämplig lag kan du även begära tillgång, rättelse, begränsning eller dataportabilitet, invända, återkalla samtycke och klaga hos behörig dataskyddsmyndighet. Använd kontosupporten i produkten.',
  '11. Changes': '11. Ändringar',
  'This policy may be updated as the product, providers or legal requirements change. Material changes should be communicated through the service when appropriate, and the revision date above will be updated.': 'Policyn kan uppdateras när produkten, leverantörerna eller rättsliga krav ändras. Väsentliga ändringar bör meddelas via tjänsten när det är lämpligt och revisionsdatumet ovan uppdateras.',
  'the operator country shown above': 'operatörens land som anges ovan',
  '1. Operator and agreement': '1. Operatör och avtal',
  'These Terms govern your use of Tayar Intelligence. By creating an account or using the service, you agree to these Terms. If you use Tayar for an organization, you confirm that you are authorized to accept them for that organization.': 'Dessa villkor reglerar din användning av Tayar Intelligence. Genom att skapa ett konto eller använda tjänsten godkänner du villkoren. Om du använder Tayar för en organisation bekräftar du att du har behörighet att godkänna dem för organisationen.',
  '2. Accounts and access': '2. Konton och åtkomst',
  'You must provide accurate account information, protect your sign-in credentials and promptly report suspected unauthorized access. You are responsible for activity performed through your account and for choosing appropriate team permissions.': 'Du måste lämna korrekta kontouppgifter, skydda dina inloggningsuppgifter och snabbt rapportera misstänkt obehörig åtkomst. Du ansvarar för aktivitet genom ditt konto och för att välja lämpliga teambehörigheter.',
  '3. Your content': '3. Ditt innehåll',
  'You keep ownership of content you submit or create. You give the operator a limited permission to host, copy, process and transmit that content only as needed to provide, secure and support the service. You must have the rights and permissions needed for content you upload, publish or share.': 'Du behåller ägandet av innehåll som du skickar in eller skapar. Du ger operatören begränsad rätt att lagra, kopiera, behandla och överföra innehållet endast i den utsträckning som behövs för att tillhandahålla, säkra och stödja tjänsten. Du måste ha nödvändiga rättigheter och tillstånd för innehåll du laddar upp, publicerar eller delar.',
  '4. AI-assisted output': '4. AI-assisterat resultat',
  'AI output may be inaccurate, incomplete or unsuitable. You are responsible for reviewing output before relying on it, publishing it or using it for legal, medical, financial, employment or other consequential decisions.': 'AI-resultat kan vara felaktiga, ofullständiga eller olämpliga. Du ansvarar för att granska resultat innan du förlitar dig på, publicerar eller använder det för juridiska, medicinska, ekonomiska, arbetsrelaterade eller andra betydelsefulla beslut.',
  '5. Acceptable use': '5. Tillåten användning',
  'You may not use the service to violate law or third-party rights, process data without authorization, distribute malicious or deceptive content, abuse forms or APIs, bypass limits or security controls, scrape other accounts, or disrupt the platform.': 'Du får inte använda tjänsten för att bryta mot lag eller tredje parts rättigheter, behandla uppgifter utan tillstånd, sprida skadligt eller vilseledande innehåll, missbruka formulär eller API:er, kringgå gränser eller säkerhetskontroller, skrapa andra konton eller störa plattformen.',
  '6. Published sites and visitor data': '6. Publicerade webbplatser och besökaruppgifter',
  'You are responsible for sites you publish, including their content, domains, legal notices, accessibility, visitor consent and handling of leads or analytics. Remove or correct unlawful content promptly.': 'Du ansvarar för webbplatser du publicerar, inklusive innehåll, domäner, juridisk information, tillgänglighet, besökarsamtycke och hantering av leads eller analys. Ta snabbt bort eller rätta olagligt innehåll.',
  '7. Plans, renewal and cancellation': '7. Planer, förnyelse och uppsägning',
  'The current features, usage limits, amount, currency and billing interval are shown in the product and Stripe Checkout. Paid subscriptions renew automatically until canceled. You can manage or cancel a subscription through the Stripe billing portal, with access continuing as shown there. Any taxes actually charged are shown in Checkout before purchase.': 'Aktuella funktioner, användningsgränser, belopp, valuta och faktureringsintervall visas i produkten och Stripe Checkout. Betalda prenumerationer förnyas automatiskt tills de sägs upp. Du kan hantera eller säga upp en prenumeration via Stripes faktureringsportal, med fortsatt åtkomst enligt vad som visas där. Eventuella skatter som faktiskt debiteras visas i Checkout före köpet.',
  'Nothing in these Terms removes mandatory consumer rights, including any applicable withdrawal, refund or digital-service remedies. Contact support promptly if you believe a charge is incorrect.': 'Inget i villkoren tar bort tvingande konsumenträttigheter, inklusive tillämplig ångerrätt, återbetalning eller påföljder för digitala tjänster. Kontakta supporten snabbt om du anser att en debitering är felaktig.',
  '8. Service changes and availability': '8. Tjänsteändringar och tillgänglighet',
  'Tayar may change, add or retire features and may interrupt access for maintenance, security or circumstances outside reasonable control. Pilot and preview features may change more frequently and are not promised for uninterrupted production use.': 'Tayar kan ändra, lägga till eller ta bort funktioner och kan avbryta åtkomst för underhåll, säkerhet eller omständigheter utanför rimlig kontroll. Pilot- och förhandsvisningsfunktioner kan ändras oftare och utlovas inte för oavbruten produktionsanvändning.',
  '9. Suspension, termination and deletion': '9. Avstängning, upphörande och radering',
  'Access may be limited or suspended when reasonably necessary to protect users, enforce these Terms, prevent abuse or comply with law. You may stop using the service at any time and can request account deletion in Settings. Subscription cancellation and account deletion are separate actions unless the deletion flow states otherwise.': 'Åtkomst kan begränsas eller stängas av när det rimligen behövs för att skydda användare, upprätthålla villkoren, förhindra missbruk eller följa lag. Du kan sluta använda tjänsten när som helst och begära kontoradering i Inställningar. Uppsägning av prenumeration och kontoradering är separata åtgärder om inte raderingsflödet anger annat.',
  '10. Disclaimers': '10. Ansvarsfriskrivningar',
  'Except for rights and guarantees that cannot legally be excluded, the service is provided as available without a promise that every feature or generated output will be error-free or fit for every purpose.': 'Med undantag för rättigheter och garantier som inte lagligen kan uteslutas tillhandahålls tjänsten i befintligt skick utan löfte om att varje funktion eller genererat resultat är felfritt eller lämpligt för alla ändamål.',
  '11. Liability': '11. Ansvar',
  'Nothing limits liability that cannot legally be limited. Otherwise, each party is responsible for reasonably foreseeable direct loss caused by its breach, and the operator is not responsible for indirect loss or third-party services outside its control to the extent permitted by law.': 'Inget begränsar ansvar som inte lagligen kan begränsas. I övrigt ansvarar varje part för rimligen förutsebar direkt skada som orsakas av dess avtalsbrott, och operatören ansvarar inte för indirekt skada eller tredjepartstjänster utanför dess kontroll i den utsträckning lagen tillåter.',
  '12. Governing law and disputes': '12. Tillämplig lag och tvister',
  'These Terms are governed by the laws of': 'Dessa villkor regleras av lagarna i',
  'These Terms are governed by applicable law.': 'Dessa villkor regleras av tillämplig lag.',
  'This does not deprive consumers of mandatory protections available in their country of residence. Contact support first so the parties can try to resolve a concern informally.': 'Detta fråntar inte konsumenter tvingande skydd i deras bosättningsland. Kontakta supporten först så att parterna kan försöka lösa frågan informellt.',
  '13. Contact': '13. Kontakt',
  'Questions about these Terms, billing or the service can be submitted through the in-product support flow or the legal contact listed above.': 'Frågor om villkoren, fakturering eller tjänsten kan skickas via supportflödet i produkten eller den juridiska kontakt som anges ovan.',
  'Questions about these Terms, billing or the service can be submitted through the in-product support flow.': 'Frågor om villkoren, fakturering eller tjänsten kan skickas via supportflödet i produkten.',
  'Close menu': 'Stäng meny',
  'Open menu': 'Öppna meny',
  'unread': 'olästa',
  'Current subscriptions by plan': 'Aktuella prenumerationer per plan',
  'Active · cancels at period end': 'Aktiv · avslutas vid periodens slut',
  'Billing / Access Date': 'Fakturerings-/åtkomstdatum',
  'Only runtime-enforced platform settings are editable here.': 'Endast plattformsinställningar som faktiskt upprätthålls vid körning kan redigeras här.',
  'Authoritative controls': 'Styrande kontroller',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'Verktygsåtkomst och användningsgränser hanteras i Tools. AI-leverantör och modellkontroller hanteras i AI Management. Äldre inställningar som inte påverkar körningen är avsiktligt dolda här.',
  'API key inventory only': 'Endast API-nyckelinventering',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'Dessa rader är endast metadata och aktiverar eller inaktiverar inte produktionshemligheterna som används av Edge Functions. Rotera eller ta bort aktiva hemligheter i Supabase-projektets secrets.',
  'Read-only service metadata': 'Skrivskyddad tjänstemetadata',
  'Failed to toggle tool': 'Det gick inte att ändra verktygets status',
  'disabled': 'inaktiverad',
  'Failed to update tool plan': 'Det gick inte att uppdatera verktygets plan',
  'Failed to update usage limits': 'Det gick inte att uppdatera användningsgränserna',
  'usage limits updated': 'användningsgränserna uppdaterades',
  'Tool plan access & limits': 'Verktygsåtkomst och gränser per plan',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'Välj vilken plan som får använda varje verktyg och hur många lyckade användningar Free-, Pro- och Business-användare kan göra per dag, månad eller under hela livstiden. Lämna en gräns tom för obegränsad användning.',
  'Minimum plan': 'Lägsta plan',
  'Reset period': 'Återställningsperiod',
  'Daily': 'Daglig',
  'Monthly': 'Månadsvis',
  'Lifetime': 'Livstid',
  'Unlimited': 'Obegränsat',
  'recorded uses': 'registrerade användningar',
  'Save limits': 'Spara gränser',
  'live quota': 'livekvot',
  'Processing...': 'Bearbetar...',
  'Change sort direction': 'Ändra sorteringsriktning',
  'Grid view': 'Rutnätsvy',
  'List view': 'Listvy',
  'File actions': 'Filåtgärder',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'Betalningen är klar. Vi synkroniserar din prenumeration nu. Din plan uppdateras automatiskt.',
  'Checkout was canceled. No plan change was made.': 'Kassan avbröts. Ingen planändring gjordes.',
  'Account menu': 'Kontomeny',
  'Could not clean this file.': 'Kunde inte rensa den här filen.',
  'Could not create invoice output.': 'Kunde inte skapa fakturautdata.',
  'Could not generate this letter.': 'Kunde inte skapa det här brevet.',
  'Could not generate names.': 'Kunde inte generera namn.',
  'Checking access...': 'Kontrollerar åtkomst...',
  'Access check unavailable': 'Åtkomstkontroll är inte tillgänglig',
  'We could not safely verify your plan. Please retry in a moment.': 'Vi kunde inte verifiera din plan på ett säkert sätt. Försök igen om en stund.',
  'Tool temporarily unavailable': 'Verktyget är tillfälligt otillgängligt',
  'This tool has been disabled by the administrator.': 'Det här verktyget har inaktiverats av administratören.',
  'Usage limit reached': 'Användningsgränsen har nåtts',
  'View plans': 'Visa planer',
  'Website published successfully. Release history was skipped:': 'Webbplatsen publicerades. Versionshistoriken hoppades över:',
  'Continue with Google': 'Fortsätt med Google',
  'Start free with your Tayar workspace, Website Builder and included tools.': 'Börja gratis med din Tayar-arbetsyta, Webbplatsbyggaren och inkluderade verktyg.',
  '1 Website Builder project with up to 3 pages': '1 Website Builder-projekt med upp till 3 sidor',
  'Free-access tools with Free plan usage limits': 'Free-verktyg med Free-planens användningsgränser',
  'Sign in to continue to your Tayar workspace.': 'Logga in för att fortsätta till din Tayar-arbetsyta.',
  'Quick setup': 'Snabb konfiguration',
  'One workspace for websites, documents, AI tools and client work. Personalize your setup, or skip and explore right away.': 'En arbetsyta för webbplatser, dokument, AI-verktyg och kundarbete. Anpassa din konfiguration eller hoppa över och utforska direkt.',
  'Personalize my workspace': 'Anpassa min arbetsyta',
  'Skip for now': 'Hoppa över just nu',
  'You can change your language, profile and preferences later in Settings.': 'Du kan ändra språk, profil och inställningar senare under Inställningar.',
  'Build and publish a website': 'Bygg och publicera en webbplats',
  'Study, write and organize work with focused tools': 'Studera, skriv och organisera arbetet med fokuserade verktyg',
  'Build CVs, cover letters and job-ready documents': 'Skapa CV:n, personliga brev och jobbfärdiga dokument',
  'Create documents and everyday work from one workspace': 'Skapa dokument och gör vardagsarbetet från en arbetsyta',
  'Build your web presence and manage business workflows': 'Bygg din webbnärvaro och hantera företagets arbetsflöden',
  'Build, write and deliver client work from one workspace': 'Bygg, skriv och leverera kundarbete från en arbetsyta',
  'Browse your tools, recommendations and recent activity from one place.': 'Se dina verktyg, rekommendationer och senaste aktivitet på ett ställe.',
  'Your projects, files and everyday work stay together here.': 'Dina projekt, filer och ditt vardagsarbete hålls samlat här.',
  'Build and publish a responsive website with manual controls and guided workflows.': 'Bygg och publicera en responsiv webbplats med manuella kontroller och guidade arbetsflöden.',
  'Find saved documents, exports and project files without hunting across tools.': 'Hitta sparade dokument, exporter och projektfiler utan att leta mellan verktyg.',
  'See your current plan, included limits and billing options in one place.': 'Se din nuvarande plan, inkluderade gränser och faktureringsalternativ på ett ställe.',
  'Your Tayar workspace is ready. Start with the recommendation below or explore everything at your own pace.': 'Din Tayar-arbetsyta är klar. Börja med rekommendationen nedan eller utforska allt i din egen takt.',
  'Explore all tools': 'Utforska alla verktyg',
  'Browse every available tool and choose what you need.': 'Bläddra bland alla tillgängliga verktyg och välj det du behöver.',
  'Take the product tour': 'Ta produktturen',
  'See where projects, tools and plan controls live.': 'Se var projekt, verktyg och plankontroller finns.',
  'Start with your recommended tool': 'Börja med ditt rekommenderade verktyg',
  'Review your plan and limits': 'Granska din plan och dina gränser',
  'project': 'projekt',
  'projects': 'projekt',
  'No-code AI Provider Control': 'AI-leverantörshantering utan kod',
  'Add a provider, Base URL, Model ID and API secret here. Secrets stay in Supabase Vault. After this control layer is installed, adding or changing providers does not require code changes or database changes.': 'Lägg till leverantör, bas-URL, modell-ID och API-hemlighet här. Hemligheter lagras i Supabase Vault. När detta kontrollager är installerat kräver tillägg eller byte av leverantör inga kod- eller databasändringar.',
  'Current Gemini fallback active': 'Nuvarande Gemini-reserv är aktiv',
  'Backend not enabled': 'Backend är inte aktiverad',
  'No managed provider has been added yet. Tayar continues using the current Gemini environment configuration until you add and activate one.': 'Ingen hanterad leverantör har lagts till ännu. Tayar fortsätter använda den nuvarande Gemini-konfigurationen från miljön tills du lägger till och aktiverar en leverantör.',
  'Key': 'Nyckel',
  'Adapter': 'Adapter',
  'Base URL': 'Bas-URL',
  'Model ID': 'Modell-ID',
  'Secret configured in Vault': 'Hemlighet sparad i Vault',
  'API secret missing': 'API-hemlighet saknas',
  'Test': 'Testa',
  'Make Default': 'Ange som standard',
  'Disable': 'Inaktivera',
  'Enable': 'Aktivera',
  'Edit AI Provider': 'Redigera AI-leverantör',
  'Add AI Provider': 'Lägg till AI-leverantör',
  'Leave API Secret empty while editing to keep the existing secret.': 'Lämna API-hemligheten tom vid redigering för att behålla den befintliga hemligheten.',
  'Provider Key': 'Leverantörsnyckel',
  'Display Name': 'Visningsnamn',
  'API Secret': 'API-hemlighet',
  'Leave blank to keep current secret': 'Lämna tomt för att behålla nuvarande hemlighet',
  'Save Provider': 'Spara leverantör',
  'Current Gemini fallback': 'Nuvarande Gemini-reserv',
  'This keeps Tayar working exactly as it does today when no managed provider is active.': 'Detta gör att Tayar fortsätter fungera som idag när ingen hanterad leverantör är aktiv.',
  'Save fallback': 'Spara reserv',
  'Configuration Center': 'Konfigurationscenter',
  'Manage AI providers, Stripe prices and coupons from the Admin Panel without editing application code. API secrets remain server-side and are never shown back in the browser.': 'Hantera AI-leverantörer, Stripe-priser och kuponger från adminpanelen utan att ändra applikationskod. API-hemligheter stannar på serversidan och visas aldrig tillbaka i webbläsaren.',
  'Refresh status': 'Uppdatera status',
  'AI Providers': 'AI-leverantörer',
  'Add, test, enable and choose the default provider': 'Lägg till, testa och aktivera leverantörer samt välj standardleverantör',
  'Gemini fallback': 'Gemini-reserv',
  'Secret': 'Hemlighet',
  'Configured securely': 'Säkert konfigurerad',
  'Manage AI Providers': 'Hantera AI-leverantörer',
  'Payments & Pricing': 'Betalningar och prissättning',
  'Manage Stripe prices and promotion codes': 'Hantera Stripe-priser och kampanjkoder',
  'Stripe': 'Stripe',
  'Not connected': 'Inte ansluten',
  'Checkout / Portal': 'Checkout / portal',
  'Ready': 'Klar',
  'Manage Prices & Coupons': 'Hantera priser och kuponger',
  'Safe operating model: adding a compatible AI provider or changing the active Stripe price is done from Admin. Existing subscribers keep their historical Stripe price unless you explicitly migrate them later.': 'Säker driftmodell: en kompatibel AI-leverantör läggs till och det aktiva Stripe-priset ändras från Admin. Befintliga prenumeranter behåller sitt tidigare Stripe-pris om du inte uttryckligen migrerar dem senare.',
  'Always': 'Alltid',
  'Enter a valid price greater than zero.': 'Ange ett giltigt pris som är större än noll.',
  'Create and activate a new Stripe price for': 'Skapa och aktivera ett nytt Stripe-pris för',
  'new price created and activated for new checkouts.': 'nytt pris skapades och aktiverades för nya checkouter.',
  'Coupon code is required.': 'Kupongkod krävs.',
  'Coupon created and activated.': 'Kupongen skapades och aktiverades.',
  'Disable this promotion code?': 'Inaktivera den här kampanjkoden?',
  'Coupon disabled.': 'Kupongen inaktiverades.',
  'Price Control': 'Prishantering',
  'Changing a plan creates a new Stripe Price and activates it for new checkouts. Existing subscribers are not migrated automatically.': 'När ett planpris ändras skapas ett nytt Stripe Price som aktiveras för nya checkouter. Befintliga prenumeranter migreras inte automatiskt.',
  'Creating…': 'Skapar…',
  'Create & Activate New Price': 'Skapa och aktivera nytt pris',
  'Coupon Manager': 'Kuponghantering',
  'Code, e.g. WELCOME20': 'Kod, t.ex. WELCOME20',
  'Percent discount': 'Procentrabatt',
  'Fixed amount': 'Fast belopp',
  'Once': 'En gång',
  'Forever': 'För alltid',
  'Max uses (optional)': 'Max antal användningar (valfritt)',
  'Working…': 'Arbetar…',
  'Create Coupon': 'Skapa kupong',
  'Loading…': 'Laddar…',
  'Refresh Coupons': 'Uppdatera kuponger',
  'No promotion codes found.': 'Inga kampanjkoder hittades.',
  'PDF Studio': 'PDF-studio',
  'Organize, edit, convert and optimize PDF files directly in your browser.': 'Ordna, redigera, konvertera och optimera PDF-filer direkt i webbläsaren.',
  '16 local tools': '16 lokala verktyg',
  'Private browser processing': 'Privat bearbetning i webbläsaren',
  'Your PDF files stay on this device. Tayar does not upload them for these tools.': 'Dina PDF-filer stannar på enheten. Tayar laddar inte upp dem för dessa verktyg.',
  'PDF tool categories': 'Kategorier för PDF-verktyg',
  'Organize': 'Ordna',
  'Edit & sign': 'Redigera och signera',
  'Convert': 'Konvertera',
  'Optimize': 'Optimera',
  'Merge PDF': 'Slå ihop PDF',
  'Combine multiple PDF files in your chosen order.': 'Kombinera flera PDF-filer i den ordning du väljer.',
  'Split PDF': 'Dela PDF',
  'Save every page as a separate PDF inside one ZIP.': 'Spara varje sida som en separat PDF i en ZIP-fil.',
  'Extract pages': 'Extrahera sidor',
  'Create a new PDF from the pages you choose.': 'Skapa en ny PDF av de sidor du väljer.',
  'Delete pages': 'Ta bort sidor',
  'Remove selected pages and keep the rest.': 'Ta bort valda sidor och behåll resten.',
  'Reorder pages': 'Ordna om sidor',
  'Enter the exact new order for every page.': 'Ange den exakta nya ordningen för alla sidor.',
  'Rotate pages': 'Rotera sidor',
  'Rotate all pages or only a selected range.': 'Rotera alla sidor eller bara ett valt intervall.',
  'Crop PDF': 'Beskär PDF',
  'Trim page edges using precise millimetre margins.': 'Beskär sidkanterna med exakta marginaler i millimeter.',
  'Add page numbers': 'Lägg till sidnummer',
  'Number all pages or a selected range.': 'Numrera alla sidor eller ett valt intervall.',
  'Add watermark': 'Lägg till vattenstämpel',
  'Stamp custom text with position and opacity controls.': 'Stämpla egen text med kontroller för position och opacitet.',
  'Add text': 'Lägg till text',
  'Place text on one page, a range, or the entire PDF.': 'Placera text på en sida, ett intervall eller hela PDF-filen.',
  'Sign PDF': 'Signera PDF',
  'Place your PNG, JPEG, or WebP signature on selected pages.': 'Placera din PNG-, JPEG- eller WebP-signatur på valda sidor.',
  'Create PDF': 'Skapa PDF',
  'Create a clean blank PDF with your page size and orientation.': 'Skapa en ren tom PDF med vald sidstorlek och orientering.',
  'PDF to images': 'PDF till bilder',
  'Export every page as PNG or JPEG in one ZIP.': 'Exportera varje sida som PNG eller JPEG i en ZIP-fil.',
  'PDF to text': 'PDF till text',
  'Extract selectable text from every page into a TXT file.': 'Extrahera markerbar text från varje sida till en TXT-fil.',
  'Compress PDF': 'Komprimera PDF',
  'Reduce file size by rebuilding pages at a chosen quality.': 'Minska filstorleken genom att bygga om sidorna med vald kvalitet.',
  'Flatten forms': 'Platta till formulär',
  'Lock completed form fields into the PDF page content.': 'Lås ifyllda formulärfält i PDF-sidornas innehåll.',
  'Add PDF files': 'Lägg till PDF-filer',
  'Replace PDF file': 'Byt PDF-fil',
  'Choose a PDF file': 'Välj en PDF-fil',
  'Up to 12 files · 120 MB combined': 'Upp till 12 filer · totalt 120 MB',
  'Up to 50 MB · 150 pages': 'Upp till 50 MB · 150 sidor',
  'Remove file': 'Ta bort fil',
  'Pages': 'Sidor',
  'Pages (optional)': 'Sidor (valfritt)',
  'Example: 1-3,5,8': 'Exempel: 1-3,5,8',
  'Leave empty for all pages': 'Lämna tomt för alla sidor',
  'pages in this PDF': 'sidor i denna PDF',
  'New page order': 'Ny sidordning',
  'Enter every page once, separated by commas. Example: 3,1,2,4': 'Ange varje sida en gång, separerad med kommatecken. Exempel: 3,1,2,4',
  'Rotation': 'Rotation',
  'Top': 'Överkant',
  'Right': 'Höger',
  'Bottom': 'Nederkant',
  'Left': 'Vänster',
  'Position': 'Position',
  'Top left': 'Uppe till vänster',
  'Top center': 'Uppe i mitten',
  'Top right': 'Uppe till höger',
  'Center': 'Mitten',
  'Bottom left': 'Nere till vänster',
  'Bottom center': 'Nere i mitten',
  'Bottom right': 'Nere till höger',
  'Start number': 'Startnummer',
  'Text size': 'Textstorlek',
  'Text': 'Text',
  'CONFIDENTIAL': 'KONFIDENTIELLT',
  'Enter text to place on the PDF': 'Ange text som ska placeras i PDF-filen',
  'Opacity': 'Opacitet',
  'Signature image': 'Signaturbild',
  'Choose signature image': 'Välj signaturbild',
  'Signature width': 'Signaturbredd',
  'This places a visual signature. It does not create a certificate-based digital signature.': 'Detta placerar en visuell signatur och skapar inte en certifikatbaserad digital signatur.',
  'Orientation': 'Orientering',
  'Portrait': 'Stående',
  'Landscape': 'Liggande',
  'Page count': 'Antal sidor',
  'Letter': 'Letter',
  'Image format': 'Bildformat',
  'Resolution': 'Upplösning',
  'Standard': 'Standard',
  'High': 'Hög',
  'Very high': 'Mycket hög',
  'Compression level': 'Komprimeringsnivå',
  'Best quality': 'Bästa kvalitet',
  'Balanced': 'Balanserad',
  'Smallest file': 'Minsta fil',
  'Strong compression rebuilds each page as an image. Links and selectable text will be flattened.': 'Stark komprimering bygger om varje sida som en bild. Länkar och markerbar text plattas till.',
  'The ZIP will contain one PDF for each page.': 'ZIP-filen innehåller en separat PDF för varje sida.',
  'Flattening makes completed form fields non-editable in the output copy.': 'Tillplattning gör ifyllda formulärfält icke-redigerbara i resultatet.',
  'Processing PDF...': 'Bearbetar PDF...',
  'Reading PDF...': 'Läser PDF...',
  'Choose a PDF tool and add your file.': 'Välj ett PDF-verktyg och lägg till filen.',
  'Ready to download': 'Klar för nedladdning',
  'PDF result preview': 'Förhandsvisning av PDF-resultat',
  'Extracted text': 'Extraherad text',
  'ZIP package ready': 'ZIP-paketet är klart',
  'Download the ZIP to access every generated file.': 'Ladda ned ZIP-filen för att komma åt alla skapade filer.',
  'Original PDF': 'Ursprunglig PDF',
  'Original PDF preview': 'Förhandsvisning av ursprunglig PDF',
  'Create a new PDF': 'Skapa en ny PDF',
  'Choose the page settings, then create and download your blank document.': 'Välj sidinställningar och skapa och ladda sedan ned det tomma dokumentet.',
  'Page numbers must be within the document range.': 'Sidnumren måste ligga inom dokumentets sidintervall.',
  'Enter every page exactly once in the new order.': 'Ange varje sida exakt en gång i den nya ordningen.',
  'PDF processing failed.': 'PDF-bearbetningen misslyckades.',
  'Choose a PDF file first.': 'Välj först en PDF-fil.',
  'Choose one PDF file for this tool.': 'Välj en PDF-fil för detta verktyg.',
  'Choose no more than 12 PDF files.': 'Välj högst 12 PDF-filer.',
  'Choose at least two PDF files to merge.': 'Välj minst två PDF-filer som ska slås ihop.',
  'The merged PDF cannot exceed 150 pages.': 'Den sammanslagna PDF-filen får inte överstiga 150 sidor.',
  'The selected PDF files exceed the 120 MB combined safety limit.': 'De valda PDF-filerna överskrider den sammanlagda säkerhetsgränsen på 120 MB.',
  'PDF files must be larger than 0 bytes and no more than 50 MB each.': 'Varje PDF-fil måste vara större än 0 byte och högst 50 MB.',
  'This file is not a valid PDF document.': 'Filen är inte ett giltigt PDF-dokument.',
  'PDF page count must be between 1 and 150 pages.': 'PDF-filen måste innehålla mellan 1 och 150 sidor.',
  'This PDF is damaged or uses an unsupported format.': 'PDF-filen är skadad eller använder ett format som inte stöds.',
  'This PDF exceeded the safe decompression limit.': 'PDF-filen överskred den säkra gränsen för dekomprimering.',
  'Password-protected PDFs must be unlocked before using this local tool.': 'Lösenordsskyddade PDF-filer måste låsas upp innan det lokala verktyget används.',
  'Password-protected PDFs must be unlocked before conversion.': 'Lösenordsskyddade PDF-filer måste låsas upp före konvertering.',
  'Enter pages like 1-3,5,8.': 'Ange sidor så här: 1-3,5,8.',
  'Enter at least one page number.': 'Ange minst ett sidnummer.',
  'You cannot delete every page from the PDF.': 'Du kan inte ta bort alla sidor från PDF-filen.',
  'Crop margins must be between 0 and 100 millimetres.': 'Beskärningsmarginalerna måste vara mellan 0 och 100 millimeter.',
  'Crop margins leave no usable page area.': 'Beskärningsmarginalerna lämnar ingen användbar sidyta.',
  'Enter the text you want to add.': 'Ange texten du vill lägga till.',
  'Text size must be between 8 and 120 points.': 'Textstorleken måste vara mellan 8 och 120 punkter.',
  'Canvas processing is not available in this browser.': 'Canvas-bearbetning är inte tillgänglig i den här webbläsaren.',
  'The browser could not create the text layer.': 'Webbläsaren kunde inte skapa textlagret.',
  'The browser could not encode this PDF page.': 'Webbläsaren kunde inte koda den här PDF-sidan.',
  'Choose a signature image first.': 'Välj först en signaturbild.',
  'Use a PNG, JPEG, or WebP signature image.': 'Använd en signaturbild i PNG-, JPEG- eller WebP-format.',
  'Signature images must be no more than 10 MB.': 'Signaturbilder får vara högst 10 MB.',
  'Signature image dimensions are too large to process safely.': 'Signaturbildens mått är för stora för säker bearbetning.',
  'Blank PDFs can contain between 1 and 20 pages.': 'Tomma PDF-filer kan innehålla mellan 1 och 20 sidor.',
  'Image and text conversion supports PDFs up to 60 pages.': 'Bild- och textkonvertering stöder PDF-filer med upp till 60 sidor.',
  'Splitting supports PDFs up to 100 pages per ZIP.': 'Delning stöder PDF-filer med upp till 100 sidor per ZIP-fil.',
  'No selectable text was found. This PDF may require OCR.': 'Ingen markerbar text hittades. PDF-filen kan behöva OCR.',
  'This PDF does not contain interactive form fields.': 'PDF-filen innehåller inga interaktiva formulärfält.',
  'This PDF could not be rendered safely in the browser.': 'PDF-filen kunde inte visas säkert i webbläsaren.',
};

const supplementalMaps: Record<Language, PhraseMap> = { en: {}, ar: arSupplement, sv: svSupplement };

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return supplementalMaps[language][text] ?? localizeBaseUi(text, language);
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  const language = prefs.language;
  return useCallback((text: string) => localizeUi(text, language), [language]);
}
