import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arSupplement: PhraseMap = {
  'Close menu': 'إغلاق القائمة',
  'Open menu': 'فتح القائمة',
  'unread': 'غير مقروء',
  'Current subscriptions by plan': 'الاشتراكات الحالية حسب الخطة',
  'Active · cancels at period end': 'نشط · يُلغى عند نهاية الفترة',
  'Billing / Access Date': 'تاريخ الفوترة / الوصول',
  'Only runtime-enforced platform settings are editable here.': 'يمكن هنا تعديل إعدادات المنصة التي تُطبَّق فعليًا أثناء التشغيل فقط.',
  'Authoritative controls': 'عناصر التحكم المعتمدة',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'تتم إدارة الوصول إلى الأدوات وحدود الاستخدام من قسم Tools، بينما تتم إدارة مزود الذكاء الاصطناعي والنماذج من AI Management. تم إخفاء الإعدادات القديمة التي لا تؤثر فعليًا في سلوك النظام.',
  'API key inventory only': 'قائمة مفاتيح API فقط',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'هذه الصفوف بيانات وصفية فقط ولا تفعّل أو تعطّل أسرار الإنتاج التي تستخدمها Edge Functions. دوّر الأسرار الحية أو احذفها من أسرار مشروع Supabase.',
  'Read-only service metadata': 'بيانات وصفية للخدمات للقراءة فقط',
  'Failed to toggle tool': 'فشل تغيير حالة الأداة',
  'disabled': 'معطّل',
  'Failed to update tool plan': 'فشل تحديث خطة الأداة',
  'Failed to update usage limits': 'فشل تحديث حدود الاستخدام',
  'usage limits updated': 'تم تحديث حدود الاستخدام',
  'Tool plan access & limits': 'الوصول وحدود الاستخدام حسب الخطة',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'اختر الخطة التي يمكنها الوصول إلى كل أداة وحدد عدد الاستخدامات الناجحة المتاحة لمستخدمي Free وPro وBusiness يوميًا أو شهريًا أو مدى الحياة. اترك الحد فارغًا للاستخدام غير المحدود.',
  'Minimum plan': 'الحد الأدنى للخطة',
  'Reset period': 'فترة إعادة التعيين',
  'Daily': 'يومي',
  'Monthly': 'شهري',
  'Lifetime': 'مدى الحياة',
  'Unlimited': 'غير محدود',
  'recorded uses': 'استخدامات مسجلة',
  'Save limits': 'حفظ الحدود',
  'live quota': 'حد الاستخدام المباشر',
  'Processing...': 'جارٍ المعالجة...',
  'Change sort direction': 'تغيير اتجاه الفرز',
  'Grid view': 'عرض شبكي',
  'List view': 'عرض قائمة',
  'File actions': 'إجراءات الملف',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'اكتملت عملية الدفع. نقوم الآن بمزامنة اشتراكك، وسيتم تحديث خطتك تلقائيًا.',
  'Checkout was canceled. No plan change was made.': 'تم إلغاء عملية الدفع. لم يتم تغيير خطتك.',
  'Account menu': 'قائمة الحساب',
  'Could not clean this file.': 'تعذر تنظيف هذا الملف.',
  'Could not create invoice output.': 'تعذر إنشاء مخرجات الفاتورة.',
  'Could not generate this letter.': 'تعذر إنشاء هذا الخطاب.',
  'Could not generate names.': 'تعذر إنشاء الأسماء.',
  'Checking access...': 'جارٍ التحقق من الوصول...',
  'Access check unavailable': 'تعذر التحقق من الوصول',
  'We could not safely verify your plan. Please retry in a moment.': 'تعذر التحقق من خطتك بأمان. يرجى المحاولة مرة أخرى بعد قليل.',
  'Tool temporarily unavailable': 'الأداة غير متاحة مؤقتًا',
  'This tool has been disabled by the administrator.': 'تم تعطيل هذه الأداة بواسطة المسؤول.',
  'Usage limit reached': 'تم بلوغ حد الاستخدام',
  'View plans': 'عرض الخطط',
  'Website published successfully. Release history was skipped:': 'تم نشر الموقع بنجاح. تم تخطي سجل الإصدارات:',
  'No-code AI Provider Control': 'إدارة مزودي الذكاء الاصطناعي بدون كود',
  'Add a provider, Base URL, Model ID and API secret here. Secrets stay in Supabase Vault. After this control layer is installed, adding or changing providers does not require code changes or database changes.': 'أضف هنا المزود والرابط الأساسي ومعرّف النموذج وسر API. تبقى الأسرار محفوظة في Supabase Vault. بعد تفعيل طبقة التحكم هذه، لا يتطلب إضافة المزودين أو تغييرهم أي تعديل على الكود أو قاعدة البيانات.',
  'Current Gemini fallback active': 'إعداد Gemini الاحتياطي الحالي نشط',
  'Backend not enabled': 'الواجهة الخلفية غير مفعلة',
  'No managed provider has been added yet. Tayar continues using the current Gemini environment configuration until you add and activate one.': 'لم تتم إضافة مزود مُدار بعد. سيستمر Tayar باستخدام إعداد Gemini الحالي من متغيرات البيئة حتى تضيف مزودًا وتفعّله.',
  'Key': 'المفتاح',
  'Adapter': 'الموائم',
  'Base URL': 'الرابط الأساسي',
  'Model ID': 'معرّف النموذج',
  'Secret configured in Vault': 'السر محفوظ في Vault',
  'API secret missing': 'سر API مفقود',
  'Test': 'اختبار',
  'Make Default': 'تعيين كافتراضي',
  'Disable': 'تعطيل',
  'Enable': 'تفعيل',
  'Edit AI Provider': 'تعديل مزود الذكاء الاصطناعي',
  'Add AI Provider': 'إضافة مزود ذكاء اصطناعي',
  'Leave API Secret empty while editing to keep the existing secret.': 'اترك حقل سر API فارغًا أثناء التعديل للاحتفاظ بالسر الحالي.',
  'Provider Key': 'مفتاح المزود',
  'Display Name': 'اسم العرض',
  'API Secret': 'سر API',
  'Leave blank to keep current secret': 'اتركه فارغًا للاحتفاظ بالسر الحالي',
  'Save Provider': 'حفظ المزود',
  'Current Gemini fallback': 'إعداد Gemini الاحتياطي الحالي',
  'This keeps Tayar working exactly as it does today when no managed provider is active.': 'يحافظ هذا على عمل Tayar بالطريقة الحالية نفسها عندما لا يكون هناك مزود مُدار نشط.',
  'Save fallback': 'حفظ الإعداد الاحتياطي',
  'Configuration Center': 'مركز الإعدادات',
  'Manage AI providers, Stripe prices and coupons from the Admin Panel without editing application code. API secrets remain server-side and are never shown back in the browser.': 'أدر مزودي الذكاء الاصطناعي وأسعار Stripe والكوبونات من لوحة الإدارة بدون تعديل كود التطبيق. تبقى أسرار API على الخادم ولا يتم عرضها مرة أخرى في المتصفح.',
  'Refresh status': 'تحديث الحالة',
  'AI Providers': 'مزودو الذكاء الاصطناعي',
  'Add, test, enable and choose the default provider': 'أضف المزودين واختبرهم وفعّلهم واختر المزود الافتراضي',
  'Gemini fallback': 'Gemini الاحتياطي',
  'Secret': 'السر',
  'Configured securely': 'مُعدّ بأمان',
  'Manage AI Providers': 'إدارة مزودي الذكاء الاصطناعي',
  'Payments & Pricing': 'المدفوعات والتسعير',
  'Manage Stripe prices and promotion codes': 'إدارة أسعار Stripe ورموز الخصم',
  'Stripe': 'Stripe',
  'Not connected': 'غير متصل',
  'Checkout / Portal': 'الدفع / البوابة',
  'Ready': 'جاهز',
  'Manage Prices & Coupons': 'إدارة الأسعار والكوبونات',
  'Safe operating model: adding a compatible AI provider or changing the active Stripe price is done from Admin. Existing subscribers keep their historical Stripe price unless you explicitly migrate them later.': 'نموذج تشغيل آمن: تتم إضافة مزود ذكاء اصطناعي متوافق أو تغيير سعر Stripe النشط من لوحة الإدارة. يحتفظ المشتركون الحاليون بسعر Stripe التاريخي الخاص بهم ما لم تقم بترحيلهم صراحةً لاحقًا.',
  'Always': 'دائمًا',
  'Enter a valid price greater than zero.': 'أدخل سعرًا صالحًا أكبر من صفر.',
  'Create and activate a new Stripe price for': 'إنشاء وتفعيل سعر Stripe جديد لخطة',
  'new price created and activated for new checkouts.': 'تم إنشاء السعر الجديد وتفعيله لعمليات الدفع الجديدة.',
  'Coupon code is required.': 'رمز الكوبون مطلوب.',
  'Coupon created and activated.': 'تم إنشاء الكوبون وتفعيله.',
  'Disable this promotion code?': 'هل تريد تعطيل رمز الخصم هذا؟',
  'Coupon disabled.': 'تم تعطيل الكوبون.',
  'Price Control': 'إدارة الأسعار',
  'Changing a plan creates a new Stripe Price and activates it for new checkouts. Existing subscribers are not migrated automatically.': 'يؤدي تغيير سعر الخطة إلى إنشاء سعر Stripe جديد وتفعيله لعمليات الدفع الجديدة. لا يتم نقل المشتركين الحاليين تلقائيًا إلى السعر الجديد.',
  'Creating…': 'جارٍ الإنشاء…',
  'Create & Activate New Price': 'إنشاء وتفعيل سعر جديد',
  'Coupon Manager': 'إدارة الكوبونات',
  'Code, e.g. WELCOME20': 'الرمز، مثال: WELCOME20',
  'Percent discount': 'خصم بالنسبة المئوية',
  'Fixed amount': 'مبلغ ثابت',
  'Once': 'مرة واحدة',
  'Forever': 'دائمًا',
  'Max uses (optional)': 'الحد الأقصى للاستخدامات (اختياري)',
  'Working…': 'جارٍ التنفيذ…',
  'Create Coupon': 'إنشاء كوبون',
  'Loading…': 'جارٍ التحميل…',
  'Refresh Coupons': 'تحديث الكوبونات',
  'No promotion codes found.': 'لم يتم العثور على رموز خصم.',
};

export const svSupplement: PhraseMap = {
  'Close menu': 'Stäng meny',
  'Open menu': 'Öppna meny',
  'unread': 'olästa',
  'Current subscriptions by plan': 'Aktuella prenumerationer per plan',
  'Active · cancels at period end': 'Aktiv · avslutas vid periodens slut',
  'Billing / Access Date': 'Fakturerings-/åtkomstdatum',
  'Only runtime-enforced platform settings are editable here.': 'Endast plattformsinställningar som faktiskt upprätthålls vid körning kan redigeras här.',
  'Authoritative controls': 'Styrande kontroller',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'Verktygsåtkomst och användningsgränser hanteras i Tools. AI-leverantör och modellkontroller hanteras i AI Management. Äldre inställningar som inte påverkar körningen är avsiktligt dolda här.',
  'API key inventory only': 'Endast API-nyckelinventering',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'Dessa rader är endast metadata och aktiverar eller inaktiverar inte produktionshemligheterna som används av Edge Functions. Rotera eller ta bort aktiva hemligheter i Supabase-projektets secrets.',
  'Read-only service metadata': 'Skrivskyddad tjänstemetadata',
  'Failed to toggle tool': 'Det gick inte att ändra verktygets status',
  'disabled': 'inaktiverad',
  'Failed to update tool plan': 'Det gick inte att uppdatera verktygets plan',
  'Failed to update usage limits': 'Det gick inte att uppdatera användningsgränserna',
  'usage limits updated': 'användningsgränserna uppdaterades',
  'Tool plan access & limits': 'Verktygsåtkomst och gränser per plan',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'Välj vilken plan som får använda varje verktyg och hur många lyckade användningar Free-, Pro- och Business-användare kan göra per dag, månad eller under hela livstiden. Lämna en gräns tom för obegränsad användning.',
  'Minimum plan': 'Lägsta plan',
  'Reset period': 'Återställningsperiod',
  'Daily': 'Daglig',
  'Monthly': 'Månadsvis',
  'Lifetime': 'Livstid',
  'Unlimited': 'Obegränsat',
  'recorded uses': 'registrerade användningar',
  'Save limits': 'Spara gränser',
  'live quota': 'livekvot',
  'Processing...': 'Bearbetar...',
  'Change sort direction': 'Ändra sorteringsriktning',
  'Grid view': 'Rutnätsvy',
  'List view': 'Listvy',
  'File actions': 'Filåtgärder',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'Betalningen är klar. Vi synkroniserar din prenumeration nu. Din plan uppdateras automatiskt.',
  'Checkout was canceled. No plan change was made.': 'Kassan avbröts. Ingen planändring gjordes.',
  'Account menu': 'Kontomeny',
  'Could not clean this file.': 'Kunde inte rensa den här filen.',
  'Could not create invoice output.': 'Kunde inte skapa fakturautdata.',
  'Could not generate this letter.': 'Kunde inte skapa det här brevet.',
  'Could not generate names.': 'Kunde inte generera namn.',
  'Checking access...': 'Kontrollerar åtkomst...',
  'Access check unavailable': 'Åtkomstkontroll är inte tillgänglig',
  'We could not safely verify your plan. Please retry in a moment.': 'Vi kunde inte verifiera din plan på ett säkert sätt. Försök igen om en stund.',
  'Tool temporarily unavailable': 'Verktyget är tillfälligt otillgängligt',
  'This tool has been disabled by the administrator.': 'Det här verktyget har inaktiverats av administratören.',
  'Usage limit reached': 'Användningsgränsen har nåtts',
  'View plans': 'Visa planer',
  'Website published successfully. Release history was skipped:': 'Webbplatsen publicerades. Versionshistoriken hoppades över:',
  'No-code AI Provider Control': 'AI-leverantörshantering utan kod',
  'Add a provider, Base URL, Model ID and API secret here. Secrets stay in Supabase Vault. After this control layer is installed, adding or changing providers does not require code changes or database changes.': 'Lägg till leverantör, bas-URL, modell-ID och API-hemlighet här. Hemligheter lagras i Supabase Vault. När detta kontrollager är installerat kräver tillägg eller byte av leverantör inga kod- eller databasändringar.',
  'Current Gemini fallback active': 'Nuvarande Gemini-reserv är aktiv',
  'Backend not enabled': 'Backend är inte aktiverad',
  'No managed provider has been added yet. Tayar continues using the current Gemini environment configuration until you add and activate one.': 'Ingen hanterad leverantör har lagts till ännu. Tayar fortsätter använda den nuvarande Gemini-konfigurationen från miljön tills du lägger till och aktiverar en leverantör.',
  'Key': 'Nyckel',
  'Adapter': 'Adapter',
  'Base URL': 'Bas-URL',
  'Model ID': 'Modell-ID',
  'Secret configured in Vault': 'Hemlighet sparad i Vault',
  'API secret missing': 'API-hemlighet saknas',
  'Test': 'Testa',
  'Make Default': 'Ange som standard',
  'Disable': 'Inaktivera',
  'Enable': 'Aktivera',
  'Edit AI Provider': 'Redigera AI-leverantör',
  'Add AI Provider': 'Lägg till AI-leverantör',
  'Leave API Secret empty while editing to keep the existing secret.': 'Lämna API-hemligheten tom vid redigering för att behålla den befintliga hemligheten.',
  'Provider Key': 'Leverantörsnyckel',
  'Display Name': 'Visningsnamn',
  'API Secret': 'API-hemlighet',
  'Leave blank to keep current secret': 'Lämna tomt för att behålla nuvarande hemlighet',
  'Save Provider': 'Spara leverantör',
  'Current Gemini fallback': 'Nuvarande Gemini-reserv',
  'This keeps Tayar working exactly as it does today when no managed provider is active.': 'Detta gör att Tayar fortsätter fungera som idag när ingen hanterad leverantör är aktiv.',
  'Save fallback': 'Spara reserv',
  'Configuration Center': 'Konfigurationscenter',
  'Manage AI providers, Stripe prices and coupons from the Admin Panel without editing application code. API secrets remain server-side and are never shown back in the browser.': 'Hantera AI-leverantörer, Stripe-priser och kuponger från adminpanelen utan att ändra applikationskod. API-hemligheter stannar på serversidan och visas aldrig tillbaka i webbläsaren.',
  'Refresh status': 'Uppdatera status',
  'AI Providers': 'AI-leverantörer',
  'Add, test, enable and choose the default provider': 'Lägg till, testa och aktivera leverantörer samt välj standardleverantör',
  'Gemini fallback': 'Gemini-reserv',
  'Secret': 'Hemlighet',
  'Configured securely': 'Säkert konfigurerad',
  'Manage AI Providers': 'Hantera AI-leverantörer',
  'Payments & Pricing': 'Betalningar och prissättning',
  'Manage Stripe prices and promotion codes': 'Hantera Stripe-priser och kampanjkoder',
  'Stripe': 'Stripe',
  'Not connected': 'Inte ansluten',
  'Checkout / Portal': 'Checkout / portal',
  'Ready': 'Klar',
  'Manage Prices & Coupons': 'Hantera priser och kuponger',
  'Safe operating model: adding a compatible AI provider or changing the active Stripe price is done from Admin. Existing subscribers keep their historical Stripe price unless you explicitly migrate them later.': 'Säker driftmodell: en kompatibel AI-leverantör läggs till och det aktiva Stripe-priset ändras från Admin. Befintliga prenumeranter behåller sitt tidigare Stripe-pris om du inte uttryckligen migrerar dem senare.',
  'Always': 'Alltid',
  'Enter a valid price greater than zero.': 'Ange ett giltigt pris som är större än noll.',
  'Create and activate a new Stripe price for': 'Skapa och aktivera ett nytt Stripe-pris för',
  'new price created and activated for new checkouts.': 'nytt pris skapades och aktiverades för nya checkouter.',
  'Coupon code is required.': 'Kupongkod krävs.',
  'Coupon created and activated.': 'Kupongen skapades och aktiverades.',
  'Disable this promotion code?': 'Inaktivera den här kampanjkoden?',
  'Coupon disabled.': 'Kupongen inaktiverades.',
  'Price Control': 'Prishantering',
  'Changing a plan creates a new Stripe Price and activates it for new checkouts. Existing subscribers are not migrated automatically.': 'När ett planpris ändras skapas ett nytt Stripe Price som aktiveras för nya checkouter. Befintliga prenumeranter migreras inte automatiskt.',
  'Creating…': 'Skapar…',
  'Create & Activate New Price': 'Skapa och aktivera nytt pris',
  'Coupon Manager': 'Kuponghantering',
  'Code, e.g. WELCOME20': 'Kod, t.ex. WELCOME20',
  'Percent discount': 'Procentrabatt',
  'Fixed amount': 'Fast belopp',
  'Once': 'En gång',
  'Forever': 'För alltid',
  'Max uses (optional)': 'Max antal användningar (valfritt)',
  'Working…': 'Arbetar…',
  'Create Coupon': 'Skapa kupong',
  'Loading…': 'Laddar…',
  'Refresh Coupons': 'Uppdatera kuponger',
  'No promotion codes found.': 'Inga kampanjkoder hittades.',
};

const supplementalMaps: Record<Language, PhraseMap> = { en: {}, ar: arSupplement, sv: svSupplement };

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return supplementalMaps[language][text] ?? localizeBaseUi(text, language);
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  return (text: string) => localizeUi(text, prefs.language);
}
