import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { localizeUi as localizeBaseUi } from './ui-localization';

type PhraseMap = Record<string, string>;

export const arSupplement: PhraseMap = {
  'Close menu': 'إغلاق القائمة',
  'Open menu': 'فتح القائمة',
  'unread': 'غير مقروء',
  'Current subscriptions by plan': 'الاشتراكات الحالية حسب الخطة',
  'Active · cancels at period end': 'نشط · يُلغى عند نهاية الفترة',
  'Billing / Access Date': 'تاريخ الفوترة / الوصول',
  'Only runtime-enforced platform settings are editable here.': 'يمكن هنا تعديل إعدادات المنصة التي تُطبَّق فعليًا أثناء التشغيل فقط.',
  'Authoritative controls': 'عناصر التحكم المعتمدة',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'تتم إدارة الوصول إلى الأدوات وحدود الاستخدام من قسم Tools، بينما تتم إدارة مزود الذكاء الاصطناعي والنماذج من AI Management. تم إخفاء الإعدادات القديمة التي لا تؤثر فعليًا في سلوك النظام.',
  'API key inventory only': 'قائمة مفاتيح API فقط',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'هذه الصفوف بيانات وصفية فقط ولا تفعّل أو تعطّل أسرار الإنتاج التي تستخدمها Edge Functions. دوّر الأسرار الحية أو احذفها من أسرار مشروع Supabase.',
  'Read-only service metadata': 'بيانات وصفية للخدمات للقراءة فقط',
  'Failed to toggle tool': 'فشل تغيير حالة الأداة',
  'disabled': 'معطّل',
  'Failed to update tool plan': 'فشل تحديث خطة الأداة',
  'Failed to update usage limits': 'فشل تحديث حدود الاستخدام',
  'usage limits updated': 'تم تحديث حدود الاستخدام',
  'Tool plan access & limits': 'الوصول وحدود الاستخدام حسب الخطة',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'اختر الخطة التي يمكنها الوصول إلى كل أداة وحدد عدد الاستخدامات الناجحة المتاحة لمستخدمي Free وPro وBusiness يوميًا أو شهريًا أو مدى الحياة. اترك الحد فارغًا للاستخدام غير المحدود.',
  'Minimum plan': 'الحد الأدنى للخطة',
  'Reset period': 'فترة إعادة التعيين',
  'Daily': 'يومي',
  'Monthly': 'شهري',
  'Lifetime': 'مدى الحياة',
  'Unlimited': 'غير محدود',
  'recorded uses': 'استخدامات مسجلة',
  'Save limits': 'حفظ الحدود',
  'live quota': 'حد الاستخدام المباشر',
  'Processing...': 'جارٍ المعالجة...',
  'Change sort direction': 'تغيير اتجاه الفرز',
  'Grid view': 'عرض شبكي',
  'List view': 'عرض قائمة',
  'File actions': 'إجراءات الملف',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'اكتملت عملية الدفع. نقوم الآن بمزامنة اشتراكك، وسيتم تحديث خطتك تلقائيًا.',
  'Checkout was canceled. No plan change was made.': 'تم إلغاء عملية الدفع. لم يتم تغيير خطتك.',
  'Account menu': 'قائمة الحساب',
  'Could not clean this file.': 'تعذر تنظيف هذا الملف.',
  'Could not create invoice output.': 'تعذر إنشاء مخرجات الفاتورة.',
  'Could not generate this letter.': 'تعذر إنشاء هذا الخطاب.',
  'Could not generate names.': 'تعذر إنشاء الأسماء.',
  'Checking access...': 'جارٍ التحقق من الوصول...',
  'Access check unavailable': 'تعذر التحقق من الوصول',
  'We could not safely verify your plan. Please retry in a moment.': 'تعذر التحقق من خطتك بأمان. يرجى المحاولة مرة أخرى بعد قليل.',
  'Tool temporarily unavailable': 'الأداة غير متاحة مؤقتًا',
  'This tool has been disabled by the administrator.': 'تم تعطيل هذه الأداة بواسطة المسؤول.',
  'Usage limit reached': 'تم بلوغ حد الاستخدام',
  'View plans': 'عرض الخطط',
  'Website published successfully. Release history was skipped:': 'تم نشر الموقع بنجاح. تم تخطي سجل الإصدارات:',
  'Continue with Google': 'المتابعة باستخدام Google',
  'Start free with your Tayar workspace, Website Builder and included tools.': 'ابدأ مجانًا مع مساحة عمل Tayar ومنشئ المواقع والأدوات المتضمنة.',
  '1 Website Builder project with up to 3 pages': 'مشروع Website Builder واحد حتى 3 صفحات',
  'Free-access tools with Free plan usage limits': 'أدوات الخطة المجانية ضمن حدود استخدام Free',
  'Sign in to continue to your Tayar workspace.': 'سجّل الدخول للمتابعة إلى مساحة عمل Tayar.',
  'Quick setup': 'إعداد سريع',
  'One workspace for websites, documents, AI tools and client work. Personalize your setup, or skip and explore right away.': 'مساحة واحدة للمواقع والمستندات وأدوات الذكاء الاصطناعي وأعمال العملاء. خصّص إعدادك أو تخطَّ الخطوات واستكشف مباشرة.',
  'Personalize my workspace': 'تخصيص مساحة عملي',
  'Skip for now': 'تخطي الآن',
  'You can change your language, profile and preferences later in Settings.': 'يمكنك تغيير اللغة والملف الشخصي والتفضيلات لاحقًا من الإعدادات.',
  'Build and publish a website': 'بناء ونشر موقع',
  'Study, write and organize work with focused tools': 'ادرس واكتب ونظّم عملك بأدوات مركزة',
  'Build CVs, cover letters and job-ready documents': 'أنشئ سيرًا ذاتية وخطابات تقديم ومستندات جاهزة للعمل',
  'Create documents and everyday work from one workspace': 'أنشئ المستندات وأنجز عملك اليومي من مساحة واحدة',
  'Build your web presence and manage business workflows': 'ابنِ حضورك على الويب وأدر سير عملك التجاري',
  'Build, write and deliver client work from one workspace': 'ابنِ واكتب وسلّم أعمال العملاء من مساحة واحدة',
  'Browse your tools, recommendations and recent activity from one place.': 'استعرض أدواتك وتوصياتك ونشاطك الأخير من مكان واحد.',
  'Your projects, files and everyday work stay together here.': 'تبقى مشاريعك وملفاتك وعملك اليومي مجتمعة هنا.',
  'Build and publish a responsive website with manual controls and guided workflows.': 'أنشئ وانشر موقعًا متجاوبًا مع تحكم يدوي وسير عمل موجّه.',
  'Find saved documents, exports and project files without hunting across tools.': 'اعثر على المستندات المحفوظة والصادرات وملفات المشاريع بدون البحث بين الأدوات.',
  'See your current plan, included limits and billing options in one place.': 'شاهد خطتك الحالية والحدود المتضمنة وخيارات الفوترة في مكان واحد.',
  'Your Tayar workspace is ready. Start with the recommendation below or explore everything at your own pace.': 'مساحة عمل Tayar جاهزة. ابدأ بالتوصية أدناه أو استكشف كل شيء بالسرعة التي تناسبك.',
  'Explore all tools': 'استكشف كل الأدوات',
  'Browse every available tool and choose what you need.': 'استعرض كل الأدوات المتاحة واختر ما تحتاجه.',
  'Take the product tour': 'ابدأ جولة المنتج',
  'See where projects, tools and plan controls live.': 'تعرّف على مكان المشاريع والأدوات والتحكم بالخطة.',
  'Start with your recommended tool': 'ابدأ بالأداة الموصى بها',
  'Review your plan and limits': 'راجع خطتك وحدودها',
  'project': 'مشروع',
  'projects': 'مشاريع',
};

export const svSupplement: PhraseMap = {
  'Close menu': 'Stäng meny',
  'Open menu': 'Öppna meny',
  'unread': 'olästa',
  'Current subscriptions by plan': 'Aktuella prenumerationer per plan',
  'Active · cancels at period end': 'Aktiv · avslutas vid periodens slut',
  'Billing / Access Date': 'Fakturerings-/åtkomstdatum',
  'Only runtime-enforced platform settings are editable here.': 'Endast plattformsinställningar som faktiskt upprätthålls vid körning kan redigeras här.',
  'Authoritative controls': 'Styrande kontroller',
  'Tool access and quotas are managed in Tools. AI provider and model controls are managed in AI Management. Legacy settings that do not enforce runtime behavior are intentionally hidden here.': 'Verktygsåtkomst och användningsgränser hanteras i Tools. AI-leverantör och modellkontroller hanteras i AI Management. Äldre inställningar som inte påverkar körningen är avsiktligt dolda här.',
  'API key inventory only': 'Endast API-nyckelinventering',
  'These rows are metadata and do not enable or disable the production secrets used by Edge Functions. Rotate or remove live secrets in Supabase project secrets.': 'Dessa rader är endast metadata och aktiverar eller inaktiverar inte produktionshemligheterna som används av Edge Functions. Rotera eller ta bort aktiva hemligheter i Supabase-projektets secrets.',
  'Read-only service metadata': 'Skrivskyddad tjänstemetadata',
  'Failed to toggle tool': 'Det gick inte att ändra verktygets status',
  'disabled': 'inaktiverad',
  'Failed to update tool plan': 'Det gick inte att uppdatera verktygets plan',
  'Failed to update usage limits': 'Det gick inte att uppdatera användningsgränserna',
  'usage limits updated': 'användningsgränserna uppdaterades',
  'Tool plan access & limits': 'Verktygsåtkomst och gränser per plan',
  'Choose which plan can access each tool and how many successful uses Free, Pro and Business users can complete per day, month or lifetime. Leave a limit empty for unlimited use.': 'Välj vilken plan som får använda varje verktyg och hur många lyckade användningar Free-, Pro- och Business-användare kan göra per dag, månad eller under hela livstiden. Lämna en gräns tom för obegränsad användning.',
  'Minimum plan': 'Lägsta plan',
  'Reset period': 'Återställningsperiod',
  'Daily': 'Daglig',
  'Monthly': 'Månadsvis',
  'Lifetime': 'Livstid',
  'Unlimited': 'Obegränsat',
  'recorded uses': 'registrerade användningar',
  'Save limits': 'Spara gränser',
  'live quota': 'livekvot',
  'Processing...': 'Bearbetar...',
  'Change sort direction': 'Ändra sorteringsriktning',
  'Grid view': 'Rutnätsvy',
  'List view': 'Listvy',
  'File actions': 'Filåtgärder',
  'Payment completed. We are syncing your subscription now. Your plan will refresh automatically.': 'Betalningen är klar. Vi synkroniserar din prenumeration nu. Din plan uppdateras automatiskt.',
  'Checkout was canceled. No plan change was made.': 'Kassan avbröts. Ingen planändring gjordes.',
  'Account menu': 'Kontomeny',
  'Could not clean this file.': 'Kunde inte rensa den här filen.',
  'Could not create invoice output.': 'Kunde inte skapa fakturautdata.',
  'Could not generate this letter.': 'Kunde inte skapa det här brevet.',
  'Could not generate names.': 'Kunde inte generera namn.',
  'Checking access...': 'Kontrollerar åtkomst...',
  'Access check unavailable': 'Åtkomstkontroll är inte tillgänglig',
  'We could not safely verify your plan. Please retry in a moment.': 'Vi kunde inte verifiera din plan på ett säkert sätt. Försök igen om en stund.',
  'Tool temporarily unavailable': 'Verktyget är tillfälligt otillgängligt',
  'This tool has been disabled by the administrator.': 'Det här verktyget har inaktiverats av administratören.',
  'Usage limit reached': 'Användningsgränsen har nåtts',
  'View plans': 'Visa planer',
  'Website published successfully. Release history was skipped:': 'Webbplatsen publicerades. Versionshistoriken hoppades över:',
  'Continue with Google': 'Fortsätt med Google',
  'Start free with your Tayar workspace, Website Builder and included tools.': 'Börja gratis med din Tayar-arbetsyta, Webbplatsbyggaren och inkluderade verktyg.',
  '1 Website Builder project with up to 3 pages': '1 Website Builder-projekt med upp till 3 sidor',
  'Free-access tools with Free plan usage limits': 'Free-verktyg med Free-planens användningsgränser',
  'Sign in to continue to your Tayar workspace.': 'Logga in för att fortsätta till din Tayar-arbetsyta.',
  'Quick setup': 'Snabb konfiguration',
  'One workspace for websites, documents, AI tools and client work. Personalize your setup, or skip and explore right away.': 'En arbetsyta för webbplatser, dokument, AI-verktyg och kundarbete. Anpassa din konfiguration eller hoppa över och utforska direkt.',
  'Personalize my workspace': 'Anpassa min arbetsyta',
  'Skip for now': 'Hoppa över just nu',
  'You can change your language, profile and preferences later in Settings.': 'Du kan ändra språk, profil och inställningar senare under Inställningar.',
  'Build and publish a website': 'Bygg och publicera en webbplats',
  'Study, write and organize work with focused tools': 'Studera, skriv och organisera arbetet med fokuserade verktyg',
  'Build CVs, cover letters and job-ready documents': 'Skapa CV:n, personliga brev och jobbfärdiga dokument',
  'Create documents and everyday work from one workspace': 'Skapa dokument och gör vardagsarbetet från en arbetsyta',
  'Build your web presence and manage business workflows': 'Bygg din webbnärvaro och hantera företagets arbetsflöden',
  'Build, write and deliver client work from one workspace': 'Bygg, skriv och leverera kundarbete från en arbetsyta',
  'Browse your tools, recommendations and recent activity from one place.': 'Se dina verktyg, rekommendationer och senaste aktivitet på ett ställe.',
  'Your projects, files and everyday work stay together here.': 'Dina projekt, filer och ditt vardagsarbete hålls samlat här.',
  'Build and publish a responsive website with manual controls and guided workflows.': 'Bygg och publicera en responsiv webbplats med manuella kontroller och guidade arbetsflöden.',
  'Find saved documents, exports and project files without hunting across tools.': 'Hitta sparade dokument, exporter och projektfiler utan att leta mellan verktyg.',
  'See your current plan, included limits and billing options in one place.': 'Se din nuvarande plan, inkluderade gränser och faktureringsalternativ på ett ställe.',
  'Your Tayar workspace is ready. Start with the recommendation below or explore everything at your own pace.': 'Din Tayar-arbetsyta är klar. Börja med rekommendationen nedan eller utforska allt i din egen takt.',
  'Explore all tools': 'Utforska alla verktyg',
  'Browse every available tool and choose what you need.': 'Bläddra bland alla tillgängliga verktyg och välj det du behöver.',
  'Take the product tour': 'Ta produktturen',
  'See where projects, tools and plan controls live.': 'Se var projekt, verktyg och plankontroller finns.',
  'Start with your recommended tool': 'Börja med ditt rekommenderade verktyg',
  'Review your plan and limits': 'Granska din plan och dina gränser',
  'project': 'projekt',
  'projects': 'projekt',
};

const supplementalMaps: Record<Language, PhraseMap> = { en: {}, ar: arSupplement, sv: svSupplement };

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return supplementalMaps[language][text] ?? localizeBaseUi(text, language);
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  return (text: string) => localizeUi(text, prefs.language);
}
