import type { Language } from './i18n';

// Tool labels that were left in English in the signed-in Swedish and Arabic workspace.
const ar: Record<string, string> = {
  'No API': 'دون واجهة برمجة',
  'Generate Names': 'إنشاء أسماء',
  'Generate New Ideas': 'إنشاء أفكار جديدة',
  'Could not generate names.': 'تعذر إنشاء الأسماء.',
  'original combinations': 'تركيبة أصلية',
  'business-ready · modern tone': 'مناسب للأعمال · طابع عصري',
  'business-ready': 'مناسب للأعمال',
  'product-friendly': 'مناسب للمنتجات',
  'brandable': 'مناسب لعلامة تجارية',
  'channel-friendly': 'مناسب للقنوات',
  'handle-friendly': 'مناسب لأسماء الحسابات',
  'modern tone': 'طابع عصري',
  'professional tone': 'طابع مهني',
  'friendly tone': 'طابع ودود',
  'bold tone': 'طابع جريء',
  'minimal tone': 'طابع بسيط',
  'Recommendation Letter': 'خطاب توصية',
  'Authorization Letter': 'خطاب تفويض',
  'Business Inquiry': 'استفسار تجاري',
  'Complaint Letter': 'خطاب شكوى',
  'Resignation Letter': 'خطاب استقالة',
  'Thank-you Letter': 'خطاب شكر',
  'Recommend a person for work, study or another opportunity.': 'قدّم توصية لشخص للعمل أو الدراسة أو فرصة أخرى.',
  'Authorize a person to act or collect something on your behalf.': 'فوّض شخصًا للتصرف أو استلام شيء نيابة عنك.',
  'Ask a company about products, services, pricing or cooperation.': 'استفسر من شركة عن المنتجات أو الخدمات أو الأسعار أو التعاون.',
  'Describe an issue clearly and request a reasonable resolution.': 'اشرح المشكلة بوضوح واطلب حلاً مناسبًا.',
  'Submit a professional notice of resignation.': 'قدّم إشعار استقالة مهنيًا.',
  'Send a professional or warm note of appreciation.': 'أرسل رسالة شكر مهنية أو ودية.',
  'Generate Letter': 'إنشاء الرسالة',
  'Regenerate Letter': 'إعادة إنشاء الرسالة',
  'Could not generate this letter.': 'تعذر إنشاء هذه الرسالة.',
  'Invoice items': 'بنود الفاتورة',
  'VAT is calculated per line.': 'تُحسب الضريبة لكل بند.',
  'Add item': 'إضافة بند',
  'Issue': 'الإصدار',
  'Due': 'الاستحقاق',
  'Price': 'السعر',
  'Classic': 'كلاسيكي',
  'Balanced and professional.': 'متوازن ومهني.',
  'Clean with a violet accent.': 'بسيط مع لمسة بنفسجية.',
  'Quiet typography and light rules.': 'خط هادئ وفواصل خفيفة.',
  'High-contrast business style.': 'طابع أعمال بتباين عالٍ.',
  'Compose': 'إنشاء',
  'Reply': 'رد',
  'Improve': 'تحسين',
  'What should the email say?': 'ما مضمون الرسالة؟',
  'Write Email': 'كتابة البريد',
  'Draft': 'مسودة',
  'Review': 'مراجعة',
  'Clause': 'بند',
  'Draft Contract': 'صياغة العقد',
  'Analyze with AI': 'تحليل بالذكاء الاصطناعي',
  'Upload a dataset to begin.': 'أضف مجموعة بيانات للبدء.',
  'Choose CSV, TSV or TXT': 'اختر CSV أو TSV أو TXT',
  'Maximum 2 MB · processed on your device': 'الحد الأقصى 2 MB · يُعالج على جهازك',
  'Private · Local AI': 'خاص · ذكاء اصطناعي محلي',
  'Local batch': 'معالجة دفعات محلية',
  'Local PDF': 'PDF محلي',
  'Original library': 'مكتبة أصلية',
  'Local processing': 'معالجة محلية',
  'Write Reply': 'كتابة رد',
  'Improve Email': 'تحسين البريد',
  'Instructions / Context': 'تعليمات / سياق',
  'Received Email': 'البريد المستلم',
  'Email to Improve': 'البريد المراد تحسينه',
  'Review Contract': 'مراجعة العقد',
  'Improve Clause': 'تحسين البند',
  'What should AI focus on?': 'ما الذي يجب أن يركز عليه الذكاء الاصطناعي؟',
  'How should the clause change?': 'كيف يجب تعديل البند؟',
  'Contract Text': 'نص العقد',
  'Clause Text': 'نص البند',
  'Draft output': 'نتيجة الصياغة',
  'Review output': 'نتيجة المراجعة',
};

const sv: Record<string, string> = {
  'No API': 'Utan API',
  'Generate Names': 'Generera namn',
  'Generate New Ideas': 'Generera nya idéer',
  'Could not generate names.': 'Kunde inte generera namn.',
  'original combinations': 'originella kombinationer',
  'business-ready · modern tone': 'företagsanpassad · modern ton',
  'business-ready': 'företagsanpassad',
  'product-friendly': 'produktanpassad',
  'brandable': 'passar som varumärke',
  'channel-friendly': 'kanalanpassad',
  'handle-friendly': 'passar som kontonamn',
  'modern tone': 'modern ton',
  'professional tone': 'professionell ton',
  'friendly tone': 'vänlig ton',
  'bold tone': 'djärv ton',
  'minimal tone': 'enkel ton',
  'Recommendation Letter': 'Rekommendationsbrev',
  'Authorization Letter': 'Fullmaktsbrev',
  'Business Inquiry': 'Företagsförfrågan',
  'Complaint Letter': 'Klagomålsbrev',
  'Resignation Letter': 'Uppsägningsbrev',
  'Thank-you Letter': 'Tackbrev',
  'Recommend a person for work, study or another opportunity.': 'Rekommendera någon för arbete, studier eller en annan möjlighet.',
  'Authorize a person to act or collect something on your behalf.': 'Ge någon rätt att agera eller hämta något åt dig.',
  'Ask a company about products, services, pricing or cooperation.': 'Fråga ett företag om produkter, tjänster, priser eller samarbete.',
  'Describe an issue clearly and request a reasonable resolution.': 'Beskriv ett problem tydligt och be om en rimlig lösning.',
  'Submit a professional notice of resignation.': 'Skriv ett professionellt uppsägningsbesked.',
  'Send a professional or warm note of appreciation.': 'Skicka ett professionellt eller varmt tackbrev.',
  'Generate Letter': 'Generera brev',
  'Regenerate Letter': 'Generera brevet igen',
  'Could not generate this letter.': 'Kunde inte generera brevet.',
  'Invoice items': 'Fakturarader',
  'VAT is calculated per line.': 'Moms beräknas per rad.',
  'Add item': 'Lägg till rad',
  'Issue': 'Utfärdad',
  'Due': 'Förfaller',
  'Price': 'Pris',
  'Classic': 'Klassisk',
  'Balanced and professional.': 'Balanserad och professionell.',
  'Clean with a violet accent.': 'Ren med en violett accent.',
  'Quiet typography and light rules.': 'Lugn typografi och tunna linjer.',
  'High-contrast business style.': 'Affärsstil med hög kontrast.',
  'Compose': 'Skriv nytt',
  'Reply': 'Svara',
  'Improve': 'Förbättra',
  'What should the email say?': 'Vad ska e-postmeddelandet innehålla?',
  'Write Email': 'Skriv e-post',
  'Draft': 'Utkast',
  'Review': 'Granska',
  'Clause': 'Klausul',
  'Draft Contract': 'Skapa avtalsutkast',
  'Analyze with AI': 'Analysera med AI',
  'Upload a dataset to begin.': 'Lägg till en datamängd för att börja.',
  'Choose CSV, TSV or TXT': 'Välj CSV, TSV eller TXT',
  'Maximum 2 MB · processed on your device': 'Högst 2 MB · behandlas på din enhet',
  'Private · Local AI': 'Privat · lokal AI',
  'Local batch': 'Lokal batch',
  'Local PDF': 'Lokal PDF',
  'Original library': 'Originalbibliotek',
  'Local processing': 'Lokal bearbetning',
  'Write Reply': 'Skriv svar',
  'Improve Email': 'Förbättra e-post',
  'Instructions / Context': 'Instruktioner / sammanhang',
  'Received Email': 'Mottaget e-postmeddelande',
  'Email to Improve': 'E-post att förbättra',
  'Review Contract': 'Granska avtal',
  'Improve Clause': 'Förbättra klausul',
  'What should AI focus on?': 'Vad ska AI fokusera på?',
  'How should the clause change?': 'Hur ska klausulen ändras?',
  'Contract Text': 'Avtalstext',
  'Clause Text': 'Klausultext',
  'Draft output': 'Utkast',
  'Review output': 'Granskningsresultat',
};

const maps: Record<Language, Record<string, string>> = { en: {}, ar, sv };

export function localizeToolPhrase(text: string, language: Language): string | undefined {
  return maps[language][text];
}
