Warning: truncated output (original token count: 104444)
Total output lines: 5684

import { usePreferences } from '@/context/PreferencesContext';
import type { Language } from '@/lib/i18n';
import { useCallback } from 'react';
import { localizeToolPhrase } from './ui-localization-tools';

type PhraseMap = Record<string, string>;

const ar: PhraseMap = {
  "Batch Image Tools": "أدوات معالجة الصور دفعة واحدة",
  "Analytics AI": "تحليلات الذكاء الاصطناعي",
  "Code Assistant": "مساعد البرمجة",
  "Could not copy to clipboard.": "تعذر النسخ إلى الحافظة.",

  'Loading CV...': 'جارٍ تحميل السيرة الذاتية...',
  'Could not open this CV': 'تعذر فتح هذه السيرة الذاتية',
  'The file may be missing or no longer accessible.': 'قد يكون الملف مفقودًا أو لم يعد بإمكانك الوصول إليه.',
  'Design System MAX': 'نظام التصميم MAX',
  'Design tokens': 'متغيرات التصميم',
  'Add token': 'إضافة متغير',
  'Token name': 'اسم المتغير',
  'Token type': 'نوع المتغير',
  'Token value': 'قيمة المتغير',
  'Style presets': 'أنماط جاهزة',
  'Add preset': 'إضافة نمط جاهز',
  'Preset name': 'اسم النمط الجاهز',
  'Design system score': 'درجة نظام التصميم',
  'contrast issues': 'مشكلات تباين',
  'off-token colors': 'ألوان خارج النظام',
  'type sizes': 'أحجام خطوط',
  'System preset': 'نمط النظام',
  'Choose a system…': 'اختر نظامًا…',
  'Auto-balance tokens': 'موازنة الرموز تلقائيًا',
  'SaaS clarity': 'وضوح SaaS',
  'Editorial': 'تحريري',
  'Bold studio': 'استوديو جريء',
  'Calm service': 'خدمة هادئة',
  'Project collaboration': 'تعاون المشروع',
  'Collaboration': 'التعاون',
  'online': 'متصلون',
  'open comments': 'تعليقات مفتوحة',
  'Comment on': 'تعليق على',
  'selected element': 'العنصر المحدد',
  'selected section': 'القسم المحدد',
  'Write a review comment…': 'اكتب تعليق مراجعة…',
  'Show resolved': 'إظهار المحلول',
  'Comment': 'تعليق',
  'No review comments yet.': 'لا توجد تعليقات مراجعة بعد.',
  'Delete this review comment?': 'هل تريد حذف تعليق المراجعة هذا؟',
  'Custom domain': 'الدومين المخصص',
  'Domain name': 'اسم الدومين',
  'Connect domain': 'ربط الدومين',
  'Disconnect': 'فصل',
  'Update domain': 'تحديث الدومين',
  'Check DNS': 'فحص DNS',
  'DNS records required': 'سجلات DNS المطلوبة',
  'Disconnect this custom domain?': 'هل تريد فصل هذا الدومين المخصص؟',
  'Save this project to the cloud before connecting a domain.': 'احفظ المشروع على السحابة قبل ربط الدومين.',
  'Publish again to update canonical URLs and activate the latest website on this domain.': 'انشر الموقع مجدداً لتحديث الروابط الأساسية وتفعيل أحدث نسخة على هذا الدومين.',
  'pending': 'بانتظار التحقق',
  'verified': 'تم التحقق',
  'misconfigured': 'إعداد غير صحيح',
  'Promoting…': 'جارٍ النشر…',
  'Promote to live': 'نشر النسخة التجريبية',
  'Default language': 'اللغة الافتراضية',
  'Locale routes': 'مسارات اللغات',
  'Staging is behind the current editor. Regenerate it before promotion if these changes should go live.': 'النسخة التجريبية أقدم من المحرر. أعد إنشاءها قبل النشر إذا أردت تضمين التغييرات الحالية.',
  'Editor clipboard': 'حافظة المحرر',
  'Copy element': 'نسخ العنصر',
  'Paste element': 'لصق العنصر',
  'Cut element': 'قص العنصر',
  'Copy section': 'نسخ القسم',
  'Paste section': 'لصق القسم',
  'Cut section': 'قص القسم',
  'Copy selected element': 'نسخ العنصر المحدد',
  'Copy selected elements': 'نسخ العناصر المحددة',
  'Paste copied element': 'لصق العنصر المنسوخ',
  'Paste copied elements': 'لصق العناصر المنسوخة',
  'Paste elements': 'لصق العناصر',
  'Copy selected section': 'نسخ القسم المحدد',
  'Cut selected element': 'قص العنصر المحدد',
  'Cut selected elements': 'قص العناصر المحددة',
  'Cut selected section': 'قص القسم المحدد',
  'Paste copied section': 'لصق القسم المنسوخ',
  'ELEMENT READY': 'عنصر جاهز',
  'ELEMENTS READY': 'عناصر جاهزة',
  'SECTION READY': 'قسم جاهز',
  'Selected elements actions': 'إجراءات العناصر المحددة',
  'Selected elements': 'العناصر المحددة',
  'Group selected elements': 'تجميع العناصر المحددة',
  'Duplicate selected elements': 'تكرار العناصر المحددة',
  'Delete selected elements': 'حذف العناصر المحددة',
  'Group': 'تجميع',
  'Arrange selected elements': 'ترتيب العناصر المحددة',
  'Arrange': 'ترتيب',
  'Align left': 'محاذاة لليسار',
  'Align center': 'محاذاة للوسط أفقيًا',
  'Align right': 'محاذاة لليمين',
  'Align top': 'محاذاة للأعلى',
  'Align middle': 'محاذاة للوسط عموديًا',
  'Align bottom': 'محاذاة للأسفل',
  'Distribute': 'توزيع',
  'Distribute horizontally': 'توزيع أفقي',
  'Distribute vertically': 'توزيع عمودي',
  'Ctrl/Cmd+K · Ctrl/Cmd+C/X/V': 'Ctrl/Cmd+K · Ctrl/Cmd+C/X/V',
  'Shortcuts: Ctrl/Cmd+K commands · Ctrl/Cmd+C/X/V copy, cut and paste · Ctrl/Cmd+S save · Ctrl/Cmd+Z undo · Ctrl/Cmd+Shift+Z redo · Ctrl/Cmd+Shift+P preview.': 'الاختصارات: Ctrl/Cmd+K للأوامر · Ctrl/Cmd+C/X/V للنسخ والقص واللصق · Ctrl/Cmd+S للحفظ · Ctrl/Cmd+Z للتراجع · Ctrl/Cmd+Shift+Z للإعادة · Ctrl/Cmd+Shift+P للمعاينة.',
  'Recent': 'الأخيرة',
  'Loading library…': 'جارٍ تحميل المكتبة…',
  'No matching templates': 'لا توجد قوالب مطابقة',
  'Unknown size': 'حجم غير معروف',
  'Format': 'التنسيق',
  'Restore this history state? Your current unsaved changes will move to the Redo queue.': 'هل تريد استعادة حالة السجل هذه؟ ستُنقل تغييراتك الحالية غير المحفوظة إلى قائمة الإعادة.',
  'You have unsaved website changes. Leave without saving?': 'لديك تغييرات غير محفوظة في الموقع. هل تريد المغادرة من دون حفظ؟',
  'AI action': 'إجراء الذكاء الاصطناعي',
  'Edit current website': 'تعديل الموقع الحالي',
  'Build new website': 'بناء موقع جديد',
  'Edit scope': 'نطاق التعديل',
  'Whole site': 'الموقع بالكامل',
  'Current page': 'الصفحة الحالية',
  'Selected section': 'القسم المحدد',
  'Selected element': 'العنصر المحدد',
  'AI proposed changes outside the locked scope. No changes were applied.': 'اقترح الذكاء الاصطناعي تغييرات خارج النطاق المحدد. لم تُطبّق أي تغييرات.',
  'out-of-scope changes were blocked': 'تغييرات خارج النطاق تم حظرها',
  'No AI changes were selected.': 'لم يتم تحديد أي تغييرات للذكاء الاصطناعي.',
  'Component name': 'اسم المكوّن',
  'Search components': 'البحث في المكوّنات',
  'instances': 'نسخ مرتبطة',
  'Rename component': 'إعادة تسمية المكوّن',
  'REN': 'تسمية',
  'No matching components': 'لا توجد مكوّنات مطابقة',
  'A component with this name already exists.': 'يوجد مكوّن بهذا الاسم بالفعل.',
  'Duplicate component': 'نسخ المكوّن',
  'Find next instance': 'العثور على النسخة التالية',
  'DUP': 'نسخ',
  'FIND': 'بحث',
  'Publish preflight blocked': 'تم حظر فحص ما قبل النشر',
  'Last checked': 'آخر فحص',
  'Run check again': 'إعادة تشغيل الفحص',
  'Your website is saved but not public.': 'موقعك محفوظ لكنه غير متاح للعامة.',
  'Your latest editor changes are not live yet.': 'أحدث تعديلات المحرر لم تُنشر بعد.',
  'A published URL is saved, but the live file could not be verified.': 'رابط النشر محفوظ، لكن تعذر التحقق من الملف المباشر.',
  'Checking the public website now…': 'جارٍ التحقق من الموقع العام الآن…',
  'Your website is public.': 'موقعك متاح للعامة.',
  'The website is published. Verify the live renderer before treating it as live.': 'تم نشر الموقع. تحقّق من العرض المباشر قبل اعتباره جاهزًا.',
  'Published': 'نُشر في',
  'Verifying…': 'جارٍ التحقق…',
  'Verify live': 'التحقق من الموقع المباشر',
  'Publish website': 'نشر الموقع',
  'Complete launch checks first': 'أكمل فحوصات الإطلاق أولًا',
  'You are offline. Reconnect and try again.': 'أنت غير متصل بالإنترنت. أعد الاتصال وحاول مجددًا.',
  'Fix critical audit errors first': 'أصلح أخطاء التدقيق الحرجة أولًا',
  'Resolve publish blockers first': 'عالج عوائق النشر أولًا',
  'Building a new website replaces the current pages. Continue?': 'بناء موقع جديد يستبدل الصفحات الحالية. هل تريد المتابعة؟',
  'Generating...': 'جارٍ الإنشاء...',
  'Your result will appear here.': 'ستظهر النتيجة هنا.',
  'Coming Soon': 'قريباً',
  "This tool is under active development. You'll be notified when it's ready.": 'هذه الأداة قيد التطوير حالياً. سنخبرك عندما تصبح جاهزة.',
  'AI Writer': 'الكاتب بالذكاء الاصطناعي',
  'Write blogs, articles, and marketing copy.': 'اكتب المدونات والمقالات والنصوص التسويقية.',
  'Content Type': 'نوع المحتوى', 'Topic': 'الموضوع', 'Tone': 'النبرة', 'Length': 'الطول',
  'Target Audience': 'الجمهور المستهدف', 'Key Points (optional)': 'النقاط الرئيسية (اختياري)',
  'The future of AI in healthcare': 'مستقبل الذكاء الاصطناعي في الرعاية الصحية',
  'Healthcare professionals': 'متخصصو الرعاية الصحية', 'One point per line': 'نقطة واحدة في كل سطر',
  'Blog Post': 'منشور مدونة', 'Article': 'مقال', 'Marketing Copy': 'نص تسويقي',
  'Social Media Post': 'منشور وسائل التواصل', 'Product Description': 'وصف منتج',
  'Professional': 'احترافية', 'Casual': 'عفوية', 'Persuasive': 'إقناعية', 'Informative': 'معلوماتية',
  'Humorous': 'مرحة', 'Inspirational': 'ملهمة', 'Short': 'قصير', 'Long': 'طويل',
  'Writing content...': 'جارٍ كتابة المحتوى...', 'Content generated': 'تم إنشاء المحتوى', 'Writing...': 'جارٍ الكتابة...',
  'Generate Content': 'إنشاء المحتوى', 'Copy': 'نسخ', 'Copied': 'تم النسخ',
  'Cover Letter Writer': 'كاتب خطاب التغطية', 'Craft personalized cover letters for any job.': 'أنشئ خطابات تغطية مخصصة لأي وظيفة.',
  'Your Name': 'اسمك', 'Job Title': 'المسمى الوظيفي', 'Company': 'الشركة', 'Key Qualifications': 'المؤهلات الرئيسية',
  'Why this job?': 'لماذا هذه الوظيفة؟', 'Software Engineer': 'مهندس برمجيات', '5 years React, led team of 4...': '5 سنوات React، وقدت فريقاً من 4 أشخاص...',
  'Passionate about...': 'شغوف بـ...', 'Writing cover letter...': 'جارٍ كتابة خطاب التغطية...', 'Cover letter written': 'تمت كتابة خطاب التغطية',
  'Write Cover Letter': 'اكتب خطاب التغطية',
  'AI CV Builder': 'منشئ السيرة الذاتية بالذكاء الاصطناعي', 'Create ATS-friendly resumes with AI.': 'أنشئ سيراً ذاتية متوافقة مع أنظمة ATS باستخدام الذكاء الاصطناعي.',
  'Full Name': 'الاسم الكامل', 'Years of Experience': 'سنوات الخبرة', 'Key Skills (comma separated)': 'المهارات الرئيسية (مفصولة بفواصل)',
  'Target Industry': 'القطاع المستهدف', 'Technology': 'التقنية', 'Generating CV...': 'جارٍ إنشاء السيرة الذاتية...', 'CV generated successfully': 'تم إنشاء السيرة الذاتية بنجاح',
  'Generate CV': 'إنشاء السيرة الذاتية',
  'Document AI': 'الذكاء الاصطناعي للمستندات', 'Summarize, analyze, and extract from documents.': 'لخّص المستندات وحللها واستخرج المعلومات منها.',
  'Action': 'الإجراء', 'Document Content': 'محتوى المستند', 'Question': 'السؤال', 'Summarize': 'تلخيص', 'Analyze': 'تحليل', 'Ask a Question': 'اطرح سؤالاً',
  'Paste your document text here...': 'ألصق نص المستند هنا...', 'What is the main conclusion?': 'ما الاستنتاج الرئيسي؟',
  'Analyzing document...': 'جارٍ تحليل المستند...', 'Analysis complete': 'اكتمل التحليل', 'Analyzing...': 'جارٍ التحليل...', 'Analyze Document': 'تحليل المستند',
  'Study Assistant': 'مساعد الدراسة', 'Explain concepts, create quizzes, and study plans.': 'اشرح المفاهيم وأنشئ اختبارات وخطط دراسة.',
  'What do you need?': 'ماذا تحتاج؟', 'Topic / Subject': 'الموضوع / المادة', 'Level': 'المستوى', 'Count': 'العدد',
  'Explain a Concept': 'شرح مفهوم', 'Create a Quiz': 'إنشاء اختبار', 'Generate Flashcards': 'إنشاء بطاقات تعليمية', 'Create Study Plan': 'إنشاء خطة دراسة',
  'Beginner': 'مبتدئ', 'Quantum computing': 'الحوسبة الكمية',
  'Generating study material...': 'جارٍ إنشاء مادة الدراسة...', 'Study material generated': 'تم إنشاء مادة الدراسة', 'Generate': 'إنشاء',
  'Team Workspace': 'مساحة عمل الفريق', 'Build websites together': 'ابنوا المواقع معاً',
  'Secure roles, invitations and shared projects. Pro supports 3 seats; Business supports 10 seats.': 'أدوار ودعوات ومشاريع مشتركة آمنة. تدعم Pro ثلاثة أعضاء وBusiness عشرة أعضاء.',
  'Paste a team invitation token or open an invitation link': 'ألصق رمز دعوة الفريق أو افتح رابط الدعوة',
  'Your teams': 'فرقك', 'No team workspaces yet.': 'لا توجد مساحات عمل للفريق بعد.', 'New workspace name': 'اسم مساحة العمل الجديدة',
  'Create or select a team workspace to manage members and projects.': 'أنشئ أو اختر مساحة عمل فريق لإدارة الأعضاء والمشاريع.',
  'Rename workspace': 'إعادة تسمية مساحة العمل', 'Delete workspace': 'حذف مساحة العمل', 'Invite teammate': 'دعوة زميل', 'Invite': 'دعوة',
  'Members': 'الأعضاء', 'Editor': 'محرر', 'Viewer': 'مشاهد', 'Transfer ownership': 'نقل الملكية',
  'Leave workspace': 'مغادرة مساحة العمل', 'Remove member': 'إزالة عضو', 'Pending invitations': 'الدعوات المعلقة',
  'Shared projects': 'المشاريع المشتركة', 'Select one of your personal projects…': 'اختر أحد مشاريعك الشخصية…', 'Share project': 'مشاركة المشروع',
  'Remove from workspace': 'إزالة من مساحة العمل',
  'Open Website Builder from the Tools menu; this shared project will appear in the Cloud Projects selector.': 'افتح منشئ المواقع من قائمة الأدوات؛ سيظهر هذا المشروع المشترك في قائمة المشاريع السحابية.',
  'No projects shared with this workspace yet.': 'لا توجد مشاريع مشتركة مع مساحة العمل هذه بعد.',
  'Settings': 'الإعدادات', 'Manage your account, security, and preferences.': 'أدر حسابك وأمانك وتفضيلاتك.',
  'Profile': 'الملف الشخصي', 'Security': 'الأمان', 'Preferences': 'التفضيلات', 'Privacy': 'الخصوصية',
  'Data Export (GDPR)': 'تصدير البيانات (GDPR)',
  'Account Data Export': 'تصدير بيانات الحساب',
  'Download a portable JSON export of your account records and stored-file inventory. Original file binaries remain available from their tools.': 'نزّل ملف JSON قابلاً للنقل يتضمن سجلات حسابك وقائمة الملفات المخزنة. تبقى الملفات الأصلية متاحة من أدواتها.',
  'Sign in to export your account data.': 'سجّل الدخول لتصدير بيانات حسابك.',
  'Download a complete copy of all your data stored on Tayar Intelligence Tools. This includes your profile, projects, files, conversations, and activity log.': 'نزّل نسخة كاملة من بياناتك المخزنة في Tayar Intelligence Tools، بما في ذلك ملفك الشخصي ومشاريعك وملفاتك ومحادثاتك وسجل النشاط.',
  'Preparing your data...': 'جارٍ تجهيز بياناتك...', 'Data exported successfully': 'تم تصدير البيانات بنجاح', 'Failed to export data': 'فشل تصدير البيانات',
  'Personal data downloaded': 'تم تنزيل البيانات الشخصية', 'Export All Data': 'تصدير كل البيانات', 'Download Personal Data': 'تنزيل البيانات الشخصية',
  'Privacy Controls': 'عناصر التحكم بالخصوصية',
  'Analytics enabled': 'تم تفعيل التحليلات', 'Analytics disabled': 'تم تعطيل التحليلات',
  'Prevent your content from being used to improve AI models': 'امنع استخدام محتواك لتحسين نماذج الذكاء الاصطناعي',
  'AI training opt-out enabled': 'تم تفعيل رفض تدريب الذكاء الاصطناعي', 'AI training opt-out disabled': 'تم تعطيل رفض تدريب الذكاء الاصطناعي',
  'Data Storage Location': 'موقع تخزين البيانات',
  'Cloud storage location follows the active service configuration. See the Privacy Policy for current providers.': 'يتبع موقع التخزين السحابي إعداد الخدمة النشط. راجع سياسة الخصوصية لمعرفة المزوّدين الحاليين.',
  'Data Encryption': 'تشفير البيانات',
  'Delete Account': 'حذف الحساب',
  'Permanently delete your Tayar account, owned projects and stored files. An active subscription is canceled first. Payment providers may retain records required by law. This action cannot be undone.': 'احذف حساب Tayar والمشاريع التي تملكها والملفات المخزنة نهائياً. يُلغى الاشتراك النشط أولاً. قد يحتفظ مزودو الدفع بسجلات يفرضها القانون. لا يمكن التراجع عن هذا الإجراء.',
  'Type "DELETE" to confirm': 'اكتب "DELETE" للتأكيد', 'Deleting account...': 'جارٍ حذف الحساب...', 'Account deleted': 'تم حذف الحساب',
  'Failed to delete account. Please contact support.': 'فشل حذف الحساب. يرجى التواصل مع الدعم.',
  'Go to Workspace →': 'الذهاب إلى مساحة العمل ←', 'Upgrade to Pro': 'الترقية إلى Pro', 'Upgrade Now': 'الترقية الآن',
  'Unlock all 50+ AI tools and unlimited documents.': 'افتح حدوداً أعلى وميزات احترافية إضافية.',
  'User': 'مستخدم', 'Soon': 'قريباً', 'Beta': 'تجريبي',
  'Delete My Account': 'حذف حسابي',
  'This will permanently delete:': 'سيؤدي هذا إلى حذف ما يلي نهائياً:',
  'Your profile and account credentials': 'ملفك الشخصي وبيانات اعتماد الحساب',
  'All projects (CVs, cover letters, documents)': 'كل المشاريع (السير الذاتية وخطابات التغطية والمستندات)',
  'All files and exports': 'كل الملفات والتصديرات',
  'All AI conversations and usage history': 'كل محادثات الذكاء الاصطناعي وسجل الاستخدام',
  'All activity logs and preferences': 'كل سجلات النشاط والتفضيلات',
  'Type': 'اكتب',
  'to confirm': 'للتأكيد',
  'Yes, Delete Everything': 'نعم، احذف كل شيء',
  'Cancel': 'إلغاء',
  'Saving profile...': 'جارٍ حفظ الملف الشخصي...',
  'Profile saved': 'تم حفظ الملف الشخصي',
  'Your name': 'اسمك',
  'Email Address': 'البريد الإلكتروني',
  'Bio': 'نبذة',
  'Tell us about yourself...': 'أخبرنا عن نفسك...',
  'Save Changes': 'حفظ التغييرات',
  'Updating password...': 'جارٍ تحديث كلمة المرور...',
  'Password updated successfully': 'تم تحديث كلمة المرور بنجاح',
  'Passwords do not match': 'كلمتا المرور غير متطابقتين',
  'Password must be at least 6 characters': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
  'Email Verification': 'تأكيد البريد الإلكتروني',
  'Email verified': 'تم تأكيد البريد الإلكتروني',
  'Your email address has been confirmed.': 'تم تأكيد عنوان بريدك الإلكتروني.',
  'Email not verified': 'البريد الإلكتروني غير مؤكد',
  'Please verify your email address to secure your account.': 'يرجى تأكيد بريدك الإلكتروني لتأمين حسابك.',
  'Sending verification email...': 'جارٍ إرسال رسالة التأكيد...',
  'Verification email sent': 'تم إرسال رسالة التأكيد',
  'Verify Now': 'تأكيد الآن',
  'Change Password': 'تغيير كلمة المرور',
  'New Password': 'كلمة المرور الجديدة',
  'Enter new password': 'أدخل كلمة مرور جديدة',
  'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
  'Confirm new password': 'أكد كلمة المرور الجديدة',
  'Update Password': 'تحديث كلمة المرور',
  'Danger Zone': 'منطقة الخطر',
  'Sign out from all devices or permanently delete your account.': 'سجّل الخروج من جميع الأجهزة أو احذف حسابك نهائياً.',
  'Sign Out': 'تسجيل الخروج',
  'Theme': 'المظهر',
  'Language': 'اللغة',
  'Dark Mode': 'الوضع الداكن',
  'Light Mode': 'الوضع الفاتح',
  'Easy on the eyes': 'مريح للعينين',
  'Bright and clean': 'فاتح وواضح',
  'Email Notifications': 'إشعارات البريد الإلكتروني',
  'Important account and security emails': 'رسائل مهمة عن الحساب والأمان',
  'Push Notifications': 'الإشعارات الفورية',
  'Real-time updates in your browser': 'تحديثات فورية في المتصفح',
  'Marketing Emails': 'رسائل تسويقية',
  'Product updates, tips, and special offers': 'تحديثات المنتج والنصائح والعروض الخاصة',
  'Notification Preferences': 'تفضيلات الإشعارات',
  'free plan': 'الخطة المجانية',
  'Verified': 'مؤكد',
  'Not verified': 'غير مؤكد',

  'Password must be at least 8 characters': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  'Password is too long': 'كلمة المرور طويلة جدًا',
  'Password must contain a lowercase letter': 'يجب أن تحتوي كلمة المرور على حرف إنجليزي صغير',
  'Password must contain an uppercase letter': 'يجب أن تحتوي كلمة المرور على حرف إنجليزي كبير',
  'Password must contain a number': 'يجب أن تحتوي كلمة المرور على رقم',
  'At least 8 characters': '8 أحرف على الأقل',
  'Choose a stronger password.': 'اختر كلمة مرور أقوى.',
  'plan': 'خطة',

  'Owner': 'المالك',
  'Full control, billing and publishing.': 'تحكم كامل والفوترة والنشر.',
  'Manage members and shared projects.': 'إدارة الأعضاء والمشاريع المشتركة.',
  'Edit shared project content.': 'تعديل محتوى المشاريع المشتركة.',
  'Read-only access.': 'صلاحية عرض فقط.',
  'Unexpected error': 'خطأ غير متوقع',
  'Create team': 'إنشاء فريق',
  'Creating...': 'جارٍ الإنشاء...',
  'Accept invite': 'قبول الدعوة',
  'Accepting...': 'جارٍ القبول...',
  'Refresh': 'تحديث',
  'Rename': 'إعادة تسمية',
  'Delete': 'حذف',
  'Copy invite link': 'نسخ رابط الدعوة',
  'Revoke': 'إلغاء',
  'Role': 'الدور',
  'Seats': 'المقاعد',
  'Projects': 'المشاريع',
  'Project': 'مشروع',
  'No pending invitations.': 'لا توجد دعوات معلقة.',

  'Command palette': 'لوحة الأوامر',
  'Command palette (Ctrl+K)': 'لوحة الأوامر (Ctrl+K)',
  'Toggle theme': 'تبديل المظهر',
  'Change language': 'تغيير اللغة',
  'AI Chat': 'محادثة الذكاء الاصطناعي',
  'Use the AI Assistant panel on the right to chat!': 'استخدم لوحة مساعد الذكاء الاصطناعي على اليمين للدردشة!',
  'Subscription': 'الاشتراك',
  'Manage your plan and billing.': 'أدر خطتك والفوترة.',
  'Support': 'الدعم',
  'Get help, browse docs, or contact our team.': 'احصل على المساعدة أو تصفح المستندات أو تواصل مع فريقنا.',
  'Keyboard Shortcuts': 'اختصارات لوحة المفاتيح',

  'About Tayar Intelligence': 'حول Tayar Intelligence',
  'A focused workspace for building, creating, collaborating and shipping finished work.': 'مساحة عمل مركزة للبناء والإنشاء والتعاون وتسليم العمل النهائي.',
  'Tayar Intelligence brings practical productivity tools into one workspace. The current product includes Website Builder V1, team workspaces, document and writing tools, translation, study workflows, project management and account-level preferences.': 'يجمع Tayar Intelligence أدوات إنتاجية عملية في مساحة عمل واحدة. يتضمن المنتج الحالي منشئ المواقع V1 ومساحات عمل الفرق وأدوات المستندات والكتابة والترجمة وسير الدراسة وإدارة المشاريع وتفضيلات الحساب.',
  'The goal is simple: reduce tool switching while keeping the important parts of a project — content, versions, permissions and delivery — connected.': 'الهدف بسيط: تقليل التنقل بين الأدوات مع إبقاء الأجزاء المهمة من المشروع — المحتوى والإصدارات والصلاحيات والتسليم — مترابطة.',
  'Website Builder V1': 'منشئ المواقع V1',
  'Website Builder V1 is active and supports responsive pages, forms, publishing, release history and rollback, multilingual pages, analytics, conversion tracking, lead management, team collaboration and client handoff workflows.': 'منشئ المواقع V1 فعال ويدعم الصفحات المتجاوبة والنماذج والنشر وسجل الإصدارات والاسترجاع والصفحات متعددة اللغات والتحليلات وتتبع التحويلات وإدارة العملاء المحتملين وتعاون الفرق وتسليم العملاء.',
  'What comes next': 'ما التالي',
  'The next major product phase is AI-assisted website generation. It is intentionally separate from V1 so the core builder can remain useful and production-ready without depending on AI generation.': 'المرحلة الرئيسية التالية هي إنشاء المواقع بمساعدة الذكاء الاصطناعي. وهي منفصلة عمداً عن V1 ليبقى المنشئ الأساسي مفيداً وجاهزاً للإنتاج دون الاعتماد على التوليد بالذكاء الاصطناعي.',
  'Contact Us': 'اتصل بنا',
  "We'd love to hear from you. Reach out with any questions or feedback.": 'يسعدنا سماعك. تواصل معنا بأي أسئلة أو ملاحظات.',
  'Phone': 'الهاتف',
  'Office': 'المكتب',
  'Stockholm, Sweden': 'ستوكهولم، السويد',
  'Your Email': 'بريدك الإلكتروني',
  'Subject': 'الموضوع',
  'Message': 'الرسالة',
  'Your email': 'بريدك الإلكتروني',
  'Your message': 'رسالتك',
  'Send Feedback': 'إرسال ملاحظات',
  'Help us improve Tayar Intelligence Tools. Share your thoughts, ideas, and suggestions.': 'ساعدنا على تحسين Tayar Intelligence Tools. شارك أفكارك وملاحظاتك واقتراحاتك.',
  'How would you rate your experience?': 'كيف تقيّم تجربتك؟',
  'Rating': 'التقييم',
  'Category': 'الفئة',
  'General': 'عام',
  'Feature Request': 'طلب ميزة',
  'UI / Design': 'الواجهة / التصميم',
  'Performance': 'الأداء',
  'Praise': 'إشادة',
  'Your Feedback': 'ملاحظاتك',
  'Tell us what you think...': 'أخبرنا برأيك...',
  'Your feedback': 'ملاحظاتك',
  'Report a Bug': 'الإبلاغ عن خطأ',
  'Found a bug? Help us fix it. Provide as much detail as possible.': 'وجدت خطأ؟ ساعدنا على إصلاحه وقدّم أكبر قدر ممكن من التفاصيل.',
  'Severity': 'الخطورة',
  'Bug severity': 'خطورة الخطأ',
  'Low - Minor issue, not blocking': 'منخفض - مشكلة بسيطة لا تعيق العمل',
  'Medium - Affects workflow': 'متوسط - تؤثر على سير العمل',
  'High - Major feature broken': 'مرتفع - ميزة رئيسية معطلة',
  'Critical - App unusable': 'حرج - التطبيق غير قابل للاستخدام',
  'Affected Tool': 'الأداة المتأثرة',
  'Affected tool': 'الأداة المتأثرة',
  'General / Platform': 'عام / المنصة',
  'CV Builder': 'منشئ السيرة الذاتية',
  'Cover Letter': 'خطاب التغطية',
  'Translator': 'المترجم',
  'Login / Signup': 'تسجيل الدخول / التسجيل',
  'Steps to Reproduce': 'خطوات إعادة المشكلة',
  'Expected Behavior': 'السلوك المتوقع',
  'Actual Behavior': 'السلوك الفعلي',
  'Help Center': 'مركز المساعدة',
  'Find answers to common questions and get support.': 'اعثر على إجابات للأسئلة الشائعة واحصل على الدعم.',
  'No results found. Try a different search.': 'لم يتم العثور على نتائج. جرّب بحثاً مختلفاً.',
  'Still need help?': 'ما زلت تحتاج للمساعدة؟',
  "Send us a message and we'll get back to you within 24 hours.": 'أرسل لنا رسالة وسنرد عليك خلال 24 ساعة.',
  'Search help articles...': 'ابحث في مقالات المساعدة...',
  'Describe your issue...': 'صف مشكلتك...',
  'Cookie Consent': 'موافقة ملفات تعريف الارتباط',
  'Privacy Policy': 'سياسة الخصوصية',
  'Necessary': 'ضرورية',
  'Analytics': 'التحليلات',
  'Marketing': 'التسويق',
  'Cookie consent': 'موافقة ملفات تعريف الارتباط',
  'Close cookie consent': 'إغلاق نافذة ملفات تعريف الارتباط',
  'Cookie settings': 'إعدادات ملفات تعريف الارتباط',
  'Last updated: August 28, 2026': 'آخر تحديث: 28 أغسطس 2026',
  'Terms of Service': 'شروط الخدمة',
  'This page describes the main categories of information Tayar Intelligence may process when you use the product. The exact data involved depends on the features you choose to use.': 'توضح هذه الصفحة الفئات الرئيسية للمعلومات التي قد يعالجها Tayar Intelligence عند استخدامك للمنتج. تعتمد البيانات الفعلية على الميزات التي تختار استخدامها.',
  'Account details, profile settings, projects, files, preferences and collaboration data may be stored so the service can authenticate you, save your work and enforce access permissions.': 'قد تُخزن تفاصيل الحساب وإعدادات الملف الشخصي والمشاريع والملفات والتفضيلات وبيانات التعاون لتمكين المصادقة وحفظ عملك وتطبيق صلاحيات الوصول.',
  'Website Builder projects can include pages, media references, form submissions, leads, analytics events, release history, publishing settings and team permissions. Public website forms and analytics use dedicated server-side controls and rate limits.': 'قد تتضمن مشاريع منشئ المواقع صفحات ومراجع وسائط وإرسالات نماذج وعملاء محتملين وأحداث تحليلات وسجل إصدارات وإعدادات نشر وصلاحيات فريق. تستخدم نماذج المواقع العامة والتحليلات ضوابط مخصصة على الخادم وحدود معدل.',
  'The application uses third-party infrastructure such as Supabase for authentication, database and storage capabilities. Features that use external AI or payment services may send the information required to complete that specific request to the configured provider.': 'يستخدم التطبيق بنية تحتية خارجية مثل Supabase للمصادقة وقواعد البيانات والتخزين. قد ترسل الميزات التي تستخدم خدمات ذكاء اصطناعي أو دفع خارجية المعلومات اللازمة لإتمام الطلب المحدد إلى المزود المهيأ.',
  'The application uses encrypted network connections and database access controls, including Row Level Security for user and workspace data. Authentication credentials are handled through the authentication provider rather than being stored as plaintext application data.': 'يستخدم التطبيق اتصالات شبكة مشفرة وضوابط وصول لقاعدة البيانات، بما في ذلك أمان مستوى الصف لبيانات المستخدم ومساحة العمل. تتم معالجة بيانات المصادقة عبر مزود المصادقة ولا تُخزن كنص صريح في التطبيق.',
  'Browser storage may be used for authentication sessions, interface preferences, recovery data and consent choices. Analytics or production integrations are controlled by the relevant product and website settings.': 'قد يُستخدم تخزين المتصفح لجلسات المصادقة وتفضيلات الواجهة وبيانات الاستعادة وخيارات الموافقة. تتحكم إعدادات المنتج والموقع ذات الصلة في التحليلات أو تكاملات الإنتاج.',
  'You can manage account preferences and many stored project settings inside the product. Requests relating to access, correction or deletion of personal data should be made through the support options available in your account.': 'يمكنك إدارة تفضيلات الحساب والعديد من إعدادات المشاريع المخزنة داخل المنتج. يجب تقديم طلبات الوصول إلى البيانات الشخصية أو تصحيحها أو حذفها عبر خيارات الدعم المتاحة في حسابك.',
  'This policy may be updated as the product, infrastructure or legal requirements change. The date at the top of this page shows the latest published revision.': 'قد تُحدّث هذه السياسة مع تغير المنتج أو البنية التحتية أو المتطلبات القانونية. يعرض التاريخ أعلى الصفحة أحدث مراجعة منشورة.',
  'By using Tayar Intelligence, you agree to use the service lawfully and in a way that does not interfere with other users, the platform or its infrastructure.': 'باستخدام Tayar Intelligence، توافق على استخدام الخدمة بشكل قانوني وبطريقة لا تتداخل مع المستخدمين الآخرين أو المنصة أو بنيتها التحتية.',
  'You are responsible for the accuracy of information submitted through your account and for keeping access to your account secure. Team and shared-project permissions should only be granted to people you intend to collaborate with.': 'أنت مسؤول عن دقة المعلومات المقدمة عبر حسابك وعن الحفاظ على أمان الوصول إليه. يجب منح صلاحيات الفرق والمشاريع المشتركة فقط للأشخاص الذين تنوي التعاون معهم.',
  'You remain responsible for reviewing the content, websites, documents and other outputs you create or publish through the platform. Automated or AI-assisted output should be checked before it is relied on or published.': 'تبقى مسؤولاً عن مراجعة المحتوى والمواقع والمستندات والمخرجات الأخرى التي تنشئها أو تنشرها عبر المنصة. يجب التحقق من المخرجات الآلية أو المدعومة بالذكاء الاصطناعي قبل الاعتماد عليها أو نشرها.',
  'You may not use the service to break the law, abuse public forms or APIs, bypass product limits or access controls, distribute malicious content, interfere with the service, or attempt unauthorized access to other accounts or projects.': 'لا يجوز استخدام الخدمة لخرق القانون أو إساءة استخدام النماذج العامة أو واجهات API أو تجاوز حدود المنتج أو ضوابط الوصول أو توزيع محتوى ضار أو تعطيل الخدمة أو محاولة الوصول غير المصرح به إلى حسابات أو مشاريع أخرى.',
  'Free, Pro and Business features and usage limits are displayed in the product. Paid pricing, renewal details, cancellation options and any applicable billing terms are presented through the configured checkout and billing portal. Applicable consumer rights remain unaffected.': 'تظهر ميزات وحدود استخدام خطط Free وPro وBusiness داخل المنتج. تُعرض الأسعار المدفوعة وتفاصيل التجديد وخيارات الإلغاء وشروط الفوترة المعمول بها عبر صفحة الدفع وبوابة الفوترة ال…84444 tokens truncated…okuserad kontaktsektion för att omvandla intresse till leads.",
  "warning": "varning",
  "improvement": "förbättring",
  "Last automated check": "Senaste automatiska kontroll",
  "Run final checks": "Kör slutkontroller",
  "period ends": "perioden slutar",
  "cancels at period end": "avslutas vid periodens slut",
  "*Media count reflects assets currently loaded into the Media Library panel.": "*Antalet medier avser tillgångar som för närvarande är inlästa i panelen Mediebibliotek.",
  "current build still matches": "nuvarande version matchar fortfarande",
  "website changed after approval": "webbplatsen ändrades efter godkännandet",
  "No approval snapshot recorded yet.": "Ingen godkännandesnapshot har registrerats ännu.",
  "loaded releases": "inlästa versioner",
  "Views · 30d": "Visningar · 30 d",
  "Visitors · 30d": "Besökare · 30 d",
  "Views · 7d": "Visningar · 7 d",
  "Views · Today": "Visningar · idag",
  "CTA clicks": "CTA-klick",
  "Form submits": "Formulärinskick",
  "Form CVR": "Formulärkonvertering",
  "One item per line": "Ett objekt per rad",
  "value | label": "värde | etikett",
  "name | quote": "namn | citat",
  "Use the styling controls below to adjust": "Använd stilkontrollerna nedan för att justera",
  "width, color and opacity": "bredd, färg och opacitet",
  "height (Padding × 2)": "höjd (utfyllnad × 2)",
  "One list item per line": "En listpost per rad",
  "desktop": "skrivbord",
  "tablet": "surfplatta",
  "mobile": "mobil",
  "qualified": "kvalificerad",
  "contacted": "kontaktad",
  "won": "vunnen",
  "lost": "förlorad",
  "read": "läst",
  "archived": "arkiverad",
  "Last automated check:": "Senaste automatiska kontroll:",
  "One item per line:": "En post per rad:",
  "Very strong": "Mycket starkt",
  "Product": "Produkt",
  "Brand": "Varumärke",
  "Modern": "Modern",
  "Friendly": "Vänlig",
  "Bold": "Djärv",
  "Minimal": "Minimal",
  "Career": "Karriär",
  "Finance": "Ekonomi",
  "Productivity": "Produktivitet",
  "Spreadsheets": "Kalkylblad",
  "Presentations": "Presentationer",
  "Bundles": "Paket",
  "Images": "Bilder",
  "Office bundle": "Office-paket",
  "tools available": "verktyg tillgängliga",
  "ready to use": "redo att användas",
  "Updated": "Uppdaterad",
  "Used": "Använd",
  "Remove image backgrounds through Tayar’s secured server-side image utility.": "Ta bort bildbakgrunder via Tayars säkrade serverbaserade bildverktyg.",
  "Resize and convert multiple images locally, with individual downloads or one ZIP.": "Ändra storlek och konvertera flera bilder lokalt, med separata nedladdningar eller en ZIP-fil.",
  "Craft personalized, compelling cover letters for any job.": "Skapa personliga och övertygande personliga brev för vilket jobb som helst.",
  "Clean, normalize and safely export CSV data directly in your browser.": "Rensa, normalisera och exportera CSV-data säkert direkt i webbläsaren.",
  "Create ATS-friendly resumes with AI-powered optimization.": "Skapa ATS-vänliga CV:n med AI-driven optimering.",
  "Summarize, analyze, extract data, and answer questions about any document.": "Sammanfatta, analysera, extrahera data och svara på frågor om valfritt dokument.",
  "PDF Tools": "PDF-verktyg",
  "Merge, split, convert, and edit PDF files with AI assistance.": "Slå ihop, dela, konvertera och redigera PDF-filer med AI-hjälp.",
  "AI Email Writer": "AI e-postskrivare",
  "Write professional emails, replies, and newsletters.": "Skriv professionella mejl, svar och nyhetsbrev.",
  "Contract Writer": "Avtalsskrivare",
  "Generate legal contracts and agreements with AI.": "Skapa juridiska avtal och överenskommelser med AI.",
  "Data Analytics AI": "Dataanalys AI",
  "Analyze data, generate insights, and create visualizations.": "Analysera data, skapa insikter och visualiseringar.",
  "Crop JPEG, PNG and WebP images locally with precise controls and aspect presets.": "Beskär JPEG-, PNG- och WebP-bilder lokalt med precisa kontroller och bildförhållanden.",
  "Combine JPEG, PNG and WebP images into one local PDF with page ordering and size controls.": "Kombinera JPEG-, PNG- och WebP-bilder till en lokal PDF med sidordning och storlekskontroller.",
  "Resize, compress and convert JPEG, PNG and WebP images locally in your browser.": "Ändra storlek, komprimera och konvertera JPEG-, PNG- och WebP-bilder lokalt i webbläsaren.",
  "Create professional invoices with automatic totals, VAT, draft saving and PDF printing.": "Skapa professionella fakturor med automatiska totalsummor, moms, utkast och PDF-utskrift.",
  "Create recommendation, authorization, business, complaint, resignation and thank-you letters.": "Skapa rekommendations-, fullmakts-, affärs-, klagomåls-, uppsägnings- och tackbrev.",
  "Generate original business, product, brand, YouTube and Instagram name ideas.": "Generera originella namnidéer för företag, produkter, varumärken, YouTube och Instagram.",
  "Search and personalize original Tayar prompts for business, career, writing and social workflows.": "Sök och anpassa Tayars egna promptar för företag, karriär, skrivande och sociala arbetsflöden.",
  "Explain concepts, create quizzes, flashcards, and personalized study plans.": "Förklara begrepp och skapa quiz, flashcards och personliga studieplaner.",
  "Browse Tayar-hosted office templates and original starter files.": "Bläddra bland Office-mallar som finns hos Tayar och egna startfiler.",
  "AI Translator": "AI-översättare",
  "Translate between 100+ languages with natural, context-aware results.": "Översätt mellan över 100 språk med naturliga och kontextmedvetna resultat.",
  "Write blogs, articles, marketing copy, and social media content.": "Skriv bloggar, artiklar, marknadsföringstexter och innehåll för sociala medier.",
  "Est. MRR": "Beräknad MRR",
  "Upcoming Renewals": "Kommande förnyelser",
  "Past Due / Grace": "Förfallen / respit",
  "Failed Payments": "Misslyckade betalningar",
  "Past Due": "Förfallen",
  "Renewals": "Förnyelser",
  "Failed": "Misslyckad",
  "trialing": "provperiod",
  "pro": "Pro",
  "business": "Business",
  "free": "Gratis",
  "Open Tickets": "Öppna ärenden",
  "Closed": "Stängda",
  "Bug Reports": "Felrapporter",
  "Feature Requests": "Funktionsförslag",
  "open": "öppen",
  "closed": "stängd",
  "bug": "fel",
  "feature": "funktion",
  "ticket": "ärende",
  "high": "hög",
  "medium": "medel",
  "low": "låg",
  "Type your response...": "Skriv ditt svar...",
  "Close Ticket": "Stäng ärende",
  "Reopen": "Öppna igen",
  "Send & Close": "Skicka och stäng",
  "System Settings": "Systeminställningar",
  "Account Blocks": "Kontoblockeringar",
  "Readiness": "Beredskap",
  "Email Templates": "E-postmallar",
  "Backups": "Säkerhetskopior",
  "Platform Name": "Plattformsnamn",
  "Default AI Provider": "Standardleverantör för AI",
  "Max Free Requests/day": "Max gratisförfrågningar/dag",
  "Maintenance Mode": "Underhållsläge",
  "Signup Enabled": "Registrering aktiverad",
  "Disabled": "Inaktiverad",
  "Failed to save settings": "Det gick inte att spara inställningarna",
  "Settings saved": "Inställningarna sparades",
  "Email subject": "E-postämne",
  "Stripe connection": "Stripe-anslutning",
  "Stripe charges": "Stripe-debiteringar",
  "Stripe payouts": "Stripe-utbetalningar",
  "Pro price": "Pro-pris",
  "Business price": "Business-pris",
  "Stripe webhook": "Stripe-webhook",
  "Checkout": "Kassa",
  "Billing portal": "Faktureringsportal",
  "unconfigured": "inte konfigurerad",
  "enabled": "aktiverad",
  "needs attention": "behöver åtgärdas",
  "missing": "saknas",
  "not verified": "inte verifierad",
  "needs setup": "behöver konfigureras",
  "Admins": "Administratörer",
  "Pro Users": "Pro-användare",
  "Search by name, email or ID...": "Sök efter namn, e-post eller ID...",
  "Unnamed": "Namnlös",
  "You cannot suspend yourself": "Du kan inte stänga av dig själv",
  "Reinstate": "Återaktivera",
  "Suspend": "Stäng av",
  "You cannot delete yourself": "Du kan inte ta bort dig själv",
  "Delete User": "Ta bort användare",
  "Delete & Block": "Ta bort och blockera",
  "Delete Permanently": "Ta bort permanent",
  "Block reason (internal note)": "Orsak till blockering (intern anteckning)",
  "Reason (internal note)": "Orsak (intern anteckning)",
  "Total Tools": "Totalt antal verktyg",
  "Premium": "Premium",
  "uses": "användningar",
  "Read-only validation of stored 24Billions templates. Progress is saved in this browser and can be paused or resumed safely.": "Skrivskyddad validering av lagrade 24Billions-mallar. Förloppet sparas i webbläsaren och kan pausas eller återupptas säkert.",
  "Resume Audit": "Återuppta granskning",
  "Run Again": "Kör igen",
  "Start Audit": "Starta granskning",
  "Analyzing…": "Analyserar…",
  "Analyze Repairs": "Analysera reparationer",
  "Deleting…": "Tar bort…",
  "Delete invalid templates": "Ta bort ogiltiga mallar",
  "scanned": "skannade",
  "Audit progress is still saved unless deletion completed.": "Granskningsförloppet är fortfarande sparat om borttagningen inte slutfördes.",
  "Valid": "Giltig",
  "Invalid": "Ogiltig",
  "Missing": "Saknas",
  "Running": "Körs",
  "Analyzing": "Analyserar",
  "Deleting": "Tar bort",
  "Paused": "Pausad",
  "Idle": "Inaktiv",
  "Rows deleted": "Borttagna rader",
  "Storage deleted": "Borttaget från lagring",
  "Shared preserved": "Delade bevarade",
  "Storage failures": "Lagringsfel",
  "Issues checked": "Kontrollerade problem",
  "Repairable": "Kan repareras",
  "Junk to hide": "Skräp att dölja",
  "Needs review": "Behöver granskas",
  "All Files": "Alla filer",
  "Articles": "Artiklar",
  "AI Chats": "AI-chattar",
  "Websites": "Webbplatser",
  "Last Updated": "Senast uppdaterad",
  "Date Created": "Skapad datum",
  "Name (A-Z)": "Namn (A–Ö)",
  "No matching files": "Inga matchande filer",
  "No files yet": "Inga filer ännu",
  "Try a different search term.": "Prova en annan sökterm.",
  "Create documents with any AI tool and they'll appear here automatically.": "Skapa dokument med valfritt AI-verktyg så visas de här automatiskt.",
  "to...": "till...",
  "Live Website": "Livewebbplats",
  "Website Draft": "Webbplatsutkast",
  "Email support": "E-postsupport",
  "Email Support": "E-postsupport",
  "Account & Privacy Support": "Support för konto och integritet",
  "Use email or the secure form below": "Använd e-post eller det säkra formuläret nedan",
  "1. Overview": "1. Översikt",
  "2. Account and workspace data": "2. Konto- och arbetsytedata",
  "3. Website Builder data": "3. Data från Website Builder",
  "4. Infrastructure and processors": "4. Infrastruktur och personuppgiftsbiträden",
  "5. Security": "5. Säkerhet",
  "6. Cookies and local storage": "6. Cookies och lokal lagring",
  "7. Your choices": "7. Dina val",
  "8. Changes": "8. Ändringar",
  "1. Using the service": "1. Användning av tjänsten",
  "2. Accounts": "2. Konton",
  "3. Projects and generated content": "3. Projekt och genererat innehåll",
  "4. Acceptable use": "4. Tillåten användning",
  "5. Plans and billing": "5. Planer och fakturering",
  "6. Availability and changes": "6. Tillgänglighet och ändringar",
  "7. Responsibility": "7. Ansvar",
  "8. Support": "8. Support",
  "Type a command or search...": "Skriv ett kommando eller sök...",
  "No results for": "Inga resultat för",
  "AI Actions": "AI-åtgärder",
  "Navigation": "Navigering",
  "Recent Projects": "Senaste projekt",
  "Search Results": "Sökresultat",
  "navigate": "navigera",
  "results": "resultat",
  "Dismiss notification": "Stäng avisering",
  "Open AI Assistant": "Öppna AI-assistent",
  "Context": "Kontext",
  "AI is thinking": "AI tänker",
  "Could not load team workspaces. Apply the Sprint 133-144 migration.": "Det gick inte att läsa in teamarbetsytor. Tillämpa Sprint 133-144-migreringen.",
  "Could not load workspace details.": "Det gick inte att läsa in arbetsytans detaljer.",
  "Team workspace created.": "Teamarbetsytan skapades.",
  "Workspace renamed.": "Arbetsytan bytte namn.",
  "Delete this team workspace? Shared projects will become personal projects again.": "Ta bort den här teamarbetsytan? Delade projekt blir personliga projekt igen.",
  "Workspace deleted.": "Arbetsytan togs bort.",
  "Invite created. Copy the secure link and send it to the teammate.": "Inbjudan skapades. Kopiera den säkra länken och skicka den till teammedlemmen.",
  "Invite accepted.": "Inbjudan accepterades.",
  "Invite revoked.": "Inbjudan återkallades.",
  "Member role updated.": "Medlemmens roll uppdaterades.",
  "this member": "den här medlemmen",
  "from the workspace?": "från arbetsytan?",
  "You left the workspace.": "Du lämnade arbetsytan.",
  "Member removed.": "Medlemmen togs bort.",
  "Transfer ownership to": "Överför ägarskapet till",
  "Workspace ownership transferred.": "Ägarskapet för arbetsytan överfördes.",
  "Project shared with the workspace.": "Projektet delades med arbetsytan.",
  "Project removed from the workspace.": "Projektet togs bort från arbetsytan.",
  "owner": "ägare",
  "admin": "admin",
  "editor": "redigerare",
  "viewer": "visare",
  "members": "medlemmar",
  "projects": "projekt",
  "seats used": "platser använda",
  "Member": "Medlem",
  "you": "du",
  "expires": "upphör",
  "owned by you": "ägs av dig",
  "shared with you": "delat med dig",
  "Passwords do not match.": "Lösenorden matchar inte.",
  "Adding to project...": "Lägger till i projektet...",
  "Failed to add item": "Det gick inte att lägga till objektet",
  "Added to project": "Tillagt i projektet",
  "Failed to remove item": "Det gick inte att ta bort objektet",
  "Item removed": "Objektet togs bort",
  "Failed to rename": "Det gick inte att byta namn",
  "Project renamed": "Projektet bytte namn",
  "Project not found": "Projektet hittades inte",
  "This project may have been deleted.": "Projektet kan ha tagits bort.",
  "Go Back": "Gå tillbaka",
  "items": "objekt",
  "Restoring...": "Återställer...",
  "Failed to restore": "Det gick inte att återställa",
  "Restored successfully": "Återställd",
  "Permanently deleting...": "Tar bort permanent...",
  "Failed to delete permanently": "Det gick inte att ta bort permanent",
  "Permanently deleted": "Permanent borttagen",
  "Emptying trash...": "Tömmer papperskorgen...",
  "Failed to empty trash": "Det gick inte att tömma papperskorgen",
  "Trash emptied": "Papperskorgen tömdes",
  "Trash is empty": "Papperskorgen är tom",
  "When you delete files or projects, they'll appear here for 30 days before being permanently removed.": "När du tar bort filer eller projekt visas de här i 30 dagar innan de tas bort permanent.",
  "Deleted": "Borttagen",
  "days left": "dagar kvar",
  "Toggle navigation menu": "Växla navigeringsmeny",
  "Product facts": "Produktfakta",
  "A component kit can contain up to": "Ett komponentpaket kan innehålla upp till",
  "AI": "AI",
  "AI / action": "AI / åtgärd",
  "AI Chat Shell": "AI-chattskal",
  "AI adaptation failed.": "AI-anpassningen misslyckades.",
  "AI did not return a structured UI audit fix plan.": "AI returnerade ingen strukturerad åtgärdsplan för UI-granskningen.",
  "AI did not return a structured component kit patch.": "AI returnerade ingen strukturerad patch för komponentpaketet.",
  "AI did not return a structured feature patch plan.": "AI returnerade ingen strukturerad patchplan för funktionen.",
  "AI did not return a structured page composition patch.": "AI returnerade ingen strukturerad patch för sidkompositionen.",
  "AI did not return a structured patch plan.": "AI returnerade ingen strukturerad patchplan.",
  "AI did not return a structured replacement patch.": "AI returnerade ingen strukturerad ersättningspatch.",
  "AI did not return structured variant options.": "AI returnerade inga strukturerade variantalternativ.",
  "Accessible": "Tillgänglig",
  "Action form": "Åtgärdsformulär",
  "Adapt the pricing cards to the existing product plans and currency, preserve billing logic, and only change presentation.": "Anpassa priskorten till befintliga produktplaner och valuta, bevara faktureringslogiken och ändra endast presentationen.",
  "Adapt this CTA to the current page goal, reuse existing actions, and keep copy concise.": "Anpassa denna CTA till sidans mål, återanvänd befintliga åtgärder och håll texten kort.",
  "Adapt this hero to the project theme, reuse existing Button primitives, keep it responsive, and preserve the project typography.": "Anpassa hero-sektionen till projektets tema, återanvänd befintliga knappkomponenter, håll den responsiv och bevara typografin.",
  "Add to favorites": "Lägg till i favoriter",
  "Add to kit": "Lägg till i paket",
  "Build a responsive dashboard shell that reuses project navigation and data boundaries without inventing backend behavior.": "Bygg ett responsivt dashboardskal som återanvänder projektets navigering och datagränser utan att hitta på backendbeteende.",
  "Build a responsive settings feature with clear sections, accessible controls and existing project persistence boundaries.": "Bygg en responsiv inställningsfunktion med tydliga sektioner, tillgängliga kontroller och projektets befintliga persistensgränser.",
  "Build a trustworthy pricing page with clear plan differences, responsive comparison and conversion CTA.": "Bygg en trovärdig prissida med tydliga planskillnader, responsiv jämförelse och konverterings-CTA.",
  "Build an AI chat UI feature that reuses an existing AI service if present and otherwise exposes a clean adapter boundary without fake network logic.": "Bygg en AI-chattfunktion som återanvänder befintlig AI-tjänst om den finns, annars en ren adaptergräns utan falsk nätverkslogik.",
  "CTA": "CTA",
  "CTA Banner": "CTA-banner",
  "Cards": "Kort",
  "Choose project component file…": "Välj en komplett komponentfil i projektet…",
  "Compact floating navigation shell for landing pages.": "Kompakt flytande navigeringsskal för landningssidor.",
  "Comparison": "Jämförelse",
  "Connect this UI to the project existing authentication handlers. Do not replace auth logic or credentials handling.": "Anslut gränssnittet till projektets befintliga autentiseringshanterare. Ersätt inte autentiseringslogik eller hantering av inloggningsuppgifter.",
  "Connect this shell to the existing AI service and streaming state. Preserve authentication, rate-limit, and error handling.": "Anslut skalet till befintlig AI-tjänst och strömningsstatus. Bevara autentisering, hastighetsgränser och felhantering.",
  "Content / FAQ": "Innehåll / FAQ",
  "Conversation shell, composer, empty/loading/error states and service boundary.": "Konversationsskal, kompositör, tom-/laddnings-/felläge och tjänstegräns.",
  "Conversion-focused call-to-action block with two actions.": "Konverteringsfokuserat CTA-block med två åtgärder.",
  "Copy result": "Kopiera resultat",
  "Current Commons Clause terms prohibit redistributing the components themselves. Keep blocked from the Tayar component registry.": "Nuvarande Commons Clause-villkor förbjuder omdistribution av själva komponenterna. Håll dem blockerade från Tayar-registret.",
  "Dashboard Shell": "Dashboardskal",
  "Dashboard content shell with summary cards and activity area.": "Dashboardinnehåll med sammanfattningskort och aktivitetsområde.",
  "Dashboard shell": "Dashboardskal",
  "Dashboards": "Dashboards",
  "Data": "Data",
  "Example: Build these into a compact onboarding flow, reuse existing project buttons and keep mobile layout simple.": "Exempel: Bygg ihop dessa till ett kompakt onboardingflöde, återanvänd projektets knappar och håll mobillayouten enkel.",
  "Example: Make this fit a dark SaaS dashboard, use our existing buttons, reduce motion on mobile, and keep it accessible.": "Exempel: Anpassa detta till en mörk SaaS-dashboard, använd våra befintliga knappar, minska rörelse på mobil och behåll tillgängligheten.",
  "Feature primary isolated preview": "Isolerad förhandsvisning av primär funktion",
  "Fit this dashboard shell into the existing application layout and route structure. Reuse current navigation and data services.": "Passa in dashboardskalet i befintlig applayout och routstruktur. Återanvänd nuvarande navigering och datatjänster.",
  "Floating Navigation": "Flytande navigering",
  "Focused pricing experience with plan comparison, FAQ/supporting proof and CTA.": "Fokuserad prisupplevelse med planjämförelse, FAQ/stödjande bevis och CTA.",
  "Follow the active project style profile as closely as possible. Reuse its tokens, spacing, radii, typography and component conventions.": "Följ det aktiva projektets stilprofil så nära som möjligt. Återanvänd tokens, avstånd, radier, typografi och komponentkonventioner.",
  "Form": "Formulär",
  "Generate 3 options": "Generera 3 alternativ",
  "Generate adaptation": "Generera anpassning",
  "Glass": "Glas",
  "Gradient Hero": "Gradient-hero",
  "Hero": "Hero",
  "Heroes": "Hero-sektioner",
  "I confirm I have the right/license to use the private files I select.": "Jag bekräftar att jag har rätt/licens att använda de privata filer jag väljer.",
  "Input tokens": "Indatatokens",
  "Integrate this navigation into the existing layout, map links to the project routes, and reuse the current logo and button system.": "Integrera navigeringen i befintlig layout, mappa länkar till projektrutter och återanvänd nuvarande logotyp och knappsystem.",
  "Landing": "Landning",
  "Landing starter": "Landningsstart",
  "Last Coding Assistance patch was rolled back.": "Den senaste Coding Assistance-patchen återställdes.",
  "Live preview is not available for this component.": "Liveförhandsvisning är inte tillgänglig för den här komponenten.",
  "Load source code": "Ladda källkod",
  "Loading projects...": "Laddar projekt...",
  "Login": "Inloggning",
  "MIT + Commons Clause. May be used as part of an application/product but must not be redistributed as a competing component library; keep blocked from Tayar public registry.": "MIT + Commons Clause. Får användas i en applikation/produkt men inte omdistribueras som konkurrerande komponentbibliotek; håll blockerad från Tayars offentliga register.",
  "MIT source with a public shadcn-style registry. Preserve the upstream copyright and permission notice when substantial code is imported.": "MIT-källa med offentligt shadcn-liknande register. Bevara upstreams copyright- och tillståndsnotis vid betydande kodimport.",
  "MIT source. Animata publishes copy-paste animated React/Tailwind components and shadcn registry items. Preserve the upstream license notice.": "MIT-källa. Animata publicerar kopierbara animerade React/Tailwind-komponenter och shadcn-registerposter. Bevara upstream-licensnotisen.",
  "MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.": "MIT-källa. Bevara upstreams copyright- och tillståndsnotis vid betydande kodimport.",
  "Map these cards to real project metrics and reuse existing number formatting. Do not invent backend data.": "Koppla korten till verkliga projektmått och återanvänd befintlig talformatering. Hitta inte på backenddata.",
  "Metric Cards": "Måttkort",
  "Model": "Modell",
  "Navigation, hero, feature/value block, pricing, FAQ/content and CTA.": "Navigering, hero, funktions-/värdeblock, priser, FAQ/innehåll och CTA.",
  "Navigation, hero, trust/value sections, CTA and footer-ready structure.": "Navigering, hero, förtroende-/värdesektioner, CTA och footer-redo struktur.",
  "No animation lib": "Inget animationsbibliotek",
  "Not detected": "Inte upptäckt",
  "Original components authored for the Tayar registry.": "Originalkomponenter skapade för Tayar-registret.",
  "Output tokens": "Utdatatokens",
  "Overview shell, metrics, navigation and responsive content states.": "Översiktsskal, mått, navigering och responsiva innehållslägen.",
  "Paid component pack delivered privately after purchase. No public redistribution license was found, so Tayar must not bundle or mirror its code. Future support should use private user-provided licensed imports only.": "Betalt komponentpaket som levereras privat efter köp. Ingen offentlig omdistributionslicens hittades, så Tayar får inte paketera eller spegla koden. Framtida stöd ska endast använda privata licensierade importer som användaren tillhandahåller.",
  "Patch applied. A rollback checkpoint is available until the project files change again.": "Patchen tillämpades. En återställningspunkt finns tills projektfilerna ändras igen.",
  "Plan file patch": "Planera filpatch",
  "Plan replacement": "Planera ersättning",
  "Planning…": "Planerar…",
  "Pricing Grid": "Prisgrid",
  "Primary feature preview is not available for this pack.": "Förhandsvisning av primär funktion är inte tillgänglig för paketet.",
  "Product proof": "Produktbevis",
  "Product-first SaaS page with hero, feature proof, product UI, pricing and CTA.": "Produktfokuserad SaaS-sida med hero, funktionsbevis, produkt-UI, priser och CTA.",
  "Project native": "Projektanpassad",
  "Proof": "Bevis",
  "Reduced motion": "Minskad rörelse",
  "Remove from favorites": "Ta bort från favoriter",
  "Remove from kit": "Ta bort från paket",
  "Repository": "Repository",
  "Responsive SaaS hero with clear hierarchy and two actions.": "Responsiv SaaS-hero med tydlig hierarki och två åtgärder.",
  "Responsive metric row for analytics and dashboards.": "Responsiv måttrad för analys och dashboards.",
  "Reuse tokens": "Återanvänd tokens",
  "Review only — no project selected": "Endast granskning — inget projekt valt",
  "Rollback last patch": "Återställ senaste patch",
  "SaaS": "SaaS",
  "SaaS dashboard": "SaaS-dashboard",
  "Search components...": "Sök komponenter...",
  "Server compatible": "Serverkompatibel",
  "Settings shell, sections, form controls and save-state UX.": "Inställningsskal, sektioner, formulärkontroller och UX för sparstatus.",
  "Showing": "Visar",
  "Sign-in UI, validation states and existing-auth integration boundary.": "Inloggnings-UI, valideringslägen och integrationsgräns mot befintlig autentisering.",
  "Simple sign-in surface with accessible labels and actions.": "Enkel inloggningsyta med tillgängliga etiketter och åtgärder.",
  "Social proof": "Socialt bevis",
  "Some registries could not be loaded": "Vissa register kunde inte laddas",
  "Support card": "Supportkort",
  "Three-tier pricing layout with a highlighted recommended plan.": "Prislayout i tre nivåer med markerad rekommenderad plan.",
  "Unable to apply the patch.": "Det gick inte att tillämpa patchen.",
  "Unable to generate a safe UI audit fix plan.": "Det gick inte att skapa en säker åtgärdsplan för UI-granskningen.",
  "Unable to generate a safe component kit patch.": "Det gick inte att skapa en säker patch för komponentpaketet.",
  "Unable to generate a safe feature pack.": "Det gick inte att skapa ett säkert funktionspaket.",
  "Unable to generate a safe page composition.": "Det gick inte att skapa en säker sidkomposition.",
  "Unable to generate a safe patch plan.": "Det gick inte att skapa en säker patchplan.",
  "Unable to generate a safe replacement patch.": "Det gick inte att skapa en säker ersättningspatch.",
  "Unable to generate component options.": "Det gick inte att generera komponentalternativ.",
  "Unable to import private component files.": "Det gick inte att importera privata komponentfiler.",
  "Unable to load component code.": "Det gick inte att läsa in komponentkoden.",
  "Unable to load project choices.": "Det gick inte att läsa in projektalternativ.",
  "Unable to load project context.": "Det gick inte att läsa in projektkontexten.",
  "Unable to prepare live preview.": "Det gick inte att förbereda liveförhandsvisningen.",
  "Unable to rollback the patch.": "Det gick inte att återställa patchen.",
  "Use layered translucent surfaces and subtle depth only where they fit the existing project; preserve contrast, readability and reduced-motion behavior.": "Använd lager av halvtransparenta ytor och subtilt djup endast där det passar projektet; bevara kontrast, läsbarhet och minskad rörelse.",
  "Use restrained surfaces, generous whitespace, simple hierarchy and subtle interaction while still reusing project tokens.": "Använd återhållna ytor, generöst tomrum, enkel hierarki och subtil interaktion samtidigt som projektets tokens återanvänds.",
  "Use stronger type hierarchy, larger visual contrast and confident section separation while staying consistent with project tokens and accessibility.": "Använd starkare typografisk hierarki, större visuell kontrast och tydligare sektionsseparation samtidigt som projektets tokens och tillgänglighet följs.",
  "User-selected licensed source kept only in the current browser session. Tayar may adapt it for the user but must never publish it into the public registry.": "Användarvald licensierad källa behålls endast i aktuell webbläsarsession. Tayar får anpassa den för användaren men aldrig publicera den i det offentliga registret.",
  "Website": "Webbplats",
  "Workspace": "Arbetsyta",
  "components": "komponenter",
  "items.": "objekt.",
  "matches": "träffar",
  "private session items": "privata sessionsobjekt",
  "upstream items loaded": "upstream-objekt laddade",
  "/about": "/om",
  "AI & media": "AI och media",
  "AI image prompt": "AI-bildprompt",
  "Accent color": "Accentfärg",
  "Accordion": "Dragspel",
  "Add a call-to-action button.": "Lägg till en CTA-knapp.",
  "Add a contact section and form.": "Lägg till en kontaktsektion och formulär.",
  "Add a countdown timer.": "Lägg till en nedräkning.",
  "Add a features section.": "Lägg till en funktionssektion.",
  "Add a flexible section you can fully restyle and replace with your own elements.": "Lägg till en flexibel sektion som du kan formge om helt och ersätta med egna element.",
  "Add a footer section.": "Lägg till en sidfot.",
  "Add a hero section.": "Lägg till en hero-sektion.",
  "Add a pricing section.": "Lägg till en prissektion.",
  "Add a services section.": "Lägg till en tjänstesektion.",
  "Add a structured list of items.": "Lägg till en strukturerad lista med objekt.",
  "Add a testimonials section.": "Lägg till en omdömessektion.",
  "Add a title or section heading.": "Lägg till en titel eller sektionsrubrik.",
  "Add an about section.": "Lägg till en om-sektion.",
  "Add an image from uploads or AI.": "Lägg till en bild från uppladdningar eller AI.",
  "Add controlled visual spacing.": "Lägg till kontrollerat visuellt mellanrum.",
  "Add paragraph or supporting copy.": "Lägg till ett stycke eller stödjande text.",
  "Add sanitized custom HTML.": "Lägg till sanerad anpassad HTML.",
  "Align self": "Egen justering",
  "Alt text": "Alt-text",
  "Anchor ID": "Ankar-ID",
  "Animate once": "Animera en gång",
  "Background color": "Bakgrundsfärg",
  "Background image": "Bakgrundsbild",
  "Background mode": "Bakgrundsläge",
  "Border & shadow": "Ram och skugga",
  "Border radius": "Kantradie",
  "Browse imported assets safely. Office, PDF and archive files download as references; Tayar-native website formats can be opened directly when available.": "Bläddra säkert bland importerade resurser. Office-, PDF- och arkivfiler laddas ned som referenser; Tayar-native webbplatsformat kan öppnas direkt när de finns.",
  "Builder tools": "Byggverktyg",
  "Button text": "Knapptext",
  "COPY": "KOPIERA",
  "Call to action": "Uppmaning",
  "Canonical URL": "Kanonisk URL",
  "Collect visitor messages safely.": "Samla in besökarmeddelanden säkert.",
  "Contact": "Kontakt",
  "Contact Form": "Kontaktformulär",
  "Container": "Behållare",
  "Container ID": "Behållar-ID",
  "Container name": "Behållarnamn",
  "Content width": "Innehållsbredd",
  "Could not download template.": "Det gick inte att ladda ned mallen.",
  "Could not load templates.": "Det gick inte att läsa in mallarna.",
  "Create visual separation.": "Skapa visuell separation.",
  "Custom HTML": "Anpassad HTML",
  "DN": "NER",
  "Describe the image": "Beskriv bilden",
  "Desktop": "Dator",
  "Device": "Enhet",
  "Distance": "Avstånd",
  "Divider": "Avdelare",
  "Download template": "Ladda ned mall",
  "Embed a map or external page.": "Bädda in en karta eller extern sida.",
  "Embed or display a video.": "Bädda in eller visa en video.",
  "Exit focus": "Avsluta fokus",
  "Expandable content for FAQs.": "Expanderbart innehåll för FAQ.",
  "Field": "Fält",
  "Field name": "Fältnamn",
  "Flexible Section": "Flexibel sektion",
  "Focus on canvas": "Fokusera på arbetsytan",
  "Font size": "Teckenstorlek",
  "Font weight": "Teckenvikt",
  "Form response": "Formulärsvar",
  "Gallery": "Galleri",
  "Gradient": "Gradient",
  "Gradient from": "Gradient från",
  "Gradient to": "Gradient till",
  "Grid": "Rutnät",
  "Group elements in a reusable layout.": "Gruppera element i en återanvändbar layout.",
  "Heading": "Rubrik",
  "Hide element": "Dölj element",
  "Hide from search engines": "Dölj från sökmotorer",
  "Hide on device": "Dölj på enhet",
  "Hide section": "Dölj sektion",
  "Hover background": "Hover-bakgrund",
  "Hover opacity": "Hover-opacitet",
  "Hover scale": "Hover-skala",
  "Hover shadow": "Hover-skugga",
  "Hover text color": "Hover-textfärg",
  "Image": "Bild",
  "Image position": "Bildposition",
  "Image size": "Bildstorlek",
  "Layout column": "Layoutkolumn",
  "Leave empty for section root": "Lämna tomt för sektionens rot",
  "List": "Lista",
  "Load more": "Ladda fler",
  "Localization": "Lokalisering",
  "Map / Embed": "Karta / inbäddning",
  "Margin bottom": "Marginal nedtill",
  "Margin left": "Marginal vänster",
  "Margin right": "Marginal höger",
  "Margin top": "Marginal upptill",
  "Max width": "Maxbredd",
  "Minimum height": "Minimihöjd",
  "Mobile": "Mobil",
  "Mobile overrides": "Mobilöverskrivningar",
  "Mobile section": "Mobilsektion",
  "No favorites yet.": "Inga favoriter ännu.",
  "Open template": "Öppna mall",
  "Option 1, Option 2, Option 3": "Alternativ 1, Alternativ 2, Alternativ 3",
  "Options": "Alternativ",
  "Organize related content in tabs.": "Organisera relaterat innehåll i flikar.",
  "Overlay color": "Överläggsfärg",
  "Overlay opacity": "Överläggsopacitet",
  "Page": "Sida",
  "Page language": "Sidspråk",
  "Position X": "Position X",
  "Position Y": "Position Y",
  "Preview device": "Förhandsvisningsenhet",
  "Redirect URL": "Omdirigerings-URL",
  "Refresh library": "Uppdatera bibliotek",
  "Required": "Obligatoriskt",
  "Reusable component": "Återanvändbar komponent",
  "SEO": "SEO",
  "SEO description": "SEO-beskrivning",
  "SEO title": "SEO-titel",
  "Section image": "Sektionsbild",
  "Section radius": "Sektionsradie",
  "Section title": "Sektionstitel",
  "Show customer testimonials in a slider.": "Visa kundomdömen i en slider.",
  "Show in navigation": "Visa i navigering",
  "Show multiple images together.": "Visa flera bilder tillsammans.",
  "Show numbers and counters.": "Visa siffror och räknare.",
  "Site": "Webbplats",
  "Size & spacing": "Storlek och avstånd",
  "Slug": "Slug",
  "Social image URL": "URL till social bild",
  "Source URL": "Käll-URL",
  "Stats": "Statistik",
  "Style": "Stil",
  "Surface": "Yta",
  "Tablet": "Surfplatta",
  "Tablet overrides": "Surfplatteöverskrivningar",
  "Tablet section": "Surfplattesektion",
  "Tabs": "Flikar",
  "Templates": "Mallar",
  "Templates you download will appear here.": "Mallar du laddar ned visas här.",
  "Testimonials Slider": "Omdömesslider",
  "Text align": "Textjustering",
  "Translation group": "Översättningsgrupp",
  "Typography": "Typografi",
  "UNGROUP": "AVGRUPPERA",
  "UP": "UPP",
  "URL": "URL",
  "Validation": "Validering",
  "Visibility": "Synlighet",
  "auto": "auto",
  "bottom": "nedtill",
  "boxed": "boxad",
  "center": "centrerad",
  "checkbox": "kryssruta",
  "color": "färg",
  "contain": "anpassa",
  "cover": "täck",
  "dashed": "streckad",
  "dotted": "prickad",
  "email": "e-post",
  "en, sv, ar...": "en, sv, ar...",
  "end": "slut",
  "full": "full",
  "gradient": "gradient",
  "image": "bild",
  "left": "vänster",
  "Admin navigation, overview, tables, filters and management states.": "Adminnavigering, översikt, tabeller, filter och hanteringslägen.",
  "Apache-2.0 source. Preserve the upstream license and attribution notices when code is imported.": "Apache-2.0-källa. Bevara upstream-licensen och attribueringsnotiser vid import.",
  "App navigation, overview metrics, dashboard content, data table/filter and AI/action panel.": "Appnavigering, översiktsmått, dashboardinnehåll, datatabell/filter och AI-/åtgärdspanel.",
  "Application shell with navigation, overview cards/data and responsive workspace structure.": "Applikationsskal med navigering, översiktskort/data och responsiv arbetsytestruktur.",
  "Apply reviewed patch": "Tillämpa granskad patch",
  "Assistant conversation surface with prompt input and status.": "Assistentens konversationsyta med promptinmatning och status.",
  "Auth": "Autentisering",
  "Auth shell": "Autentiseringsskal",
  "Auth starter": "Autentiseringsstart",
  "Authentication Card": "Autentiseringskort",
  "Authentication shell, login form, secondary auth state and supporting CTA/content.": "Autentiseringsskal, inloggningsformulär, sekundärt autentiseringsläge och stödjande CTA/innehåll.",
  "Browse reusable UI, inspect code and dependencies, then hand source-aware adaptation instructions to AI. Only approved redistributable sources are loaded.": "Bläddra bland återanvändbara UI-komponenter, granska kod och beroenden och skicka sedan källmedvetna anpassningsinstruktioner till AI. Endast godkända omdistribuerbara källor laddas.",
  "Build a complete conversion-focused landing page that feels native to the active project.": "Bygg en komplett konverteringsfokuserad landningssida som känns naturlig i det aktiva projektet.",
  "Build a complete sign-in feature that reuses existing authentication services when present and never invents a backend.": "Bygg en komplett inloggningsfunktion som återanvänder befintliga autentiseringstjänster när de finns och aldrig hittar på en backend.",
  "Build a polished SaaS marketing page with strong hierarchy, product proof and clear conversion flow.": "Bygg en polerad SaaS-marknadsföringssida med tydlig hierarki, produktbevis och klart konverteringsflöde.",
  "Build a polished responsive dashboard feature using existing project data boundaries and style tokens.": "Bygg en polerad responsiv dashboardfunktion med projektets befintliga datagränser och stiltokens.",
  "Build a production-minded admin feature with responsive navigation, management tables/forms and no invented privileged backend actions.": "Bygg en produktionsinriktad adminfunktion med responsiv navigering, hanteringstabeller/formulär och utan påhittade privilegierade backendåtgärder.",
  "message": "meddelande",
  "redirect": "omdirigera",
  "right": "höger",
  "row": "rad",
  "select": "välj",
  "solid": "heldragen",
  "stack": "stapel",
  "start": "start",
  "stretch": "sträck",
  "tel": "telefon",
  "text": "text",
  "textarea": "textområde",
  "three-column": "tre kolumner",
  "top": "upptill",
  "two-column": "två kolumner",
};
const maps: Record<Language, PhraseMap> = { en: {}, ar, sv };

export function localizeUi(text: string, language: Language): string {
  if (language === 'en') return text;
  return localizeToolPhrase(text, language) ?? maps[language][text] ?? text;
}

export function useLocalizer() {
  const { prefs } = usePreferences();
  const language = prefs.language;
  return useCallback((text: string) => localizeUi(text, language), [language]);
}
