import { useCallback } from 'react';
import { usePreferences } from '@/context/PreferencesContext';

const ar: Record<string, string> = {
  'Template selected': 'تم اختيار القالب', 'Add an experience entry first': 'أضف خبرة أولاً',
  'AI ATS rewrite. Verify that every statement remains accurate.': 'إعادة صياغة بالذكاء الاصطناعي لنظام ATS. تحقق من دقة كل عبارة.',
  'Add experience first': 'أضف الخبرة أولاً', 'AI rewrite. Verify every detail before applying.': 'إعادة صياغة بالذكاء الاصطناعي. تحقق من كل التفاصيل قبل التطبيق.',
  'AI request failed': 'فشل طلب الذكاء الاصطناعي', exported: 'تم التصدير', 'Export failed': 'فشل التصدير', 'Back to Tools': 'العودة إلى الأدوات',
  'Select a starting design. You can change it later.': 'اختر تصميماً للبدء. يمكنك تغييره لاحقاً.', 'Untitled Resume': 'سيرة ذاتية بلا عنوان',
  'Zoom out': 'تصغير', 'Zoom in': 'تكبير', 'Close cover letter': 'إغلاق خطاب التقديم', 'Target company': 'الشركة المستهدفة',
  'AI proposals to review': 'اقتراحات الذكاء الاصطناعي للمراجعة', 'AI suggestions are drafts only. Verify that each statement is factually true before applying it to your CV.': 'اقتراحات الذكاء الاصطناعي مسودات فقط. تحقق من صحة كل عبارة قبل تطبيقها على سيرتك الذاتية.',
  'No AI proposals waiting for review': 'لا توجد اقتراحات ذكاء اصطناعي بانتظار المراجعة', 'Suggestions generated by CV AI tools will appear here before they can change your resume.': 'ستظهر هنا اقتراحات أدوات الذكاء الاصطناعي قبل أن تتمكن من تغيير سيرتك الذاتية.', 'Verify & apply': 'تحقق وطبّق',
  'Cover Letter': 'خطاب التقديم', 'Resume Template': 'قالب السيرة الذاتية', 'Color Theme': 'سمة الألوان', 'Font Family': 'نوع الخط', 'Section Order': 'ترتيب الأقسام',
  'Current role': 'الوظيفة الحالية', 'Add Experience': 'إضافة خبرة', 'Add Education': 'إضافة تعليم', Beginner: 'مبتدئ', Intermediate: 'متوسط', Advanced: 'متقدم', Expert: 'خبير', 'Add Skill': 'إضافة مهارة', Basic: 'أساسي', Conversational: 'محادثة', Fluent: 'طليق', Native: 'لغة أم', 'Add Language': 'إضافة لغة', 'Add Project': 'إضافة مشروع', 'Add Certificate': 'إضافة شهادة', 'Add Award': 'إضافة جائزة',
  'Job Match Analysis': 'تحليل مطابقة الوظيفة', 'Analysis updates automatically as you edit the job description or CV.': 'يتحدث التحليل تلقائياً عند تعديل وصف الوظيفة أو السيرة الذاتية.', 'Verify relevant missing keywords': 'تحقق من الكلمات المفتاحية ذات الصلة المفقودة', 'Matched keywords': 'الكلمات المفتاحية المتطابقة', 'Safe tailoring guidance': 'إرشادات تخصيص آمنة', 'Only add missing keywords when they truthfully describe your skills or experience.': 'أضف الكلمات المفتاحية المفقودة فقط عندما تصف مهاراتك أو خبرتك بصدق.',
  'Version History': 'سجل الإصدارات', 'No versions yet': 'لا توجد إصدارات بعد', 'Save a snapshot to restore it later.': 'احفظ لقطة لاستعادتها لاحقاً.'
};
const sv: Record<string, string> = {
  'Template selected': 'Mall vald', 'Add an experience entry first': 'Lägg till en erfarenhet först',
  'AI ATS rewrite. Verify that every statement remains accurate.': 'AI-omskrivning för ATS. Kontrollera att varje påstående fortfarande är korrekt.',
  'Add experience first': 'Lägg till erfarenhet först', 'AI rewrite. Verify every detail before applying.': 'AI-omskrivning. Kontrollera varje detalj innan du tillämpar den.',
  'AI request failed': 'AI-begäran misslyckades', exported: 'exporterad', 'Export failed': 'Exporten misslyckades', 'Back to Tools': 'Tillbaka till verktyg',
  'Select a starting design. You can change it later.': 'Välj en startdesign. Du kan ändra den senare.', 'Untitled Resume': 'Namnlöst CV',
  'Zoom out': 'Zooma ut', 'Zoom in': 'Zooma in', 'Close cover letter': 'Stäng personligt brev', 'Target company': 'Målföretag',
  'AI proposals to review': 'AI-förslag att granska', 'AI suggestions are drafts only. Verify that each statement is factually true before applying it to your CV.': 'AI-förslag är endast utkast. Kontrollera att varje påstående är sant innan du tillämpar det på ditt CV.',
  'No AI proposals waiting for review': 'Inga AI-förslag väntar på granskning', 'Suggestions generated by CV AI tools will appear here before they can change your resume.': 'Förslag från CV:s AI-verktyg visas här innan de kan ändra ditt CV.', 'Verify & apply': 'Verifiera och tillämpa',
  'Cover Letter': 'Personligt brev', 'Resume Template': 'CV-mall', 'Color Theme': 'Färgtema', 'Font Family': 'Typsnitt', 'Section Order': 'Avsnittsordning',
  'Current role': 'Nuvarande roll', 'Add Experience': 'Lägg till erfarenhet', 'Add Education': 'Lägg till utbildning', Beginner: 'Nybörjare', Intermediate: 'Medel', Advanced: 'Avancerad', Expert: 'Expert', 'Add Skill': 'Lägg till färdighet', Basic: 'Grundläggande', Conversational: 'Konversationsnivå', Fluent: 'Flytande', Native: 'Modersmål', 'Add Language': 'Lägg till språk', 'Add Project': 'Lägg till projekt', 'Add Certificate': 'Lägg till certifikat', 'Add Award': 'Lägg till utmärkelse',
  'Job Match Analysis': 'Jobbmatchningsanalys', 'Analysis updates automatically as you edit the job description or CV.': 'Analysen uppdateras automatiskt när du redigerar jobbannonsen eller CV:t.', 'Verify relevant missing keywords': 'Kontrollera relevanta saknade nyckelord', 'Matched keywords': 'Matchade nyckelord', 'Safe tailoring guidance': 'Säker anpassningsvägledning', 'Only add missing keywords when they truthfully describe your skills or experience.': 'Lägg bara till saknade nyckelord när de sanningsenligt beskriver dina färdigheter eller erfarenheter.',
  'Version History': 'Versionshistorik', 'No versions yet': 'Inga versioner ännu', 'Save a snapshot to restore it later.': 'Spara en ögonblicksbild för att återställa den senare.'
};

export function useCVText() {
  const { prefs } = usePreferences();
  return useCallback((phrase: string) => prefs.language === 'ar' ? (ar[phrase] ?? phrase) : prefs.language === 'sv' ? (sv[phrase] ?? phrase) : phrase, [prefs.language]);
}
