import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CVData, ColorTheme, SectionConfig, TemplateId } from '@/lib/cv-types';
import { createCVAutosaveController, CVSaveStatus } from './cv-autosave';
import { clearLocalCVDraft, loadLocalCVDraft, saveLocalCVDraft } from './cv-draft-recovery';
import { CVDocument, createCVDocument, normalizeCVDocument } from './cv-document';
import { canRedoCVHistory, canUndoCVHistory, commitCVHistory, createCVHistory, redoCVHistory, undoCVHistory } from './cv-history';
interface UseCVDocumentOptions { userId?: string | null; cvId?: string | null; autosave?: (document: CVDocument) => Promise<void>; enabled?: boolean; }
export function useCVDocument(options: UseCVDocumentOptions = {}) {
 const {userId,cvId,autosave,enabled=true}=options; const [history,setHistory]=useState(()=>createCVHistory(createCVDocument())); const [saveStatus,setSaveStatus]=useState<CVSaveStatus>('idle'); const autosaveRef=useRef(createCVAutosaveController()); const hydratedRef=useRef(false); const document=history.present;
 const replaceDocument=useCallback((next:CVDocument,recordHistory=true)=>{setHistory(current=>{const updated=recordHistory?commitCVHistory(current,next):createCVHistory(next);if(updated===current)return current;hydratedRef.current=true;setSaveStatus('dirty');return updated;});},[]);
 const updateDocument=useCallback((recipe:(current:CVDocument)=>CVDocument)=>{setHistory(current=>{const next=recipe(current.present);if(next===current.present)return current;const updated=commitCVHistory(current,next);if(updated===current)return current;hydratedRef.current=true;setSaveStatus('dirty');return updated;});},[]);
 const setData=useCallback((next:CVData|((current:CVData)=>CVData))=>{updateDocument(current=>{const data=typeof next==='function'?next(current.data):next;return data===current.data?current:{...current,data};});},[updateDocument]);
 const updateSettings=useCallback((patch:Partial<CVDocument['settings']>)=>{updateDocument(current=>{const changed=(Object.keys(patch) as Array<keyof CVDocument['settings']>).some(key=>!Object.is(current.settings[key],patch[key]));return changed?{...current,settings:{...current.settings,...patch}}:current;});},[updateDocument]);
 const restoreLocalDraft=useCallback(()=>{if(!userId)return false;const snapshot=loadLocalCVDraft(userId,cvId);if(!snapshot)return false;setHistory(createCVHistory(snapshot.document));setSaveStatus('dirty');hydratedRef.current=true;return true;},[userId,cvId]);
 const hydrate=useCallback((value:unknown)=>{const next=normalizeCVDocument(value);autosaveRef.current.cancel();setHistory(createCVHistory(next));setSaveStatus('saved');hydratedRef.current=true;},[]);
 const undo=useCallback(()=>setHistory(current=>{if(!canUndoCVHistory(current))return current;hydratedRef.current=true;setSaveStatus('dirty');return undoCVHistory(current);}),[]);
 const redo=useCallback(()=>setHistory(current=>{if(!canRedoCVHistory(current))return current;hydratedRef.current=true;setSaveStatus('dirty');return redoCVHistory(current);}),[]);
 useEffect(()=>{if(!enabled||!userId||!hydratedRef.current)return;saveLocalCVDraft(userId,document,cvId);if(!autosave)return;setSaveStatus('dirty');autosaveRef.current.schedule(async()=>{setSaveStatus('saving');try{await autosave(document);setSaveStatus('saved');clearLocalCVDraft(userId,cvId);}catch{setSaveStatus('error');}});},[document,enabled,userId,cvId,autosave]);
 useEffect(()=>()=>{void autosaveRef.current.flush();},[]);
 return useMemo(()=>({document,cv:document.data,template:document.settings.template as TemplateId,colorTheme:document.settings.colorTheme as ColorTheme,fontId:document.settings.fontId,sections:document.settings.sections as SectionConfig[],saveStatus,setData,setTemplate:(template:TemplateId)=>updateSettings({template}),setColorTheme:(colorTheme:ColorTheme)=>updateSettings({colorTheme}),setFontId:(fontId:string)=>updateSettings({fontId}),setSections:(sections:SectionConfig[])=>updateSettings({sections}),replaceDocument,hydrate,restoreLocalDraft,undo,redo,canUndo:canUndoCVHistory(history),canRedo:canRedoCVHistory(history),flushAutosave:()=>autosaveRef.current.flush()}),[document,saveStatus,setData,updateSettings,replaceDocument,hydrate,restoreLocalDraft,undo,redo,history]);
}
