import React from 'react';
import { Award, Briefcase, FileText, FolderOpen, Languages, Trash2, Zap } from 'lucide-react';
import { CVData } from '@/lib/cv-types';
import { CVCollectionKey } from '../core/cv-operations';

interface Props {
  cv: CVData;
  section: string;
  setCV: (next: CVData | ((current: CVData) => CVData)) => void;
  editor: {
    updateItem: <K extends CVCollectionKey>(collection: K, id: string, patch: Partial<CVData[K][number]>) => void;
    deleteItem: <K extends CVCollectionKey>(collection: K, id: string) => void;
    addExperience: () => void; addEducation: () => void; addSkill: () => void; addLanguage: () => void;
    addProject: () => void; addCertificate: () => void; addAward: () => void;
  };
}

const input = 'w-full bg-white/[0.04] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-violet-500/50';
const Add = ({ onClick, children }: { onClick: () => void; children: React.ReactNode }) => <button type="button" onClick={onClick} className="w-full border border-dashed border-white/15 hover:border-violet-500/40 text-gray-400 hover:text-violet-300 rounded-xl py-2 text-xs">+ {children}</button>;
const Delete = ({ onClick, label }: { onClick: () => void; label: string }) => <button type="button" aria-label={label} onClick={onClick}><Trash2 className="w-4 h-4 text-red-400" /></button>;
const Empty = ({ icon: Icon, text }: { icon: React.ElementType; text: string }) => <div className="py-6 text-center text-gray-500 text-xs"><Icon className="w-5 h-5 mx-auto mb-2 opacity-50" />{text}</div>;

export function CVContentEditor({ cv, section, setCV, editor }: Props) {
  if (section === 'summary') return <textarea aria-label="Professional summary" className={input + ' min-h-[200px] resize-y'} value={cv.summary} onChange={e => setCV(current => ({ ...current, summary: e.target.value }))} />;
  if (section === 'experience') return <div className="space-y-3">{!cv.experience.length && <Empty icon={Briefcase} text="No experience yet" />}{cv.experience.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label="Delete experience" onClick={() => editor.deleteItem('experience', item.id)} /></div><input className={input} value={item.jobTitle} placeholder="Job title" onChange={e => editor.updateItem('experience', item.id, { jobTitle: e.target.value })} /><input className={input} value={item.company} placeholder="Company" onChange={e => editor.updateItem('experience', item.id, { company: e.target.value })} /><input className={input} value={item.location} placeholder="Location" onChange={e => editor.updateItem('experience', item.id, { location: e.target.value })} /><div className="grid grid-cols-2 gap-2"><input className={input} value={item.startDate} placeholder="Start date" onChange={e => editor.updateItem('experience', item.id, { startDate: e.target.value })} /><input className={input} value={item.endDate} disabled={item.current} placeholder={item.current ? 'Present' : 'End date'} onChange={e => editor.updateItem('experience', item.id, { endDate: e.target.value })} /></div><label className="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={item.current} onChange={e => editor.updateItem('experience', item.id, { current: e.target.checked, ...(e.target.checked ? { endDate: '' } : {}) })} />Current role</label><textarea className={input + ' min-h-[90px]'} value={item.description} placeholder="Description" onChange={e => editor.updateItem('experience', item.id, { description: e.target.value })} /></div>)}<Add onClick={editor.addExperience}>Add Experience</Add></div>;
  if (section === 'education') return <div className="space-y-3">{!cv.education.length && <Empty icon={FileText} text="No education yet" />}{cv.education.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label="Delete education" onClick={() => editor.deleteItem('education', item.id)} /></div><input className={input} value={item.degree} placeholder="Degree" onChange={e => editor.updateItem('education', item.id, { degree: e.target.value })} /><input className={input} value={item.institution} placeholder="Institution" onChange={e => editor.updateItem('education', item.id, { institution: e.target.value })} /><input className={input} value={item.location} placeholder="Location" onChange={e => editor.updateItem('education', item.id, { location: e.target.value })} /><div className="grid grid-cols-2 gap-2"><input className={input} value={item.startDate} placeholder="Start date" onChange={e => editor.updateItem('education', item.id, { startDate: e.target.value })} /><input className={input} value={item.endDate} placeholder="End date" onChange={e => editor.updateItem('education', item.id, { endDate: e.target.value })} /></div><textarea className={input} value={item.description} placeholder="Description" onChange={e => editor.updateItem('education', item.id, { description: e.target.value })} /></div>)}<Add onClick={editor.addEducation}>Add Education</Add></div>;
  if (section === 'skills') return <div className="space-y-2">{!cv.skills.length && <Empty icon={Zap} text="No skills yet" />}{cv.skills.map(item => <div key={item.id} className="grid grid-cols-[1fr_140px_auto] gap-2"><input className={input} value={item.name} placeholder="Skill" onChange={e => editor.updateItem('skills', item.id, { name: e.target.value })} /><select className={input} value={item.level} onChange={e => editor.updateItem('skills', item.id, { level: e.target.value as typeof item.level })}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select><Delete label="Delete skill" onClick={() => editor.deleteItem('skills', item.id)} /></div>)}<Add onClick={editor.addSkill}>Add Skill</Add></div>;
  if (section === 'languages') return <div className="space-y-2">{!cv.languages.length && <Empty icon={Languages} text="No languages yet" />}{cv.languages.map(item => <div key={item.id} className="grid grid-cols-[1fr_140px_auto] gap-2"><input className={input} value={item.name} placeholder="Language" onChange={e => editor.updateItem('languages', item.id, { name: e.target.value })} /><select className={input} value={item.proficiency} onChange={e => editor.updateItem('languages', item.id, { proficiency: e.target.value as typeof item.proficiency })}><option>Basic</option><option>Conversational</option><option>Fluent</option><option>Native</option></select><Delete label="Delete language" onClick={() => editor.deleteItem('languages', item.id)} /></div>)}<Add onClick={editor.addLanguage}>Add Language</Add></div>;
  if (section === 'projects') return <div className="space-y-3">{!cv.projects.length && <Empty icon={FolderOpen} text="No projects yet" />}{cv.projects.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label="Delete project" onClick={() => editor.deleteItem('projects', item.id)} /></div><input className={input} value={item.name} placeholder="Project name" onChange={e => editor.updateItem('projects', item.id, { name: e.target.value })} /><input className={input} value={item.link} placeholder="Project link" onChange={e => editor.updateItem('projects', item.id, { link: e.target.value })} /><textarea className={input} value={item.description} placeholder="Description" onChange={e => editor.updateItem('projects', item.id, { description: e.target.value })} /></div>)}<Add onClick={editor.addProject}>Add Project</Add></div>;
  if (section === 'certificates') return <div className="space-y-3">{!cv.certificates.length && <Empty icon={FileText} text="No certificates yet" />}{cv.certificates.map(item => <div key={item.id} className="grid grid-cols-[1fr_1fr_120px_auto] gap-2"><input className={input} value={item.name} placeholder="Certificate" onChange={e => editor.updateItem('certificates', item.id, { name: e.target.value })} /><input className={input} value={item.issuer} placeholder="Issuer" onChange={e => editor.updateItem('certificates', item.id, { issuer: e.target.value })} /><input className={input} value={item.date} placeholder="Date" onChange={e => editor.updateItem('certificates', item.id, { date: e.target.value })} /><Delete label="Delete certificate" onClick={() => editor.deleteItem('certificates', item.id)} /></div>)}<Add onClick={editor.addCertificate}>Add Certificate</Add></div>;
  if (section === 'awards') return <div className="space-y-3">{!cv.awards.length && <Empty icon={Award} text="No awards yet" />}{cv.awards.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label="Delete award" onClick={() => editor.deleteItem('awards', item.id)} /></div><input className={input} value={item.title} placeholder="Award" onChange={e => editor.updateItem('awards', item.id, { title: e.target.value })} /><input className={input} value={item.issuer} placeholder="Issuer" onChange={e => editor.updateItem('awards', item.id, { issuer: e.target.value })} /><input className={input} value={item.date} placeholder="Date" onChange={e => editor.updateItem('awards', item.id, { date: e.target.value })} /><textarea className={input} value={item.description} placeholder="Description" onChange={e => editor.updateItem('awards', item.id, { description: e.target.value })} /></div>)}<Add onClick={editor.addAward}>Add Award</Add></div>;
  return null;
}
