import React from 'react';
import { Award, Briefcase, FileText, FolderOpen, Languages, Trash2, Zap } from 'lucide-react';
import { CVData } from '@/lib/cv-types';
import { CVCollectionKey } from '../core/cv-operations';
import { useCVText } from '../i18n/use-cv-text';

interface Props {
  cv: CVData; section: string;
  setCV: (next: CVData | ((current: CVData) => CVData)) => void;
  editor: { updatePersonal?: <K extends keyof CVData['personal']>(field: K, value: CVData['personal'][K]) => void; updateItem: <K extends CVCollectionKey>(collection: K, id: string, patch: Partial<CVData[K][number]>) => void; deleteItem: <K extends CVCollectionKey>(collection: K, id: string) => void; addExperience: () => void; addEducation: () => void; addSkill: () => void; addLanguage: () => void; addProject: () => void; addCertificate: () => void; addAward: () => void; };
}
const input = 'w-full bg-white/[0.04] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-violet-500/50';
const Add = ({ onClick, children }: { onClick: () => void; children: React.ReactNode }) => <button type="button" onClick={onClick} className="w-full border border-dashed border-white/15 hover:border-violet-500/40 text-gray-400 hover:text-violet-300 rounded-xl py-2 text-xs">+ {children}</button>;
const Delete = ({ onClick, label }: { onClick: () => void; label: string }) => <button type="button" aria-label={label} onClick={onClick}><Trash2 aria-hidden="true" className="w-4 h-4 text-red-400" /></button>;
const Empty = ({ icon: Icon, text }: { icon: React.ElementType; text: string }) => <div className="py-6 text-center text-gray-500 text-xs"><Icon aria-hidden="true" className="w-5 h-5 mx-auto mb-2 opacity-50" />{text}</div>;

export function CVContentEditor({ cv, section, setCV, editor }: Props) {
  const t = useCVText();
  const updatePersonal = <K extends keyof CVData['personal']>(field: K, value: CVData['personal'][K]) => editor.updatePersonal ? editor.updatePersonal(field, value) : setCV(current => ({ ...current, personal: { ...current.personal, [field]: value } }));
  const field = (label: string, value: string, onChange: (value: string) => void, type = 'text') => <input aria-label={t(label)} type={type} className={input} value={value} placeholder={t(label)} onChange={event => onChange(event.target.value)} />;
  if (section === 'personal') return <div className="space-y-3">{field('Full name', cv.personal.fullName, value => updatePersonal('fullName', value))}{field('Job title', cv.personal.jobTitle, value => updatePersonal('jobTitle', value))}{field('Email', cv.personal.email, value => updatePersonal('email', value), 'email')}{field('Phone', cv.personal.phone, value => updatePersonal('phone', value), 'tel')}{field('Address', cv.personal.address, value => updatePersonal('address', value))}{field('LinkedIn', cv.personal.linkedin, value => updatePersonal('linkedin', value))}{field('Portfolio', cv.personal.portfolio, value => updatePersonal('portfolio', value))}</div>;
  if (section === 'summary') return <textarea aria-label={t('Professional summary')} placeholder={t('Professional summary')} className={input + ' min-h-[200px] resize-y'} value={cv.summary} onChange={event => setCV(current => ({ ...current, summary: event.target.value }))} />;
  if (section === 'experience') return <div className="space-y-3">{!cv.experience.length && <Empty icon={Briefcase} text={t('No experience yet')} />}{cv.experience.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label={t('Delete experience')} onClick={() => editor.deleteItem('experience', item.id)} /></div>{field('Job title', item.jobTitle, value => editor.updateItem('experience', item.id, { jobTitle: value }))}{field('Company', item.company, value => editor.updateItem('experience', item.id, { company: value }))}{field('Location', item.location, value => editor.updateItem('experience', item.id, { location: value }))}<div className="grid grid-cols-2 gap-2">{field('Start date', item.startDate, value => editor.updateItem('experience', item.id, { startDate: value }))}<input aria-label={t('End date')} className={input} value={item.endDate} disabled={item.current} placeholder={t(item.current ? 'Present' : 'End date')} onChange={event => editor.updateItem('experience', item.id, { endDate: event.target.value })} /></div><label className="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={item.current} onChange={event => editor.updateItem('experience', item.id, { current: event.target.checked, ...(event.target.checked ? { endDate: '' } : {}) })} />{t('Current role')}</label><textarea aria-label={t('Description')} className={input + ' min-h-[90px]'} value={item.description} placeholder={t('Description')} onChange={event => editor.updateItem('experience', item.id, { description: event.target.value })} /></div>)}<Add onClick={editor.addExperience}>{t('Add Experience')}</Add></div>;
  if (section === 'education') return <div className="space-y-3">{!cv.education.length && <Empty icon={FileText} text={t('No education yet')} />}{cv.education.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label={t('Delete education')} onClick={() => editor.deleteItem('education', item.id)} /></div>{field('Degree', item.degree, value => editor.updateItem('education', item.id, { degree: value }))}{field('Institution', item.institution, value => editor.updateItem('education', item.id, { institution: value }))}{field('Location', item.location, value => editor.updateItem('education', item.id, { location: value }))}<div className="grid grid-cols-2 gap-2">{field('Start date', item.startDate, value => editor.updateItem('education', item.id, { startDate: value }))}{field('End date', item.endDate, value => editor.updateItem('education', item.id, { endDate: value }))}</div><textarea aria-label={t('Description')} className={input} value={item.description} placeholder={t('Description')} onChange={event => editor.updateItem('education', item.id, { description: event.target.value })} /></div>)}<Add onClick={editor.addEducation}>{t('Add Education')}</Add></div>;
  if (section === 'skills') return <div className="space-y-2">{!cv.skills.length && <Empty icon={Zap} text={t('No skills yet')} />}{cv.skills.map(item => <div key={item.id} className="grid grid-cols-[1fr_140px_auto] gap-2">{field('Skill', item.name, value => editor.updateItem('skills', item.id, { name: value }))}<select aria-label={t('Skill level')} className={input} value={item.level} onChange={event => editor.updateItem('skills', item.id, { level: event.target.value as typeof item.level })}>{['Beginner','Intermediate','Advanced','Expert'].map(level => <option key={level} value={level}>{t(level)}</option>)}</select><Delete label={t('Delete skill')} onClick={() => editor.deleteItem('skills', item.id)} /></div>)}<Add onClick={editor.addSkill}>{t('Add Skill')}</Add></div>;
  if (section === 'languages') return <div className="space-y-2">{!cv.languages.length && <Empty icon={Languages} text={t('No languages yet')} />}{cv.languages.map(item => <div key={item.id} className="grid grid-cols-[1fr_140px_auto] gap-2">{field('Language', item.name, value => editor.updateItem('languages', item.id, { name: value }))}<select aria-label={t('Language proficiency')} className={input} value={item.proficiency} onChange={event => editor.updateItem('languages', item.id, { proficiency: event.target.value as typeof item.proficiency })}>{['Basic','Conversational','Fluent','Native'].map(level => <option key={level} value={level}>{t(level)}</option>)}</select><Delete label={t('Delete language')} onClick={() => editor.deleteItem('languages', item.id)} /></div>)}<Add onClick={editor.addLanguage}>{t('Add Language')}</Add></div>;
  if (section === 'projects') return <div className="space-y-3">{!cv.projects.length && <Empty icon={FolderOpen} text={t('No projects yet')} />}{cv.projects.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label={t('Delete project')} onClick={() => editor.deleteItem('projects', item.id)} /></div>{field('Project name', item.name, value => editor.updateItem('projects', item.id, { name: value }))}{field('Project link', item.link, value => editor.updateItem('projects', item.id, { link: value }))}<textarea aria-label={t('Description')} className={input} value={item.description} placeholder={t('Description')} onChange={event => editor.updateItem('projects', item.id, { description: event.target.value })} /></div>)}<Add onClick={editor.addProject}>{t('Add Project')}</Add></div>;
  if (section === 'certificates') return <div className="space-y-3">{!cv.certificates.length && <Empty icon={FileText} text={t('No certificates yet')} />}{cv.certificates.map(item => <div key={item.id} className="grid grid-cols-[1fr_1fr_120px_auto] gap-2">{field('Certificate', item.name, value => editor.updateItem('certificates', item.id, { name: value }))}{field('Issuer', item.issuer, value => editor.updateItem('certificates', item.id, { issuer: value }))}{field('Date', item.date, value => editor.updateItem('certificates', item.id, { date: value }))}<Delete label={t('Delete certificate')} onClick={() => editor.deleteItem('certificates', item.id)} /></div>)}<Add onClick={editor.addCertificate}>{t('Add Certificate')}</Add></div>;
  if (section === 'awards') return <div className="space-y-3">{!cv.awards.length && <Empty icon={Award} text={t('No awards yet')} />}{cv.awards.map(item => <div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2"><div className="flex justify-end"><Delete label={t('Delete award')} onClick={() => editor.deleteItem('awards', item.id)} /></div>{field('Award', item.title, value => editor.updateItem('awards', item.id, { title: value }))}{field('Issuer', item.issuer, value => editor.updateItem('awards', item.id, { issuer: value }))}{field('Date', item.date, value => editor.updateItem('awards', item.id, { date: value }))}<textarea aria-label={t('Description')} className={input} value={item.description} placeholder={t('Description')} onChange={event => editor.updateItem('awards', item.id, { description: event.target.value })} /></div>)}<Add onClick={editor.addAward}>{t('Add Award')}</Add></div>;
  return null;
}
