import React from 'react';
import { Briefcase, FileText, Languages, Trash2, Zap } from 'lucide-react';
import { CVData } from '@/lib/cv-types';
import { CVCollectionKey } from '../core/cv-operations';
import { useCVText } from '../i18n/use-cv-text';

interface Props { cv: CVData; section: string; setCV: (next: CVData | ((current: CVData) => CVData)) => void; editor: { updatePersonal?: <K extends keyof CVData['personal']>(field: K, value: CVData['personal'][K]) => void; updateItem: <K extends CVCollectionKey>(collection: K, id: string, patch: Partial<CVData[K][number]>) => void; deleteItem: <K extends CVCollectionKey>(collection: K, id: string) => void; addExperience: () => void; addEducation: () => void; addSkill: () => void; addLanguage: () => void; addProject: () => void; addCertificate: () => void; addAward: () => void; }; }
const input = 'w-full min-w-0 bg-white/[0.04] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-violet-500/50';
const Add = ({ onClick, children }: { onClick: () => void; children: React.ReactNode }) => <button type="button" onClick={onClick} className="w-full border border-dashed border-white/15 hover:border-violet-500/40 text-gray-400 hover:text-violet-300 rounded-xl py-2 text-xs">+ {children}</button>;
const Delete = ({ onClick, label }: { onClick: () => void; label: string }) => <button type="button" aria-label={label} onClick={onClick} className="shrink-0"><Trash2 aria-hidden="true" className="w-4 h-4 text-red-400" /></button>;
const Empty = ({ icon: Icon, text }: { icon: React.ElementType; text: string }) => <div className="py-6 text-center text-gray-500 text-xs"><Icon aria-hidden="true" className="w-5 h-5 mx-auto mb-2 opacity-50" />{text}</div>;

export function CVContentEditor({ cv, section, setCV, editor }: Props) {
  const t = useCVText();
  const updatePersonal = <K extends keyof CVData['personal']>(field: K, value: CVData['personal'][K]) => editor.updatePersonal ? editor.updatePersonal(field, value) : setCV(current => ({ ...current, personal: { ...current.personal, [field]: value } }));
  const field = (label: string, value: string, onChange: (value: string) => void, type = 'text') => <input aria-label={t(label)} type={type} className={input} value={value} placeholder={t(label)} onChange={event => onChange(event.target.value)} />;
  if (section === 'personal') return <div className="space-y-3 min-w-0">{field('Full name',cv.personal.fullName,v=>updatePersonal('fullName',v))}{field('Job title',cv.personal.jobTitle,v=>updatePersonal('jobTitle',v))}{field('Email',cv.personal.email,v=>updatePersonal('email',v),'email')}{field('Phone',cv.personal.phone,v=>updatePersonal('phone',v),'tel')}{field('Address',cv.personal.address,v=>updatePersonal('address',v))}{field('LinkedIn',cv.personal.linkedin,v=>updatePersonal('linkedin',v))}{field('Portfolio',cv.personal.portfolio,v=>updatePersonal('portfolio',v))}</div>;
  if (section === 'summary') return <textarea aria-label={t('Professional summary')} placeholder={t('Professional summary')} className={input+' min-h-[200px] resize-y'} value={cv.summary} onChange={e=>setCV(c=>({...c,summary:e.target.value}))}/>;
  if (section === 'experience') return <div className="space-y-3">{!cv.experience.length&&<Empty icon={Briefcase} text={t('No experience yet')}/>} {cv.experience.map(item=><div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2 min-w-0"><div className="flex justify-end"><Delete label={t('Delete experience')} onClick={()=>editor.deleteItem('experience',item.id)}/></div>{field('Job title',item.jobTitle,v=>editor.updateItem('experience',item.id,{jobTitle:v}))}{field('Company',item.company,v=>editor.updateItem('experience',item.id,{company:v}))}{field('Location',item.location,v=>editor.updateItem('experience',item.id,{location:v}))}<div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{field('Start date',item.startDate,v=>editor.updateItem('experience',item.id,{startDate:v}))}{field('End date',item.endDate,v=>editor.updateItem('experience',item.id,{endDate:v}))}</div><label className="flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={item.current} onChange={e=>editor.updateItem('experience',item.id,{current:e.target.checked,...(e.target.checked?{endDate:''}:{})})}/>{t('Current role')}</label><textarea className={input+' min-h-[90px]'} value={item.description} onChange={e=>editor.updateItem('experience',item.id,{description:e.target.value})}/></div>)}<Add onClick={editor.addExperience}>{t('Add Experience')}</Add></div>;
  if (section === 'education') return <div className="space-y-3">{!cv.education.length&&<Empty icon={FileText} text={t('No education yet')}/>} {cv.education.map(item=><div key={item.id} className="border border-white/10 rounded-xl p-3 space-y-2 min-w-0"><div className="flex justify-end"><Delete label={t('Delete education')} onClick={()=>editor.deleteItem('education',item.id)}/></div>{field('Degree',item.degree,v=>editor.updateItem('education',item.id,{degree:v}))}{field('Institution',item.institution,v=>editor.updateItem('education',item.id,{institution:v}))}{field('Location',item.location,v=>editor.updateItem('education',item.id,{location:v}))}<div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{field('Start date',item.startDate,v=>editor.updateItem('education',item.id,{startDate:v}))}{field('End date',item.endDate,v=>editor.updateItem('education',item.id,{endDate:v}))}</div><textarea className={input} value={item.description} onChange={e=>editor.updateItem('education',item.id,{description:e.target.value})}/></div>)}<Add onClick={editor.addEducation}>{t('Add Education')}</Add></div>;
  if (section === 'skills') return <div className="space-y-2">{!cv.skills.length && <Empty icon={Zap} text={t('No skills yet')}/>}{cv.skills.map(skill => <div key={skill.id} className="grid grid-cols-1 sm:grid-cols-[minmax(0,1fr)_140px_auto] gap-2 items-center">{field('Skill', skill.name, value => editor.updateItem('skills', skill.id, { name: value }))}<select className={input} value={skill.level} onChange={event => editor.updateItem('skills', skill.id, { level: event.target.value })}>{['Beginner','Intermediate','Advanced','Expert'].map(level => <option key={level} value={level}>{t(level)}</option>)}</select><Delete label={t('Delete')} onClick={() => editor.deleteItem('skills', skill.id)}/></div>)}<Add onClick={editor.addSkill}>{t('Add Skill')}</Add></div>;
  if (section === 'languages') return <div className="space-y-2">{!cv.languages.length && <Empty icon={Languages} text={t('No languages yet')}/>}{cv.languages.map(language => <div key={language.id} className="grid grid-cols-1 sm:grid-cols-[minmax(0,1fr)_140px_auto] gap-2 items-center">{field('Language', language.name, value => editor.updateItem('languages', language.id, { name: value }))}<select className={input} value={language.proficiency} onChange={event => editor.updateItem('languages', language.id, { proficiency: event.target.value })}>{['Basic','Conversational','Fluent','Native'].map(level => <option key={level} value={level}>{t(level)}</option>)}</select><Delete label={t('Delete')} onClick={() => editor.deleteItem('languages', language.id)}/></div>)}<Add onClick={editor.addLanguage}>{t('Add Language')}</Add></div>;
  if(section==='projects') return <div className="space-y-3">{cv.projects.map(i=><div key={i.id} className="border border-white/10 rounded-xl p-3 space-y-2">{field('Project name',i.name,v=>editor.updateItem('projects',i.id,{name:v}))}{field('Project link',i.link,v=>editor.updateItem('projects',i.id,{link:v}))}<textarea className={input} value={i.description} onChange={e=>editor.updateItem('projects',i.id,{description:e.target.value})}/><Delete label={t('Delete project')} onClick={()=>editor.deleteItem('projects',i.id)}/></div>)}<Add onClick={editor.addProject}>{t('Add Project')}</Add></div>;
  if(section==='certificates') return <div className="space-y-3">{cv.certificates.map(i=><div key={i.id} className="grid grid-cols-1 sm:grid-cols-2 gap-2">{field('Certificate',i.name,v=>editor.updateItem('certificates',i.id,{name:v}))}{field('Issuer',i.issuer,v=>editor.updateItem('certificates',i.id,{issuer:v}))}{field('Date',i.date,v=>editor.updateItem('certificates',i.id,{date:v}))}<Delete label={t('Delete certificate')} onClick={()=>editor.deleteItem('certificates',i.id)}/></div>)}<Add onClick={editor.addCertificate}>{t('Add Certificate')}</Add></div>;
  if(section==='awards') return <div className="space-y-3">{cv.awards.map(i=><div key={i.id} className="border border-white/10 rounded-xl p-3 space-y-2">{field('Award',i.title,v=>editor.updateItem('awards',i.id,{title:v}))}{field('Issuer',i.issuer,v=>editor.updateItem('awards',i.id,{issuer:v}))}{field('Date',i.date,v=>editor.updateItem('awards',i.id,{date:v}))}<textarea className={input} value={i.description} onChange={e=>editor.updateItem('awards',i.id,{description:e.target.value})}/><Delete label={t('Delete award')} onClick={()=>editor.deleteItem('awards',i.id)}/></div>)}<Add onClick={editor.addAward}>{t('Add Award')}</Add></div>;
  return null;
}
