// Generated by scripts/build-website-github-connection.mjs; edit server/service source.
/* eslint-disable no-var, @typescript-eslint/no-unused-vars -- Generated bundle. */

// server/website-github-connection-edge.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

// src/modules/website-builder/services/trustedServerRuntime.ts
function isUntrustedBrowserRuntime() {
  const deno = globalThis.Deno;
  return typeof window !== "undefined" && typeof deno?.version?.deno !== "string";
}

// src/modules/website-builder/services/websiteConnectionOAuthStateService.ts
var uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var statePattern = /^[0-9a-f]{64}$/;
var providers = ["github", "supabase", "vercel", "stripe"];
function serverOnly() {
  if (isUntrustedBrowserRuntime()) throw new Error("OAuth state requires a trusted server.");
}
async function hash(state2) {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(state2));
  return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join("");
}
async function createWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!uuid.test(input.ownerId) || !uuid.test(input.projectId) || !providers.includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  const raw = Array.from(crypto.getRandomValues(new Uint8Array(32)), (byte) => byte.toString(16).padStart(2, "0")).join("");
  const digest = await hash(raw);
  const expiresAt = new Date((input.now ?? Date.now)() + 9 * 6e4).toISOString();
  const { error } = await input.client.rpc("website_create_connection_oauth_state", {
    p_state_hash: digest,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_expires_at: expiresAt
  });
  if (error || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  return raw;
}
async function consumeWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!statePattern.test(input.state) || !providers.includes(input.provider)) throw new Error("Connection state is invalid or expired.");
  const { data, error } = await input.client.rpc("website_consume_connection_oauth_state", { p_state_hash: await hash(input.state) });
  if (error || !data || !uuid.test(data.ownerId) || !uuid.test(data.projectId) || data.provider !== input.provider || !["preview", "production"].includes(data.environment)) {
    throw new Error("Connection state is invalid or expired.");
  }
  return { ownerId: data.ownerId, projectId: data.projectId, provider: data.provider, environment: data.environment };
}

// src/modules/website-builder/services/websiteGithubOAuthService.ts
var statePattern2 = /^[0-9a-f]{64}$/;
var appId = /^[a-zA-Z0-9_]{5,100}$/;
var codePattern = /^[a-zA-Z0-9_-]{1,1024}$/;
function callbackUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || url.search && url.search !== "?action=callback") {
    throw new Error("GitHub connection is not configured.");
  }
  return url.toString();
}
function githubAuthorizationUrl(input) {
  if (!appId.test(input.clientId) || !statePattern2.test(input.state)) throw new Error("GitHub connection is not configured.");
  const url = new URL("https://github.com/login/oauth/authorize");
  url.searchParams.set("client_id", input.clientId);
  url.searchParams.set("redirect_uri", callbackUrl(input.callback));
  url.searchParams.set("state", input.state);
  return url.toString();
}
async function exchangeGitHubAppUserCode(input) {
  if (isUntrustedBrowserRuntime()) throw new Error("GitHub exchange requires a server.");
  if (!appId.test(input.clientId) || !input.clientSecret || input.clientSecret.length > 4096 || !codePattern.test(input.code)) throw new Error("GitHub authorization failed.");
  try {
    const body = new URLSearchParams({
      client_id: input.clientId,
      client_secret: input.clientSecret,
      code: input.code,
      redirect_uri: callbackUrl(input.callback)
    });
    const response = await (input.fetcher ?? fetch)("https://github.com/login/oauth/access_token", {
      method: "POST",
      redirect: "error",
      signal: AbortSignal.timeout(8e3),
      headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" },
      body
    });
    if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 16384) throw new Error();
    const raw = await response.text();
    if (raw.length > 16384) throw new Error();
    const token = JSON.parse(raw);
    if (!token || token.token_type?.toLowerCase() !== "bearer" || typeof token.access_token !== "string" || token.access_token.length < 20 || token.access_token.length > 4096) throw new Error();
    return token.access_token;
  } catch {
    throw new Error("GitHub authorization failed.");
  }
}
async function acceptGitHubOAuthCallback(input) {
  const scope = await consumeWebsiteConnectionOAuthState({ client: input.stateClient, state: input.state, provider: "github" });
  const userToken = await exchangeGitHubAppUserCode(input);
  return { ownerId: scope.ownerId, projectId: scope.projectId, environment: scope.environment, userToken };
}

// src/modules/website-builder/services/websiteConnectionHandoffService.ts
var uuid2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function serverOnly2() {
  if (isUntrustedBrowserRuntime()) throw new Error("Connection handoff requires a trusted server.");
}
async function storeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !["github", "supabase", "vercel", "stripe"].includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.userToken || input.userToken.length < 20 || new TextEncoder().encode(input.userToken).length > 65536) {
    throw new Error("Connection handoff could not be stored.");
  }
  const id = crypto.randomUUID();
  const { error } = await input.client.rpc("website_store_connection_handoff", {
    p_id: id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_token: input.userToken,
    p_expires_at: new Date((input.now ?? Date.now)() + 4 * 6e4).toISOString()
  });
  if (error) throw new Error("Connection handoff could not be stored.");
  return id;
}
async function consumeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_consume_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > 65536 || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}
async function peekWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_peek_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > 65536 || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}

// src/modules/website-builder/services/websiteGithubInstallationService.ts
var numeric = /^[1-9][0-9]{0,19}$/;
var repoName = /^[a-zA-Z0-9_.-]{1,39}\/[a-zA-Z0-9_.-]{1,100}$/;
var branch = /^[a-zA-Z0-9_./-]{1,200}$/;
var api = "https://api.github.com";
function object(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("GitHub account could not be verified.");
  return value;
}
async function githubGet(fetcher, token, path) {
  const response = await fetcher(`${api}${path}`, {
    method: "GET",
    redirect: "error",
    signal: AbortSignal.timeout(8e3),
    headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "X-GitHub-Api-Version": "2022-11-28" }
  });
  if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 3e6) throw new Error("GitHub account could not be verified.");
  const body = await response.text();
  if (body.length > 3e6) throw new Error("GitHub account could not be verified.");
  try {
    return object(JSON.parse(body));
  } catch {
    throw new Error("GitHub account could not be verified.");
  }
}
async function listGitHubRepositoryChoices(input) {
  if (isUntrustedBrowserRuntime() || !input.userToken || input.userToken.length > 4096 || !Number.isSafeInteger(input.page) || input.page < 1 || input.page > 10 || input.installationId !== void 0 && !numeric.test(input.installationId)) {
    throw new Error("GitHub repositories are unavailable.");
  }
  try {
    const fetcher = input.fetcher ?? fetch;
    const installations = [];
    let chosen;
    let installationHasMore = false;
    const last = input.installationId ? 10 : input.page;
    for (let page = 1; page <= last; page++) {
      const result2 = await githubGet(fetcher, input.userToken, `/user/installations?per_page=100&page=${page}`);
      if (!Array.isArray(result2.installations) || result2.installations.length > 100) throw new Error();
      if (page === input.page) installationHasMore = result2.installations.length === 100;
      for (const item of result2.installations.map(object)) {
        if (item.suspended_at || object(item.permissions).contents !== "write") continue;
        const account = object(item.account);
        const entry = { id: String(item.id), accountId: String(account.id), accountLogin: String(account.login) };
        if (!numeric.test(entry.id) || !numeric.test(entry.accountId) || !/^[a-zA-Z0-9-]{1,100}$/.test(entry.accountLogin)) throw new Error();
        if (entry.id === input.installationId) chosen = entry;
        if (!input.installationId && page === input.page) installations.push(entry);
      }
      if (result2.installations.length < 100) break;
    }
    if (!input.installationId) return { installations, repositories: [], hasMore: installationHasMore };
    if (!chosen) throw new Error();
    const result = await githubGet(
      fetcher,
      input.userToken,
      `/user/installations/${input.installationId}/repositories?per_page=100&page=${input.page}`
    );
    if (!Array.isArray(result.repositories) || result.repositories.length > 100) throw new Error();
    const repositories = result.repositories.map(object).filter((item) => !item.archived && !item.disabled && object(item.owner).id !== void 0 && String(object(item.owner).id) === chosen.accountId && object(item.permissions).push === true).map((item) => {
      const entry = { id: String(item.id), fullName: String(item.full_name), defaultBranch: String(item.default_branch) };
      if (!numeric.test(entry.id) || !repoName.test(entry.fullName) || !branch.test(entry.defaultBranch)) throw new Error();
      return entry;
    });
    return { installations: [chosen], repositories, hasMore: result.repositories.length === 100 };
  } catch {
    throw new Error("GitHub repositories are unavailable.");
  }
}
async function verifyGitHubInstallationRepository(input) {
  if (isUntrustedBrowserRuntime()) throw new Error("GitHub verification requires a server.");
  const { userToken, installationId, repositoryId } = input;
  if (!numeric.test(installationId) || !numeric.test(repositoryId) || !userToken || userToken.length > 4096) {
    throw new Error("GitHub account could not be verified.");
  }
  const fetcher = input.fetcher ?? fetch;
  try {
    let installation;
    for (let page = 1; page <= 10 && !installation; page++) {
      const result = await githubGet(fetcher, userToken, `/user/installations?per_page=100&page=${page}`);
      if (!Array.isArray(result.installations) || result.installations.length > 100) throw new Error();
      installation = result.installations.map(object).find((item) => String(item.id) === installationId);
      if (result.installations.length < 100) break;
    }
    if (!installation || installation.suspended_at || object(installation.permissions).contents !== "write") throw new Error();
    const account = object(installation.account);
    const accountId = String(account.id);
    if (!numeric.test(accountId) || typeof account.login !== "string" || !/^[a-zA-Z0-9-]{1,100}$/.test(account.login)) throw new Error();
    let repository;
    for (let page = 1; page <= 10 && !repository; page++) {
      const result = await githubGet(fetcher, userToken, `/user/installations/${installationId}/repositories?per_page=100&page=${page}`);
      if (!Array.isArray(result.repositories) || result.repositories.length > 100) throw new Error();
      repository = result.repositories.map(object).find((item) => String(item.id) === repositoryId);
      if (result.repositories.length < 100) break;
    }
    if (!repository || repository.archived || repository.disabled || object(repository.owner).id !== account.id || typeof repository.full_name !== "string" || !repoName.test(repository.full_name) || typeof repository.default_branch !== "string" || !branch.test(repository.default_branch) || object(repository.permissions).push !== true) throw new Error();
    return {
      installationId,
      accountId,
      accountLogin: account.login,
      repositoryId,
      repositoryFullName: repository.full_name,
      defaultBranch: repository.default_branch
    };
  } catch {
    throw new Error("GitHub account could not be verified.");
  }
}

// src/modules/website-builder/services/websiteGithubRepositoryBindingService.ts
var uuid3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function bindWebsiteGitHubRepository(input) {
  if (isUntrustedBrowserRuntime()) throw new Error("GitHub binding requires a trusted server.");
  if (!uuid3.test(input.ownerId) || !uuid3.test(input.projectId) || !uuid3.test(input.handoffId) || input.connectionId !== void 0 && !uuid3.test(input.connectionId) || input.expectedVersion !== void 0 && (!Number.isSafeInteger(input.expectedVersion) || input.expectedVersion < 1) || Boolean(input.connectionId) !== Boolean(input.expectedVersion) || !input.isCurrentOwner()) throw new Error("GitHub connection could not be verified.");
  const connectionId = input.connectionId ?? input.handoffId;
  const expectedVersion = input.expectedVersion ?? 0;
  const reconcile = async () => {
    const { data, error } = await input.client.rpc("website_reconcile_infrastructure_connection", {
      p_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_provider: "github",
      p_commit_id: input.handoffId,
      p_expected_version: expectedVersion,
      p_target_id: input.repositoryId
    });
    if (error || !input.isCurrentOwner()) throw new Error();
    if (!data) return null;
    if (data.connectionId !== connectionId || data.repositoryId !== input.repositoryId || data.version !== expectedVersion + 1 || !["preview", "production"].includes(data.environment)) throw new Error();
    return { connectionId, repositoryId: input.repositoryId, version: data.version };
  };
  try {
    const previouslyCommitted = await reconcile();
    if (previouslyCommitted) return previouslyCommitted;
    const grant = await consumeWebsiteConnectionHandoff({
      client: input.client,
      id: input.handoffId,
      ownerId: input.ownerId,
      projectId: input.projectId,
      provider: "github",
      isCurrentOwner: input.isCurrentOwner
    });
    if (!input.isCurrentOwner()) throw new Error();
    const observed = await verifyGitHubInstallationRepository({
      userToken: grant.userToken,
      installationId: input.installationId,
      repositoryId: input.repositoryId,
      fetcher: input.fetcher
    });
    if (!input.isCurrentOwner()) throw new Error();
    const { data, error } = await input.client.rpc("website_record_infrastructure_connection", {
      p_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_expected_version: expectedVersion,
      p_provider: "github",
      p_environment: grant.environment,
      p_account_id: observed.accountId,
      p_target_id: observed.repositoryId,
      p_permissions: ["contents:write"],
      p_status: "connected",
      p_operation_id: null,
      p_verified_at: (input.now ?? (() => (/* @__PURE__ */ new Date()).toISOString()))(),
      p_commit_id: input.handoffId
    });
    if (error || data !== expectedVersion + 1 || !input.isCurrentOwner()) {
      const committed = await reconcile();
      if (committed) return committed;
      throw new Error();
    }
    return {
      connectionId,
      repositoryId: observed.repositoryId,
      repositoryFullName: observed.repositoryFullName,
      version: data
    };
  } catch {
    throw new Error("GitHub connection could not be verified.");
  }
}

// server/website-github-connection.ts
var uuid4 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var state = /^[a-f0-9]{64}$/;
var code = /^[a-zA-Z0-9_-]{1,1024}$/;
var responseHeaders = { "cache-control": "no-store", "referrer-policy": "no-referrer", "content-security-policy": "default-src 'none'", "x-content-type-options": "nosniff" };
function json(status, body) {
  return new Response(JSON.stringify(body), { status, headers: { ...responseHeaders, "content-type": "application/json" } });
}
function fixedHttps(value, callback = false) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || (callback ? url.search !== "?action=callback" : !!url.search)) throw new Error();
  return url;
}
async function handleWebsiteGitHubConnection(request, context) {
  let callback, destination;
  try {
    callback = fixedHttps(context.callback, true);
    destination = fixedHttps(context.returnUrl);
    if (!callback.pathname.endsWith("/functions/v1/website-github-connection") || !/^[a-zA-Z0-9_]{5,100}$/.test(context.clientId) || !context.clientSecret) throw new Error();
  } catch {
    return json(503, { error: "GitHub connection is not configured." });
  }
  const action = new URL(request.url).searchParams.get("action");
  if (action === "callback") {
    if (request.method !== "GET") return json(405, { error: "Method not allowed." });
    const params = new URL(request.url).searchParams;
    if (params.has("error") || !state.test(params.get("state") ?? "") || !code.test(params.get("code") ?? "")) {
      return json(400, { error: "GitHub authorization failed. Start the connection again." });
    }
    try {
      const grant = await acceptGitHubOAuthCallback({
        stateClient: context.platform,
        state: params.get("state"),
        code: params.get("code"),
        clientId: context.clientId,
        clientSecret: context.clientSecret,
        callback: callback.toString(),
        fetcher: context.fetcher
      });
      const handoffId = await storeWebsiteConnectionHandoff({ client: context.platform, ...grant, provider: "github" });
      destination.hash = new URLSearchParams({ tayar_github_handoff: handoffId }).toString();
      return new Response(null, { status: 303, headers: { ...responseHeaders, location: destination.toString() } });
    } catch {
      return json(409, { error: "GitHub authorization could not be completed. Start the connection again." });
    }
  }
  if (!["begin", "options", "bind"].includes(action ?? "") || request.method !== "POST") return json(405, { error: "Method not allowed." });
  if (!/^application\/json(?:\s*;|$)/i.test(request.headers.get("content-type") ?? "")) return json(415, { error: "JSON request required." });
  const token = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/i.exec(request.headers.get("authorization") ?? "")?.[1];
  if (!token || token.length > 16384) return json(401, { error: "Sign in required." });
  let ownerId;
  try {
    const identity = await context.platform.auth.getUser(token);
    if (identity.error || !identity.data.user || identity.data.user.is_anonymous || !uuid4.test(identity.data.user.id)) throw new Error();
    ownerId = identity.data.user.id;
  } catch {
    return json(401, { error: "Sign in required." });
  }
  let projectId, input;
  try {
    if (Number(request.headers.get("content-length") ?? 0) > 4096) throw new Error();
    const body = await request.text();
    if (body.length > 4096) throw new Error();
    input = JSON.parse(body);
    const keys2 = action === "begin" ? ["projectId", "environment"] : action === "options" ? ["projectId", "handoffId", "installationId", "page"] : ["projectId", "handoffId", "installationId", "repositoryId", "connectionId", "expectedVersion"];
    if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).some((key) => !keys2.includes(key)) || typeof input.projectId !== "string" || !uuid4.test(input.projectId)) throw new Error();
    if (action === "begin" && !["preview", "production"].includes(String(input.environment))) throw new Error();
    if (action !== "begin" && (typeof input.handoffId !== "string" || !uuid4.test(input.handoffId))) throw new Error();
    projectId = input.projectId;
  } catch {
    return json(400, { error: "Invalid connection request." });
  }
  try {
    const { data, error } = await context.platform.from("projects").select("id").eq("id", projectId).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
    if (error) return json(503, { error: "Project is unavailable." });
    if (!data) return json(404, { error: "Project not found." });
    if (action === "begin") {
      const rawState = await createWebsiteConnectionOAuthState({
        client: context.platform,
        ownerId,
        projectId,
        environment: input.environment,
        provider: "github",
        isCurrentOwner: () => true
      });
      return json(200, { authorizationUrl: githubAuthorizationUrl({ clientId: context.clientId, callback: callback.toString(), state: rawState }) });
    }
    if (action === "options") {
      const grant = await peekWebsiteConnectionHandoff({
        client: context.platform,
        id: input.handoffId,
        ownerId,
        projectId,
        provider: "github",
        isCurrentOwner: () => true
      });
      const choices = await listGitHubRepositoryChoices({
        userToken: grant.userToken,
        installationId: input.installationId,
        page: input.page,
        fetcher: context.fetcher
      });
      return json(200, choices);
    }
    const result = await bindWebsiteGitHubRepository({
      client: context.platform,
      ownerId,
      projectId,
      handoffId: input.handoffId,
      installationId: input.installationId,
      repositoryId: input.repositoryId,
      connectionId: input.connectionId,
      expectedVersion: input.expectedVersion,
      isCurrentOwner: () => true,
      fetcher: context.fetcher
    });
    return json(200, { status: "connected", ...result });
  } catch {
    return json(409, { error: "GitHub connection could not be completed. Refresh and try again." });
  }
}

// server/website-github-connection-edge.ts
var client = /^[A-Za-z0-9_]{5,100}$/;
var publicSecret = /^(?:NEXT_PUBLIC_|VITE_|PUBLIC_).*?(?:SECRET|SERVICE_ROLE)/i;
var keys = {
  url: "SUPABASE_URL",
  secret: "SUPABASE_SERVICE_ROLE_KEY",
  clientId: "WEBSITE_GITHUB_APP_CLIENT_ID",
  clientSecret: "WEBSITE_GITHUB_APP_CLIENT_SECRET",
  callback: "WEBSITE_GITHUB_CALLBACK_URL",
  returnUrl: "WEBSITE_GITHUB_RETURN_URL"
};
var fixedHeaders = {
  "cache-control": "no-store",
  "referrer-policy": "no-referrer",
  "content-security-policy": "default-src 'none'",
  "x-content-type-options": "nosniff"
};
function required(environment, key, max) {
  const value = environment[key];
  if (typeof value !== "string" || !value || value.length > max || value.trim() !== value || value.includes(String.fromCharCode(0))) throw new Error();
  return value;
}
function platformUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== value || url.pathname !== "/" || url.port || url.username || url.password || url.search || url.hash || !/^[a-z0-9]{20}[.]supabase[.]co$/.test(url.hostname)) throw new Error();
  return url.origin;
}
function callbackUrl2(value, platformOrigin) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== platformOrigin || url.username || url.password || url.hash || url.search !== "?action=callback" || !url.pathname.endsWith("/functions/v1/website-github-connection")) throw new Error();
  return url.toString();
}
function browserReturn(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.username || url.password || url.hash || url.search) throw new Error();
  return { value: url.toString(), origin: url.origin };
}
function legacyServiceRole(value) {
  try {
    const parts = value.split(".");
    if (parts.length !== 3 || parts.some((part) => !part)) return false;
    const base = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const payload = JSON.parse(atob(base.padEnd(Math.ceil(base.length / 4) * 4, "=")));
    return !!payload && typeof payload === "object" && payload.role === "service_role";
  } catch {
    return false;
  }
}
function serviceKey(value) {
  if (/[\s\r\n]/.test(value) || value.length > 4096 || !/^sb_secret_[A-Za-z0-9_-]{20,}$/.test(value) && !legacyServiceRole(value)) throw new Error();
  return value;
}
function json2(status, error) {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { ...fixedHeaders, "content-type": "application/json" }
  });
}
function createWebsiteGitHubConnectionEdge(input) {
  try {
    if (input.fetcher !== void 0 && typeof input.fetcher !== "function") throw new Error();
    for (const [key, value] of Object.entries(input.environment)) if (value && publicSecret.test(key)) throw new Error();
    const url = platformUrl(required(input.environment, keys.url, 2048));
    const serviceRole = serviceKey(required(input.environment, keys.secret, 4096));
    const clientId = required(input.environment, keys.clientId, 100);
    const clientSecret = required(input.environment, keys.clientSecret, 4096);
    const callback = callbackUrl2(required(input.environment, keys.callback, 2048), url);
    const destination = browserReturn(required(input.environment, keys.returnUrl, 2048));
    if (!client.test(clientId) || clientSecret.length < 20 || /[\r\n]/.test(clientSecret)) throw new Error();
    const factory = input.clientFactory ?? createClient;
    const options = {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
      ...input.fetcher ? { global: { fetch: input.fetcher } } : {}
    };
    const platform = factory(url, serviceRole, options);
    return async (request) => {
      const origin = request.headers.get("origin");
      const headers = new Headers(fixedHeaders);
      headers.set("vary", "Origin");
      if (origin && origin !== destination.origin) return json2(403, "Origin not allowed.");
      if (origin) headers.set("access-control-allow-origin", origin);
      headers.set("access-control-allow-methods", "POST, GET, OPTIONS");
      headers.set("access-control-allow-headers", "authorization, apikey, content-type, x-client-info");
      if (request.method === "OPTIONS") return new Response(null, { status: 204, headers });
      try {
        const response = await handleWebsiteGitHubConnection(request, {
          platform,
          clientId,
          clientSecret,
          callback,
          returnUrl: destination.value,
          fetcher: input.fetcher
        });
        const combined = new Headers(response.headers);
        headers.forEach((value, key) => combined.set(key, value));
        return new Response(response.body, { status: response.status, headers: combined });
      } catch {
        return json2(503, "GitHub connection is unavailable.");
      }
    };
  } catch {
    throw new Error("GitHub connection deployment unavailable.");
  }
}
function createWebsiteGitHubConnectionDeployment(input) {
  try {
    return createWebsiteGitHubConnectionEdge(input);
  } catch {
    return async () => json2(503, "GitHub connection is unavailable.");
  }
}
export {
  createWebsiteGitHubConnectionDeployment,
  createWebsiteGitHubConnectionEdge
};
Deno.serve(createWebsiteGitHubConnectionDeployment({environment:{"SUPABASE_URL":Deno.env.get("SUPABASE_URL"),"SUPABASE_SERVICE_ROLE_KEY":Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),"WEBSITE_GITHUB_APP_CLIENT_ID":Deno.env.get("WEBSITE_GITHUB_APP_CLIENT_ID"),"WEBSITE_GITHUB_APP_CLIENT_SECRET":Deno.env.get("WEBSITE_GITHUB_APP_CLIENT_SECRET"),"WEBSITE_GITHUB_CALLBACK_URL":Deno.env.get("WEBSITE_GITHUB_CALLBACK_URL"),"WEBSITE_GITHUB_RETURN_URL":Deno.env.get("WEBSITE_GITHUB_RETURN_URL")}}));
