import { FileText } from 'lucide-react';
import { PageShell, PageSection } from './PageShell';

export default function TermsOfService() {
  return (
    <PageShell icon={FileText} title="Terms of Service" subtitle="Last updated: August 4, 2026">
      <PageSection title="1. Acceptance of Terms">
        <p>By accessing or using Tayar Intelligence Tools, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
      </PageSection>
      <PageSection title="2. Description of Service">
        <p>Tayar Intelligence Tools provides AI-powered tools for CV building, cover letter writing, document analysis, translation, study assistance, and content creation. We offer both free and premium subscription tiers.</p>
      </PageSection>
      <PageSection title="3. User Accounts">
        <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account and password. You must be at least 16 years old to use the platform.</p>
      </PageSection>
      <PageSection title="4. Acceptable Use">
        <p>You agree not to:</p>
        <p>- Use the platform for illegal or unauthorized purposes</p>
        <p>- Generate harmful, offensive, or misleading content</p>
        <p>- Attempt to access, tamper with, or disrupt our systems</p>
        <p>- Reverse engineer, decompile, or disassemble the platform</p>
        <p>- Share your account credentials with others</p>
        <p>- Use automated scripts or bots to access the platform</p>
      </PageSection>
      <PageSection title="5. AI-Generated Content">
        <p>Content generated by AI tools is provided for informational and assistance purposes only. You are responsible for reviewing and verifying all AI-generated content before use. We are not liable for any consequences of using AI-generated content.</p>
      </PageSection>
      <PageSection title="6. Subscriptions and Billing">
        <p>Premium subscriptions are billed monthly or annually. You can cancel at any time. Refunds are issued at our discretion within 14 days of a billing cycle. Prices may change with 30 days notice.</p>
      </PageSection>
      <PageSection title="7. Intellectual Property">
        <p>The platform, including its design, code, and branding, is owned by Tayar Intelligence Tools. Content you create using the platform belongs to you. AI-generated content is yours to use, subject to applicable laws.</p>
      </PageSection>
      <PageSection title="8. Limitation of Liability">
        <p>The platform is provided "as is" without warranties of any kind. We are not liable for indirect, incidental, or consequential damages. Our total liability shall not exceed the amount you paid in the preceding 12 months.</p>
      </PageSection>
      <PageSection title="9. Termination">
        <p>We may suspend or terminate your account for violations of these Terms. You may delete your account at any time through Settings.</p>
      </PageSection>
      <PageSection title="10. Contact">
        <p>For questions about these Terms, contact us at legal@tayar.ai</p>
      </PageSection>
    </PageShell>
  );
}
