// Generated by scripts/build-application-backend-link.mjs; edit the server/service source.
/* eslint-disable no-var, @typescript-eslint/no-unused-vars -- Generated bundler syntax; lint the original server/service modules. */

// server/website-application-backend-link.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.57.4";

// supabase/functions/_shared/billing.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
var HttpError = class extends Error {
  status;
  code;
  constructor(status, message, code = null) {
    super(message);
    this.status = status;
    this.code = code;
  }
};
function parseNamedSecret(envName) {
  const raw = Deno.env.get(envName);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    return parsed.default || Object.values(parsed)[0] || null;
  } catch {
    return null;
  }
}
function getSupabaseUrl() {
  const value = Deno.env.get("SUPABASE_URL");
  if (!value) throw new HttpError(500, "SUPABASE_URL is not configured");
  return value;
}
function getSecretKey() {
  const value = parseNamedSecret("SUPABASE_SECRET_KEYS") || Deno.env.get("SUPABASE_SECRET_KEY") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!value) throw new HttpError(500, "Supabase secret key is not configured");
  return value;
}

// src/modules/website-builder/core/application-model.ts
var APPLICATION_LIMITS = { tables: 50, fields: 80, roles: 30, permissions: 120, pageAccess: 100 };
var APPLICATION_SYSTEM_FIELDS = ["id", "owner_id", "created_at", "updated_at"];
function createApplicationDefinition() {
  return { version: 1, tables: [], roles: [], auth: { enabled: false, signUpEnabled: false, emailVerificationRequired: true }, pageAccess: [] };
}

// src/modules/website-builder/core/application-validation.ts
var object = (value) => !!value && typeof value === "object" && !Array.isArray(value);
var identifier = (value) => typeof value === "string" && /^[a-z][a-z0-9_]{0,47}$/.test(value);
var id = (value) => typeof value === "string" && /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,119}$/.test(value);
var name = (value) => typeof value === "string" && value.trim().length > 0 && value.length <= 160;
function validateApplicationDefinition(value, pageIds) {
  const issues = [];
  const issue = (path, code, message) => issues.push({ path, code, message });
  function shape(item, keys, path) {
    if (!object(item)) {
      issue(path, "invalid-object", "Expected an application configuration object.");
      return false;
    }
    if (Object.keys(item).some((key) => !keys.includes(key))) issue(path, "unknown-property", "Unsupported configuration property; credentials and runtime data cannot be stored here.");
    return true;
  }
  function list(input, limit, path) {
    if (!Array.isArray(input) || input.length > limit) {
      issue(path, "invalid-list", `Expected a list with at most ${limit} items.`);
      return [];
    }
    return input;
  }
  if (!shape(value, ["version", "tables", "roles", "auth", "pageAccess"], "application")) return issues;
  if (value.version !== 1) issue("application.version", "unsupported-version", "Unsupported application schema version. Keep the source project and use a compatible editor.");
  const tables = list(value.tables, APPLICATION_LIMITS.tables, "application.tables");
  const roles = list(value.roles, APPLICATION_LIMITS.roles, "application.roles");
  const tableIds = /* @__PURE__ */ new Set();
  const roleIds = /* @__PURE__ */ new Set();
  const allIds = /* @__PURE__ */ new Set();
  const tableKeys = /* @__PURE__ */ new Set();
  function identity(candidate, path, bucket) {
    if (!id(candidate) || allIds.has(candidate)) {
      issue(path, "invalid-id", "IDs must be valid and globally unique within the application definition.");
      return;
    }
    allIds.add(candidate);
    bucket?.add(candidate);
  }
  roles.forEach((role, index) => {
    const path = `application.roles[${index}]`;
    if (!shape(role, ["id", "name"], path)) return;
    identity(role.id, `${path}.id`, roleIds);
    if (!name(role.name)) issue(`${path}.name`, "invalid-name", "A role requires a display name.");
  });
  const auth = value.auth;
  if (shape(auth, ["enabled", "signUpEnabled", "emailVerificationRequired"], "application.auth")) {
    for (const key of ["enabled", "signUpEnabled", "emailVerificationRequired"]) if (typeof auth[key] !== "boolean") issue(`application.auth.${key}`, "invalid-boolean", "Expected a boolean setting.");
    if (auth.signUpEnabled && !auth.enabled) issue("application.auth", "auth-disabled", "Enable authentication before allowing registration.");
  }
  const authEnabled = object(auth) && auth.enabled === true;
  tables.forEach((table, index) => {
    const path = `application.tables[${index}]`;
    if (!shape(table, ["id", "key", "name", "fields", "permissions"], path)) return;
    identity(table.id, `${path}.id`, tableIds);
    if (!identifier(table.key) || tableKeys.has(table.key) || table.key.startsWith("tayar_") || table.key === "user_roles") issue(`${path}.key`, "invalid-key", "Table keys must be unique lower-case identifiers outside reserved namespaces.");
    else tableKeys.add(table.key);
    if (!name(table.name)) issue(`${path}.name`, "invalid-name", "A table requires a display name.");
  });
  function access(rule, path, allowOwner) {
    const allowed = allowOwner ? ["public", "authenticated", "owner", "role"] : ["public", "authenticated", "role"];
    if (!allowed.includes(String(rule.access))) issue(`${path}.access`, "invalid-access", "Unsupported access rule.");
    if (rule.access !== "public" && !authEnabled) issue(path, "auth-disabled", "Authentication is required for this permission.");
    if (rule.access === "role" && !roleIds.has(String(rule.roleId))) issue(`${path}.roleId`, "missing-role", "Select an existing application role.");
    if (rule.access !== "role" && rule.roleId !== void 0) issue(`${path}.roleId`, "unexpected-role", "Role restrictions require role-based access.");
  }
  tables.forEach((table, tableIndex) => {
    if (!object(table)) return;
    const path = `application.tables[${tableIndex}]`;
    const keys = new Set(APPLICATION_SYSTEM_FIELDS);
    list(table.fields, APPLICATION_LIMITS.fields, `${path}.fields`).forEach((field, fieldIndex) => {
      const fieldPath = `${path}.fields[${fieldIndex}]`;
      if (!shape(field, ["id", "key", "name", "type", "required", "unique", "indexed", "defaultValue", "options", "referenceTableId"], fieldPath)) return;
      identity(field.id, `${fieldPath}.id`);
      if (!identifier(field.key) || keys.has(field.key)) issue(`${fieldPath}.key`, "invalid-key", "Field keys must be unique lower-case identifiers and cannot replace system fields.");
      else keys.add(field.key);
      if (!name(field.name)) issue(`${fieldPath}.name`, "invalid-name", "A field requires a display name.");
      if (!["text", "number", "boolean", "date", "datetime", "uuid", "json", "enum", "reference"].includes(String(field.type))) issue(`${fieldPath}.type`, "invalid-type", "Unsupported field type.");
      if (typeof field.required !== "boolean" || ["unique", "indexed"].some((key) => field[key] !== void 0 && typeof field[key] !== "boolean")) issue(fieldPath, "invalid-boolean", "Field constraint flags must be booleans.");
      if (field.type === "reference" && !tableIds.has(String(field.referenceTableId))) issue(fieldPath, "missing-table", "A relationship requires an existing target table.");
      if (field.type !== "reference" && field.referenceTableId !== void 0) issue(fieldPath, "unexpected-reference", "Only reference fields can target a table.");
      if (field.type === "enum") {
        if (!Array.isArray(field.options) || field.options.length < 1 || field.options.length > 100 || field.options.some((item) => typeof item !== "string" || !item || item.length > 200) || new Set(field.options).size !== field.options.length) issue(fieldPath, "invalid-options", "An enum requires 1\u2013100 unique nonempty options.");
      } else if (field.options !== void 0) issue(fieldPath, "unexpected-options", "Only enum fields can define options.");
      const def = field.defaultValue;
      if (def !== void 0) {
        const validDefault = def === null ? !field.required : field.type === "number" ? typeof def === "number" && Number.isFinite(def) : field.type === "boolean" ? typeof def === "boolean" : field.type === "text" ? typeof def === "string" && def.length <= 4e3 : field.type === "enum" ? Array.isArray(field.options) && field.options.includes(def) : false;
        if (!validDefault) issue(`${fieldPath}.defaultValue`, "invalid-default", "The default must match the field type. Computed, relationship and structured defaults are not accepted.");
      }
    });
    const permissionKeys = /* @__PURE__ */ new Set();
    list(table.permissions, APPLICATION_LIMITS.permissions, `${path}.permissions`).forEach((permission, index) => {
      const permissionPath = `${path}.permissions[${index}]`;
      if (!shape(permission, ["operation", "access", "roleId"], permissionPath)) return;
      if (!["read", "create", "update", "delete"].includes(String(permission.operation))) issue(permissionPath, "invalid-operation", "Unsupported database operation.");
      access(permission, permissionPath, true);
      if (permission.access === "public" && permission.operation !== "read") issue(permissionPath, "public-write", "Anonymous database writes require a validated server action.");
      const key = `${permission.operation}:${permission.access}:${permission.roleId ?? ""}`;
      if (permissionKeys.has(key)) issue(permissionPath, "duplicate-permission", "Duplicate permission rule.");
      permissionKeys.add(key);
    });
    if (Array.isArray(table.permissions) && table.permissions.some((p) => object(p) && ["update", "delete"].includes(String(p.operation))) && !table.permissions.some((p) => object(p) && p.operation === "read")) issue(`${path}.permissions`, "read-required", "Update and delete require a read policy.");
  });
  const protectedPages = /* @__PURE__ */ new Set();
  list(value.pageAccess, APPLICATION_LIMITS.pageAccess, "application.pageAccess").forEach((rule, index) => {
    const path = `application.pageAccess[${index}]`;
    if (!shape(rule, ["pageId", "access", "roleId"], path)) return;
    if (!id(rule.pageId) || protectedPages.has(rule.pageId) || pageIds && !pageIds.has(rule.pageId)) issue(path, "invalid-page", "Access rules require a unique existing page.");
    else protectedPages.add(rule.pageId);
    access(rule, path, false);
  });
  return issues;
}
function readApplicationDefinition(value, pageIds) {
  if (value === void 0) return createApplicationDefinition();
  const issues = validateApplicationDefinition(value, pageIds);
  if (issues.length) throw new Error(issues.map((item) => `${item.path}: ${item.message}`).join("\n"));
  return structuredClone(value);
}

// src/modules/website-builder/core/application-data-runtime.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.57.4";
function projectRef(url) {
  const parsed = new URL(url);
  const match = /^([a-z0-9]{20})\.supabase\.co$/.exec(parsed.hostname);
  if (parsed.protocol !== "https:" || !match || parsed.username || parsed.password || parsed.port || parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("Generated applications require a dedicated HTTPS Supabase project URL.");
  }
  return match[1];
}
function publicKey(key, ref) {
  if (/^sb_publishable_[A-Za-z0-9_-]+$/.test(key)) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    const body = JSON.parse(atob(parts[1].replace(/-/g, "+").replace(/_/g, "/")));
    return body.role === "anon" && body.ref === ref && body.iss === "supabase";
  } catch {
    return false;
  }
}
function validateApplicationPublicBackend(config, platformUrl) {
  const ref = projectRef(config.url);
  if (ref !== config.projectRef || ref === projectRef(platformUrl)) throw new Error("Application backend identity does not match its dedicated project.");
  if (!publicKey(config.publishableKey, ref)) throw new Error("Application backend requires a public anon or publishable key for this project.");
}

// src/modules/website-builder/core/application-backend-verification.ts
function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
  return JSON.stringify(value) ?? "undefined";
}
async function assertApplicationBackendRevision(definition, backend, platformUrl, reader) {
  validateApplicationPublicBackend(backend, platformUrl);
  if (reader.url !== backend.url) throw new Error("Application revision reader targets another backend.");
  const expected = readApplicationDefinition(definition);
  let deployed;
  try {
    deployed = readApplicationDefinition(await reader.readDeployedDefinition());
  } catch {
    throw new Error("Application backend revision could not be verified.");
  }
  if (canonical(deployed) !== canonical(expected)) throw new Error("Application backend schema revision does not match the project.");
}
async function applicationDefinitionDigest(definition) {
  const bytes = new TextEncoder().encode(canonical(readApplicationDefinition(definition)));
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

// src/modules/website-builder/services/websiteApplicationAuthSettingsService.ts
async function assertDedicatedApplicationAuthSettings(definition, config, platformUrl) {
  if (typeof window !== "undefined") throw new Error("Backend authentication verification requires a server runtime.");
  const backend = { ...config };
  validateApplicationPublicBackend(backend, platformUrl);
  const app = readApplicationDefinition(definition);
  let settings;
  try {
    const response2 = await fetch(`${backend.url}/auth/v1/settings`, {
      headers: { apikey: backend.publishableKey, Accept: "application/json" },
      redirect: "error",
      cache: "no-store",
      signal: AbortSignal.timeout(1e4)
    });
    if (!response2.ok) throw new Error();
    const body = await response2.text();
    if (body.length > 65536) throw new Error();
    const raw = JSON.parse(body);
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error();
    settings = raw;
  } catch {
    throw new Error("Dedicated application authentication settings are unavailable.");
  }
  const providers = settings.external;
  if (!providers || typeof providers !== "object" || Array.isArray(providers) || typeof settings.disable_signup !== "boolean" || typeof settings.mailer_autoconfirm !== "boolean") {
    throw new Error("Dedicated application authentication settings are invalid.");
  }
  const external = providers;
  if (external.email !== app.auth.enabled || external.anonymous_users !== false || settings.disable_signup !== !app.auth.signUpEnabled || app.auth.enabled && settings.mailer_autoconfirm !== !app.auth.emailVerificationRequired || Object.entries(external).some(([provider, enabled]) => typeof enabled !== "boolean" || provider !== "email" && enabled) || ["saml_enabled", "passkeys_enabled"].some((key) => settings[key] !== void 0 && settings[key] !== false)) {
    throw new Error("Dedicated application authentication settings do not match the project.");
  }
}

// src/modules/website-builder/services/websiteApplicationBackendService.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.57.4";
function isDedicatedServiceKey(key, ref) {
  if (/^sb_secret_[A-Za-z0-9_-]+$/.test(key)) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    const claims = JSON.parse(atob(parts[1].replace(/-/g, "+").replace(/_/g, "/")));
    return claims.role === "service_role" && claims.ref === ref && claims.iss === "supabase";
  } catch {
    return false;
  }
}
function createDedicatedApplicationRevisionReader(backend, platformUrl, serviceKey) {
  if (typeof window !== "undefined") throw new Error("Application service credentials require a server runtime.");
  validateApplicationPublicBackend(backend, platformUrl);
  if (!isDedicatedServiceKey(serviceKey, backend.projectRef)) throw new Error("A dedicated backend service credential is required.");
  const backendUrl = backend.url;
  const client = createClient3(backendUrl, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
    global: {
      fetch: (input, init) => {
        const target = input instanceof Request ? input.url : String(input);
        if (target !== `${backendUrl}/rest/v1/rpc/app_deployed_definition` && target !== `${backendUrl}/rest/v1/rpc/app_form_request_revision`) {
          throw new Error("Unexpected application revision endpoint.");
        }
        return fetch(input, { ...init, redirect: "error", signal: AbortSignal.timeout(1e4) });
      }
    }
  });
  return {
    url: backendUrl,
    async readDeployedDefinition() {
      try {
        const { data, error } = await client.rpc("app_deployed_definition");
        if (error || !data) throw new Error();
        return data;
      } catch {
        throw new Error("Dedicated application revision is unavailable.");
      }
    },
    async readFormRequestRevision() {
      try {
        const { data, error } = await client.rpc("app_form_request_revision");
        if (error || data !== 1) throw new Error();
        return data;
      } catch {
        throw new Error("Dedicated application request capability is unavailable.");
      }
    }
  };
}

// src/modules/website-builder/services/websiteApplicationBackendLinkService.ts
var uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var response = (status, body) => new Response(JSON.stringify(body), {
  status,
  headers: { "content-type": "application/json", "cache-control": "no-store" }
});
async function readBoundedJson(request, limit = 32768) {
  if (Number(request.headers.get("content-length")) > limit || !request.body) throw new Error();
  const reader = request.body.getReader();
  const chunks = [];
  let length = 0;
  try {
    for (; ; ) {
      const { value, done } = await reader.read();
      if (done) break;
      length += value.byteLength;
      if (length > limit) {
        await reader.cancel();
        throw new Error();
      }
      chunks.push(value);
    }
  } finally {
    reader.releaseLock();
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes));
}
async function handleWebsiteApplicationBackendLink(request, context) {
  if (typeof window !== "undefined") throw new Error("Backend linking requires a server runtime.");
  if (request.method !== "POST") return response(405, { error: "Method not allowed." });
  if (!/^application\/json(?:\s*;|$)/i.test(request.headers.get("content-type") ?? "")) return response(415, { error: "JSON request required." });
  const token = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/i.exec(request.headers.get("authorization") ?? "")?.[1];
  if (!token || token.length > 16384) return response(401, { error: "Sign in required." });
  const { platform, platformUrl } = context;
  let ownerId;
  try {
    const { data, error } = await platform.auth.getUser(token);
    if (error || !data.user || data.user.is_anonymous || !uuid.test(data.user.id)) return response(401, { error: "Sign in required." });
    ownerId = data.user.id;
  } catch {
    return response(401, { error: "Sign in required." });
  }
  let projectId;
  let backend;
  let serviceKey;
  let expectedRevision;
  try {
    const value = await readBoundedJson(request);
    if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error();
    const body = value;
    if (Object.keys(body).some((key) => !["projectId", "backend", "serviceKey", "expectedRevision"].includes(key)) || typeof body.projectId !== "string" || !uuid.test(body.projectId)) throw new Error();
    if (!body.backend || typeof body.backend !== "object" || Array.isArray(body.backend)) throw new Error();
    const config = body.backend;
    if (Object.keys(config).some((key) => !["url", "projectRef", "publishableKey"].includes(key)) || typeof config.url !== "string" || typeof config.projectRef !== "string" || typeof config.publishableKey !== "string") throw new Error();
    if (typeof body.serviceKey !== "string" || body.serviceKey.length < 20 || body.serviceKey.length > 16384 || /\s/.test(body.serviceKey)) throw new Error();
    if (typeof body.expectedRevision !== "string" || !/^[a-f0-9]{64}$/.test(body.expectedRevision)) throw new Error();
    expectedRevision = body.expectedRevision;
    projectId = body.projectId;
    backend = { url: config.url, projectRef: config.projectRef, publishableKey: config.publishableKey };
    serviceKey = body.serviceKey;
    validateApplicationPublicBackend(backend, platformUrl);
  } catch {
    return response(400, { error: "Invalid application backend request." });
  }
  try {
    const { data: project, error } = await platform.from("projects").select("content").eq("id", projectId).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
    if (error) return response(503, { error: "Project is unavailable." });
    if (!project) return response(404, { error: "Project not found." });
    if (!project.content?.application) return response(409, { error: "Save an application definition before linking its backend." });
    const definition = readApplicationDefinition(project.content.application);
    if (await applicationDefinitionDigest(definition) !== expectedRevision) return response(409, { error: "Save and refresh the application before linking its backend." });
    const reader = createDedicatedApplicationRevisionReader(backend, platformUrl, serviceKey);
    await Promise.all([
      assertApplicationBackendRevision(definition, backend, platformUrl, reader),
      assertDedicatedApplicationAuthSettings(definition, backend, platformUrl)
    ]);
    const result = await platform.rpc("website_link_application_backend", {
      p_project_id: projectId,
      p_owner_id: ownerId,
      p_backend_ref: backend.projectRef,
      p_publishable_key: backend.publishableKey,
      p_deployed_definition: definition,
      p_service_key: serviceKey
    });
    if (result.error) return response(409, { error: "Backend link could not be committed. Verify the saved project and backend ownership." });
    return response(200, { status: "linked", backend });
  } catch {
    return response(409, { error: "Application backend could not be verified or linked." });
  }
}

// server/website-application-backend-link.ts
Deno.serve(async (request) => {
  const origin = request.headers.get("origin");
  const allowedOrigins = new Set((Deno.env.get("WEBSITE_BACKEND_LINK_ORIGINS") ?? "https://tayar.se,https://www.tayar.se").split(",").map((value) => value.trim()).filter(Boolean));
  const headers = new Headers({ "cache-control": "no-store", "vary": "Origin" });
  const reply = (status, message) => new Response(JSON.stringify({ error: message }), { status, headers });
  headers.set("content-type", "application/json");
  if (origin && !allowedOrigins.has(origin)) return reply(403, "Origin not allowed.");
  if (origin) headers.set("access-control-allow-origin", origin);
  headers.set("access-control-allow-methods", "POST, OPTIONS");
  headers.set("access-control-allow-headers", "authorization, apikey, content-type, x-client-info");
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers });
  if (request.method !== "POST") return reply(405, "Method not allowed.");
  try {
    const platformUrl = getSupabaseUrl();
    const platform = createClient4(platformUrl, getSecretKey(), {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
      global: {
        fetch: async (resource, init) => {
          try {
            const url = resource instanceof Request ? resource.url : String(resource);
            if (new URL(url).origin !== new URL(platformUrl).origin) throw new Error();
            return await fetch(resource, { ...init, redirect: "error", signal: AbortSignal.timeout(15e3) });
          } catch {
            return new Response(JSON.stringify({ message: "Platform request unavailable." }), {
              status: 503,
              headers: { "content-type": "application/json" }
            });
          }
        }
      }
    });
    const result = await handleWebsiteApplicationBackendLink(request, { platform, platformUrl });
    const resultHeaders = new Headers(result.headers);
    headers.forEach((value, key) => resultHeaders.set(key, value));
    return new Response(result.body, { status: result.status, headers: resultHeaders });
  } catch {
    return reply(503, "Application backend linking is unavailable.");
  }
});
