// Generated by scripts/build-application-backend-link.mjs; edit the server/service source.
/* eslint-disable no-var, @typescript-eslint/no-unused-vars -- Generated bundler syntax; lint the original server/service modules. */

// server/website-application-backend-link.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@2.57.4";

// supabase/functions/_shared/billing.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
var HttpError = class extends Error {
  status;
  code;
  constructor(status, message, code = null) {
    super(message);
    this.status = status;
    this.code = code;
  }
};
function parseNamedSecret(envName) {
  const raw = Deno.env.get(envName);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    return parsed.default || Object.values(parsed)[0] || null;
  } catch {
    return null;
  }
}
function getSupabaseUrl() {
  const value = Deno.env.get("SUPABASE_URL");
  if (!value) throw new HttpError(500, "SUPABASE_URL is not configured");
  return value;
}
function getSecretKey() {
  const value = parseNamedSecret("SUPABASE_SECRET_KEYS") || Deno.env.get("SUPABASE_SECRET_KEY") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!value) throw new HttpError(500, "Supabase secret key is not configured");
  return value;
}

// src/modules/website-builder/core/application-files.ts
var APPLICATION_FILE_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/webp",
  "text/plain",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
];
var APPLICATION_FILE_MAX_BYTES = 25 * 1024 * 1024;

// src/modules/website-builder/core/application-email-notifications.ts
var identifier = /^[A-Za-z0-9][A-Za-z0-9_-]{0,119}$/;
var object = (value) => !!value && typeof value === "object" && !Array.isArray(value);
function applicationEmailTemplateParts(value, fields) {
  const parts = [];
  let cursor = 0;
  for (const match of value.matchAll(/\{\{(record\.id|field:([A-Za-z0-9][A-Za-z0-9_-]{0,119}))\}\}/g)) {
    const preceding = value.slice(cursor, match.index);
    if (preceding.includes("{{") || preceding.includes("}}")) throw new Error("Unknown email template variable.");
    if (preceding) parts.push({ literal: preceding });
    if (match[1] === "record.id") parts.push({ recordId: true });
    else {
      const field = fields.find((field2) => field2.id === match[2]);
      if (!field || field.type === "json") throw new Error("Unknown email template field.");
      parts.push({ field });
    }
    cursor = match.index + match[0].length;
  }
  const remainder = value.slice(cursor);
  if (remainder.includes("{{") || remainder.includes("}}")) throw new Error("Unknown email template variable.");
  if (remainder) parts.push({ literal: remainder });
  if (parts.length > 100) throw new Error("Email template too large.");
  return parts;
}
function validateApplicationEmailNotification(value, table) {
  if (!object(value) || Object.keys(value).sort().join(",") !== "connectionId,event,id,subject,text" || typeof value.id !== "string" || !identifier.test(value.id) || typeof value.connectionId !== "string" || !identifier.test(value.connectionId) || typeof value.subject !== "string" || !value.subject.trim() || value.subject.length > 200 || Array.from(value.subject).some((character) => character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127) || typeof value.text !== "string" || !value.text.trim() || value.text.length > 16e3 || value.text.includes("\0")) return "Invalid email notification rule.";
  if (!table.permissions.some((permission) => permission.operation === "read" && permission.access === "owner")) return "Email recipients require owner read access.";
  const event = value.event;
  if (!object(event)) return "Unknown email notification event.";
  if (event.type === "created" && Object.keys(event).join(",") === "type") {
    if (!table.permissions.some((permission) => permission.operation === "create" && permission.access !== "public")) return "Email source write unavailable.";
  } else if (event.type === "transition" && Object.keys(event).sort().join(",") === "transitionId,type") {
    const transition = table.workflow?.transitions.find((item) => item.id === event.transitionId);
    if (!transition) return "Unknown email workflow transition.";
    if (table.workflow.transitions.some((other) => other.id !== transition.id && other.to === transition.to && other.from.some((state) => transition.from.includes(state)))) return "Email source transition is ambiguous.";
  } else return "Unknown email notification event.";
  try {
    applicationEmailTemplateParts(value.subject, table.fields);
    applicationEmailTemplateParts(value.text, table.fields);
  } catch (error) {
    return error instanceof Error ? error.message : "Invalid email notification rule.";
  }
  return null;
}

// src/modules/website-builder/core/application-model.ts
var APPLICATION_LIMITS = { tables: 50, fields: 80, roles: 30, permissions: 120, pageAccess: 100, requirements: 100, requirementEvidence: 20 };
var APPLICATION_SYSTEM_FIELDS = ["id", "owner_id", "created_at", "updated_at"];
function createApplicationDefinition() {
  return { version: 1, tables: [], roles: [], auth: { enabled: false, signUpEnabled: false, emailVerificationRequired: true }, pageAccess: [] };
}

// src/modules/website-builder/core/application-validation.ts
var object2 = (value) => !!value && typeof value === "object" && !Array.isArray(value);
var identifier2 = (value) => typeof value === "string" && /^[a-z][a-z0-9_]{0,47}$/.test(value);
var id = (value) => typeof value === "string" && /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,119}$/.test(value);
var name = (value) => typeof value === "string" && value.trim().length > 0 && value.length <= 160;
function validateApplicationDefinition(value, pageIds) {
  const issues = [];
  const issue = (path, code, message) => issues.push({ path, code, message });
  function shape(item, keys, path) {
    if (!object2(item)) {
      issue(path, "invalid-object", "Expected an application configuration object.");
      return false;
    }
    if (Object.keys(item).some((key) => !keys.includes(key))) issue(path, "unknown-property", "Unsupported configuration property; credentials and runtime data cannot be stored here.");
    return true;
  }
  function list(input, limit, path) {
    if (!Array.isArray(input) || input.length > limit) {
      issue(path, "invalid-list", `Expected a list with at most ${limit} items.`);
      return [];
    }
    return input;
  }
  if (!shape(value, ["version", "tables", "roles", "auth", "pageAccess", "requirements"], "application")) return issues;
  if (value.version !== 1) issue("application.version", "unsupported-version", "Unsupported application schema version. Keep the source project and use a compatible editor.");
  const tables = list(value.tables, APPLICATION_LIMITS.tables, "application.tables");
  const roles = list(value.roles, APPLICATION_LIMITS.roles, "application.roles");
  const tableIds = /* @__PURE__ */ new Set();
  const roleIds = /* @__PURE__ */ new Set();
  const allIds = /* @__PURE__ */ new Set();
  const tableKeys = /* @__PURE__ */ new Set();
  function identity(candidate, path, bucket) {
    if (!id(candidate) || allIds.has(candidate)) {
      issue(path, "invalid-id", "IDs must be valid and globally unique within the application definition.");
      return;
    }
    allIds.add(candidate);
    bucket?.add(candidate);
  }
  roles.forEach((role, index) => {
    const path = `application.roles[${index}]`;
    if (!shape(role, ["id", "name"], path)) return;
    identity(role.id, `${path}.id`, roleIds);
    if (!name(role.name)) issue(`${path}.name`, "invalid-name", "A role requires a display name.");
  });
  const auth = value.auth;
  if (shape(auth, ["enabled", "signUpEnabled", "emailVerificationRequired"], "application.auth")) {
    for (const key of ["enabled", "signUpEnabled", "emailVerificationRequired"]) if (typeof auth[key] !== "boolean") issue(`application.auth.${key}`, "invalid-boolean", "Expected a boolean setting.");
    if (auth.signUpEnabled && !auth.enabled) issue("application.auth", "auth-disabled", "Enable authentication before allowing registration.");
  }
  const authEnabled = object2(auth) && auth.enabled === true;
  tables.forEach((table, index) => {
    const path = `application.tables[${index}]`;
    if (!shape(table, ["id", "key", "name", "fields", "permissions", "booking", "counter", "transaction", "workflow", "attachments", "notifications"], path)) return;
    identity(table.id, `${path}.id`, tableIds);
    if (!identifier2(table.key) || tableKeys.has(table.key) || table.key.startsWith("tayar_") || table.key === "user_roles") issue(`${path}.key`, "invalid-key", "Table keys must be unique lower-case identifiers outside reserved namespaces.");
    else tableKeys.add(table.key);
    if (!name(table.name)) issue(`${path}.name`, "invalid-name", "A table requires a display name.");
  });
  function access(rule, path, allowOwner) {
    const allowed = allowOwner ? ["public", "authenticated", "owner", "role"] : ["public", "authenticated", "role"];
    if (!allowed.includes(String(rule.access))) issue(`${path}.access`, "invalid-access", "Unsupported access rule.");
    if (rule.access !== "public" && !authEnabled) issue(path, "auth-disabled", "Authentication is required for this permission.");
    if (rule.access === "role" && !roleIds.has(String(rule.roleId))) issue(`${path}.roleId`, "missing-role", "Select an existing application role.");
    if (rule.access !== "role" && rule.roleId !== void 0) issue(`${path}.roleId`, "unexpected-role", "Role restrictions require role-based access.");
  }
  tables.forEach((table, tableIndex) => {
    if (!object2(table)) return;
    const path = `application.tables[${tableIndex}]`;
    const keys = new Set(APPLICATION_SYSTEM_FIELDS);
    list(table.fields, APPLICATION_LIMITS.fields, `${path}.fields`).forEach((field, fieldIndex) => {
      const fieldPath = `${path}.fields[${fieldIndex}]`;
      if (!shape(field, ["id", "key", "name", "type", "required", "unique", "indexed", "defaultValue", "options", "referenceTableId", "formula"], fieldPath)) return;
      identity(field.id, `${fieldPath}.id`);
      if (!identifier2(field.key) || keys.has(field.key)) issue(`${fieldPath}.key`, "invalid-key", "Field keys must be unique lower-case identifiers and cannot replace system fields.");
      else keys.add(field.key);
      if (!name(field.name)) issue(`${fieldPath}.name`, "invalid-name", "A field requires a display name.");
      if (!["text", "number", "boolean", "date", "datetime", "uuid", "json", "enum", "reference"].includes(String(field.type))) issue(`${fieldPath}.type`, "invalid-type", "Unsupported field type.");
      if (typeof field.required !== "boolean" || ["unique", "indexed"].some((key) => field[key] !== void 0 && typeof field[key] !== "boolean")) issue(fieldPath, "invalid-boolean", "Field constraint flags must be booleans.");
      if (field.type === "reference" && !tableIds.has(String(field.referenceTableId))) issue(fieldPath, "missing-table", "A relationship requires an existing target table.");
      if (field.type !== "reference" && field.referenceTableId !== void 0) issue(fieldPath, "unexpected-reference", "Only reference fields can target a table.");
      if (field.formula !== void 0) {
        const formulaPath = `${fieldPath}.formula`, formula = field.formula;
        if (!shape(formula, ["operation", "fieldIds"], formulaPath) || field.type !== "number" || field.required !== true || field.defaultValue !== void 0 || !["sum", "subtract", "multiply"].includes(String(formula.operation)) || !Array.isArray(formula.fieldIds) || formula.fieldIds.length < 2 || formula.fieldIds.length > 20 || formula.operation !== "sum" && formula.fieldIds.length !== 2 || new Set(formula.fieldIds).size !== formula.fieldIds.length || formula.fieldIds.some((sourceId) => sourceId === field.id || !table.fields.some((source) => object2(source) && source.id === sourceId && source.type === "number" && source.required === true && source.formula === void 0))) {
          issue(formulaPath, "invalid-formula", "A formula needs a required numeric result and 2\u201320 distinct required numeric source fields.");
        }
      }
      if (field.type === "enum") {
        if (!Array.isArray(field.options) || field.options.length < 1 || field.options.length > 100 || field.options.some((item) => typeof item !== "string" || !item || item.length > 200) || new Set(field.options).size !== field.options.length) issue(fieldPath, "invalid-options", "An enum requires 1\u2013100 unique nonempty options.");
      } else if (field.options !== void 0) issue(fieldPath, "unexpected-options", "Only enum fields can define options.");
      const def = field.defaultValue;
      if (def !== void 0) {
        const validDefault = def === null ? !field.required : field.type === "number" ? typeof def === "number" && Number.isFinite(def) : field.type === "boolean" ? typeof def === "boolean" : field.type === "text" ? typeof def === "string" && def.length <= 4e3 : field.type === "enum" ? Array.isArray(field.options) && field.options.includes(def) : false;
        if (!validDefault) issue(`${fieldPath}.defaultValue`, "invalid-default", "The default must match the field type. Computed, relationship and structured defaults are not accepted.");
      }
    });
    if (table.booking !== void 0) {
      const bookingPath = `${path}.booking`;
      if (shape(table.booking, ["resourceFieldId", "startFieldId", "endFieldId", "statusFieldId", "blockingStatuses"], bookingPath)) {
        const rule = table.booking;
        const fields = Array.isArray(table.fields) ? table.fields.filter(object2) : [];
        const find = (fieldId) => fields.find((field) => field.id === fieldId);
        const resource = find(rule.resourceFieldId), start = find(rule.startFieldId), end = find(rule.endFieldId);
        if (!authEnabled || !id(rule.resourceFieldId) || !id(rule.startFieldId) || !id(rule.endFieldId) || (/* @__PURE__ */ new Set([rule.resourceFieldId, rule.startFieldId, rule.endFieldId])).size !== 3 || !resource?.required || !["uuid", "reference"].includes(String(resource.type)) || !start?.required || start.type !== "datetime" || !end?.required || end.type !== "datetime") {
          issue(bookingPath, "invalid-booking", "Booking needs Auth, a required UUID/resource reference and two distinct required datetime fields.");
        }
        if (rule.statusFieldId !== void 0 || rule.blockingStatuses !== void 0) {
          const status = find(rule.statusFieldId);
          if (!id(rule.statusFieldId) || !status?.required || status.type !== "enum" || !Array.isArray(rule.blockingStatuses) || !rule.blockingStatuses.length || rule.blockingStatuses.length > 100 || new Set(rule.blockingStatuses).size !== rule.blockingStatuses.length || rule.blockingStatuses.some((value2) => typeof value2 !== "string" || !Array.isArray(status.options) || !status.options.includes(value2))) {
            issue(bookingPath, "invalid-booking-status", "Blocking statuses must reference a required enum and declared unique values.");
          }
        }
      }
    }
    if (table.attachments !== void 0) {
      const filePath = `${path}.attachments`, rule = table.attachments;
      if (!shape(rule, ["maxBytes", "mimeTypes"], filePath) || !authEnabled || !Number.isSafeInteger(rule.maxBytes) || Number(rule.maxBytes) < 1 || Number(rule.maxBytes) > APPLICATION_FILE_MAX_BYTES || !Array.isArray(rule.mimeTypes) || !rule.mimeTypes.length || rule.mimeTypes.length > APPLICATION_FILE_TYPES.length || new Set(rule.mimeTypes).size !== rule.mimeTypes.length || rule.mimeTypes.some((type) => !APPLICATION_FILE_TYPES.includes(type))) {
        issue(filePath, "invalid-files", "Attachments need Auth, a size limit up to 25 MiB and declared download-safe MIME types.");
      }
      if (!Array.isArray(table.permissions) || !table.permissions.some((rule2) => object2(rule2) && rule2.operation === "read") || !table.permissions.some((rule2) => object2(rule2) && rule2.operation === "update")) issue(filePath, "files-permissions", "Attachments require read and update permissions.");
    }
    if (table.counter !== void 0) {
      const counterPath = `${path}.counter`;
      if (shape(table.counter, ["fieldId", "minimum", "maximum", "integer"], counterPath)) {
        const rule = table.counter;
        const field = Array.isArray(table.fields) ? table.fields.find((field2) => object2(field2) && field2.id === rule.fieldId) : void 0;
        if (!authEnabled || !id(rule.fieldId) || !object2(field) || field.type !== "number" || field.required !== true || typeof rule.minimum !== "number" || !Number.isFinite(rule.minimum) || Math.abs(rule.minimum) > 1e12 || field.defaultValue !== rule.minimum || typeof rule.integer !== "boolean" || rule.integer === true && !Number.isSafeInteger(rule.minimum) || rule.maximum !== void 0 && (typeof rule.maximum !== "number" || !Number.isFinite(rule.maximum) || rule.maximum < Number(rule.minimum) || Math.abs(rule.maximum) > 1e12 || rule.integer === true && !Number.isSafeInteger(rule.maximum))) {
          issue(counterPath, "invalid-counter", "A counter needs Auth, a required numeric field defaulting to its finite minimum, and valid optional bounds.");
        }
        if (!Array.isArray(table.permissions) || !table.permissions.some((rule2) => object2(rule2) && rule2.operation === "read") || !table.permissions.some((rule2) => object2(rule2) && rule2.operation === "update")) issue(counterPath, "counter-permissions", "Counter adjustment requires explicit read and update permissions.");
      }
    }
    if (table.transaction !== void 0) {
      const transactionPath = `${path}.transaction`;
      if (shape(table.transaction, ["itemTableId", "lineTableId", "lineTransactionFieldId", "lineItemFieldId", "lineQuantityFieldId", "counterDirection"], transactionPath)) {
        const rule = table.transaction;
        const itemTable = tables.find((candidate) => object2(candidate) && candidate.id === rule.itemTableId);
        const lineTable = tables.find((candidate) => object2(candidate) && candidate.id === rule.lineTableId);
        const lineFields = object2(lineTable) && Array.isArray(lineTable.fields) ? lineTable.fields.filter(object2) : [];
        const transactionField = lineFields.find((field) => field.id === rule.lineTransactionFieldId);
        const itemField = lineFields.find((field) => field.id === rule.lineItemFieldId);
        const quantityField = lineFields.find((field) => field.id === rule.lineQuantityFieldId);
        const distinct = /* @__PURE__ */ new Set([rule.lineTransactionFieldId, rule.lineItemFieldId, rule.lineQuantityFieldId]);
        if (!authEnabled || !id(rule.itemTableId) || !id(rule.lineTableId) || rule.itemTableId === table.id || rule.lineTableId === table.id || rule.itemTableId === rule.lineTableId || !object2(itemTable) || !object2(itemTable.counter) || !object2(lineTable) || distinct.size !== 3 || !id(rule.lineTransactionFieldId) || !id(rule.lineItemFieldId) || !id(rule.lineQuantityFieldId) || transactionField?.type !== "reference" || transactionField.required !== true || transactionField.referenceTableId !== table.id || itemField?.type !== "reference" || itemField.required !== true || itemField.referenceTableId !== rule.itemTableId || quantityField?.type !== "number" || quantityField.required !== true || quantityField.formula !== void 0 || !["decrement", "increment"].includes(String(rule.counterDirection)) || table.booking !== void 0 || table.counter !== void 0) {
          issue(transactionPath, "invalid-transaction", "A transaction needs Auth, a counter item table and a separate line table with required parent, item and numeric quantity fields.");
        }
        const has = (candidate, operation) => object2(candidate) && Array.isArray(candidate.permissions) && candidate.permissions.some((permission) => object2(permission) && permission.operation === operation);
        if (!has(table, "read") || !has(table, "create") || !has(itemTable, "read") || !has(itemTable, "update") || !has(lineTable, "read") || object2(lineTable) && Array.isArray(lineTable.permissions) && lineTable.permissions.some((permission) => object2(permission) && permission.operation !== "read")) {
          issue(transactionPath, "transaction-permissions", "Transactions require parent read/create, item read/update and read-only line permissions.");
        }
      }
    }
    if (table.workflow !== void 0) {
      const workflowPath = `${path}.workflow`;
      if (shape(table.workflow, ["fieldId", "transitions"], workflowPath)) {
        const workflow = table.workflow;
        const field = Array.isArray(table.fields) ? table.fields.find((candidate) => object2(candidate) && candidate.id === workflow.fieldId) : void 0;
        const options = object2(field) && Array.isArray(field.options) ? field.options.filter((value2) => typeof value2 === "string") : [];
        if (!authEnabled || !id(workflow.fieldId) || !object2(field) || field.type !== "enum" || field.required !== true || typeof field.defaultValue !== "string" || !options.includes(field.defaultValue)) {
          issue(workflowPath, "invalid-workflow", "A workflow needs Auth and a required enum state field with a declared default state.");
        }
        const transitionIds = /* @__PURE__ */ new Set();
        const transitions = list(workflow.transitions, 100, `${workflowPath}.transitions`);
        if (!transitions.length) issue(`${workflowPath}.transitions`, "missing-transitions", "A workflow needs at least one transition.");
        transitions.forEach((transition, transitionIndex) => {
          const transitionPath = `${workflowPath}.transitions[${transitionIndex}]`;
          if (!shape(transition, ["id", "label", "from", "to", "access", "roleId"], transitionPath)) return;
          if (!id(transition.id) || transitionIds.has(String(transition.id))) issue(`${transitionPath}.id`, "invalid-id", "Workflow transition IDs must be valid and unique.");
          else transitionIds.add(String(transition.id));
          if (!name(transition.label)) issue(`${transitionPath}.label`, "invalid-name", "A workflow transition requires a label.");
          if (!Array.isArray(transition.from) || !transition.from.length || transition.from.length > 100 || new Set(transition.from).size !== transition.from.length || transition.from.some((value2) => typeof value2 !== "string" || !options.includes(value2))) {
            issue(`${transitionPath}.from`, "invalid-workflow-state", "Workflow source states must be unique declared enum options.");
          }
          if (typeof transition.to !== "string" || !options.includes(transition.to) || Array.isArray(transition.from) && transition.from.includes(transition.to)) {
            issue(`${transitionPath}.to`, "invalid-workflow-state", "Workflow destination must be a different declared enum option.");
          }
          if (!["authenticated", "owner", "role"].includes(String(transition.access))) issue(`${transitionPath}.access`, "invalid-access", "Workflow transitions require authenticated, owner or role access.");
          if (transition.access === "role" && !roleIds.has(String(transition.roleId))) issue(`${transitionPath}.roleId`, "missing-role", "Role workflow access requires an existing role.");
          if (transition.access !== "role" && transition.roleId !== void 0) issue(`${transitionPath}.roleId`, "unexpected-role", "Only role transitions can specify a role.");
        });
        if (!Array.isArray(table.permissions) || !table.permissions.some((rule) => object2(rule) && rule.operation === "read") || !table.permissions.some((rule) => object2(rule) && rule.operation === "update")) issue(workflowPath, "workflow-permissions", "Workflow transitions require explicit read and update permissions.");
      }
    }
    const permissionKeys = /* @__PURE__ */ new Set();
    list(table.permissions, APPLICATION_LIMITS.permissions, `${path}.permissions`).forEach((permission, index) => {
      const permissionPath = `${path}.permissions[${index}]`;
      if (!shape(permission, ["operation", "access", "roleId"], permissionPath)) return;
      if (!["read", "create", "update", "delete"].includes(String(permission.operation))) issue(permissionPath, "invalid-operation", "Unsupported database operation.");
      access(permission, permissionPath, true);
      if (permission.access === "public" && permission.operation !== "read") issue(permissionPath, "public-write", "Anonymous database writes require a validated server action.");
      const key = `${permission.operation}:${permission.access}:${permission.roleId ?? ""}`;
      if (permissionKeys.has(key)) issue(permissionPath, "duplicate-permission", "Duplicate permission rule.");
      permissionKeys.add(key);
    });
    if (Array.isArray(table.permissions) && table.permissions.some((p) => object2(p) && ["update", "delete"].includes(String(p.operation))) && !table.permissions.some((p) => object2(p) && p.operation === "read")) issue(`${path}.permissions`, "read-required", "Update and delete require a read policy.");
  });
  let notificationCount = 0;
  tables.forEach((table, index) => {
    if (!object2(table) || table.notifications === void 0) return;
    const path = `application.tables[${index}]`, rulePath = `${path}.notifications`;
    const rules = list(table.notifications, 50, rulePath);
    notificationCount += rules.length;
    if (!authEnabled || !object2(auth) || auth.emailVerificationRequired !== true) issue(rulePath, "email-auth-required", "Email notifications require authentication and verified email addresses.");
    const validTable = !issues.some((item) => item.path === path || item.path.startsWith(`${path}.`));
    rules.forEach((rule, ruleIndex) => {
      const itemPath = `${rulePath}[${ruleIndex}]`;
      if (object2(rule)) identity(rule.id, `${itemPath}.id`);
      if (validTable) {
        const error = validateApplicationEmailNotification(rule, table);
        if (error) issue(itemPath, "invalid-email-notification", error);
      }
    });
  });
  if (notificationCount > 50) issue("application.tables", "too-many-email-notifications", "An application supports at most 50 email notification rules.");
  const lineTables = /* @__PURE__ */ new Set();
  tables.forEach((table, index) => {
    if (!object2(table) || !object2(table.transaction)) return;
    const line = String(table.transaction.lineTableId);
    if (lineTables.has(line)) issue(`application.tables[${index}].transaction.lineTableId`, "duplicate-transaction-line-table", "A line table can belong to only one native transaction.");
    lineTables.add(line);
  });
  const protectedPages = /* @__PURE__ */ new Set();
  list(value.pageAccess, APPLICATION_LIMITS.pageAccess, "application.pageAccess").forEach((rule, index) => {
    const path = `application.pageAccess[${index}]`;
    if (!shape(rule, ["pageId", "access", "roleId"], path)) return;
    if (!id(rule.pageId) || protectedPages.has(rule.pageId) || pageIds && !pageIds.has(rule.pageId)) issue(path, "invalid-page", "Access rules require a unique existing page.");
    else protectedPages.add(rule.pageId);
    access(rule, path, false);
  });
  if (value.requirements !== void 0 && shape(value.requirements, ["version", "request", "items"], "application.requirements")) {
    const manifest = value.requirements;
    if (manifest.version !== 1) issue("application.requirements.version", "unsupported-version", "Unsupported requirements manifest version.");
    if (typeof manifest.request !== "string" || !manifest.request.trim() || manifest.request.length > 4e3) issue("application.requirements.request", "invalid-request", "Requirements need the original nonempty request.");
    const requirementIds = /* @__PURE__ */ new Set();
    const capabilities = /* @__PURE__ */ new Set(["page", "auth", "form", "records", "booking", "counter", "transaction", "workflow", "formula", "files"]);
    list(manifest.items, APPLICATION_LIMITS.requirements, "application.requirements.items").forEach((item, index) => {
      const path = `application.requirements.items[${index}]`;
      if (!shape(item, ["id", "summary", "capability", "evidence"], path)) return;
      if (!id(item.id) || requirementIds.has(String(item.id))) issue(`${path}.id`, "invalid-id", "Requirement IDs must be valid and unique.");
      else requirementIds.add(String(item.id));
      if (typeof item.summary !== "string" || !item.summary.trim() || item.summary.length > 300) issue(`${path}.summary`, "invalid-summary", "A requirement needs a concise summary.");
      if (!capabilities.has(String(item.capability))) issue(`${path}.capability`, "invalid-capability", "Unsupported requirement capability.");
      const evidence = list(item.evidence, APPLICATION_LIMITS.requirementEvidence, `${path}.evidence`);
      if (!evidence.length) issue(`${path}.evidence`, "missing-evidence", "A completed requirement needs verified implementation evidence.");
      evidence.forEach((entry, evidenceIndex) => {
        const evidencePath = `${path}.evidence[${evidenceIndex}]`;
        if (typeof entry !== "string" || entry.length > 260) {
          issue(evidencePath, "invalid-evidence", "Invalid requirement evidence.");
          return;
        }
        if (entry === "auth") {
          if (!authEnabled) issue(evidencePath, "missing-auth", "Auth evidence requires enabled authentication.");
          return;
        }
        const match = /^(page|form|view|booking|counter|transaction|workflow|formula|files):([a-zA-Z0-9_-]{1,120})(?::(read|create|update|delete|adjust|transact|transition|attachments))?$/.exec(entry);
        if (!match) {
          issue(evidencePath, "invalid-evidence", "Evidence must reference a supported page, table or action.");
          return;
        }
        if (match[1] === "page") {
          if (match[3] || pageIds && !pageIds.has(match[2])) issue(evidencePath, "missing-page", "Page evidence requires an existing page.");
          return;
        }
        const table = tables.find((candidate) => object2(candidate) && candidate.id === match[2]);
        if (!object2(table)) {
          issue(evidencePath, "missing-table", "Requirement evidence requires an existing table.");
          return;
        }
        if (match[1] === "booking" && !object2(table.booking)) issue(evidencePath, "missing-booking", "Booking evidence requires a native booking rule.");
        if (match[1] === "counter" && !object2(table.counter)) issue(evidencePath, "missing-counter", "Counter evidence requires a native counter rule.");
        if (match[1] === "transaction" && !object2(table.transaction)) issue(evidencePath, "missing-transaction", "Transaction evidence requires a native transaction rule.");
        if (match[1] === "files" && !object2(table.attachments)) issue(evidencePath, "missing-files", "Files evidence requires an attachment rule.");
        if (match[1] === "workflow" && !object2(table.workflow)) issue(evidencePath, "missing-workflow", "Workflow evidence requires a native workflow rule.");
        if (match[1] === "formula" && !table.fields.some((field) => object2(field) && object2(field.formula))) issue(evidencePath, "missing-formula", "Formula evidence requires a server-computed field.");
        if (match[1] === "view" && !match[3]) issue(evidencePath, "missing-action", "Data-view evidence requires an action.");
        if (match[1] !== "view" && match[3]) issue(evidencePath, "unexpected-action", "Only data-view evidence can include an action.");
      });
    });
    if (!Array.isArray(manifest.items) || !manifest.items.length) issue("application.requirements.items", "missing-requirements", "An application requirements manifest cannot be empty.");
  }
  return issues;
}
function readApplicationDefinition(value, pageIds) {
  if (value === void 0) return createApplicationDefinition();
  const issues = validateApplicationDefinition(value, pageIds);
  if (issues.length) throw new Error(issues.map((item) => `${item.path}: ${item.message}`).join("\n"));
  return structuredClone(value);
}

// src/modules/website-builder/core/application-files-runtime.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.57.4";

// src/modules/website-builder/core/application-data-runtime.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.57.4";
function projectRef(url) {
  const parsed = new URL(url);
  const match = /^([a-z0-9]{20})\.supabase\.co$/.exec(parsed.hostname);
  if (parsed.protocol !== "https:" || !match || parsed.username || parsed.password || parsed.port || parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("Generated applications require a dedicated HTTPS Supabase project URL.");
  }
  return match[1];
}
function publicKey(key, ref) {
  if (/^sb_publishable_[A-Za-z0-9_-]+$/.test(key)) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    const body = JSON.parse(atob(parts[1].replace(/-/g, "+").replace(/_/g, "/")));
    return body.role === "anon" && body.ref === ref && body.iss === "supabase";
  } catch {
    return false;
  }
}
function validateApplicationPublicBackend(config, platformUrl) {
  const ref = projectRef(config.url);
  if (ref !== config.projectRef || ref === projectRef(platformUrl)) throw new Error("Application backend identity does not match its dedicated project.");
  if (!publicKey(config.publishableKey, ref)) throw new Error("Application backend requires a public anon or publishable key for this project.");
}

// src/modules/website-builder/core/application-backend-verification.ts
function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;
  return JSON.stringify(value) ?? "undefined";
}
async function assertApplicationBackendRevision(definition, backend, platformUrl, reader) {
  validateApplicationPublicBackend(backend, platformUrl);
  return assertBackendRevision(definition, backend, reader);
}
async function assertBackendRevision(definition, backend, reader) {
  if (reader.url !== backend.url) throw new Error("Application revision reader targets another backend.");
  const expected = readApplicationDefinition(definition);
  let deployed;
  try {
    deployed = readApplicationDefinition(await reader.readDeployedDefinition());
  } catch {
    throw new Error("Application backend revision could not be verified.");
  }
  if (canonical(deployed) !== canonical(expected)) throw new Error("Application backend schema revision does not match the project.");
}
async function applicationDefinitionDigest(definition) {
  const bytes = new TextEncoder().encode(canonical(readApplicationDefinition(definition)));
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
}

// src/modules/website-builder/services/websiteApplicationAuthSettingsService.ts
async function assertDedicatedApplicationAuthSettings(definition, config, platformUrl) {
  if (typeof window !== "undefined") throw new Error("Backend authentication verification requires a server runtime.");
  const backend = { ...config };
  validateApplicationPublicBackend(backend, platformUrl);
  return assertAuthSettings(definition, backend);
}
async function assertAuthSettings(definition, backend) {
  const app = readApplicationDefinition(definition);
  let settings;
  try {
    const response2 = await fetch(`${backend.url}/auth/v1/settings`, {
      headers: { apikey: backend.publishableKey, Accept: "application/json" },
      redirect: "error",
      cache: "no-store",
      signal: AbortSignal.timeout(1e4)
    });
    if (!response2.ok) throw new Error();
    const body = await response2.text();
    if (body.length > 65536) throw new Error();
    const raw = JSON.parse(body);
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error();
    settings = raw;
  } catch {
    throw new Error("Dedicated application authentication settings are unavailable.");
  }
  const providers = settings.external;
  if (!providers || typeof providers !== "object" || Array.isArray(providers) || typeof settings.disable_signup !== "boolean" || typeof settings.mailer_autoconfirm !== "boolean") {
    throw new Error("Dedicated application authentication settings are invalid.");
  }
  const external = providers;
  if (external.email !== app.auth.enabled || external.anonymous_users !== false || settings.disable_signup !== !app.auth.signUpEnabled || app.auth.enabled && settings.mailer_autoconfirm !== !app.auth.emailVerificationRequired || Object.entries(external).some(([provider, enabled]) => typeof enabled !== "boolean" || provider !== "email" && enabled) || ["saml_enabled", "passkeys_enabled"].some((key) => settings[key] !== void 0 && settings[key] !== false)) {
    throw new Error("Dedicated application authentication settings do not match the project.");
  }
}

// src/modules/website-builder/services/websiteApplicationBackendService.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.57.4";
function isDedicatedServiceKey(key, ref) {
  if (/^sb_secret_[A-Za-z0-9_-]+$/.test(key)) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    const claims = JSON.parse(atob(parts[1].replace(/-/g, "+").replace(/_/g, "/")));
    return claims.role === "service_role" && claims.ref === ref && claims.iss === "supabase";
  } catch {
    return false;
  }
}
function createDedicatedApplicationRevisionReader(backend, platformUrl, serviceKey) {
  if (typeof window !== "undefined") throw new Error("Application service credentials require a server runtime.");
  validateApplicationPublicBackend(backend, platformUrl);
  if (!isDedicatedServiceKey(serviceKey, backend.projectRef)) throw new Error("A dedicated backend service credential is required.");
  const backendUrl = backend.url;
  const client = createClient4(backendUrl, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
    global: {
      fetch: (input, init) => {
        const target = input instanceof Request ? input.url : String(input);
        if (target !== `${backendUrl}/rest/v1/rpc/app_deployed_definition` && target !== `${backendUrl}/rest/v1/rpc/app_form_request_revision`) {
          throw new Error("Unexpected application revision endpoint.");
        }
        return fetch(input, { ...init, redirect: "error", signal: AbortSignal.timeout(1e4) });
      }
    }
  });
  return {
    url: backendUrl,
    async readDeployedDefinition() {
      try {
        const { data, error } = await client.rpc("app_deployed_definition");
        if (error || !data) throw new Error();
        return data;
      } catch {
        throw new Error("Dedicated application revision is unavailable.");
      }
    },
    async readFormRequestRevision() {
      try {
        const { data, error } = await client.rpc("app_form_request_revision");
        if (error || data !== 2) throw new Error();
        return data;
      } catch {
        throw new Error("Dedicated application request capability is unavailable.");
      }
    }
  };
}

// src/modules/website-builder/services/websiteApplicationBackendLinkService.ts
var uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var response = (status, body) => new Response(JSON.stringify(body), {
  status,
  headers: { "content-type": "application/json", "cache-control": "no-store" }
});
async function readBoundedJson(request, limit = 32768) {
  if (Number(request.headers.get("content-length")) > limit || !request.body) throw new Error();
  const reader = request.body.getReader();
  const chunks = [];
  let length = 0;
  try {
    for (; ; ) {
      const { value, done } = await reader.read();
      if (done) break;
      length += value.byteLength;
      if (length > limit) {
        await reader.cancel();
        throw new Error();
      }
      chunks.push(value);
    }
  } finally {
    reader.releaseLock();
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes));
}
async function handleWebsiteApplicationBackendLink(request, context) {
  if (typeof window !== "undefined") throw new Error("Backend linking requires a server runtime.");
  if (request.method !== "POST") return response(405, { error: "Method not allowed." });
  if (!/^application\/json(?:\s*;|$)/i.test(request.headers.get("content-type") ?? "")) return response(415, { error: "JSON request required." });
  const token = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/i.exec(request.headers.get("authorization") ?? "")?.[1];
  if (!token || token.length > 16384) return response(401, { error: "Sign in required." });
  const { platform, platformUrl } = context;
  let ownerId;
  try {
    const { data, error } = await platform.auth.getUser(token);
    if (error || !data.user || data.user.is_anonymous || !uuid.test(data.user.id)) return response(401, { error: "Sign in required." });
    ownerId = data.user.id;
  } catch {
    return response(401, { error: "Sign in required." });
  }
  let projectId;
  let backend;
  let serviceKey;
  let expectedRevision;
  try {
    const value = await readBoundedJson(request);
    if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error();
    const body = value;
    if (Object.keys(body).some((key) => !["projectId", "backend", "serviceKey", "expectedRevision"].includes(key)) || typeof body.projectId !== "string" || !uuid.test(body.projectId)) throw new Error();
    if (!body.backend || typeof body.backend !== "object" || Array.isArray(body.backend)) throw new Error();
    const config = body.backend;
    if (Object.keys(config).some((key) => !["url", "projectRef", "publishableKey"].includes(key)) || typeof config.url !== "string" || typeof config.projectRef !== "string" || typeof config.publishableKey !== "string") throw new Error();
    if (typeof body.serviceKey !== "string" || body.serviceKey.length < 20 || body.serviceKey.length > 16384 || /\s/.test(body.serviceKey)) throw new Error();
    if (typeof body.expectedRevision !== "string" || !/^[a-f0-9]{64}$/.test(body.expectedRevision)) throw new Error();
    expectedRevision = body.expectedRevision;
    projectId = body.projectId;
    backend = { url: config.url, projectRef: config.projectRef, publishableKey: config.publishableKey };
    serviceKey = body.serviceKey;
    validateApplicationPublicBackend(backend, platformUrl);
  } catch {
    return response(400, { error: "Invalid application backend request." });
  }
  try {
    const { data: project, error } = await platform.from("projects").select("content").eq("id", projectId).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
    if (error) return response(503, { error: "Project is unavailable." });
    if (!project) return response(404, { error: "Project not found." });
    if (!project.content?.application) return response(409, { error: "Save an application definition before linking its backend." });
    const definition = readApplicationDefinition(project.content.application);
    if (await applicationDefinitionDigest(definition) !== expectedRevision) return response(409, { error: "Save and refresh the application before linking its backend." });
    const reader = createDedicatedApplicationRevisionReader(backend, platformUrl, serviceKey);
    await Promise.all([
      assertApplicationBackendRevision(definition, backend, platformUrl, reader),
      assertDedicatedApplicationAuthSettings(definition, backend, platformUrl)
    ]);
    const result = await platform.rpc("website_link_application_backend", {
      p_project_id: projectId,
      p_owner_id: ownerId,
      p_backend_ref: backend.projectRef,
      p_publishable_key: backend.publishableKey,
      p_deployed_definition: definition,
      p_service_key: serviceKey
    });
    if (result.error) return response(409, { error: "Backend link could not be committed. Verify the saved project and backend ownership." });
    return response(200, { status: "linked", backend });
  } catch {
    return response(409, { error: "Application backend could not be verified or linked." });
  }
}

// server/website-application-backend-link.ts
Deno.serve(async (request) => {
  const origin = request.headers.get("origin");
  const allowedOrigins = new Set((Deno.env.get("WEBSITE_BACKEND_LINK_ORIGINS") ?? "https://tayar.se,https://www.tayar.se").split(",").map((value) => value.trim()).filter(Boolean));
  const headers = new Headers({ "cache-control": "no-store", "vary": "Origin" });
  const reply = (status, message) => new Response(JSON.stringify({ error: message }), { status, headers });
  headers.set("content-type", "application/json");
  if (origin && !allowedOrigins.has(origin)) return reply(403, "Origin not allowed.");
  if (origin) headers.set("access-control-allow-origin", origin);
  headers.set("access-control-allow-methods", "POST, OPTIONS");
  headers.set("access-control-allow-headers", "authorization, apikey, content-type, x-client-info");
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers });
  if (request.method !== "POST") return reply(405, "Method not allowed.");
  try {
    const platformUrl = getSupabaseUrl();
    const platform = createClient5(platformUrl, getSecretKey(), {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
      global: {
        fetch: async (resource, init) => {
          try {
            const url = resource instanceof Request ? resource.url : String(resource);
            if (new URL(url).origin !== new URL(platformUrl).origin) throw new Error();
            return await fetch(resource, { ...init, redirect: "error", signal: AbortSignal.timeout(15e3) });
          } catch {
            return new Response(JSON.stringify({ message: "Platform request unavailable." }), {
              status: 503,
              headers: { "content-type": "application/json" }
            });
          }
        }
      }
    });
    const result = await handleWebsiteApplicationBackendLink(request, { platform, platformUrl });
    const resultHeaders = new Headers(result.headers);
    headers.forEach((value, key) => resultHeaders.set(key, value));
    return new Response(result.body, { status: result.status, headers: resultHeaders });
  } catch {
    return reply(503, "Application backend linking is unavailable.");
  }
});
