import { UIComponentRecord } from './types';

const code = (...lines: string[]) => lines.join('\n');

export const SEED_COMPONENTS: UIComponentRecord[] = [
  {
    id: 'tayar-gradient-hero',
    name: 'Gradient Hero',
    description: 'Responsive SaaS hero with clear hierarchy and two actions.',
    category: 'hero',
    tags: ['saas', 'landing', 'responsive'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'hero',
    aiPrompt: 'Adapt this hero to the project theme, reuse existing Button primitives, keep it responsive, and preserve the project typography.',
    code: code(
      "export function GradientHero() {",
      "  return (",
      "    <section className=\"relative overflow-hidden rounded-3xl border border-white/10 bg-slate-950 px-6 py-20 text-center text-white\">",
      "      <div className=\"absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(139,92,246,.28),transparent_55%)]\" />",
      "      <div className=\"relative mx-auto max-w-3xl\">",
      "        <span className=\"rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1 text-xs text-violet-200\">Build faster</span>",
      "        <h1 className=\"mt-5 text-4xl font-bold tracking-tight sm:text-6xl\">Turn ideas into polished interfaces</h1>",
      "        <p className=\"mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base\">A focused hero for modern product pages.</p>",
      "        <div className=\"mt-8 flex flex-wrap justify-center gap-3\">",
      "          <button className=\"rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950\">Get started</button>",
      "          <button className=\"rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold\">View demo</button>",
      "        </div>",
      "      </div>",
      "    </section>",
      "  );",
      "}"
    ),
  },
  {
    id: 'tayar-floating-nav',
    name: 'Floating Navigation',
    description: 'Compact floating navigation shell for landing pages.',
    category: 'navigation',
    tags: ['navbar', 'floating', 'landing'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'nav',
    aiPrompt: 'Integrate this navigation into the existing layout, map links to the project routes, and reuse the current logo and button system.',
    code: code(
      "export function FloatingNav() {",
      "  return (",
      "    <nav className=\"mx-auto flex max-w-4xl items-center justify-between rounded-2xl border border-white/10 bg-slate-950/80 px-4 py-3 text-white backdrop-blur\">",
      "      <strong className=\"text-sm\">Product</strong>",
      "      <div className=\"hidden gap-6 text-sm text-slate-300 md:flex\"><a href=\"#features\">Features</a><a href=\"#pricing\">Pricing</a><a href=\"#about\">About</a></div>",
      "      <button className=\"rounded-lg bg-violet-500 px-3 py-2 text-xs font-semibold\">Start free</button>",
      "    </nav>",
      "  );",
      "}"
    ),
  },
  {
    id: 'tayar-pricing-grid',
    name: 'Pricing Grid',
    description: 'Three-tier pricing layout with a highlighted recommended plan.',
    category: 'pricing',
    tags: ['pricing', 'plans', 'saas'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'pricing',
    aiPrompt: 'Adapt the pricing cards to the existing product plans and currency, preserve billing logic, and only change presentation.',
    code: code(
      "const plans = [{name:'Starter',price:'$0'},{name:'Pro',price:'$19'},{name:'Business',price:'$49'}];",
      "export function PricingGrid() {",
      "  return <div className=\"grid gap-4 md:grid-cols-3\">{plans.map((plan, index) => (",
      "    <article key={plan.name} className={`rounded-2xl border p-6 ${index === 1 ? 'border-violet-400 bg-violet-500/10' : 'border-white/10 bg-white/5'}`}>",
      "      <h3 className=\"font-semibold\">{plan.name}</h3><div className=\"mt-4 text-3xl font-bold\">{plan.price}<span className=\"text-sm font-normal opacity-60\">/mo</span></div>",
      "      <button className=\"mt-6 w-full rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950\">Choose plan</button>",
      "    </article>",
      "  ))}</div>;",
      "}"
    ),
  },
  {
    id: 'tayar-auth-card',
    name: 'Authentication Card',
    description: 'Simple sign-in surface with accessible labels and actions.',
    category: 'authentication',
    tags: ['login', 'auth', 'form'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'auth',
    aiPrompt: 'Connect this UI to the project existing authentication handlers. Do not replace auth logic or credentials handling.',
    code: code(
      "export function AuthCard() {",
      "  return (",
      "    <form className=\"mx-auto max-w-sm rounded-2xl border border-white/10 bg-slate-950 p-6 text-white\">",
      "      <h2 className=\"text-xl font-semibold\">Welcome back</h2>",
      "      <label className=\"mt-5 block text-xs text-slate-300\">Email<input type=\"email\" className=\"mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2\" /></label>",
      "      <label className=\"mt-4 block text-xs text-slate-300\">Password<input type=\"password\" className=\"mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2\" /></label>",
      "      <button className=\"mt-5 w-full rounded-xl bg-violet-500 py-2.5 text-sm font-semibold\">Sign in</button>",
      "    </form>",
      "  );",
      "}"
    ),
  },
  {
    id: 'tayar-stat-cards',
    name: 'Metric Cards',
    description: 'Responsive metric row for analytics and dashboards.',
    category: 'data',
    tags: ['stats', 'analytics', 'dashboard'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'stats',
    aiPrompt: 'Map these cards to real project metrics and reuse existing number formatting. Do not invent backend data.',
    code: code(
      "const metrics = [{label:'Revenue',value:'$42.8k'},{label:'Users',value:'12.4k'},{label:'Conversion',value:'8.7%'}];",
      "export function MetricCards() {",
      "  return <div className=\"grid gap-3 sm:grid-cols-3\">{metrics.map(metric => <div key={metric.label} className=\"rounded-2xl border border-white/10 bg-white/5 p-5\"><p className=\"text-xs text-slate-400\">{metric.label}</p><p className=\"mt-2 text-2xl font-bold\">{metric.value}</p></div>)}</div>;",
      "}"
    ),
  },
  {
    id: 'tayar-dashboard-shell',
    name: 'Dashboard Shell',
    description: 'Dashboard content shell with summary cards and activity area.',
    category: 'dashboard',
    tags: ['dashboard', 'admin', 'analytics'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'dashboard',
    aiPrompt: 'Fit this dashboard shell into the existing application layout and route structure. Reuse current navigation and data services.',
    code: code(
      "export function DashboardShell() {",
      "  return <section className=\"space-y-4\"><header><p className=\"text-sm text-slate-400\">Overview</p><h1 className=\"text-2xl font-bold\">Dashboard</h1></header><div className=\"grid gap-3 md:grid-cols-3\">{['Traffic','Orders','Revenue'].map(x => <div key={x} className=\"h-28 rounded-2xl border border-white/10 bg-white/5 p-4\">{x}</div>)}</div><div className=\"h-64 rounded-2xl border border-white/10 bg-white/5 p-4\">Recent activity</div></section>;",
      "}"
    ),
  },
  {
    id: 'tayar-ai-chat-shell',
    name: 'AI Chat Shell',
    description: 'Assistant conversation surface with prompt input and status.',
    category: 'ai',
    tags: ['ai', 'chat', 'assistant'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'chat',
    aiPrompt: 'Connect this shell to the existing AI service and streaming state. Preserve authentication, rate-limit, and error handling.',
    code: code(
      "export function AIChatShell() {",
      "  return <div className=\"flex min-h-[420px] flex-col rounded-2xl border border-white/10 bg-slate-950 p-4 text-white\"><div className=\"flex-1 space-y-3\"><div className=\"max-w-[80%] rounded-2xl bg-white/5 p-3 text-sm\">How can I help?</div><div className=\"ml-auto max-w-[80%] rounded-2xl bg-violet-500 p-3 text-sm\">Build a pricing section.</div></div><div className=\"mt-4 flex gap-2 rounded-xl border border-white/10 bg-white/5 p-2\"><input className=\"flex-1 bg-transparent px-2 text-sm outline-none\" placeholder=\"Ask anything...\"/><button className=\"rounded-lg bg-violet-500 px-3 py-2 text-xs\">Send</button></div></div>;",
      "}"
    ),
  },
  {
    id: 'tayar-cta-banner',
    name: 'CTA Banner',
    description: 'Conversion-focused call-to-action block with two actions.',
    category: 'cta',
    tags: ['cta', 'marketing', 'banner'],
    sourceId: 'tayar-native',
    license: 'Tayar',
    dependencies: [],
    preview: 'cta',
    aiPrompt: 'Adapt this CTA to the current page goal, reuse existing actions, and keep copy concise.',
    code: code(
      "export function CTABanner() {",
      "  return <section className=\"rounded-3xl border border-violet-400/20 bg-violet-500/10 p-8 text-center\"><h2 className=\"text-2xl font-bold\">Ready to ship?</h2><p className=\"mx-auto mt-2 max-w-xl text-sm opacity-70\">Move from idea to production with a focused workflow.</p><div className=\"mt-5 flex justify-center gap-3\"><button className=\"rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950\">Start now</button><button className=\"rounded-xl border border-white/15 px-4 py-2 text-sm\">Learn more</button></div></section>;",
      "}"
    ),
  },
];
