import { RegistrySource } from './types';

export const REGISTRY_SOURCES: RegistrySource[] = [
  {
    id: 'tayar-native',
    name: 'Tayar Native',
    repository: 'khatay1/Tayar-Intelligence-Tools',
    license: 'Tayar',
    redistributionAllowed: true,
    attributionRequired: false,
    note: 'Original components authored for the Tayar registry.',
  },
  {
    id: 'private-session',
    name: 'Private Session',
    license: 'restricted',
    redistributionAllowed: false,
    attributionRequired: false,
    note: 'User-selected licensed source kept only in the current browser session. Tayar may adapt it for the user but must never publish it into the public registry.',
  },
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    repository: 'shadcn-ui/ui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'magic-ui',
    name: 'Magic UI',
    repository: 'magicuidesign/magicui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'kokonut-ui',
    name: 'KokonutUI',
    repository: 'kokonut-labs/kokonutui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'cult-ui',
    name: 'Cult UI',
    repository: 'nolly-studio/cult-ui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: '8bitcn',
    name: '8bitcn',
    repository: 'TheOrcDev/8bitcn-ui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'eldora-ui',
    name: 'Eldora UI',
    repository: 'karthikmudunuri/eldoraui',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'ui-layouts',
    name: 'UI Layouts',
    repository: 'ui-layouts/uilayouts',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'spectrum-ui',
    name: 'Spectrum UI',
    repository: 'arihantcodes/spectrum-ui',
    license: 'Apache-2.0',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'Apache-2.0 source. Preserve the upstream license and attribution notices when code is imported.',
  },
  {
    id: 'shadcn-space',
    name: 'Shadcn Space',
    repository: 'shadcnspace/shadcnspace',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'motion-primitives',
    name: 'Motion Primitives',
    repository: 'ibelick/motion-primitives',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source with a public shadcn-style registry. Preserve the upstream copyright and permission notice when substantial code is imported.',
  },
  {
    id: 'animata',
    name: 'Animata',
    repository: 'codse/animata',
    license: 'MIT',
    redistributionAllowed: true,
    attributionRequired: true,
    note: 'MIT source. Animata publishes copy-paste animated React/Tailwind components and shadcn registry items. Preserve the upstream license notice.',
  },
  {
    id: 'animate-ui',
    name: 'Animate UI',
    repository: 'imskyleen/animate-ui',
    license: 'restricted',
    redistributionAllowed: false,
    attributionRequired: true,
    note: 'MIT + Commons Clause. May be used as part of an application/product but must not be redistributed as a competing component library; keep blocked from Tayar public registry.',
  },
  {
    id: 'animmaster-lib',
    name: 'Animmaster Lib',
    homepageUrl: 'https://animmasterlib.dev/',
    license: 'restricted',
    redistributionAllowed: false,
    attributionRequired: true,
    note: 'Paid component pack delivered privately after purchase. No public redistribution license was found, so Tayar must not bundle or mirror its code. Future support should use private user-provided licensed imports only.',
  },
  {
    id: 'react-bits',
    name: 'React Bits',
    repository: 'DavidHDev/react-bits',
    license: 'restricted',
    redistributionAllowed: false,
    attributionRequired: true,
    note: 'Current Commons Clause terms prohibit redistributing the components themselves. Keep blocked from the Tayar component registry.',
  },
];

export function getRegistrySource(sourceId: string) {
  return REGISTRY_SOURCES.find((source) => source.id === sourceId);
}

export function isRedistributableSource(sourceId: string): boolean {
  return getRegistrySource(sourceId)?.redistributionAllowed === true;
}
