// AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Source: codse/animata @ de9aabb0eed14e0db944bb07720961ddc450c672
// Generated by Animata's own registry builder, then normalized for Tayar.
export const ANIMATA_CATALOG_REVISION = 'de9aabb0eed14e0db944bb07720961ddc450c672';
export const ANIMATA_CATALOG_COUNT = 154;
export const ANIMATA_CATALOG = [
  {
    "name": "background-animated-beam",
    "title": "Animated Beam",
    "description": "A dark section background where light beams streak diagonally down a grid of faint lines, each at its own length and speed.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/animated-beam.tsx"
      },
      {
        "path": "animata/background/animated-beam.css"
      }
    ]
  },
  {
    "name": "background-blurry-blob",
    "title": "Blurry blob",
    "description": "Animated blurry blob background",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/blurry-blob.tsx"
      }
    ],
    "css": {
      "@keyframes pop-blob": {
        "0%": {
          "transform": "scale(1)"
        },
        "33%": {
          "transform": "scale(1.2)"
        },
        "66%": {
          "transform": "scale(0.8)"
        },
        "100%": {
          "transform": "scale(1)"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-pop-blob": "pop-blob 5s infinite"
      }
    }
  },
  {
    "name": "background-boids-ecosystem",
    "title": "Boids Ecosystem",
    "description": "A canvas flocking simulation — separation, alignment, cohesion — that parts around your cursor like a school of fish.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/boids-ecosystem.tsx"
      }
    ]
  },
  {
    "name": "background-diagonal-lines",
    "title": "Diagonal Lines",
    "description": "A diagonal line background component",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/diagonal-lines.tsx"
      }
    ]
  },
  {
    "name": "background-dot",
    "title": "Dot",
    "description": "A dot background component",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/dot.tsx"
      }
    ]
  },
  {
    "name": "background-grid",
    "title": "Grid",
    "description": "A grid background component",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/grid.tsx"
      }
    ]
  },
  {
    "name": "background-interactive-grid",
    "title": "Interactive Grid",
    "description": "An interactive grid background component.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/interactive-grid.tsx"
      }
    ]
  },
  {
    "name": "background-moving-gradient",
    "title": "Moving Gradient",
    "description": "Animated moving gradient background",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/moving-gradient.tsx"
      }
    ],
    "css": {
      "@keyframes bg-position": {
        "0%": {
          "background-position": "0% 50%"
        },
        "100%": {
          "background-position": "100% 50%"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-bg-position": "bg-position 3s infinite alternate"
      }
    }
  },
  {
    "name": "background-shooting-stars",
    "title": "Shooting Stars",
    "description": "A dark sky where light streaks shoot across at different lengths, speeds and angles over a twinkling starfield.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/shooting-stars.tsx"
      },
      {
        "path": "animata/background/shooting-stars.css"
      }
    ]
  },
  {
    "name": "background-zigzag",
    "title": "Zigzag",
    "description": "A zigzag background component",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/background/zigzag.tsx"
      }
    ]
  },
  {
    "name": "bento-grid-eight",
    "title": "Eight",
    "description": "Bento grid with eight items",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-bar-chart",
      "list-avatar-list",
      "skeleton-report",
      "skeleton-wide-card",
      "text-counter",
      "text-ticker",
      "text-typing-text"
    ],
    "files": [
      {
        "path": "animata/bento-grid/eight.tsx"
      }
    ]
  },
  {
    "name": "bento-grid-gradient",
    "title": "Gradient",
    "description": "Bento grid with gradient background cards",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "background-moving-gradient"
    ],
    "files": [
      {
        "path": "animata/bento-grid/gradient.tsx"
      }
    ]
  },
  {
    "name": "bento-grid-three",
    "title": "Three",
    "description": "Bento grid with 3 items",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "widget-expense-tracker"
    ],
    "files": [
      {
        "path": "animata/bento-grid/three.tsx"
      }
    ]
  },
  {
    "name": "button-ai-button",
    "title": "AI Button",
    "description": "Animated AI button with shimmer effect for loading and idle states.",
    "type": "registry:component",
    "dependencies": [
      "@tsparticles/engine@^3.5.0",
      "@tsparticles/react@^3.0.0",
      "tsparticles@^3.5.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/ai-button.tsx"
      }
    ],
    "css": {
      "@keyframes sparkle": {
        "0%, 100%": {
          "opacity": "0.75",
          "scale": "0.9"
        },
        "50%": {
          "opacity": "1",
          "scale": "1"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-sparkle": "sparkle 2s ease-in-out infinite"
      }
    }
  },
  {
    "name": "button-algolia-blue-button",
    "title": "Algolia Blue Button",
    "description": "Algolia-inspired blue primary button with brand styling and hover state.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/algolia-blue-button.tsx"
      },
      {
        "path": "animata/button/algolia-blue-button.css"
      }
    ]
  },
  {
    "name": "button-algolia-white-button",
    "title": "Algolia White Button",
    "description": "Algolia-inspired white search CTA with icon and hover lift.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/algolia-white-button.tsx"
      },
      {
        "path": "animata/button/algolia-white-button.css"
      }
    ]
  },
  {
    "name": "button-animated-follow-button",
    "title": "Animated Follow Button",
    "description": "Follow/subscribe button with entrance animation and dynamic label swap on click.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/animated-follow-button.tsx"
      }
    ]
  },
  {
    "name": "button-duolingo",
    "title": "Duolingo",
    "description": "Duolingo-style 3D press button with depth and bounce on click.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/duolingo.tsx"
      }
    ]
  },
  {
    "name": "button-get-started-button",
    "title": "Get started button",
    "description": "Gradient CTA button with smooth color shift on hover.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/get-started-button.tsx"
      }
    ]
  },
  {
    "name": "button-ripple-button",
    "title": "Ripple Button",
    "description": "Button with a ripple effect that originates from the cursor position on click.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/ripple-button.tsx"
      },
      {
        "path": "animata/button/ripple-button.css"
      }
    ]
  },
  {
    "name": "button-shining-button",
    "title": "Shining Button",
    "description": "CTA button with a sweeping shine highlight on hover.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/shining-button.tsx"
      }
    ],
    "css": {
      "@keyframes blink-red": {
        "0%, 100%": {
          "background-color": "rgba(239, 68, 68, 0.7)",
          "box-shadow": "0 0 30px 10px rgba(239, 68, 68, 0.5)"
        },
        "50%": {
          "background-color": "rgba(239, 68, 68, 0.5)",
          "box-shadow": "0 0 30px 10px rgba(239, 68, 68, 1)"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--bg-striped": "repeating-linear-gradient(45deg, #3B3A3D, #3B3A3D 5px, transparent 5px, transparent 20px)",
        "--animate-blink-red": "blink-red 2s infinite linear"
      }
    }
  },
  {
    "name": "button-slide-arrow-button",
    "title": "Slide Arrow Button",
    "description": "Arrow CTA with sliding chevron and label shift on hover.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/slide-arrow-button.tsx"
      }
    ]
  },
  {
    "name": "button-status-button",
    "title": "Status Button",
    "description": "Button that animates between idle, loading, and success states on click.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/status-button.tsx"
      }
    ]
  },
  {
    "name": "button-swipe-button",
    "title": "Swipe Button",
    "description": "Swipe-to-confirm button with sliding fill and label transition.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/swipe-button.tsx"
      }
    ]
  },
  {
    "name": "button-toggle-switch",
    "title": "Toggle Switch",
    "description": "Animated toggle switch for on/off settings with smooth thumb transition.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/toggle-switch.tsx"
      }
    ]
  },
  {
    "name": "button-work-button",
    "title": "Work Button",
    "description": "Minimal button with underline and arrow slide on hover.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/button/work-button.tsx"
      }
    ]
  },
  {
    "name": "card-card-comment",
    "title": "Card Comment",
    "description": "A Skeleton of Comment Card",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/card-comment.tsx"
      }
    ]
  },
  {
    "name": "card-card-spread",
    "title": "Card Spread",
    "description": "A stacked deck of widget cards with a hover peek and a throw-on-spread animation — layout-first, CSS-only.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "widget-notes",
      "widget-shopping-list"
    ],
    "files": [
      {
        "path": "animata/card/card-spread.tsx"
      },
      {
        "path": "animata/card/card-spread.css"
      }
    ]
  },
  {
    "name": "card-card-stack",
    "title": "Card Stack",
    "description": "Click-through card stack. The deck loops; cards shuffle in one motion.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/card-stack.tsx"
      },
      {
        "path": "hooks/use-prefers-reduced-motion.ts"
      }
    ]
  },
  {
    "name": "card-case-study-card",
    "title": "Case Study Card",
    "description": "An interactive case study card that expands on hover, revealing a hidden tab with a clickable link to read comments.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/case-study-card.tsx"
      }
    ]
  },
  {
    "name": "card-collab-card",
    "title": "Collab Card",
    "description": "Bento tile for realtime collaboration—not a generic card. Live presence, selection frame, teammate cursors.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/collab-card.tsx"
      },
      {
        "path": "animata/card/collab-card.css"
      }
    ]
  },
  {
    "name": "card-flip-card",
    "title": "Flip Card",
    "description": "A dynamic flip card featuring smooth 180-degree flip animations along both the X and Y axes.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/flip-card.tsx"
      }
    ]
  },
  {
    "name": "card-github-card-shiny",
    "title": "GitHub Card - Shiny",
    "description": "A card component where a shiny background follows the mouse when hovered, as seen in GitHub's homepage",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/github-card-shiny.tsx"
      },
      {
        "path": "hooks/use-mouse-position.ts"
      }
    ]
  },
  {
    "name": "card-github-card-skew",
    "title": "GitHub Card - Skew",
    "description": "A card component which skews  when hovered, as seen in GitHub's homepage",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/github-card-skew.tsx"
      },
      {
        "path": "hooks/use-mouse-position.ts"
      }
    ]
  },
  {
    "name": "card-glowing-card",
    "title": "Glowing Card",
    "description": "The card glows in gradient colours when hovered",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/glowing-card.tsx"
      }
    ],
    "cssVars": {
      "theme": {
        "--shadow-glow": "0 0 20px rgba(255, 204, 112, 0.7), 0 0 40px rgba(200, 80, 192, 0.5), 0 0 60px rgba(65, 88, 208, 0.3)",
        "--shadow-glow2": "0 0 20px rgba(50, 255, 50, 0.7), 0 0 40px rgba(20, 200, 20, 0.5), 0 0 60px rgba(5, 150, 5, 0.3)",
        "--blur-20": "20px",
        "--blur-25": "25px",
        "--brightness-150": "1.5"
      }
    }
  },
  {
    "name": "card-led-board",
    "title": "Led Board",
    "description": "A component that mimicks LED board and can display words; as seen in NextJS's homepage. Hover over the component to see the animation.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/card/led-board.tsx"
      }
    ],
    "css": {
      "@keyframes led": {
        "0%": {
          "fill": "currentColor",
          "brightness": "1"
        },
        "50%": {
          "fill": "#a855f7",
          "brightness": "500%"
        },
        "100%": {
          "fill": "currentColor",
          "brightness": "1"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-led": "led 100ms ease-in-out"
      }
    }
  },
  {
    "name": "card-swap-text-card",
    "title": "Swap Text Card",
    "description": "Text inside the card swaps",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "text-swap-text"
    ],
    "files": [
      {
        "path": "animata/card/swap-text-card.tsx"
      }
    ]
  },
  {
    "name": "container-animated-border-trail",
    "title": "Animated Border Trail",
    "description": "A container with animated border trail, this can be used for buttons as well as cards.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/container/animated-border-trail.tsx"
      },
      {
        "path": "animata/container/animated-border-trail.css"
      }
    ]
  },
  {
    "name": "container-announcement-ribbon",
    "title": "Announcement Ribbon",
    "description": "A sticky scrolling banner for top-of-page announcements.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "container-marquee"
    ],
    "files": [
      {
        "path": "animata/container/announcement-ribbon.tsx"
      }
    ]
  },
  {
    "name": "container-cursor-tracker",
    "title": "Cursor Tracker",
    "description": "A wrapper component that tracks the cursor moving within it",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/container/cursor-tracker.tsx"
      },
      {
        "path": "hooks/use-mouse-position.ts"
      }
    ]
  },
  {
    "name": "container-marquee",
    "title": "Marquee",
    "description": "A marquee component",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/container/marquee.tsx"
      },
      {
        "path": "animata/container/marquee.css"
      }
    ]
  },
  {
    "name": "container-sibling-focus-nav",
    "title": "Sibling Focus Nav",
    "description": "A nav row that dims or blurs sibling links when one item is hovered or focused — padding-based spacing keeps the effect alive between items.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/container/sibling-focus-nav.tsx"
      }
    ],
    "css": {
      "[&": "has(>a:hover)>a:not(:hover)]:opacity-30\n[&:has(>a:focus-visible)>a:not(:focus-visible)]:opacity-30"
    }
  },
  {
    "name": "fabs-flower-menu",
    "title": "Flower Menu",
    "description": "Circular FAB that fans links out from a center toggle. CSS stagger, keyboard nav.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/fabs/flower-menu.tsx"
      },
      {
        "path": "animata/fabs/flower-menu.css"
      }
    ]
  },
  {
    "name": "fabs-speed-dial",
    "title": "Speed Dial",
    "description": "FAB that expands into a row of actions on click. CSS stagger, no hover gate.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/fabs/speed-dial.tsx"
      },
      {
        "path": "animata/fabs/speed-dial.css"
      }
    ]
  },
  {
    "name": "graphs-bar-chart",
    "title": "Bar Chart",
    "description": "A sample bar chart for widgets/presentation",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/graphs/bar-chart.tsx"
      }
    ]
  },
  {
    "name": "graphs-donut-chart",
    "title": "Donut Chart",
    "description": "A simple donut chart for showing progress. Useful for widget and bento grids.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/graphs/donut-chart.tsx"
      }
    ]
  },
  {
    "name": "graphs-gauge-chart",
    "title": "Gauge Chart",
    "description": "This graph shows the progress in a donut chart with a gap at bottom.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/graphs/gauge-chart.tsx"
      }
    ]
  },
  {
    "name": "graphs-progress",
    "title": "Progress",
    "description": "A sample progress graph for widgets/presentation. This is not a full-fledged chart library. Just use for presentation or as an interactive part of the app.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/graphs/progress.tsx"
      }
    ]
  },
  {
    "name": "graphs-ring-chart",
    "title": "Ring Chart",
    "description": "A simple ring-chart chart as seen in iOS apps",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-donut-chart"
    ],
    "files": [
      {
        "path": "animata/graphs/ring-chart.tsx"
      }
    ]
  },
  {
    "name": "hero-hero-section-text-hover",
    "title": "Hero Section Text Hover",
    "description": "Hover on \"Uncharted Adventures\" and \"Feel Alive\" text to reveal the images.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/hero/hero-section-text-hover.tsx"
      }
    ]
  },
  {
    "name": "hero-product-features",
    "title": "Product Features",
    "description": "A hero section showcasing product features",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0",
      "react-wrap-balancer@^1.1.1"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/hero/product-features.tsx"
      }
    ]
  },
  {
    "name": "hero-shape-shifter",
    "title": "Shape Shifter",
    "description": "A hero section with a shape-shifting component in the center",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "container-marquee"
    ],
    "files": [
      {
        "path": "animata/hero/shape-shifter.tsx"
      }
    ],
    "css": {
      "@keyframes shape-shift": {
        "0%": {
          "width": "40px",
          "height": "20px"
        },
        "20%": {
          "width": "240px",
          "height": "128px"
        },
        "40%": {
          "width": "80px",
          "height": "80px"
        },
        "80%": {
          "width": "128px",
          "height": "240px"
        },
        "100%": {
          "width": "40px",
          "height": "20px"
        }
      }
    }
  },
  {
    "name": "hero-slack-intro",
    "title": "Slack's intro screen",
    "description": "An intro hero inspired by Slack's intro screen.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "text-wave-reveal"
    ],
    "files": [
      {
        "path": "animata/hero/slack-intro.tsx"
      }
    ]
  },
  {
    "name": "icon-hover-interaction",
    "title": "Hover Interaction",
    "description": "This is a component which shows icon based on text hovered by user. By default it has alreay imported Twitter/x, Framer, Figma, Instagram, GitHub, LinkedIn, and it shows Square-Box icon by default it user tries to get other icons without importing. Importing steps are provided below.",
    "type": "registry:component",
    "dependencies": [
      "@radix-ui/react-icons@^1.3.2",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/icon/hover-interaction.tsx"
      }
    ]
  },
  {
    "name": "icon-icon-ripple",
    "title": "Icon Ripple",
    "description": "Create a ripple animation on an icon",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/icon/icon-ripple.tsx"
      }
    ]
  },
  {
    "name": "image-disclose-image",
    "title": "Disclose Image",
    "description": "Reveal the image using a sliding door-like effect",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/image/disclose-image.tsx"
      }
    ],
    "cssVars": {
      "theme": {
        "--ease-slow": "cubic-bezier(.405, 0, .025, 1)",
        "--duration-mid": "3s"
      }
    }
  },
  {
    "name": "image-images-reveal",
    "title": "Images Reveal",
    "description": "An image reveal animation",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/image/images-reveal.tsx"
      }
    ]
  },
  {
    "name": "image-skew-image",
    "title": "Skew Image",
    "description": "A component that skews an image on hover.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/image/skew-image.tsx"
      }
    ]
  },
  {
    "name": "image-tilted-cover",
    "title": "Tilted Cover",
    "description": "A titled image component with a background element",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/image/tilted-cover.tsx"
      }
    ],
    "cssVars": {
      "theme": {
        "--ease-slow": "cubic-bezier(.405, 0, .025, 1)",
        "--ease-minor-spring": "cubic-bezier(0.18, 0.89, 0.82, 1.04)"
      }
    }
  },
  {
    "name": "image-trailing-image",
    "title": "Trailing Image",
    "description": "A trailing effect where the images move with the mouse.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/image/trailing-image.tsx"
      },
      {
        "path": "hooks/use-mouse-position.ts"
      }
    ]
  },
  {
    "name": "list-avatar-list",
    "title": "Avatar List",
    "description": "A component that displays list of user's avatar",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/avatar-list.tsx"
      }
    ],
    "css": {
      "@keyframes bg-position": {
        "0%": {
          "background-position": "0% 50%"
        },
        "100%": {
          "background-position": "100% 50%"
        }
      }
    }
  },
  {
    "name": "list-flipping-cards",
    "title": "Flipping cards",
    "description": "A list of flip cards arranged, each card representing an item or concept. Hovering on a card flips it to reveal additional details.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "card-flip-card"
    ],
    "files": [
      {
        "path": "animata/list/flipping-cards.tsx"
      }
    ]
  },
  {
    "name": "list-menu-animation",
    "title": "Menu list",
    "description": "Animation for menu list",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/menu-animation.tsx"
      }
    ]
  },
  {
    "name": "list-orbiting-items-3-d",
    "title": "Orbiting Items 3D",
    "description": "List component with orbiting items. The items orbit around the center of an element in 3D Ellipse.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/orbiting-items-3-d.tsx"
      }
    ],
    "css": {
      "@keyframes float": {
        "0%, 100%": {
          "transform": "translateY(0)"
        },
        "50%": {
          "transform": "translateY(-40px)"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-float": "float 3s ease-in-out infinite"
      }
    }
  },
  {
    "name": "list-orbiting-items",
    "title": "Orbiting Items",
    "description": "List component with orbiting items. The items orbit around the center of the list.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/orbiting-items.tsx"
      }
    ],
    "css": {
      "@keyframes rotate-full": {
        "0%": {
          "transform": "rotate(0deg)"
        },
        "100%": {
          "transform": "rotate(360deg)"
        }
      }
    }
  },
  {
    "name": "list-reveal-image",
    "title": "Reveal images",
    "description": "Reveals the images on hover.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/reveal-image.tsx"
      }
    ]
  },
  {
    "name": "list-transaction-list",
    "title": "Transaction List",
    "description": "A simple component to list all the recent transaction.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/list/transaction-list.tsx"
      }
    ]
  },
  {
    "name": "overlay-modal",
    "title": "Modal",
    "description": "A modal is a dialog that overlays the primary content with a window, drawing the user's attention exclusively to specific information.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/overlay/modal.tsx"
      }
    ]
  },
  {
    "name": "preloader-split-reveal",
    "title": "Split Reveal",
    "description": "Full-screen preloader that loads images, locks scroll, then opens from the center seam.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/preloader/split-reveal.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/index.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/images.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/preload-images.ts"
      },
      {
        "path": "animata/preloader/split-reveal/types.ts"
      },
      {
        "path": "animata/preloader/split-reveal/task.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/context.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/overlay.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/progress.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/progress-count.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/progress-slot.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/progress-track.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/root.tsx"
      },
      {
        "path": "animata/preloader/split-reveal/execute-task.ts"
      },
      {
        "path": "animata/preloader/split-reveal/shutter.tsx"
      },
      {
        "path": "animata/preloader/split-reveal.css"
      },
      {
        "path": "hooks/use-prefers-reduced-motion.ts"
      },
      {
        "path": "hooks/use-lock-body.ts"
      }
    ]
  },
  {
    "name": "preloader-vertical-tiles",
    "title": "Vertical Tiles",
    "description": "A preloader component that makes transition to any section look vivid",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/preloader/vertical-tiles.tsx"
      }
    ]
  },
  {
    "name": "progress-animatedtimeline",
    "title": "Animated Timeline",
    "description": "The Animated Timeline component is an interactive, visually appealing timeline that responds to user interaction. Built with Framer Motion and React, this component highlights key events or milestones in a vertical timeline structure.When a user hovers over a specific timeline item, the associated circular dot and all previous dots in the sequence turn green, indicating progression. The dot size also enlarges slightly, enhancing the focus on the current event. The component offers a sleek and smooth animation experience, perfect for showcasing chronological steps, milestones, or achievements in an engaging and user-friendly manner.This component is highly customizable, allowing easy modifications to the timeline content and styling, making it suitable for diverse applications such as resumes, project timelines, or product roadmaps.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/progress/animatedtimeline.tsx"
      }
    ]
  },
  {
    "name": "progress-spinner",
    "title": "Spinner",
    "description": "Just a spinner to check the loading state",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/progress/spinner.tsx"
      }
    ]
  },
  {
    "name": "scroll-stacked-sections",
    "title": "Stacked Sections",
    "description": "A vertical deck primitive that pins each child as a sticky pane, leaving a thin strip of the one before visible above — a true stack of cards.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/scroll/stacked-sections.tsx"
      },
      {
        "path": "animata/scroll/stacked-sections.css"
      }
    ]
  },
  {
    "name": "skeleton-code",
    "title": "Code",
    "description": "Code-block skeleton with a Lucide icon and stacked text bars.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/code.tsx"
      }
    ]
  },
  {
    "name": "skeleton-cookie-banner",
    "title": "Cookie Banner",
    "description": "Consent-style skeleton with body copy lines and a full-width action bar.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/cookie-banner.tsx"
      }
    ]
  },
  {
    "name": "skeleton-list",
    "title": "List",
    "description": "List-row skeleton with avatar dots, text bars, and dual action buttons.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/list.tsx"
      }
    ]
  },
  {
    "name": "skeleton-receipt",
    "title": "Receipt",
    "description": "Receipt-style loading placeholder with header icons and staggered line items.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/receipt.tsx"
      }
    ]
  },
  {
    "name": "skeleton-report",
    "title": "Report",
    "description": "Export-card skeleton with a CSV badge and uniform data rows.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/report.tsx"
      }
    ]
  },
  {
    "name": "skeleton-wide-card",
    "title": "Wide Card",
    "description": "Horizontal card skeleton with thumbnail, text lines, and a compact CTA block.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/skeleton/wide-card.tsx"
      }
    ]
  },
  {
    "name": "tabs-fluid-tabs",
    "title": "Fluid Tabs",
    "description": "Composable tabs with a sliding pill indicator and manual keyboard selection.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/tabs/fluid-tabs.tsx"
      },
      {
        "path": "animata/tabs/shared.ts"
      }
    ]
  },
  {
    "name": "tabs-gooey-tabs",
    "title": "Gooey Tabs",
    "description": "Icon tabs that merge with an SVG goo filter when one label expands to show its title.",
    "type": "registry:component",
    "dependencies": [
      "@phosphor-icons/react@^2.1.10",
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/tabs/gooey-tabs.tsx"
      },
      {
        "path": "animata/tabs/shared.ts"
      }
    ]
  },
  {
    "name": "tabs-shift-tabs",
    "title": "Shift Tabs",
    "description": "Composable shift-style tabs with hover tilt and manual keyboard selection.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/tabs/shift-tabs.tsx"
      },
      {
        "path": "animata/tabs/shared.ts"
      }
    ]
  },
  {
    "name": "text-animated-gradient-text",
    "title": "Animated Gradient Text",
    "description": "A component to animate the text using gradient",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/animated-gradient-text.tsx"
      }
    ],
    "css": {
      "@keyframes bg-position": {
        "0%": {
          "background-position": "0% 50%"
        },
        "100%": {
          "background-position": "100% 50%"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-bg-position": "bg-position 3s infinite alternate"
      }
    }
  },
  {
    "name": "text-blur-out-up",
    "title": "Blur Out Up",
    "description": "Words arrive clean and depart upward with increasing blur for airy exits.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/blur-out-up.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-bold-copy",
    "title": "Bold Copy",
    "description": "A text effect with bold text as background",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/bold-copy.tsx"
      }
    ]
  },
  {
    "name": "text-bottom-up-letters",
    "title": "Bottom-Up Letters",
    "description": "Letters rise from below in a pronounced staircase, one symbol at a time, with zero blur.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/bottom-up-letters.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-circular-text",
    "title": "Circular Text",
    "description": "Displays text arranged in a rotating circular path with customizable speed.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/circular-text.tsx"
      }
    ]
  },
  {
    "name": "text-counter",
    "title": "Counter",
    "description": "A counter component that counts up to given number. Works with both increment and decrement.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/counter.tsx"
      }
    ]
  },
  {
    "name": "text-cycle-text",
    "title": "Cycle Text",
    "description": "A component that cycles text over certain interval.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/cycle-text.tsx"
      }
    ]
  },
  {
    "name": "text-double-underline",
    "title": "Double Underline",
    "description": "Show double underline for the text on hover or click",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/double-underline.tsx"
      }
    ]
  },
  {
    "name": "text-fade-through",
    "title": "Fade Through",
    "description": "A Material-style content transition: old fades out, new fades in with a soft delay.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/fade-through.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-focus-blur-resolve",
    "title": "Focus Blur Resolve",
    "description": "A premium focus pull from heavy blur to crisp text, then a soft blur-out exit.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/focus-blur-resolve.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-gibberish-text",
    "title": "Gibberish Text",
    "description": "A component that displays gibberish text initially and then reveals the actual text.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/gibberish-text.tsx"
      }
    ]
  },
  {
    "name": "text-glitch-text",
    "title": "Glitch text",
    "description": "RGB-split glitch on text — two colored ghosts jitter on a loop while the label stays sharp on top.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/glitch-text.tsx"
      },
      {
        "path": "animata/text/glitch-text.css"
      }
    ]
  },
  {
    "name": "text-jitter-text",
    "title": "Jitter Text",
    "description": "Animated Text component that applies a jittery effect",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/jitter-text.tsx"
      }
    ]
  },
  {
    "name": "text-jumping-text-instagram",
    "title": "Jumping Text (Instagram)",
    "description": "Jumping text effect similar to the one seen in Instagram's text effects",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/jumping-text-instagram.tsx"
      }
    ]
  },
  {
    "name": "text-kinetic-center-build",
    "title": "Kinetic Center Build",
    "description": "A word appears in the center; each new word enters from right to left with a soft blur and pushes the existing line until the full phrase locks centered.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/kinetic-center-build.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-line-by-line-slide",
    "title": "Line-by-Line Slide",
    "description": "Each line enters from the left with a staggered slide and exits to the right for a flowing paragraph reveal.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/line-by-line-slide.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-mask-reveal-up",
    "title": "Mask Reveal Up",
    "description": "Lines reveal upward with a soft masked feel and compact stagger.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/mask-reveal-up.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-metis-text",
    "title": "Metis text",
    "description": "Hover draws an underline in from the left; on exit it retracts back out to the right.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/metis-text.tsx"
      },
      {
        "path": "animata/text/metis-text.css"
      }
    ]
  },
  {
    "name": "text-micro-scale-fade",
    "title": "Micro Scale Fade",
    "description": "A calm, tiny scale pop used as subtle premium polish for labels and headings.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/micro-scale-fade.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-mirror-text",
    "title": "Mirror Text",
    "description": "An effect where given text has the mirror/clone text and follows it.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/mirror-text.tsx"
      }
    ]
  },
  {
    "name": "text-per-character-rise",
    "title": "Per-Character Rise",
    "description": "Letters slide up from below with no blur — crisp, deliberate, kinetic. Apple's clean tvOS-style reveal.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/per-character-rise.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-per-word-crossfade",
    "title": "Per-Word Crossfade",
    "description": "Words gently fade into place one after another, with a short vertical drift for a calm keynote rhythm.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/per-word-crossfade.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-roll-text",
    "title": "Roll text",
    "description": "Stacked text layers that roll vertically on hover — top slides up, bottom rises in. Playback latches until the animation finishes.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/roll-text.tsx"
      },
      {
        "path": "animata/text/roll-text.css"
      }
    ]
  },
  {
    "name": "text-scale-down-fade",
    "title": "Scale Down Fade",
    "description": "Subtle premium settle-in with a restrained scale-down fade on exit.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/scale-down-fade.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-scroll-reveal",
    "title": "Scroll Reveal",
    "description": "A component that reveals text based on the scroll position. Make sure to scroll inside the preview to see the effect.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/scroll-reveal.tsx"
      }
    ],
    "css": {
      ".scroll-baby[style*=\"opacity: 1\"]": {
        "@apply text-yellow-300 dark": "text-yellow-500"
      },
      ".scroll-file[style*=\"opacity: 1\"]": {
        "@apply text-blue-300 dark": "text-blue-500"
      }
    }
  },
  {
    "name": "text-shared-axis-y",
    "title": "Shared Axis Y",
    "description": "Per-word hard-cut transition with staircase timing for sharp editorial swaps.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/shared-axis-y.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-shared-axis-z",
    "title": "Shared Axis Z",
    "description": "Scale-based shared-axis transition for focus shifts and context depth.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/shared-axis-z.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-shimmer-sweep",
    "title": "Shimmer Sweep",
    "description": "A subtle sweep across a clean headline, blending in while gliding from left to center.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/shimmer-sweep.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-short-slide-down",
    "title": "Short Slide Down",
    "description": "Each new word drops in from above into its own line and pushes the existing stack downward until a centered three-line composition locks in place.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/short-slide-down.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-short-slide-right",
    "title": "Short Slide Right",
    "description": "The whole phrase glides in from the left as one compact move, while the words themselves are revealed in sequence only through opacity.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/short-slide-right.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-soft-blur-in",
    "title": "Soft Blur In",
    "description": "Per-character fade-in with a gentle blur and upward motion. Apple's signature hero-title reveal.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/soft-blur-in.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-split-text",
    "title": "Split Text",
    "description": "A text effect where the text splits into two when hovered",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/split-text.tsx"
      }
    ]
  },
  {
    "name": "text-spring-scale-in",
    "title": "Spring Scale In",
    "description": "Words pop in with a soft overshoot scale, like a physical spring settling into place.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/spring-scale-in.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-swap-text",
    "title": "Swap Text",
    "description": "A component that swaps text on click or hover.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/swap-text.tsx"
      }
    ],
    "cssVars": {
      "theme": {
        "--ease-slow": "cubic-bezier(.405, 0, .025, 1)",
        "--ease-minor-spring": "cubic-bezier(0.18, 0.89, 0.82, 1.04)"
      }
    }
  },
  {
    "name": "text-text-border-animation",
    "title": "Text Border Animation",
    "description": "Border animation below text",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/text-border-animation.tsx"
      }
    ]
  },
  {
    "name": "text-text-explode-imessage",
    "title": "Text Explode (iMessage)",
    "description": "Text explode effect as seen in iMessage",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/text-explode-imessage.tsx"
      }
    ]
  },
  {
    "name": "text-text-flip",
    "title": "Text Flip",
    "description": "Text with flipping effect",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/text-flip.tsx"
      }
    ],
    "css": {
      "@keyframes flip-words": {
        "10%": {
          "transform": "translateY(-112%)"
        },
        "25%": {
          "transform": "translateY(-100%)"
        },
        "35%": {
          "transform": "translateY(-212%)"
        },
        "50%": {
          "transform": "translateY(-200%)"
        },
        "60%": {
          "transform": "translateY(-312%)"
        },
        "75%": {
          "transform": "translateY(-300%)"
        },
        "85%": {
          "transform": "translateY(-412%)"
        },
        "100%": {
          "transform": "translateY(-400%)"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--animate-flip-words": "flip-words 8s infinite"
      }
    }
  },
  {
    "name": "text-ticker",
    "title": "Ticker",
    "description": "A ticker component that animates number on change",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/ticker.tsx"
      }
    ]
  },
  {
    "name": "text-top-down-letters",
    "title": "Top-Down Letters",
    "description": "Letters descend from above in a pronounced staircase, one symbol at a time, with zero blur.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/top-down-letters.tsx"
      },
      {
        "path": "animata/text/text-animator.css"
      },
      {
        "path": "animata/text/text-animator.tsx"
      },
      {
        "path": "animata/text/text-animator-demo.ts"
      }
    ]
  },
  {
    "name": "text-typing-text",
    "title": "Typing Text",
    "description": "Creates a typing effect for given text",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/typing-text.tsx"
      }
    ]
  },
  {
    "name": "text-underline-hover-text",
    "title": "Underline hover text",
    "description": "A customizable text component with an underline hover effect.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/underline-hover-text.tsx"
      }
    ]
  },
  {
    "name": "text-wave-reveal",
    "title": "Wave Reveal",
    "description": "Reveal letter or word one by one with a wave effect & optional blur effect.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/text/wave-reveal.tsx"
      }
    ],
    "css": {
      "@keyframes reveal-up": {
        "0%": {
          "opacity": "0",
          "transform": "translateY(80%)"
        },
        "100%": {
          "opacity": "1",
          "transform": "translateY(0)"
        }
      },
      "@keyframes reveal-down": {
        "0%": {
          "opacity": "0",
          "transform": "translateY(-80%)"
        },
        "100%": {
          "opacity": "1",
          "transform": "translateY(0)"
        }
      },
      "@keyframes content-blur": {
        "0%": {
          "filter": "blur(0.3rem)"
        },
        "100%": {
          "filter": "blur(0)"
        }
      }
    },
    "cssVars": {
      "theme": {
        "--ease-minor-spring": "cubic-bezier(0.18, 0.89, 0.82, 1.04)"
      }
    }
  },
  {
    "name": "widget-alarm-clock",
    "title": "Alarm Clock",
    "description": "Toggle one or two alarms on a compact card — built for a morning routine glance.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [
      "button-toggle-switch"
    ],
    "files": [
      {
        "path": "animata/widget/alarm-clock.tsx"
      }
    ]
  },
  {
    "name": "widget-battery-level",
    "title": "Battery Level",
    "description": "A widget that shows battery level of different devices",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-donut-chart"
    ],
    "files": [
      {
        "path": "animata/widget/battery-level.tsx"
      }
    ]
  },
  {
    "name": "widget-battery",
    "title": "Battery",
    "description": "This is a basic widget that shows battery percentage.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/battery.tsx"
      }
    ]
  },
  {
    "name": "widget-calendar-event",
    "title": "Calendar event",
    "description": "Show today’s date plus the next events — built for a calendar home-screen widget.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/calendar-event.tsx"
      }
    ]
  },
  {
    "name": "widget-calorie-counter",
    "title": "Calorie Counter",
    "description": "A calorie counter for your app",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-donut-chart"
    ],
    "files": [
      {
        "path": "animata/widget/calorie-counter.tsx"
      }
    ]
  },
  {
    "name": "widget-clock-with-photo",
    "title": "Clock With Photo",
    "description": "A widget to display clock with photo",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/clock-with-photo.tsx"
      }
    ]
  },
  {
    "name": "widget-cycling",
    "title": "Cycling",
    "description": "A widget that shows the distance covered and heart-rate of cyclist",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-progress",
      "text-swap-text"
    ],
    "files": [
      {
        "path": "animata/widget/cycling.tsx"
      }
    ]
  },
  {
    "name": "widget-delivery-card",
    "title": "Delivery Card",
    "description": "Show delivery ETA, status, and route progress on a single home-screen tile.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/delivery-card.tsx"
      }
    ]
  },
  {
    "name": "widget-direction-card",
    "title": "Direction Card",
    "description": "A direction card which adapts itself on directions and distance",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/direction-card.tsx"
      }
    ]
  },
  {
    "name": "widget-expense-tracker",
    "title": "Expense Tracker",
    "description": "Tracks your weekly spending or expenses",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/expense-tracker.tsx"
      }
    ]
  },
  {
    "name": "widget-flight-widget",
    "title": "Flight widget",
    "description": "A widget that shows flight detail",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/flight-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-fund-widget",
    "title": "Fund Widget",
    "description": "This component is a financial dashboard-like UI element for showing the current status of the funds.",
    "type": "registry:component",
    "dependencies": [
      "motion@^12.38.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/fund-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-live-score",
    "title": "Live score",
    "description": "Live score widget that displays the score of a match.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/live-score.tsx"
      }
    ]
  },
  {
    "name": "widget-mobile-detail",
    "title": "Mobile Detail",
    "description": "Mobile widget",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/mobile-detail.tsx"
      }
    ]
  },
  {
    "name": "widget-music-widget",
    "title": "Music Widget",
    "description": "Widget to display music playing/paused.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/music-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-notes",
    "title": "Notes",
    "description": "A notes widget",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/notes.tsx"
      }
    ]
  },
  {
    "name": "widget-profile",
    "title": "Profile",
    "description": "A widget that shows user profile",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/profile.tsx"
      }
    ]
  },
  {
    "name": "widget-reminder-widget",
    "title": "Reminder Widget",
    "description": "Reminder widget",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/reminder-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-reminder",
    "title": "Reminder",
    "description": "Glance at open tasks by list and see what is coming up next.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/reminder.tsx"
      }
    ]
  },
  {
    "name": "widget-score-board",
    "title": "Score Board",
    "description": "A widget that shows progress and score",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-bar-chart"
    ],
    "files": [
      {
        "path": "animata/widget/score-board.tsx"
      }
    ]
  },
  {
    "name": "widget-security-alert",
    "title": "Security Alert",
    "description": "This widget notifies the user about a security alert in the system.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/security-alert.tsx"
      }
    ]
  },
  {
    "name": "widget-shopping-list",
    "title": "Shopping List",
    "description": "A shopping list widget",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/shopping-list.tsx"
      }
    ]
  },
  {
    "name": "widget-sleep-tracker",
    "title": "Sleep Tracker",
    "description": "An elegant sleep tracker for your use",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [
      "graphs-bar-chart"
    ],
    "files": [
      {
        "path": "animata/widget/sleep-tracker.tsx"
      }
    ]
  },
  {
    "name": "widget-storage-status",
    "title": "Storage Status",
    "description": "This widget shows storage occupied by different file.",
    "type": "registry:component",
    "dependencies": [],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/storage-status.tsx"
      }
    ]
  },
  {
    "name": "widget-storage-widget",
    "title": "Storage Widget",
    "description": "A widget to display storage",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/storage-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-study-timer",
    "title": "Study Timer",
    "description": "Displays a study timer with segmented time tracking.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/study-timer.tsx"
      }
    ]
  },
  {
    "name": "widget-vpn-widget",
    "title": "VPN Connection",
    "description": "See server, speed, and connection status at a glance — with a slide-to-connect control.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/vpn-widget.tsx"
      }
    ]
  },
  {
    "name": "widget-water-tracker",
    "title": "Water Tracker",
    "description": "Track daily water intake with a glanceable fill bar and one-tap top-ups.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/water-tracker.tsx"
      }
    ]
  },
  {
    "name": "widget-weather-card",
    "title": "Weather Card",
    "description": "Current temperature, feels-like, and today’s high/low for any city.",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/weather-card.tsx"
      }
    ]
  },
  {
    "name": "widget-weekly-progress",
    "title": "Weekly progress",
    "description": "A widget that shows weekly progress",
    "type": "registry:component",
    "dependencies": [
      "lucide-react@^0.475.0"
    ],
    "registryDependencies": [],
    "files": [
      {
        "path": "animata/widget/weekly-progress.tsx"
      }
    ]
  }
] as const;
