import { useLocalizer } from '@/lib/ui-localization';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { createEditorControllerState } from '../core/editor-controller';
import { createEditorShellContract, type EditorShellAdapterCallbacks } from '../core/editor-shell-adapter';
import type { EditorInspectorTab, EditorLeftPanel, EditorPreviewDevice } from '../core/editor-layout';
import type { EditorContainerLike, EditorElementLike, EditorPageLike, EditorProjectLike, EditorSectionLike } from '../core/editor-model';
import type { EditorSelection } from '../core/editor-selection';
import type { EditorShellContract } from '../core/editor-shell-contract';
import type { EditorInsertCatalogItem } from '../core/editor-insert-catalog';
import type { EditorMediaAsset } from '../core/editor-media-library';
import type { EditorNativeOperation } from '../core/editor-native-operation';
import type { EditorTemplateLibraryItem } from '../core/editor-template-library';
import type { EditorQualityIssue } from '../core/editor-site-quality';
import type { EditorPublishPlan, EditorPublishRedirect, EditorPublishRevision } from '../core/editor-publishing';
import { createElement as createWebsiteElement, createSection as createWebsiteSection } from '../core/defaults';
import type { SectionType, WebsiteElementType } from '../core/types';
import { BuilderPageSeoPanel } from './BuilderPageSeoPanel';
import { BuilderPublishingMaxPanel } from './BuilderPublishingMaxPanel';
import { BuilderRedirectsPanel } from './BuilderRedirectsPanel';
import { BuilderPublishVersionsPanel } from './BuilderPublishVersionsPanel';
import { BuilderSiteQualityPanel } from './BuilderSiteQualityPanel';
import { BuilderV2NativeBridge } from './BuilderV2NativeBridge';
import './website-builder-v2.css';

export interface WebsiteBuilderV2BridgeProps {
  canvas: ReactNode; overlaySlot?: ReactNode; aiPanel?: ReactNode; cmsPanel?: ReactNode; topbarTrailingSlot?: ReactNode; sitePanel?: ReactNode; settingsPanel?: ReactNode;
  symbols?: EditorProjectLike['symbols']; onCreateSymbol?(): void; onDetachSymbol?(): void; onInsertSymbol?(symbolId: string): void; onDeleteSymbol?(symbolId: string): void; onRenameSymbol?(symbolId: string, name: string): void; onDuplicateSymbol?(symbolId: string): void; onSelectSymbolInstance?(symbolId: string): void;
  pages: EditorPageLike[]; homePageId?: string; activePageId: string; selectedSectionId?: string | null; selectedElementId?: string | null; selectedElementIds?: string[]; selectedContainerId?: string | null; selectedFormFieldId?: string | null;
  device: EditorPreviewDevice; dirty: boolean; canUndo: boolean; canRedo: boolean;
  historyEntries?: Array<{ id: string; label: string; createdAt: number; source: 'manual' | 'ai' | 'system' }>; futureEntries?: Array<{ id: string; label: string; createdAt: number; source: 'manual' | 'ai' | 'system' }>;
  saving?: boolean; publishing?: boolean; checking?: boolean; mutating?: boolean; saveError?: string; publishError?: string; checkScore?: number; checkErrors?: number; checkWarnings?: number; lastCheckedAt?: number; publishedUrl?: string; publishedAt?: number; publishedOutdated?: boolean; liveVerification?: 'idle' | 'checking' | 'healthy' | 'failed'; publishBlockers?: string[]; mediaAssets?: EditorMediaAsset[]; accent?: string;
  publishRedirects?: EditorPublishRedirect[]; publishRevisions?: EditorPublishRevision[]; restoringRevisionId?: string;
  onPublishPlan?(plan: EditorPublishPlan): void | Promise<void>; onChangePublishRedirects?(redirects: EditorPublishRedirect[]): void; onSavePublishRedirects?(): void | Promise<void>; onRestorePublishRevision?(revision: EditorPublishRevision): void | Promise<void>; onOpenDomains?(): void;
  onMediaOpen?(): void; onMediaUpload?(): void; onGenerateMediaWithAI?(prompt: string): void | Promise<void>; onAddPage?(): void; onMovePage?(pageId: string, direction: 'up' | 'down'): void; onDuplicatePage?(): void; onDeletePage?(): void; onSetHomePage?(): void;
  onMoveSection?(sectionId: string, direction: 'up' | 'down'): void; onDuplicateSection?(sectionId: string): void; onDeleteSection?(sectionId: string): void; onMoveElement?(sectionId: string, elementId: string, direction: 'up' | 'down'): void; onDuplicateElement?(sectionId: string, elementId: string): void;
  onCopySelection?(): void; onCutSelection?(): void; onPasteSelection?(): void; clipboardKind?: 'element' | 'elements' | 'section'; onDeleteElement?(sectionId: string, elementId: string): void;
  onApplyOperations(operations: EditorNativeOperation[], nextSelection?: EditorSelection): void; onRestoreHistoryEntry?(entryId: string): void; onUndo(): void; onRedo(): void; onSave(): void; onPreview(): void; onPublish(): void; onRunCheck(): void; onSetDevice(device: EditorPreviewDevice): void; onSelect(selection: EditorSelection): void; onSelectElement?(sectionId: string, elementId: string, additive?: boolean, range?: boolean): void;
  onCustomizeTemplateWithAI?(template: EditorTemplateLibraryItem, prompt: string): void | Promise<void>; onFixSiteQualityWithAI?(issues: EditorQualityIssue[]): void | Promise<void>;
}
const SECTION_TYPES = new Set<SectionType>(['hero','features','about','services','pricing','testimonials','contact','footer']);
function createNativeId(prefix:string){const uuid=globalThis.crypto?.randomUUID?.();return uuid?`${prefix}-${uuid}`:`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
export function WebsiteBuilderV2Bridge(props:WebsiteBuilderV2BridgeProps){
 const {canvas,overlaySlot,aiPanel,cmsPanel,topbarTrailingSlot,sitePanel,settingsPanel,symbols=[],pages,homePageId,activePageId,selectedSectionId,selectedElementId,selectedElementIds=[],selectedContainerId,selectedFormFieldId,device,dirty,canUndo,canRedo,historyEntries=[],futureEntries=[],saving,publishing,checking,mutating,saveError,publishError,checkScore,checkErrors,checkWarnings,lastCheckedAt,publishedUrl,publishedAt,publishedOutdated,liveVerification,publishBlockers=[],mediaAssets=[],accent='#7c3aed',publishRedirects=[],publishRevisions=[],restoringRevisionId,onPublishPlan,onChangePublishRedirects,onSavePublishRedirects,onRestorePublishRevision,onOpenDomains,onMediaOpen,onMediaUpload,onGenerateMediaWithAI,onAddPage,onMovePage,onDuplicatePage,onDeletePage,onSetHomePage,onMoveSection,onDuplicateSection,onDeleteSection,onMoveElement,onDuplicateElement,onCopySelection,onCutSelection,onPasteSelection,clipboardKind,onDeleteElement,onApplyOperations,onRestoreHistoryEntry,onUndo,onRedo,onSave,onPreview,onPublish,onRunCheck,onSetDevice,onSelect,onSelectElement,onCustomizeTemplateWithAI,onFixSiteQualityWithAI,onCreateSymbol,onDetachSymbol,onInsertSymbol,onDeleteSymbol,onRenameSymbol,onDuplicateSymbol,onSelectSymbolInstance}=props;
 const l=useLocalizer(); const [leftPanel,setLeftPanel]=useState<EditorLeftPanel>('pages'); const [leftSidebarOpen,setLeftSidebarOpen]=useState(true); const [inspectorOpen,setInspectorOpen]=useState(true); const [inspectorTab,setInspectorTab]=useState<EditorInspectorTab>('content'); const [focusMode,setFocusMode]=useState(false); const [publishingTool,setPublishingTool]=useState<'release'|'redirects'|'versions'>('release');
 const unsavedExitMessage=l('You have unsaved website changes. Leave without saving?');
 useEffect(()=>{if(!dirty||typeof window==='undefined')return;const before=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=unsavedExitMessage;};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty,unsavedExitMessage]);
 const selection=useMemo<EditorSelection>(()=>({pageId:activePageId,sectionId:selectedSectionId||undefined,elementId:selectedElementId||undefined,containerId:selectedContainerId||undefined,formFieldId:selectedFormFieldId||undefined}),[activePageId,selectedSectionId,selectedElementId,selectedContainerId,selectedFormFieldId]);
 const project=useMemo<EditorProjectLike>(()=>({id:'website-builder-v2',pages,homePageId,symbols}),[pages,homePageId,symbols]);
 const controllerState=useMemo(()=>createEditorControllerState(project,{selection,layout:{leftPanel,leftSidebarOpen,inspectorOpen,inspectorTab,focusMode,previewDevice:device}}),[project,selection,leftPanel,leftSidebarOpen,inspectorOpen,inspectorTab,focusMode,device]);
 const shellCallbacks=useMemo<EditorShellAdapterCallbacks>(()=>({undo:onUndo,redo:onRedo,save:onSave,preview:onPreview,publish:onPublish,runCheck:()=>{setLeftPanel('settings');setLeftSidebarOpen(true);setFocusMode(false);onRunCheck();},toggleFocus:()=>setFocusMode(x=>!x),toggleLeftSidebar:()=>setLeftSidebarOpen(x=>!x),toggleInspector:()=>setInspectorOpen(x=>!x),openLeftPanel:panel=>{setLeftPanel(panel);setLeftSidebarOpen(true);setFocusMode(false);if(panel==='media')onMediaOpen?.();},openInspectorTab:tab=>{setInspectorTab(tab);setInspectorOpen(true);setFocusMode(false);},setPreviewDevice:onSetDevice,select:onSelect}),[onUndo,onRedo,onSave,onPreview,onPublish,onRunCheck,onSetDevice,onSelect,onMediaOpen]);
 const baseShell=useMemo(()=>createEditorShellContract(controllerState,shellCallbacks,{saving,publishing,checking,mutating,saveError,publishError,checkScore,checkErrors,checkWarnings,lastCheckedAt,publishedUrl,publishedAt,publishedOutdated,liveVerification}),[controllerState,shellCallbacks,saving,publishing,checking,mutating,saveError,publishError,checkScore,checkErrors,checkWarnings,lastCheckedAt,publishedUrl,publishedAt,publishedOutdated,liveVerification]);
 const shell=useMemo<EditorShellContract>(()=>{const blockers=publishBlockers.map((message,index)=>({code:`V1_PREFLIGHT_${index+1}`,severity:'blocker' as const,message}));return {...baseShell,view:{...baseShell.view,dirty,canUndo,canRedo,publish:{...baseShell.view.publish,canPublish:blockers.length===0,blockers},history:{undo:[...historyEntries].reverse().map(entry=>({...entry,direction:'undo' as const})),redo:futureEntries.map(entry=>({...entry,direction:'redo' as const})),latest:historyEntries.at(-1)?{...historyEntries.at(-1)!,direction:'undo' as const}:undefined,total:historyEntries.length+futureEntries.length}}};},[baseShell,dirty,canUndo,canRedo,historyEntries,futureEntries,publishBlockers]);
 const activePage=pages.find(page=>page.id===activePageId)??pages[0];
 function createNativeSection(item:EditorInsertCatalogItem):EditorSectionLike{const requested=item.sectionType as SectionType|undefined;const type:SectionType=requested&&SECTION_TYPES.has(requested)?requested:item.id==='contact-form'?'contact':'features';return createWebsiteSection(type) as unknown as EditorSectionLike;}
 function createNativeContainer(_item:EditorInsertCatalogItem):EditorContainerLike{return {id:createNativeId('container'),name:'Container',layout:'stack',gap:16,align:'stretch',backgroundColor:'transparent',padding:0,borderRadius:0,borderWidth:0,borderColor:'#374151',shadow:'none'};}
 function createNativeElement(item:EditorInsertCatalogItem,asset?:EditorMediaAsset):EditorElementLike{if(!item.elementType||item.elementType==='container')throw new Error(`Invalid V2 element type: ${item.id}`);const element=createWebsiteElement(item.elementType as WebsiteElementType,accent) as unknown as EditorElementLike;return asset&&item.elementType==='image'?{...element,src:asset.url,content:asset.alt||asset.name,alt:asset.alt||asset.name}:element;}
 const qualityPanel=<BuilderSiteQualityPanel project={project} onSelectIssue={item=>{onSelect({pageId:item.pageId||activePageId,sectionId:item.sectionId,elementId:item.elementId});setInspectorOpen(true);}} onFixWithAI={onFixSiteQualityWithAI}/>; const seoPanel=<BuilderPageSeoPanel page={activePage} onApplyOperations={onApplyOperations}/>;
 const publishingPanel=<><BuilderPublishingMaxPanel pages={pages} publishing={publishing} onPublishPlan={onPublishPlan} onOpenRedirects={()=>setPublishingTool('redirects')} onOpenVersions={()=>setPublishingTool('versions')} onOpenDomains={onOpenDomains}/>{publishingTool==='redirects'&&<BuilderRedirectsPanel redirects={publishRedirects} onChange={onChangePublishRedirects||(()=>{})} onSave={onSavePublishRedirects}/>} {publishingTool==='versions'&&<BuilderPublishVersionsPanel revisions={publishRevisions} environment="production" restoringId={restoringRevisionId} onRestore={onRestorePublishRevision}/>}</>;
 const combinedSettingsPanel=<>{publishingPanel}{qualityPanel}{seoPanel}{settingsPanel}</>;
 return <BuilderV2NativeBridge shell={shell} project={project} selection={selection} selectedElementIds={selectedElementIds} onSelectElement={onSelectElement} brandSlot={<div><strong>{l('Website Builder')}</strong><small style={{marginLeft:8,opacity:.55}}>V2</small></div>} topbarCenterSlot={<span>{activePage?.name||'Website'}</span>} canvas={canvas} canvasOverlaySlot={overlaySlot} topbarTrailingSlot={topbarTrailingSlot} aiPanel={aiPanel} cmsPanel={cmsPanel} sitePanel={sitePanel} settingsPanel={combinedSettingsPanel} symbols={symbols} onCreateSymbol={onCreateSymbol} onDetachSymbol={onDetachSymbol} onInsertSymbol={onInsertSymbol} onDeleteSymbol={onDeleteSymbol} onRenameSymbol={onRenameSymbol} onDuplicateSymbol={onDuplicateSymbol} onSelectSymbolInstance={onSelectSymbolInstance} mediaAssets={mediaAssets} onMediaUpload={onMediaUpload} onGenerateMediaWithAI={onGenerateMediaWithAI} onAddPage={onAddPage} onMovePage={onMovePage} onDuplicatePage={onDuplicatePage} onDeletePage={onDeletePage} onSetHomePage={onSetHomePage} onMoveSection={onMoveSection} onDuplicateSection={onDuplicateSection} onDeleteSection={onDeleteSection} onMoveElement={onMoveElement} onDuplicateElement={onDuplicateElement} onCopySelection={onCopySelection} onCutSelection={onCutSelection} onPasteSelection={onPasteSelection} clipboardKind={clipboardKind} onDeleteElement={onDeleteElement} onPreviewTemplate={()=>onPreview()} onCustomizeTemplateWithAI={template=>void onCustomizeTemplateWithAI?.(template,`Customize the ${template.kind} template "${template.name}" for this website.`)} createSection={createNativeSection} createContainer={createNativeContainer} createElement={createNativeElement} onApplyOperations={onApplyOperations} onRestoreHistoryEntry={onRestoreHistoryEntry}/>;
}
export default WebsiteBuilderV2Bridge;
