// Generated by scripts/build-website-supabase-connection.mjs; edit server/service source.
/* eslint-disable no-var, @typescript-eslint/no-unused-vars -- Generated bundle. */

// server/website-supabase-connection-edge.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

// src/modules/website-builder/services/trustedServerRuntime.ts
function isUntrustedBrowserRuntime() {
  const deno = globalThis.Deno;
  return typeof window !== "undefined" && typeof deno?.version?.deno !== "string";
}

// src/modules/website-builder/services/websiteConnectionOAuthStateService.ts
var uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var statePattern = /^[0-9a-f]{64}$/;
var providers = ["github", "supabase", "vercel", "stripe"];
function serverOnly() {
  if (isUntrustedBrowserRuntime()) throw new Error("OAuth state requires a trusted server.");
}
async function hash(state2) {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(state2));
  return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join("");
}
async function createWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!uuid.test(input.ownerId) || !uuid.test(input.projectId) || !providers.includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  const raw = Array.from(crypto.getRandomValues(new Uint8Array(32)), (byte) => byte.toString(16).padStart(2, "0")).join("");
  const digest = await hash(raw);
  const expiresAt = new Date((input.now ?? Date.now)() + 9 * 6e4).toISOString();
  const { error } = await input.client.rpc("website_create_connection_oauth_state", {
    p_state_hash: digest,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_expires_at: expiresAt
  });
  if (error || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  return raw;
}
async function consumeWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!statePattern.test(input.state) || !providers.includes(input.provider)) throw new Error("Connection state is invalid or expired.");
  const { data, error } = await input.client.rpc("website_consume_connection_oauth_state", { p_state_hash: await hash(input.state) });
  if (error || !data || !uuid.test(data.ownerId) || !uuid.test(data.projectId) || data.provider !== input.provider || !["preview", "production"].includes(data.environment)) {
    throw new Error("Connection state is invalid or expired.");
  }
  return { ownerId: data.ownerId, projectId: data.projectId, provider: data.provider, environment: data.environment };
}

// src/modules/website-builder/services/websiteSupabaseOAuthService.ts
var statePattern2 = /^[0-9a-f]{64}$/;
var codePattern = /^[A-Za-z0-9._~-]{1,2048}$/;
var clientPattern = /^[A-Za-z0-9_-]{5,128}$/;
function callbackUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || url.search && url.search !== "?action=callback") {
    throw new Error("Supabase connection is not configured.");
  }
  return url.toString();
}
function encoded(bytes) {
  return btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}
async function verifier(state2, secret2) {
  if (!statePattern2.test(state2) || secret2.length < 32 || secret2.length > 4096) {
    throw new Error("Supabase connection is not configured.");
  }
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret2),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  return encoded(new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`supabase-pkce:${state2}`))));
}
async function supabaseAuthorizationUrl(input) {
  if (isUntrustedBrowserRuntime() || !clientPattern.test(input.clientId)) throw new Error("Supabase connection is not configured.");
  const codeVerifier = await verifier(input.state, input.pkceSecret);
  const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(codeVerifier)));
  const url = new URL("https://api.supabase.com/v1/oauth/authorize");
  url.searchParams.set("client_id", input.clientId);
  url.searchParams.set("redirect_uri", callbackUrl(input.callback));
  url.searchParams.set("response_type", "code");
  url.searchParams.set("state", input.state);
  url.searchParams.set("code_challenge", encoded(digest));
  url.searchParams.set("code_challenge_method", "S256");
  return url.toString();
}
async function acceptSupabaseOAuthCallback(input) {
  if (isUntrustedBrowserRuntime() || !clientPattern.test(input.clientId) || !input.clientSecret || input.clientSecret.length > 4096 || /[\r\n]/.test(input.clientSecret) || !codePattern.test(input.code)) throw new Error("Supabase authorization failed.");
  const callback = callbackUrl(input.callback);
  const codeVerifier = await verifier(input.state, input.pkceSecret);
  const scope = await consumeWebsiteConnectionOAuthState({
    client: input.stateClient,
    state: input.state,
    provider: "supabase"
  });
  try {
    const credentials = encoded(new TextEncoder().encode(`${input.clientId}:${input.clientSecret}`));
    const basic = credentials.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(credentials.length / 4) * 4, "=");
    const response = await (input.fetcher ?? fetch)("https://api.supabase.com/v1/oauth/token", {
      method: "POST",
      redirect: "error",
      cache: "no-store",
      signal: AbortSignal.timeout(8e3),
      headers: {
        Accept: "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: `Basic ${basic}`
      },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        code: input.code,
        redirect_uri: callback,
        code_verifier: codeVerifier
      })
    });
    if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 16384) throw new Error();
    const raw = await response.text();
    if (raw.length > 16384) throw new Error();
    const tokens = JSON.parse(raw);
    if (tokens?.token_type?.toLowerCase() !== "bearer" || typeof tokens.access_token !== "string" || tokens.access_token.length < 20 || tokens.access_token.length > 4096 || typeof tokens.refresh_token !== "string" || tokens.refresh_token.length < 20 || tokens.refresh_token.length > 4096 || !Number.isInteger(tokens.expires_in) || tokens.expires_in < 60 || tokens.expires_in > 86400) throw new Error();
    return {
      ownerId: scope.ownerId,
      projectId: scope.projectId,
      environment: scope.environment,
      accessToken: tokens.access_token,
      refreshToken: tokens.refresh_token,
      expiresIn: tokens.expires_in
    };
  } catch {
    throw new Error("Supabase authorization failed.");
  }
}

// src/modules/website-builder/services/websiteConnectionHandoffService.ts
var uuid2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function serverOnly2() {
  if (isUntrustedBrowserRuntime()) throw new Error("Connection handoff requires a trusted server.");
}
async function storeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !["github", "supabase", "vercel", "stripe"].includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.userToken || input.userToken.length < 20 || new TextEncoder().encode(input.userToken).length > 65536) {
    throw new Error("Connection handoff could not be stored.");
  }
  const id = crypto.randomUUID();
  const { error } = await input.client.rpc("website_store_connection_handoff", {
    p_id: id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_token: input.userToken,
    p_expires_at: new Date((input.now ?? Date.now)() + 4 * 6e4).toISOString()
  });
  if (error) throw new Error("Connection handoff could not be stored.");
  return id;
}
async function consumeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_consume_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > 65536 || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}
async function peekWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_peek_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > 65536 || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}

// src/modules/website-builder/services/websiteSupabaseProjectBindingService.ts
var uuid3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var ref = /^[a-z]{20}$/;
var slug = /^[a-z0-9][a-z0-9-]{0,199}$/;
var token = (value) => typeof value === "string" && value.length >= 20 && new TextEncoder().encode(value).length <= 4096 && !/[\r\n]/.test(value);
function encodeSupabaseOAuthHandoff(grant) {
  if (!token(grant.accessToken) || !token(grant.refreshToken) || !Number.isInteger(grant.expiresIn) || grant.expiresIn < 60 || grant.expiresIn > 86400 || !Number.isFinite(Date.parse(grant.receivedAt))) throw new Error("Supabase authorization is unavailable.");
  return JSON.stringify(grant);
}
function decodeGrant(value) {
  let grant;
  try {
    grant = JSON.parse(value);
  } catch {
    throw new Error("Supabase authorization is unavailable.");
  }
  if (!token(grant.accessToken) || !token(grant.refreshToken) || !Number.isInteger(grant.expiresIn) || grant.expiresIn < 60 || grant.expiresIn > 86400 || !Number.isFinite(Date.parse(grant.receivedAt)) || Date.parse(grant.receivedAt) + grant.expiresIn * 1e3 <= Date.now()) {
    throw new Error("Supabase authorization is unavailable.");
  }
  return grant;
}
async function api(accessToken, path, fetcher) {
  const response = await fetcher(`https://api.supabase.com/v1/${path}`, {
    method: "GET",
    redirect: "error",
    cache: "no-store",
    headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" },
    signal: AbortSignal.timeout(8e3)
  });
  if (response.status !== 200 || Number(response.headers.get("content-length") ?? 0) > 65536) throw new Error();
  const text = await response.text();
  if (text.length > 65536) throw new Error();
  return JSON.parse(text);
}
async function listWebsiteSupabaseProjectChoices(input) {
  if (isUntrustedBrowserRuntime() || !uuid3.test(input.ownerId) || !uuid3.test(input.projectId) || !uuid3.test(input.handoffId) || !input.platformOrganizationId || !input.isCurrentOwner()) {
    throw new Error("Supabase projects are unavailable.");
  }
  try {
    const handoff = await peekWebsiteConnectionHandoff({
      client: input.client,
      id: input.handoffId,
      ownerId: input.ownerId,
      projectId: input.projectId,
      provider: "supabase",
      isCurrentOwner: input.isCurrentOwner
    });
    const grant = decodeGrant(handoff.userToken), fetcher = input.fetcher ?? fetch;
    const [profile, organizations, projects] = await Promise.all([
      api(grant.accessToken, "profile", fetcher),
      api(grant.accessToken, "organizations", fetcher),
      api(grant.accessToken, "projects", fetcher)
    ]);
    if (!profile || typeof profile !== "object" || Array.isArray(profile) || typeof profile.gotrue_id !== "string" || !Array.isArray(organizations) || organizations.length > 100 || !Array.isArray(projects) || projects.length > 500) throw new Error();
    const accountUserId = profile.gotrue_id;
    const owned = /* @__PURE__ */ new Map();
    for (const raw of organizations) {
      if (!raw || typeof raw !== "object") throw new Error();
      const org = raw;
      if (typeof org.id !== "string" || !org.id || org.id === input.platformOrganizationId || typeof org.slug !== "string" || !slug.test(org.slug) || typeof org.name !== "string" || !org.name.trim() || org.name.length > 200) continue;
      const members = await api(grant.accessToken, `organizations/${org.slug}/members`, fetcher);
      if (!Array.isArray(members) || members.length > 1e3) throw new Error();
      if (members.filter((member) => member && typeof member === "object" && member.user_id === accountUserId && member.role_name === "Owner").length === 1) {
        owned.set(org.id, { id: org.id, slug: org.slug, name: org.name.trim() });
      }
    }
    const choices = [];
    for (const raw of projects) {
      if (!raw || typeof raw !== "object") throw new Error();
      const project = raw, org = owned.get(String(project.organization_id));
      if (!org || typeof project.ref !== "string" || !ref.test(project.ref) || typeof project.name !== "string" || !project.name.trim() || project.name.length > 200 || project.status !== "ACTIVE_HEALTHY") continue;
      choices.push({
        projectRef: project.ref,
        projectName: project.name.trim(),
        organizationId: org.id,
        organizationSlug: org.slug,
        organizationName: org.name
      });
    }
    if (!input.isCurrentOwner()) throw new Error();
    choices.sort((a, b) => a.organizationName.localeCompare(b.organizationName) || a.projectName.localeCompare(b.projectName) || a.projectRef.localeCompare(b.projectRef));
    return { accountUserId, projects: choices };
  } catch {
    throw new Error("Supabase projects are unavailable.");
  }
}
async function bindWebsiteSupabaseProject(input) {
  if (isUntrustedBrowserRuntime() || !uuid3.test(input.ownerId) || !uuid3.test(input.projectId) || !uuid3.test(input.handoffId) || input.connectionId !== void 0 && !uuid3.test(input.connectionId) || Boolean(input.connectionId) !== Boolean(input.expectedVersion) || input.expectedVersion !== void 0 && (!Number.isSafeInteger(input.expectedVersion) || input.expectedVersion < 1) || !ref.test(input.projectRef) || !slug.test(input.organizationSlug) || !input.organizationId || input.organizationId === input.platformOrganizationId || !input.isCurrentOwner()) {
    throw new Error("Supabase project could not be connected.");
  }
  const connectionId = input.connectionId ?? input.handoffId, expectedVersion = input.expectedVersion ?? 0;
  const reconcile = async () => {
    const { data, error } = await input.client.rpc("website_reconcile_supabase_project_binding", {
      p_connection_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_expected_version: expectedVersion,
      p_project_ref: input.projectRef,
      p_operation_id: input.handoffId
    });
    if (error || !input.isCurrentOwner()) throw new Error();
    return data === expectedVersion + 1;
  };
  try {
    if (await reconcile()) return { connectionId, projectRef: input.projectRef, version: expectedVersion + 1 };
    const handoff = await consumeWebsiteConnectionHandoff({
      client: input.client,
      id: input.handoffId,
      ownerId: input.ownerId,
      projectId: input.projectId,
      provider: "supabase",
      isCurrentOwner: input.isCurrentOwner
    });
    const grant = decodeGrant(handoff.userToken);
    const choices = await listDirect(grant.accessToken, input, input.fetcher ?? fetch);
    if (!choices) throw new Error();
    const accessExpiresAt = new Date(Date.parse(grant.receivedAt) + grant.expiresIn * 1e3).toISOString();
    const { data, error } = await input.client.rpc("website_bind_supabase_project", {
      p_connection_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_expected_version: expectedVersion,
      p_environment: handoff.environment,
      p_account_id: input.accountUserId,
      p_organization_id: input.organizationId,
      p_organization_slug: input.organizationSlug,
      p_project_ref: input.projectRef,
      p_access_token: grant.accessToken,
      p_refresh_token: grant.refreshToken,
      p_access_expires_at: accessExpiresAt,
      p_custody_expires_at: new Date(Date.now() + 30 * 864e5).toISOString(),
      p_operation_id: input.handoffId
    });
    if (error || data !== expectedVersion + 1 || !input.isCurrentOwner()) {
      if (await reconcile()) return { connectionId, projectRef: input.projectRef, version: expectedVersion + 1 };
      throw new Error();
    }
    return { connectionId, projectRef: input.projectRef, version: data };
  } catch {
    throw new Error("Supabase project could not be connected.");
  }
}
async function listDirect(accessToken, input, fetcher) {
  if (!input.isCurrentOwner()) return false;
  const [profile, project, members] = await Promise.all([
    api(accessToken, "profile", fetcher),
    api(accessToken, `projects/${input.projectRef}`, fetcher),
    api(accessToken, `organizations/${input.organizationSlug}/members`, fetcher)
  ]);
  return input.isCurrentOwner() && !!profile && typeof profile === "object" && !Array.isArray(profile) && profile.gotrue_id === input.accountUserId && !!project && typeof project === "object" && !Array.isArray(project) && project.ref === input.projectRef && project.organization_id === input.organizationId && project.organization_slug === input.organizationSlug && project.status === "ACTIVE_HEALTHY" && input.organizationId !== input.platformOrganizationId && Array.isArray(members) && members.filter((member) => member && typeof member === "object" && member.user_id === input.accountUserId && member.role_name === "Owner").length === 1;
}

// server/website-supabase-connection.ts
var uuid4 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var state = /^[a-f0-9]{64}$/;
var code = /^[A-Za-z0-9._~-]{1,2048}$/;
var ref2 = /^[a-z]{20}$/;
var slug2 = /^[a-z0-9][a-z0-9-]{0,199}$/;
var responseHeaders = {
  "cache-control": "no-store",
  "referrer-policy": "no-referrer",
  "content-security-policy": "default-src 'none'",
  "x-content-type-options": "nosniff"
};
var json = (status, body) => new Response(
  JSON.stringify(body),
  { status, headers: { ...responseHeaders, "content-type": "application/json" } }
);
function fixedHttps(value, callback = false) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || (callback ? url.search !== "?action=callback" : !!url.search)) throw new Error();
  return url;
}
async function handleWebsiteSupabaseConnection(request, context) {
  let callback, destination;
  try {
    callback = fixedHttps(context.callback, true);
    destination = fixedHttps(context.returnUrl);
    if (!callback.pathname.endsWith("/functions/v1/website-supabase-connection") || !/^[A-Za-z0-9_-]{5,128}$/.test(context.clientId) || !context.clientSecret || context.pkceSecret.length < 32 || !context.platformOrganizationId) throw new Error();
  } catch {
    return json(503, { error: "Supabase connection is not configured." });
  }
  const action = new URL(request.url).searchParams.get("action");
  if (action === "callback") {
    if (request.method !== "GET") return json(405, { error: "Method not allowed." });
    const params = new URL(request.url).searchParams;
    if (params.has("error") || !state.test(params.get("state") ?? "") || !code.test(params.get("code") ?? ""))
      return json(400, { error: "Supabase authorization failed. Start the connection again." });
    try {
      const grant = await acceptSupabaseOAuthCallback({
        stateClient: context.platform,
        state: params.get("state"),
        code: params.get("code"),
        clientId: context.clientId,
        clientSecret: context.clientSecret,
        callback: callback.toString(),
        pkceSecret: context.pkceSecret,
        fetcher: context.fetcher
      });
      const handoffId = await storeWebsiteConnectionHandoff({
        client: context.platform,
        ownerId: grant.ownerId,
        projectId: grant.projectId,
        environment: grant.environment,
        provider: "supabase",
        userToken: encodeSupabaseOAuthHandoff({
          accessToken: grant.accessToken,
          refreshToken: grant.refreshToken,
          expiresIn: grant.expiresIn,
          receivedAt: (/* @__PURE__ */ new Date()).toISOString()
        })
      });
      destination.hash = new URLSearchParams({ tayar_supabase_handoff: handoffId }).toString();
      return new Response(null, { status: 303, headers: { ...responseHeaders, location: destination.toString() } });
    } catch {
      return json(409, { error: "Supabase authorization could not be completed. Start again." });
    }
  }
  if (!["begin", "options", "bind"].includes(action ?? "") || request.method !== "POST")
    return json(405, { error: "Method not allowed." });
  if (!/^application\/json(?:\s*;|$)/i.test(request.headers.get("content-type") ?? ""))
    return json(415, { error: "JSON request required." });
  const bearer = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/i.exec(request.headers.get("authorization") ?? "")?.[1];
  if (!bearer || bearer.length > 16384) return json(401, { error: "Sign in required." });
  let ownerId, input, projectId;
  try {
    const identity = await context.platform.auth.getUser(bearer);
    if (identity.error || !identity.data.user || identity.data.user.is_anonymous || !uuid4.test(identity.data.user.id)) throw new Error();
    ownerId = identity.data.user.id;
  } catch {
    return json(401, { error: "Sign in required." });
  }
  try {
    if (Number(request.headers.get("content-length") ?? 0) > 8192) throw new Error();
    const body = await request.text();
    if (body.length > 8192) throw new Error();
    input = JSON.parse(body);
    const keys2 = action === "begin" ? ["projectId", "environment"] : action === "options" ? ["projectId", "handoffId"] : [
      "projectId",
      "handoffId",
      "connectionId",
      "expectedVersion",
      "projectRef",
      "organizationId",
      "organizationSlug",
      "accountUserId"
    ];
    if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).some((key) => !keys2.includes(key)) || typeof input.projectId !== "string" || !uuid4.test(input.projectId) || action === "begin" && !["preview", "production"].includes(String(input.environment)) || action !== "begin" && (typeof input.handoffId !== "string" || !uuid4.test(input.handoffId))) throw new Error();
    if (action === "bind" && (typeof input.projectRef !== "string" || !ref2.test(input.projectRef) || typeof input.organizationId !== "string" || !input.organizationId || typeof input.organizationSlug !== "string" || !slug2.test(input.organizationSlug) || typeof input.accountUserId !== "string" || !input.accountUserId)) throw new Error();
    projectId = input.projectId;
  } catch {
    return json(400, { error: "Invalid connection request." });
  }
  try {
    const { data, error } = await context.platform.from("projects").select("id").eq("id", projectId).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
    if (error) return json(503, { error: "Project is unavailable." });
    if (!data) return json(404, { error: "Project not found." });
    if (action === "begin") {
      const rawState = await createWebsiteConnectionOAuthState({
        client: context.platform,
        ownerId,
        projectId,
        environment: input.environment,
        provider: "supabase",
        isCurrentOwner: () => true
      });
      return json(200, { authorizationUrl: await supabaseAuthorizationUrl({
        clientId: context.clientId,
        callback: callback.toString(),
        state: rawState,
        pkceSecret: context.pkceSecret
      }) });
    }
    if (action === "options") return json(200, await listWebsiteSupabaseProjectChoices({
      client: context.platform,
      ownerId,
      projectId,
      handoffId: input.handoffId,
      platformOrganizationId: context.platformOrganizationId,
      isCurrentOwner: () => true,
      fetcher: context.fetcher
    }));
    const result = await bindWebsiteSupabaseProject({
      client: context.platform,
      ownerId,
      projectId,
      handoffId: input.handoffId,
      connectionId: input.connectionId,
      expectedVersion: input.expectedVersion,
      projectRef: input.projectRef,
      organizationId: input.organizationId,
      organizationSlug: input.organizationSlug,
      accountUserId: input.accountUserId,
      platformOrganizationId: context.platformOrganizationId,
      isCurrentOwner: () => true,
      fetcher: context.fetcher
    });
    return json(200, { status: "connected", ...result });
  } catch {
    return json(409, { error: "Supabase connection could not be completed. Refresh and try again." });
  }
}

// server/website-supabase-connection-edge.ts
var provider = /^[A-Za-z0-9_-]{5,128}$/;
var organization = /^[A-Za-z0-9_-]{1,128}$/;
var publicSecret = /^(?:NEXT_PUBLIC_|VITE_|PUBLIC_).*?(?:SECRET|SERVICE_ROLE|PKCE)/i;
var keys = {
  url: "SUPABASE_URL",
  secret: "SUPABASE_SERVICE_ROLE_KEY",
  clientId: "WEBSITE_SUPABASE_OAUTH_CLIENT_ID",
  clientSecret: "WEBSITE_SUPABASE_OAUTH_CLIENT_SECRET",
  pkceSecret: "WEBSITE_SUPABASE_PKCE_SECRET",
  callback: "WEBSITE_SUPABASE_CALLBACK_URL",
  returnUrl: "WEBSITE_SUPABASE_RETURN_URL",
  organization: "WEBSITE_SUPABASE_PLATFORM_ORGANIZATION_ID"
};
var fixedHeaders = {
  "cache-control": "no-store",
  "referrer-policy": "no-referrer",
  "content-security-policy": "default-src 'none'",
  "x-content-type-options": "nosniff"
};
function required(environment, key, max) {
  const value = environment[key];
  if (typeof value !== "string" || !value || value.length > max || value.trim() !== value || value.includes(String.fromCharCode(0))) throw new Error();
  return value;
}
function platformUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== value || url.pathname !== "/" || url.port || url.username || url.password || url.search || url.hash || !/^[a-z0-9]{20}[.]supabase[.]co$/.test(url.hostname)) throw new Error();
  return url.origin;
}
function callbackUrl2(value, platformOrigin) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== platformOrigin || url.username || url.password || url.hash || url.search !== "?action=callback" || !url.pathname.endsWith("/functions/v1/website-supabase-connection")) throw new Error();
  return url.toString();
}
function browserReturn(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.username || url.password || url.hash || url.search) throw new Error();
  return { value: url.toString(), origin: url.origin };
}
function legacyServiceRole(value) {
  try {
    const parts = value.split(".");
    if (parts.length !== 3 || parts.some((part) => !part)) return false;
    const base = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const payload = JSON.parse(atob(base.padEnd(Math.ceil(base.length / 4) * 4, "=")));
    return !!payload && typeof payload === "object" && payload.role === "service_role";
  } catch {
    return false;
  }
}
function serviceKey(value) {
  if (/[\s\r\n]/.test(value) || value.length > 4096 || !/^sb_secret_[A-Za-z0-9_-]{20,}$/.test(value) && !legacyServiceRole(value)) throw new Error();
  return value;
}
function secret(value, minimum) {
  if (value.length < minimum || /[\r\n]/.test(value)) throw new Error();
  return value;
}
function json2(status, error) {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { ...fixedHeaders, "content-type": "application/json" }
  });
}
function createWebsiteSupabaseConnectionEdge(input) {
  try {
    if (input.fetcher !== void 0 && typeof input.fetcher !== "function") throw new Error();
    for (const [key, value] of Object.entries(input.environment)) if (value && publicSecret.test(key)) throw new Error();
    const url = platformUrl(required(input.environment, keys.url, 2048));
    const serviceRole = serviceKey(required(input.environment, keys.secret, 4096));
    const clientId = required(input.environment, keys.clientId, 128);
    const clientSecret = secret(required(input.environment, keys.clientSecret, 4096), 20);
    const pkceSecret = secret(required(input.environment, keys.pkceSecret, 4096), 32);
    const callback = callbackUrl2(required(input.environment, keys.callback, 2048), url);
    const destination = browserReturn(required(input.environment, keys.returnUrl, 2048));
    const platformOrganizationId = required(input.environment, keys.organization, 128);
    if (!provider.test(clientId) || !organization.test(platformOrganizationId)) throw new Error();
    const factory = input.clientFactory ?? createClient;
    const options = {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
      ...input.fetcher ? { global: { fetch: input.fetcher } } : {}
    };
    const platform = factory(url, serviceRole, options);
    return async (request) => {
      const origin = request.headers.get("origin");
      const headers = new Headers(fixedHeaders);
      headers.set("vary", "Origin");
      if (origin && origin !== destination.origin) return json2(403, "Origin not allowed.");
      if (origin) headers.set("access-control-allow-origin", origin);
      headers.set("access-control-allow-methods", "POST, GET, OPTIONS");
      headers.set("access-control-allow-headers", "authorization, apikey, content-type, x-client-info");
      if (request.method === "OPTIONS") return new Response(null, { status: 204, headers });
      try {
        const response = await handleWebsiteSupabaseConnection(request, {
          platform,
          clientId,
          clientSecret,
          pkceSecret,
          callback,
          returnUrl: destination.value,
          platformOrganizationId,
          fetcher: input.fetcher
        });
        const combined = new Headers(response.headers);
        headers.forEach((value, key) => combined.set(key, value));
        return new Response(response.body, { status: response.status, headers: combined });
      } catch {
        return json2(503, "Supabase connection is unavailable.");
      }
    };
  } catch {
    throw new Error("Supabase connection deployment unavailable.");
  }
}
function createWebsiteSupabaseConnectionDeployment(input) {
  try {
    return createWebsiteSupabaseConnectionEdge(input);
  } catch {
    return async () => json2(503, "Supabase connection is unavailable.");
  }
}
export {
  createWebsiteSupabaseConnectionDeployment,
  createWebsiteSupabaseConnectionEdge
};
Deno.serve(createWebsiteSupabaseConnectionDeployment({environment:{"SUPABASE_URL":Deno.env.get("SUPABASE_URL"),"SUPABASE_SERVICE_ROLE_KEY":Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),"WEBSITE_SUPABASE_OAUTH_CLIENT_ID":Deno.env.get("WEBSITE_SUPABASE_OAUTH_CLIENT_ID"),"WEBSITE_SUPABASE_OAUTH_CLIENT_SECRET":Deno.env.get("WEBSITE_SUPABASE_OAUTH_CLIENT_SECRET"),"WEBSITE_SUPABASE_PKCE_SECRET":Deno.env.get("WEBSITE_SUPABASE_PKCE_SECRET"),"WEBSITE_SUPABASE_CALLBACK_URL":Deno.env.get("WEBSITE_SUPABASE_CALLBACK_URL"),"WEBSITE_SUPABASE_RETURN_URL":Deno.env.get("WEBSITE_SUPABASE_RETURN_URL"),"WEBSITE_SUPABASE_PLATFORM_ORGANIZATION_ID":Deno.env.get("WEBSITE_SUPABASE_PLATFORM_ORGANIZATION_ID")}}));
