import React from 'react';
import { Check, Sparkles, Trash2 } from 'lucide-react';
import { CVProposal } from './cv-proposals';

interface Props {
  proposals: CVProposal[];
  onVerifyApply: (id: string) => void;
  onDismiss: (id: string) => void;
}

export function CVAIProposalPanel({ proposals, onVerifyApply, onDismiss }: Props) {
  return <div className="space-y-3">
    <div className="rounded-xl border border-violet-500/20 bg-violet-600/5 p-3">
      <div className="flex items-center gap-2"><Sparkles aria-hidden="true" className="w-4 h-4 text-violet-400" /><h3 className="text-white text-sm font-semibold">AI proposals to review</h3><span className="ml-auto text-[10px] text-violet-300" aria-label={`${proposals.length} proposals`}>{proposals.length}</span></div>
      <p className="text-gray-400 text-[11px] mt-1">AI suggestions are drafts only. Verify that each statement is factually true before applying it to your CV.</p>
    </div>
    {!proposals.length ? <div className="rounded-xl border border-white/10 bg-white/[0.02] py-8 px-4 text-center" role="status"><Sparkles aria-hidden="true" className="w-6 h-6 text-gray-600 mx-auto mb-2" /><p className="text-gray-400 text-xs font-medium">No AI proposals waiting for review</p><p className="text-gray-600 text-[11px] mt-1">Suggestions generated by CV AI tools will appear here before they can change your resume.</p></div> : <div className="space-y-2">{proposals.map(proposal => <article key={proposal.id} className="rounded-xl border border-violet-500/20 bg-violet-600/5 p-3 space-y-2"><div className="flex items-center gap-2"><span className="text-[10px] uppercase tracking-wide text-violet-400">{proposal.kind}</span>{proposal.section && <span className="text-[10px] text-gray-600">• {proposal.section}</span>}</div><div className="text-xs text-white whitespace-pre-wrap break-words">{proposal.proposed}</div>{proposal.reason && <div className="text-[10px] text-gray-500">{proposal.reason}</div>}<div className="flex gap-2"><button type="button" onClick={() => onVerifyApply(proposal.id)} className="flex-1 flex items-center justify-center gap-1.5 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-xs py-2"><Check aria-hidden="true" className="w-3.5 h-3.5" /> Verify & apply</button><button type="button" aria-label="Dismiss AI proposal" onClick={() => onDismiss(proposal.id)} className="px-3 rounded-lg border border-white/10 text-gray-400 hover:text-red-300"><Trash2 aria-hidden="true" className="w-3.5 h-3.5" /></button></div></article>)}</div>}
  </div>;
}
