// Generated by scripts/build-website-vercel-connection.mjs; edit server/service source.
/* eslint-disable no-var, @typescript-eslint/no-unused-vars -- Generated bundle. */

// server/website-vercel-connection-edge.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.57.4";

// src/modules/website-builder/services/trustedServerRuntime.ts
function isUntrustedBrowserRuntime() {
  const deno = globalThis.Deno;
  return typeof window !== "undefined" && typeof deno?.version?.deno !== "string";
}

// src/modules/website-builder/services/websiteConnectionOAuthStateService.ts
var uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var statePattern = /^[0-9a-f]{64}$/;
var providers = ["github", "supabase", "vercel", "stripe"];
function serverOnly() {
  if (isUntrustedBrowserRuntime()) throw new Error("OAuth state requires a trusted server.");
}
async function hash(state2) {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(state2));
  return Array.from(new Uint8Array(bytes), (byte) => byte.toString(16).padStart(2, "0")).join("");
}
async function createWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!uuid.test(input.ownerId) || !uuid.test(input.projectId) || !providers.includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  const raw = Array.from(crypto.getRandomValues(new Uint8Array(32)), (byte) => byte.toString(16).padStart(2, "0")).join("");
  const digest = await hash(raw);
  const expiresAt = new Date((input.now ?? Date.now)() + 9 * 6e4).toISOString();
  const { error } = await input.client.rpc("website_create_connection_oauth_state", {
    p_state_hash: digest,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_expires_at: expiresAt
  });
  if (error || !input.isCurrentOwner()) throw new Error("Connection could not be started.");
  return raw;
}
async function consumeWebsiteConnectionOAuthState(input) {
  serverOnly();
  if (!statePattern.test(input.state) || !providers.includes(input.provider)) throw new Error("Connection state is invalid or expired.");
  const { data, error } = await input.client.rpc("website_consume_connection_oauth_state", { p_state_hash: await hash(input.state) });
  if (error || !data || !uuid.test(data.ownerId) || !uuid.test(data.projectId) || data.provider !== input.provider || !["preview", "production"].includes(data.environment)) {
    throw new Error("Connection state is invalid or expired.");
  }
  return { ownerId: data.ownerId, projectId: data.projectId, provider: data.provider, environment: data.environment };
}

// src/modules/website-builder/services/websiteConnectionHandoffService.ts
var uuid2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var handoffTokenMaxBytes = 131072;
function serverOnly2() {
  if (isUntrustedBrowserRuntime()) throw new Error("Connection handoff requires a trusted server.");
}
async function storeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !["github", "supabase", "vercel", "stripe"].includes(input.provider) || !["preview", "production"].includes(input.environment) || !input.userToken || input.userToken.length < 20 || new TextEncoder().encode(input.userToken).length > handoffTokenMaxBytes) {
    throw new Error("Connection handoff could not be stored.");
  }
  const id = crypto.randomUUID();
  const { error } = await input.client.rpc("website_store_connection_handoff", {
    p_id: id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider,
    p_environment: input.environment,
    p_token: input.userToken,
    p_expires_at: new Date((input.now ?? Date.now)() + 4 * 6e4).toISOString()
  });
  if (error) throw new Error("Connection handoff could not be stored.");
  return id;
}
async function consumeWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_consume_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > handoffTokenMaxBytes || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}
async function peekWebsiteConnectionHandoff(input) {
  serverOnly2();
  if (!uuid2.test(input.id) || !uuid2.test(input.ownerId) || !uuid2.test(input.projectId) || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  const { data, error } = await input.client.rpc("website_peek_connection_handoff", {
    p_id: input.id,
    p_owner_id: input.ownerId,
    p_project_id: input.projectId,
    p_provider: input.provider
  });
  if (error || !data || !["preview", "production"].includes(data.environment) || typeof data.userToken !== "string" || data.userToken.length < 20 || new TextEncoder().encode(data.userToken).length > handoffTokenMaxBytes || !input.isCurrentOwner()) throw new Error("Connection handoff is unavailable.");
  return { environment: data.environment, userToken: data.userToken };
}

// src/modules/website-builder/services/websiteVercelOAuthService.ts
var statePattern2 = /^[0-9a-f]{64}$/;
var codePattern = /^[A-Za-z0-9._~-]{1,2048}$/;
var slugPattern = /^[a-z0-9][a-z0-9-]{1,99}$/;
var providerId = /^[A-Za-z0-9_-]{3,128}$/;
var configurationId = /^icfg_[A-Za-z0-9]{8,128}$/;
var teamId = /^team_[A-Za-z0-9]{8,128}$/;
function callbackUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || url.search !== "?action=callback") throw new Error("Vercel connection is not configured.");
  return url.toString();
}
function secret(value) {
  return typeof value === "string" && value.length >= 20 && new TextEncoder().encode(value).length <= 4096 && !/[\r\n]/.test(value);
}
function vercelAuthorizationUrl(input) {
  if (isUntrustedBrowserRuntime() || !slugPattern.test(input.integrationSlug) || !statePattern2.test(input.state)) throw new Error("Vercel connection is not configured.");
  const url = new URL(`https://vercel.com/integrations/${input.integrationSlug}/new`);
  url.searchParams.set("state", input.state);
  return url.toString();
}
async function acceptVercelOAuthCallback(input) {
  if (isUntrustedBrowserRuntime() || !providerId.test(input.clientId) || !secret(input.clientSecret) || !codePattern.test(input.code) || !configurationId.test(input.callbackConfigurationId) || input.callbackTeamId != null && !teamId.test(input.callbackTeamId)) {
    throw new Error("Vercel authorization failed.");
  }
  const callback = callbackUrl(input.callback);
  const scope = await consumeWebsiteConnectionOAuthState({
    client: input.stateClient,
    state: input.state,
    provider: "vercel"
  });
  try {
    const response = await (input.fetcher ?? fetch)("https://api.vercel.com/v2/oauth/access_token", {
      method: "POST",
      redirect: "error",
      cache: "no-store",
      signal: AbortSignal.timeout(8e3),
      headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: input.clientId,
        client_secret: input.clientSecret,
        code: input.code,
        redirect_uri: callback
      })
    });
    if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 16384) throw new Error();
    const raw = await response.text();
    if (raw.length > 16384) throw new Error();
    const grant = JSON.parse(raw);
    const returnedTeamId = grant.team_id == null ? null : grant.team_id;
    if (!secret(grant.access_token) || String(grant.token_type).toLowerCase() !== "bearer" || typeof grant.user_id !== "string" || !providerId.test(grant.user_id) || returnedTeamId !== null && (typeof returnedTeamId !== "string" || !teamId.test(returnedTeamId)) || (input.callbackTeamId ?? null) !== returnedTeamId || grant.installation_id != null && grant.installation_id !== input.callbackConfigurationId) throw new Error();
    return {
      ownerId: scope.ownerId,
      projectId: scope.projectId,
      environment: scope.environment,
      accessToken: grant.access_token,
      userId: grant.user_id,
      teamId: returnedTeamId,
      configurationId: input.callbackConfigurationId
    };
  } catch {
    throw new Error("Vercel authorization failed.");
  }
}

// src/modules/website-builder/services/websiteVercelProjectChoiceService.ts
var uuid3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var providerId2 = /^[A-Za-z0-9_-]{3,128}$/;
var teamId2 = /^team_[A-Za-z0-9]{8,128}$/;
var projectId = /^prj_[A-Za-z0-9]{8,128}$/;
var gitName = /^[A-Za-z0-9_.-]{1,100}$/;
var branch = /^[A-Za-z0-9_./-]{1,200}$/;
function token(value) {
  return typeof value === "string" && value.length >= 20 && new TextEncoder().encode(value).length <= 4096 && !/[\r\n]/.test(value);
}
function encodeVercelOAuthHandoff(grant) {
  if (!token(grant.accessToken) || !providerId2.test(grant.userId) || grant.teamId !== null && !teamId2.test(grant.teamId) || !/^icfg_[A-Za-z0-9]{8,128}$/.test(grant.configurationId) || !Number.isFinite(Date.parse(grant.receivedAt))) throw new Error("Vercel authorization is unavailable.");
  return JSON.stringify(grant);
}
function decodeGrant(raw) {
  let grant;
  try {
    grant = JSON.parse(raw);
  } catch {
    throw new Error("Vercel authorization is unavailable.");
  }
  if (!token(grant.accessToken) || !providerId2.test(grant.userId ?? "") || grant.teamId !== null && !teamId2.test(grant.teamId ?? "") || !/^icfg_[A-Za-z0-9]{8,128}$/.test(grant.configurationId ?? "") || !Number.isFinite(Date.parse(grant.receivedAt ?? ""))) throw new Error("Vercel authorization is unavailable.");
  return grant;
}
async function read(accessToken, path, fetcher) {
  const response = await fetcher(`https://api.vercel.com${path}`, {
    method: "GET",
    redirect: "error",
    cache: "no-store",
    signal: AbortSignal.timeout(8e3),
    headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" }
  });
  if (response.status !== 200 || Number(response.headers.get("content-length") ?? 0) > 131072) throw new Error();
  const raw = await response.text();
  if (raw.length > 131072) throw new Error();
  const parsed = JSON.parse(raw);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error();
  return parsed;
}
async function listWebsiteVercelProjectChoices(input) {
  if (isUntrustedBrowserRuntime() || !uuid3.test(input.ownerId) || !uuid3.test(input.projectId) || !uuid3.test(input.handoffId) || !providerId2.test(input.platformAccountId) || !/^\d+$/.test(input.repositoryId) || !gitName.test(input.repositoryOwner) || !gitName.test(input.repositoryName) || !branch.test(input.productionBranch) || input.productionBranch.includes("..") || input.productionBranch.startsWith("/") || input.productionBranch.endsWith("/") || !input.isCurrentOwner()) {
    throw new Error("Vercel projects are unavailable.");
  }
  try {
    const handoff = await peekWebsiteConnectionHandoff({
      client: input.client,
      id: input.handoffId,
      ownerId: input.ownerId,
      projectId: input.projectId,
      provider: "vercel",
      isCurrentOwner: input.isCurrentOwner
    });
    const grant = decodeGrant(handoff.userToken), fetcher = input.fetcher ?? fetch;
    const accountId = grant.teamId ?? grant.userId;
    if (accountId === input.platformAccountId) throw new Error();
    const profile = await read(grant.accessToken, "/v2/user", fetcher);
    if (!profile.user || typeof profile.user !== "object" || profile.user.id !== grant.userId) throw new Error();
    if (grant.teamId) {
      const team = await read(grant.accessToken, `/v2/teams/${grant.teamId}`, fetcher);
      const membership = team.membership;
      if (team.id !== grant.teamId || !membership || typeof membership !== "object" || membership.uid !== grant.userId || membership.role !== "OWNER" || membership.confirmed !== true) throw new Error();
    }
    const scope = grant.teamId ? `&teamId=${encodeURIComponent(grant.teamId)}` : "";
    const catalog = await read(grant.accessToken, `/v9/projects?limit=100${scope}`, fetcher);
    if (!Array.isArray(catalog.projects) || catalog.projects.length > 100) throw new Error();
    const projects = [];
    for (const raw of catalog.projects) {
      if (!raw || typeof raw !== "object" || Array.isArray(raw)) continue;
      const project2 = raw, link = project2.link;
      if (!projectId.test(String(project2.id)) || typeof project2.name !== "string" || project2.name.length < 1 || project2.name.length > 100 || project2.accountId !== accountId || project2.paused === true || !link || typeof link !== "object" || Array.isArray(link)) continue;
      const git = link;
      if (git.type !== "github" || String(git.repoId) !== input.repositoryId || git.org !== input.repositoryOwner || git.repo !== input.repositoryName || git.productionBranch !== input.productionBranch) continue;
      projects.push({
        projectId: String(project2.id),
        projectName: project2.name,
        accountId,
        accountType: grant.teamId ? "team" : "personal",
        productionBranch: input.productionBranch
      });
    }
    if (!input.isCurrentOwner()) throw new Error();
    return {
      userId: grant.userId,
      accountId,
      configurationId: grant.configurationId,
      projects: projects.sort((a, b) => a.projectName.localeCompare(b.projectName) || a.projectId.localeCompare(b.projectId))
    };
  } catch {
    throw new Error("Vercel projects are unavailable.");
  }
}
function projectMatches(raw, expected) {
  const link = raw.link;
  return raw.id === expected.vercelProjectId && raw.accountId === expected.accountId && raw.paused !== true && !!link && typeof link === "object" && !Array.isArray(link) && link.type === "github" && String(link.repoId) === expected.repositoryId && link.org === expected.repositoryOwner && link.repo === expected.repositoryName && link.productionBranch === expected.productionBranch;
}
async function bindWebsiteVercelProject(input) {
  if (isUntrustedBrowserRuntime() || !uuid3.test(input.ownerId) || !uuid3.test(input.projectId) || !uuid3.test(input.handoffId) || input.connectionId !== void 0 && !uuid3.test(input.connectionId) || Boolean(input.connectionId) !== Boolean(input.expectedVersion) || input.expectedVersion !== void 0 && (!Number.isSafeInteger(input.expectedVersion) || input.expectedVersion < 1) || !providerId2.test(input.userId) || !providerId2.test(input.accountId) || !/^icfg_[A-Za-z0-9]{8,128}$/.test(input.configurationId) || !projectId.test(input.vercelProjectId) || input.accountId === input.platformAccountId || !/^\d+$/.test(input.repositoryId) || !gitName.test(input.repositoryOwner) || !gitName.test(input.repositoryName) || !branch.test(input.productionBranch) || input.productionBranch.includes("..") || input.productionBranch.startsWith("/") || input.productionBranch.endsWith("/") || !input.isCurrentOwner()) {
    throw new Error("Vercel project could not be connected.");
  }
  const connectionId = input.connectionId ?? input.handoffId, expectedVersion = input.expectedVersion ?? 0;
  const reconcile = async () => {
    const { data, error } = await input.client.rpc("website_reconcile_vercel_project_binding", {
      p_connection_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_expected_version: expectedVersion,
      p_account_id: input.accountId,
      p_vercel_project_id: input.vercelProjectId,
      p_configuration_id: input.configurationId,
      p_operation_id: input.handoffId
    });
    if (error || !input.isCurrentOwner()) throw new Error();
    return data === expectedVersion + 1;
  };
  try {
    if (await reconcile()) return {
      connectionId,
      accountId: input.accountId,
      vercelProjectId: input.vercelProjectId,
      version: expectedVersion + 1
    };
    const handoff = await consumeWebsiteConnectionHandoff({
      client: input.client,
      id: input.handoffId,
      ownerId: input.ownerId,
      projectId: input.projectId,
      provider: "vercel",
      isCurrentOwner: input.isCurrentOwner
    });
    const grant = decodeGrant(handoff.userToken), accountId = grant.teamId ?? grant.userId;
    if (grant.userId !== input.userId || accountId !== input.accountId || grant.configurationId !== input.configurationId) throw new Error();
    const fetcher = input.fetcher ?? fetch;
    const profile = await read(grant.accessToken, "/v2/user", fetcher);
    if (!profile.user || typeof profile.user !== "object" || profile.user.id !== grant.userId) throw new Error();
    if (grant.teamId) {
      const team = await read(grant.accessToken, `/v2/teams/${grant.teamId}`, fetcher), membership = team.membership;
      if (team.id !== grant.teamId || !membership || typeof membership !== "object" || membership.uid !== grant.userId || membership.role !== "OWNER" || membership.confirmed !== true) throw new Error();
    }
    const selectedPath = `/v9/projects/${input.vercelProjectId}${grant.teamId ? `?teamId=${encodeURIComponent(grant.teamId)}` : ""}`;
    const expected = {
      vercelProjectId: input.vercelProjectId,
      accountId,
      repositoryId: input.repositoryId,
      repositoryOwner: input.repositoryOwner,
      repositoryName: input.repositoryName,
      productionBranch: input.productionBranch
    };
    if (!projectMatches(await read(grant.accessToken, selectedPath, fetcher), expected) || !input.isCurrentOwner() || !projectMatches(await read(grant.accessToken, selectedPath, fetcher), expected)) throw new Error();
    const { data, error } = await input.client.rpc("website_bind_vercel_project", {
      p_connection_id: connectionId,
      p_project_id: input.projectId,
      p_owner_id: input.ownerId,
      p_expected_version: expectedVersion,
      p_environment: handoff.environment,
      p_user_id: grant.userId,
      p_account_id: accountId,
      p_configuration_id: grant.configurationId,
      p_vercel_project_id: input.vercelProjectId,
      p_repository_id: input.repositoryId,
      p_repository_owner: input.repositoryOwner,
      p_repository_name: input.repositoryName,
      p_production_branch: input.productionBranch,
      p_access_token: grant.accessToken,
      p_custody_expires_at: new Date(Date.now() + 90 * 864e5 - 6e4).toISOString(),
      p_operation_id: input.handoffId
    });
    if (error || data !== expectedVersion + 1 || !input.isCurrentOwner()) {
      if (await reconcile()) return {
        connectionId,
        accountId,
        vercelProjectId: input.vercelProjectId,
        version: expectedVersion + 1
      };
      throw new Error();
    }
    return { connectionId, accountId, vercelProjectId: input.vercelProjectId, version: data };
  } catch {
    throw new Error("Vercel project could not be connected.");
  }
}

// src/modules/website-builder/core/application-infrastructure-connections.ts
var uuid4 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var identity = /^[a-zA-Z0-9][a-zA-Z0-9_./:-]{0,199}$/;
var permission = /^[a-zA-Z0-9][a-zA-Z0-9_:./-]{0,119}$/;
var providers2 = ["github", "supabase", "vercel", "stripe", "external"];
var statuses = ["disconnected", "connecting", "connected", "permissions-missing", "setup-incomplete", "outdated-schema", "deployment-failed", "credentials-revoked", "ready"];
function assertInfrastructureConnection(value) {
  if (!uuid4.test(value.id) || !uuid4.test(value.ownerId) || !uuid4.test(value.projectId) || !providers2.includes(value.provider) || !["preview", "production"].includes(value.environment) || !identity.test(value.accountId) || value.targetId !== null && !identity.test(value.targetId) || !statuses.includes(value.status) || !Number.isSafeInteger(value.version) || value.version < 1 || !Array.isArray(value.permissions) || value.permissions.length > 40 || value.permissions.some((scope) => typeof scope !== "string" || !permission.test(scope)) || new Set(value.permissions).size !== value.permissions.length || value.operationId !== null && !uuid4.test(value.operationId) || !Number.isFinite(Date.parse(value.updatedAt)) || value.verifiedAt !== null && !Number.isFinite(Date.parse(value.verifiedAt))) throw new Error("Invalid infrastructure connection.");
  if (value.status === "connecting" !== (value.operationId !== null)) throw new Error("Invalid infrastructure operation.");
  if (["connected", "ready"].includes(value.status) && !value.verifiedAt) throw new Error("Infrastructure is not verified.");
  if (value.status === "ready" && (!value.targetId || !value.verifiedAt)) throw new Error("Infrastructure is not verified.");
  return value;
}
function publicInfrastructureConnection(value) {
  const source = assertInfrastructureConnection(value);
  return {
    id: source.id,
    ownerId: source.ownerId,
    projectId: source.projectId,
    provider: source.provider,
    environment: source.environment,
    accountId: source.accountId,
    targetId: source.targetId,
    permissions: [...source.permissions],
    status: source.status,
    version: source.version,
    verifiedAt: source.verifiedAt,
    updatedAt: source.updatedAt
  };
}

// src/modules/website-builder/core/application-data-runtime.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
function projectRef(url) {
  const parsed = new URL(url);
  const match = /^([a-z0-9]{20})\.supabase\.co$/.exec(parsed.hostname);
  if (parsed.protocol !== "https:" || !match || parsed.username || parsed.password || parsed.port || parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("Generated applications require a dedicated HTTPS Supabase project URL.");
  }
  return match[1];
}
function publicKey(key, ref) {
  if (/^sb_publishable_[A-Za-z0-9_-]+$/.test(key)) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    const body = JSON.parse(atob(parts[1].replace(/-/g, "+").replace(/_/g, "/")));
    return body.role === "anon" && body.ref === ref && body.iss === "supabase";
  } catch {
    return false;
  }
}
function validateOwnedApplicationPublicBackend(config, expectedProjectRef) {
  if (!/^[a-z0-9]{20}$/.test(expectedProjectRef) || projectRef(config.url) !== expectedProjectRef || config.projectRef !== expectedProjectRef || !publicKey(config.publishableKey, expectedProjectRef)) {
    throw new Error("Customer Supabase backend identity is unavailable.");
  }
}

// server/website-owned-source-reader.ts
var uuid5 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var object = (value) => value && typeof value === "object" && !Array.isArray(value) ? value : null;
async function rpc(client, name, args) {
  const { data, error } = await client.rpc(name, args);
  if (error) return null;
  return data;
}
function createWebsiteOwnedSourceReader(client) {
  return {
    async readSavedProject(projectId2, ownerId) {
      if (!uuid5.test(projectId2) || !uuid5.test(ownerId)) return null;
      const row = object(await rpc(client, "website_byo_saved_project", { p_project_id: projectId2, p_owner_id: ownerId }));
      const snapshot = object(row?.snapshot);
      if (!row || row.projectId !== projectId2 || row.ownerId !== ownerId || !snapshot) return null;
      return { projectId: projectId2, ownerId, snapshot: structuredClone(snapshot) };
    },
    async readConnection(connectionId, projectId2, ownerId) {
      if (![connectionId, projectId2, ownerId].every((value) => uuid5.test(value))) return null;
      const row = object(await rpc(client, "website_byo_connection_for_worker", {
        p_connection_id: connectionId,
        p_project_id: projectId2,
        p_owner_id: ownerId
      }));
      if (!row) return null;
      try {
        const value = structuredClone(row);
        assertInfrastructureConnection(value);
        if (value.id !== connectionId || value.projectId !== projectId2 || value.ownerId !== ownerId) return null;
        return value;
      } catch {
        return null;
      }
    },
    async readOwnedRuntimeBinding(projectId2, ownerId, environment) {
      if (!uuid5.test(projectId2) || !uuid5.test(ownerId) || !["preview", "production"].includes(environment)) return null;
      const row = object(await rpc(client, "website_byo_runtime_binding_for_worker", {
        p_project_id: projectId2,
        p_owner_id: ownerId,
        p_environment: environment
      })), backend = object(row?.backend);
      if (!row || !backend || row.projectId !== projectId2 || row.ownerId !== ownerId || row.environment !== environment || !Number.isSafeInteger(row.bindingVersion) || row.bindingVersion < 1 || typeof row.supabaseConnectionId !== "string" || !uuid5.test(row.supabaseConnectionId) || !Number.isSafeInteger(row.supabaseConnectionVersion) || row.supabaseConnectionVersion < 1 || typeof row.vercelConnectionId !== "string" || !uuid5.test(row.vercelConnectionId) || !Number.isSafeInteger(row.vercelConnectionVersion) || row.vercelConnectionVersion < 1 || row.supabaseConnectionId === row.vercelConnectionId || typeof row.applicationOrigin !== "string" || typeof backend.url !== "string" || typeof backend.projectRef !== "string" || typeof backend.publishableKey !== "string") return null;
      try {
        const origin = new URL(row.applicationOrigin);
        if (origin.protocol !== "https:" || origin.origin !== row.applicationOrigin || origin.username || origin.password || origin.port || origin.hostname.endsWith(".supabase.co")) return null;
        const publicBackend = { url: backend.url, publishableKey: backend.publishableKey, projectRef: backend.projectRef };
        validateOwnedApplicationPublicBackend(publicBackend, publicBackend.projectRef);
        return structuredClone({
          projectId: projectId2,
          ownerId,
          environment,
          bindingVersion: row.bindingVersion,
          supabaseConnectionId: row.supabaseConnectionId,
          supabaseConnectionVersion: row.supabaseConnectionVersion,
          vercelConnectionId: row.vercelConnectionId,
          vercelConnectionVersion: row.vercelConnectionVersion,
          applicationOrigin: row.applicationOrigin,
          backend: publicBackend
        });
      } catch {
        return null;
      }
    }
  };
}

// server/website-owned-vercel-disconnect.ts
var uuid6 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var provider = /^[A-Za-z0-9_-]{3,128}$/;
var project = /^prj_[A-Za-z0-9]{8,128}$/;
var names = ["SUPABASE_ANON_KEY", "SUPABASE_URL"];
function object2(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error();
  return value;
}
function environmentIds(value) {
  const parsed = object2(value);
  if (Object.keys(parsed).sort().join(",") !== names.join(",") || names.some((name) => typeof parsed[name] !== "string" || !provider.test(parsed[name])) || new Set(Object.values(parsed)).size !== names.length) throw new Error();
  return parsed;
}
function completed(value, expectedConnectionVersion) {
  if (value == null) return null;
  const parsed = object2(value);
  if (parsed.connectionVersion !== expectedConnectionVersion || !(parsed.receiptVersion == null || Number.isSafeInteger(parsed.receiptVersion) && Number(parsed.receiptVersion) > 0)) throw new Error();
  return parsed;
}
async function disconnectOwnedVercelProject(input) {
  try {
    if (isUntrustedBrowserRuntime() || !await input.isCurrentOwner() || !uuid6.test(input.operationId) || !uuid6.test(input.commitId)) throw new Error();
    const connection = assertInfrastructureConnection(input.connection);
    if (connection.provider !== "vercel" || connection.version < 1 || connection.status === "disconnected" || !project.test(connection.targetId ?? "")) throw new Error();
    const expectedConnectionVersion = connection.version + 1;
    const completedArgs = {
      p_connection_id: connection.id,
      p_project_id: connection.projectId,
      p_owner_id: connection.ownerId,
      p_expected_connection_version: connection.version,
      p_operation_id: input.operationId,
      p_commit_id: input.commitId
    };
    const initial = await input.client.rpc("website_reconcile_completed_vercel_runtime_disconnect", completedArgs);
    if (initial.error || !await input.isCurrentOwner()) throw new Error();
    const alreadyCompleted = completed(initial.data, expectedConnectionVersion);
    if (alreadyCompleted) return { version: alreadyCompleted.connectionVersion, installation: "retained" };
    const begun = await input.client.rpc("website_begin_vercel_runtime_disconnect", {
      p_connection_id: connection.id,
      p_project_id: connection.projectId,
      p_owner_id: connection.ownerId,
      p_expected_connection_version: connection.version,
      p_operation_id: input.operationId
    });
    if (begun.error || !await input.isCurrentOwner()) throw new Error();
    const begin = object2(begun.data);
    if (typeof begin.cleanupRequired !== "boolean" || !(begin.receiptVersion == null || Number.isSafeInteger(begin.receiptVersion) && begin.receiptVersion > 0)) throw new Error();
    let removedEnvironmentIds = [];
    if (begin.cleanupRequired) {
      const ids = environmentIds(begin.environmentIds);
      if (!Number.isSafeInteger(begin.receiptVersion) || Number(begin.receiptVersion) < 1 || typeof begin.accessToken !== "string" || begin.accessToken.length < 20 || begin.accessToken.length > 4096 || /[\r\n]/.test(begin.accessToken) || typeof begin.userId !== "string" || !provider.test(begin.userId) || typeof begin.accountId !== "string" || !provider.test(begin.accountId) || begin.vercelProjectId !== connection.targetId || !project.test(begin.vercelProjectId) || begin.environment !== connection.environment || typeof begin.marker !== "string") throw new Error();
      const preview = begin.environment === "preview";
      const expectedBranch = preview ? `tayar/${connection.projectId}/preview` : null;
      const expectedMarker = new RegExp(`^Tayar ${preview ? "" : "production "}runtime [0-9a-f-]{36}$`, "i");
      if (begin.gitBranch !== expectedBranch || !expectedMarker.test(begin.marker)) throw new Error();
      const team = begin.accountId !== begin.userId ? `&teamId=${encodeURIComponent(begin.accountId)}` : "";
      const listUrl = `https://api.vercel.com/v10/projects/${begin.vercelProjectId}/env?decrypt=false${team}`;
      const headers = { Authorization: `Bearer ${begin.accessToken}`, "Content-Type": "application/json", Accept: "application/json" };
      const read2 = async () => {
        if (!await input.isCurrentOwner()) throw new Error();
        const response = await (input.fetcher ?? fetch)(listUrl, {
          method: "GET",
          redirect: "error",
          cache: "no-store",
          signal: AbortSignal.timeout(8e3),
          headers
        });
        if (response.status !== 200 || Number(response.headers.get("content-length") ?? 0) > 262144) throw new Error();
        const text = await response.text();
        if (text.length > 262144) throw new Error();
        const payload = object2(JSON.parse(text));
        if (!Array.isArray(payload.envs) || payload.envs.length > 1e3) throw new Error();
        return payload.envs;
      };
      const before = await read2();
      for (const name of names) {
        const id = ids[name];
        const matches = before.filter((item) => !!item && typeof item === "object" && !Array.isArray(item) && item.id === id);
        if (matches.length > 1) throw new Error();
        if (matches.length === 1) {
          const row = matches[0];
          const targets = Array.isArray(row.target) ? row.target : [];
          if (row.key !== name || row.type !== "plain" || row.comment !== begin.marker || targets.length !== 1 || targets[0] !== begin.environment || (preview ? row.gitBranch !== expectedBranch : row.gitBranch != null)) throw new Error();
          if (!await input.isCurrentOwner()) throw new Error();
          const suffix = team ? `?${team.slice(1)}` : "";
          try {
            await (input.fetcher ?? fetch)(
              `https://api.vercel.com/v9/projects/${begin.vercelProjectId}/env/${id}${suffix}`,
              { method: "DELETE", redirect: "error", cache: "no-store", signal: AbortSignal.timeout(8e3), headers }
            );
          } catch {
            continue;
          }
        }
      }
      const after = await read2();
      if (after.some((item) => !!item && typeof item === "object" && !Array.isArray(item) && Object.values(ids).includes(item.id)) || !await input.isCurrentOwner()) throw new Error();
      removedEnvironmentIds = Object.values(ids).sort();
    } else if (begin.receiptVersion != null) throw new Error();
    const commitArgs = {
      ...completedArgs,
      p_expected_receipt_version: begin.receiptVersion,
      p_removed_environment_ids: removedEnvironmentIds
    };
    const expectedReceiptVersion = begin.receiptVersion == null ? null : begin.receiptVersion + 1;
    const reconcile = async () => {
      const result2 = await input.client.rpc("website_reconcile_vercel_runtime_disconnect", commitArgs);
      if (result2.error || !await input.isCurrentOwner()) return null;
      const exact = completed(result2.data, expectedConnectionVersion);
      if (exact && exact.receiptVersion !== expectedReceiptVersion) throw new Error();
      return exact;
    };
    let result = await reconcile();
    if (!result) {
      try {
        const committed = await input.client.rpc("website_commit_vercel_runtime_disconnect", commitArgs);
        if (committed.error || !await input.isCurrentOwner()) throw new Error();
        result = completed(committed.data, expectedConnectionVersion);
        if (!result || result.receiptVersion !== expectedReceiptVersion) throw new Error();
      } catch {
        result = await reconcile();
        if (!result) throw new Error();
      }
    }
    return { version: result.connectionVersion, installation: "retained" };
  } catch {
    throw new Error("Vercel disconnect unavailable.");
  }
}

// server/website-vercel-connection.ts
var uuid7 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var state = /^[a-f0-9]{64}$/;
var code = /^[A-Za-z0-9._~-]{1,2048}$/;
var providerId3 = /^[A-Za-z0-9_-]{3,128}$/;
var configurationId2 = /^icfg_[A-Za-z0-9]{8,128}$/;
var teamId3 = /^team_[A-Za-z0-9]{8,128}$/;
var vercelProjectId = /^prj_[A-Za-z0-9]{8,128}$/;
var responseHeaders = {
  "cache-control": "no-store",
  "referrer-policy": "no-referrer",
  "content-security-policy": "default-src 'none'",
  "x-content-type-options": "nosniff"
};
var json = (status, body) => new Response(
  JSON.stringify(body),
  { status, headers: { ...responseHeaders, "content-type": "application/json" } }
);
function fixedHttps(value, callback = false) {
  const url = new URL(value);
  if (url.protocol !== "https:" || !url.hostname || url.username || url.password || url.hash || (callback ? url.search !== "?action=callback" : !!url.search)) throw new Error();
  return url;
}
async function handleWebsiteVercelConnection(request, context) {
  const action = new URL(request.url).searchParams.get("action");
  let callback, destination = null;
  try {
    callback = fixedHttps(context.callback, true);
    if (!callback.pathname.endsWith("/functions/v1/website-vercel-connection") || action !== "disconnect" && (!/^[a-z0-9][a-z0-9-]{1,99}$/.test(context.integrationSlug) || !providerId3.test(context.clientId) || context.clientSecret.length < 20 || /[\r\n]/.test(context.clientSecret) || !providerId3.test(context.platformAccountId))) throw new Error();
    if (action !== "disconnect") destination = fixedHttps(context.returnUrl);
  } catch {
    return json(503, { error: "Vercel connection is not configured." });
  }
  if (action === "callback") {
    if (request.method !== "GET") return json(405, { error: "Method not allowed." });
    const params = new URL(request.url).searchParams, callbackTeamId = params.get("teamId");
    if (params.has("error") || !state.test(params.get("state") ?? "") || !code.test(params.get("code") ?? "") || !configurationId2.test(params.get("configurationId") ?? "") || callbackTeamId !== null && !teamId3.test(callbackTeamId)) {
      return json(400, { error: "Vercel authorization failed. Start the connection again." });
    }
    try {
      const grant = await acceptVercelOAuthCallback({
        stateClient: context.platform,
        state: params.get("state"),
        code: params.get("code"),
        callbackTeamId,
        callbackConfigurationId: params.get("configurationId"),
        clientId: context.clientId,
        clientSecret: context.clientSecret,
        callback: callback.toString(),
        fetcher: context.fetcher
      });
      const handoffId = await storeWebsiteConnectionHandoff({
        client: context.platform,
        ownerId: grant.ownerId,
        projectId: grant.projectId,
        environment: grant.environment,
        provider: "vercel",
        userToken: encodeVercelOAuthHandoff({
          accessToken: grant.accessToken,
          userId: grant.userId,
          teamId: grant.teamId,
          configurationId: grant.configurationId,
          receivedAt: (/* @__PURE__ */ new Date()).toISOString()
        })
      });
      destination.hash = new URLSearchParams({ tayar_vercel_handoff: handoffId }).toString();
      return new Response(null, { status: 303, headers: { ...responseHeaders, location: destination.toString() } });
    } catch {
      return json(409, { error: "Vercel authorization could not be completed. Start again." });
    }
  }
  if (!["begin", "options", "bind", "disconnect"].includes(action ?? "") || request.method !== "POST")
    return json(405, { error: "Method not allowed." });
  if (!/^application\/json(?:\s*;|$)/i.test(request.headers.get("content-type") ?? ""))
    return json(415, { error: "JSON request required." });
  const bearer = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/i.exec(request.headers.get("authorization") ?? "")?.[1];
  if (!bearer || bearer.length > 16384) return json(401, { error: "Sign in required." });
  let ownerId, input, projectId2;
  try {
    const identity2 = await context.platform.auth.getUser(bearer);
    if (identity2.error || !identity2.data.user || identity2.data.user.is_anonymous || !uuid7.test(identity2.data.user.id)) throw new Error();
    ownerId = identity2.data.user.id;
  } catch {
    return json(401, { error: "Sign in required." });
  }
  try {
    if (Number(request.headers.get("content-length") ?? 0) > 8192) throw new Error();
    const raw = await request.text();
    if (raw.length > 8192) throw new Error();
    input = JSON.parse(raw);
    const keys2 = action === "begin" ? ["projectId", "environment"] : action === "options" ? ["projectId", "handoffId"] : action === "disconnect" ? ["projectId", "connectionId", "expectedVersion", "operationId", "commitId"] : [
      "projectId",
      "handoffId",
      "connectionId",
      "expectedVersion",
      "userId",
      "accountId",
      "configurationId",
      "vercelProjectId"
    ];
    if (!input || typeof input !== "object" || Array.isArray(input) || Object.keys(input).some((key) => !keys2.includes(key)) || typeof input.projectId !== "string" || !uuid7.test(input.projectId) || action === "begin" && !["preview", "production"].includes(String(input.environment)) || ["options", "bind"].includes(action ?? "") && (typeof input.handoffId !== "string" || !uuid7.test(input.handoffId))) throw new Error();
    if (action === "disconnect" && (Object.keys(input).sort().join(",") !== keys2.sort().join(",") || typeof input.connectionId !== "string" || !uuid7.test(input.connectionId) || !Number.isSafeInteger(input.expectedVersion) || Number(input.expectedVersion) < 1 || typeof input.operationId !== "string" || !uuid7.test(input.operationId) || typeof input.commitId !== "string" || !uuid7.test(input.commitId))) throw new Error();
    if (action === "bind" && (!providerId3.test(String(input.userId)) || !providerId3.test(String(input.accountId)) || !configurationId2.test(String(input.configurationId)) || !vercelProjectId.test(String(input.vercelProjectId)))) throw new Error();
    projectId2 = input.projectId;
  } catch {
    return json(400, { error: "Invalid connection request." });
  }
  try {
    const { data, error } = await context.platform.from("projects").select("id").eq("id", projectId2).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
    if (error) return json(503, { error: "Project is unavailable." });
    if (!data) return json(404, { error: "Project not found." });
    const isCurrentOwner = async () => {
      try {
        const currentIdentity = await context.platform.auth.getUser(bearer);
        if (currentIdentity.error || currentIdentity.data.user?.id !== ownerId || currentIdentity.data.user.is_anonymous) return false;
        const currentProject = await context.platform.from("projects").select("id").eq("id", projectId2).eq("user_id", ownerId).eq("type", "website-builder").is("deleted_at", null).maybeSingle();
        return !currentProject.error && currentProject.data?.id === projectId2;
      } catch {
        return false;
      }
    };
    if (action === "begin") {
      const rawState = await createWebsiteConnectionOAuthState({
        client: context.platform,
        ownerId,
        projectId: projectId2,
        environment: input.environment,
        provider: "vercel",
        isCurrentOwner: () => true
      });
      return json(200, { authorizationUrl: vercelAuthorizationUrl({
        integrationSlug: context.integrationSlug,
        state: rawState
      }) });
    }
    if (action === "disconnect") {
      const connectionId = input.connectionId, expectedVersion = input.expectedVersion;
      const operationId = input.operationId, commitId = input.commitId;
      const completedArgs = {
        p_connection_id: connectionId,
        p_project_id: projectId2,
        p_owner_id: ownerId,
        p_expected_connection_version: expectedVersion,
        p_operation_id: operationId,
        p_commit_id: commitId
      };
      const completed2 = await context.platform.rpc("website_reconcile_completed_vercel_runtime_disconnect", completedArgs);
      if (completed2.error || !await isCurrentOwner()) throw new Error();
      if (completed2.data != null) {
        const exact = completed2.data;
        if (!exact || typeof exact !== "object" || Array.isArray(exact) || Object.keys(exact).sort().join(",") !== "connectionVersion,receiptVersion" || exact.connectionVersion !== expectedVersion + 1 || !(exact.receiptVersion == null || Number.isSafeInteger(exact.receiptVersion) && Number(exact.receiptVersion) > 0)) throw new Error();
        return json(200, {
          status: "disconnected",
          connectionId,
          version: exact.connectionVersion,
          installation: "retained"
        });
      }
      const connection = await createWebsiteOwnedSourceReader(context.platform).readConnection(connectionId, projectId2, ownerId);
      if (!connection || connection.provider !== "vercel" || connection.version !== expectedVersion || connection.status === "disconnected") throw new Error();
      const result2 = await disconnectOwnedVercelProject({
        client: context.platform,
        connection,
        operationId,
        commitId,
        isCurrentOwner,
        fetcher: context.fetcher
      });
      return json(200, { status: "disconnected", connectionId, ...result2 });
    }
    const target = await context.loadGithubTarget({ ownerId, projectId: projectId2, isCurrentOwner });
    if (!target) return json(409, { error: "Connect the correct GitHub repository first." });
    const shared = {
      client: context.platform,
      ownerId,
      projectId: projectId2,
      handoffId: input.handoffId,
      platformAccountId: context.platformAccountId,
      ...target,
      isCurrentOwner: () => true,
      fetcher: context.fetcher
    };
    if (action === "options") return json(200, await listWebsiteVercelProjectChoices(shared));
    const result = await bindWebsiteVercelProject({
      ...shared,
      connectionId: input.connectionId,
      expectedVersion: input.expectedVersion,
      userId: input.userId,
      accountId: input.accountId,
      configurationId: input.configurationId,
      vercelProjectId: input.vercelProjectId
    });
    return json(200, { status: "connected", ...result });
  } catch {
    return json(409, { error: action === "disconnect" ? "Vercel connection could not be disconnected. Refresh and try again." : "Vercel connection could not be completed. Refresh and try again." });
  }
}

// src/modules/website-builder/services/websiteInfrastructureConnectionClient.ts
var uuid8 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var validationOperationId = "00000000-0000-4000-8000-000000000000";
async function readWebsiteInfrastructureConnections(input) {
  if (!uuid8.test(input.projectId) || !uuid8.test(input.ownerId) || !input.isCurrent()) throw new Error("Infrastructure scope changed.");
  const { data, error } = await input.client.rpc("website_infrastructure_connections_for_owner", { p_project_id: input.projectId });
  if (error || !Array.isArray(data) || data.length > 10) throw new Error("Infrastructure status is unavailable.");
  const seen = /* @__PURE__ */ new Set();
  const records = data.map((row) => {
    if (!row || typeof row !== "object") throw new Error("Infrastructure status is unavailable.");
    const record = row;
    const candidate = {
      id: record.id,
      ownerId: record.ownerId,
      projectId: record.projectId,
      provider: record.provider,
      environment: record.environment,
      accountId: record.accountId,
      targetId: record.targetId,
      permissions: record.permissions,
      status: record.status,
      version: record.version,
      verifiedAt: record.verifiedAt,
      updatedAt: record.updatedAt,
      operationId: record.status === "connecting" ? validationOperationId : null
    };
    try {
      assertInfrastructureConnection(candidate);
    } catch {
      throw new Error("Infrastructure status is unavailable.");
    }
    if (candidate.projectId !== input.projectId || candidate.ownerId !== input.ownerId) throw new Error("Infrastructure scope changed.");
    const key = `${candidate.provider}:${candidate.environment}`;
    if (seen.has(key)) throw new Error("Infrastructure status is unavailable.");
    seen.add(key);
    return publicInfrastructureConnection(candidate);
  });
  if (!input.isCurrent()) throw new Error("Infrastructure scope changed.");
  return records;
}

// src/modules/website-builder/services/websiteGithubOAuthService.ts
var appId = /^[a-zA-Z0-9_]{5,100}$/;
var providerTokenMaxBytes = 65536;
function token2(value) {
  return typeof value === "string" && value.length >= 20 && new TextEncoder().encode(value).length <= providerTokenMaxBytes && !/[\r\n\s]/.test(value);
}
function seconds(value, max) {
  if (value === void 0 || value === null) return null;
  return Number.isSafeInteger(value) && value > 0 && value <= max ? value : NaN;
}
function parseGrant(value, receivedAt) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error();
  const row = value;
  const expiresIn = seconds(row.expires_in, 86400);
  const refreshExpiresIn = seconds(row.refresh_token_expires_in, 31536e3);
  const refreshToken = row.refresh_token === void 0 || row.refresh_token === null ? null : row.refresh_token;
  if (row.token_type?.toString().toLowerCase() !== "bearer" || !token2(row.access_token) || Number.isNaN(expiresIn) || Number.isNaN(refreshExpiresIn) || refreshToken !== null && !token2(refreshToken) || (expiresIn !== null || refreshExpiresIn !== null || refreshToken !== null) && (expiresIn === null || refreshExpiresIn === null || refreshToken === null) || expiresIn !== null && refreshExpiresIn !== null && refreshExpiresIn <= expiresIn || !Number.isFinite(Date.parse(receivedAt))) throw new Error();
  return { accessToken: row.access_token, receivedAt, expiresIn, refreshToken, refreshTokenExpiresIn: refreshExpiresIn };
}
function parseStoredGrant(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error();
  const row = value;
  if (Object.keys(row).some((key) => !["accessToken", "receivedAt", "expiresIn", "refreshToken", "refreshTokenExpiresIn"].includes(key)) || !token2(row.accessToken) || typeof row.receivedAt !== "string" || !Number.isFinite(Date.parse(row.receivedAt)) || !(row.expiresIn === null || Number.isSafeInteger(row.expiresIn) && row.expiresIn > 0 && row.expiresIn <= 86400) || !(row.refreshToken === null || token2(row.refreshToken)) || !(row.refreshTokenExpiresIn === null || Number.isSafeInteger(row.refreshTokenExpiresIn) && row.refreshTokenExpiresIn > 0 && row.refreshTokenExpiresIn <= 31536e3) || (row.expiresIn !== null || row.refreshToken !== null || row.refreshTokenExpiresIn !== null) && (row.expiresIn === null || row.refreshToken === null || row.refreshTokenExpiresIn === null) || row.expiresIn !== null && row.refreshTokenExpiresIn !== null && row.refreshTokenExpiresIn <= row.expiresIn) throw new Error();
  return {
    accessToken: row.accessToken,
    receivedAt: row.receivedAt,
    expiresIn: row.expiresIn,
    refreshToken: row.refreshToken,
    refreshTokenExpiresIn: row.refreshTokenExpiresIn
  };
}
function githubGrantExpiries(grant) {
  const parsed = parseStoredGrant(grant), received = Date.parse(parsed.receivedAt);
  const access = parsed.expiresIn === null ? null : received + parsed.expiresIn * 1e3;
  const refresh = parsed.refreshTokenExpiresIn === null ? null : received + parsed.refreshTokenExpiresIn * 1e3;
  const custody = refresh ?? received + 180 * 864e5;
  if (!Number.isFinite(custody) || custody <= received) throw new Error("GitHub authorization failed.");
  return {
    accessExpiresAt: access === null ? null : new Date(access).toISOString(),
    refreshExpiresAt: refresh === null ? null : new Date(refresh).toISOString(),
    custodyExpiresAt: new Date(custody).toISOString()
  };
}
async function tokenRequest(input) {
  if (isUntrustedBrowserRuntime()) throw new Error("GitHub exchange requires a server.");
  if (!appId.test(input.clientId) || !input.clientSecret || input.clientSecret.length > 4096 || /[\r\n]/.test(input.clientSecret)) {
    throw new Error("GitHub authorization failed.");
  }
  try {
    const response = await (input.fetcher ?? fetch)("https://github.com/login/oauth/access_token", {
      method: "POST",
      redirect: "error",
      signal: AbortSignal.timeout(8e3),
      headers: { Accept: "application/json", "Content-Type": "application/x-www-form-urlencoded" },
      body: input.body
    });
    if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 16384) throw new Error();
    const raw = await response.text();
    if (raw.length > 16384) throw new Error();
    const now = (input.now ?? Date.now)();
    if (!Number.isFinite(now)) throw new Error();
    return parseGrant(JSON.parse(raw), new Date(now).toISOString());
  } catch {
    throw new Error("GitHub authorization failed.");
  }
}
async function refreshGitHubAppUserGrant(input) {
  if (!token2(input.refreshToken)) throw new Error("GitHub authorization failed.");
  const body = new URLSearchParams({
    client_id: input.clientId,
    client_secret: input.clientSecret,
    grant_type: "refresh_token",
    refresh_token: input.refreshToken
  });
  return tokenRequest({ ...input, body });
}

// src/modules/website-builder/services/websiteGithubInstallationService.ts
var numeric = /^[1-9][0-9]{0,19}$/;
var repoName = /^[a-zA-Z0-9_.-]{1,39}\/[a-zA-Z0-9_.-]{1,100}$/;
var branch2 = /^[a-zA-Z0-9_./-]{1,200}$/;
var api = "https://api.github.com";
function object3(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("GitHub account could not be verified.");
  return value;
}
async function githubGet(fetcher, token4, path) {
  const response = await fetcher(`${api}${path}`, {
    method: "GET",
    redirect: "error",
    signal: AbortSignal.timeout(8e3),
    headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token4}`, "X-GitHub-Api-Version": "2022-11-28" }
  });
  if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 3e6) throw new Error("GitHub account could not be verified.");
  const body = await response.text();
  if (body.length > 3e6) throw new Error("GitHub account could not be verified.");
  try {
    return object3(JSON.parse(body));
  } catch {
    throw new Error("GitHub account could not be verified.");
  }
}
async function verifyGitHubInstallationRepository(input) {
  if (isUntrustedBrowserRuntime()) throw new Error("GitHub verification requires a server.");
  const { userToken, installationId, repositoryId } = input;
  if (!numeric.test(installationId) || !numeric.test(repositoryId) || !userToken || userToken.length > 4096) {
    throw new Error("GitHub account could not be verified.");
  }
  const fetcher = input.fetcher ?? fetch;
  try {
    let installation;
    for (let page = 1; page <= 10 && !installation; page++) {
      const result = await githubGet(fetcher, userToken, `/user/installations?per_page=100&page=${page}`);
      if (!Array.isArray(result.installations) || result.installations.length > 100) throw new Error();
      installation = result.installations.map(object3).find((item) => String(item.id) === installationId);
      if (result.installations.length < 100) break;
    }
    if (!installation || installation.suspended_at || object3(installation.permissions).contents !== "write") throw new Error();
    const account = object3(installation.account);
    const accountId = String(account.id);
    if (!numeric.test(accountId) || typeof account.login !== "string" || !/^[a-zA-Z0-9-]{1,100}$/.test(account.login)) throw new Error();
    let repository;
    for (let page = 1; page <= 10 && !repository; page++) {
      const result = await githubGet(fetcher, userToken, `/user/installations/${installationId}/repositories?per_page=100&page=${page}`);
      if (!Array.isArray(result.repositories) || result.repositories.length > 100) throw new Error();
      repository = result.repositories.map(object3).find((item) => String(item.id) === repositoryId);
      if (result.repositories.length < 100) break;
    }
    if (!repository || repository.archived || repository.disabled || object3(repository.owner).id !== account.id || typeof repository.full_name !== "string" || !repoName.test(repository.full_name) || typeof repository.default_branch !== "string" || !branch2.test(repository.default_branch) || object3(repository.permissions).push !== true) throw new Error();
    return {
      installationId,
      accountId,
      accountLogin: account.login,
      repositoryId,
      repositoryFullName: repository.full_name,
      defaultBranch: repository.default_branch
    };
  } catch {
    throw new Error("GitHub account could not be verified.");
  }
}

// src/modules/website-builder/services/websiteGithubOAuthCustodyService.ts
var uuid9 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var numeric2 = /^[1-9][0-9]{0,19}$/;
var repoName2 = /^[a-zA-Z0-9_.-]{1,39}\/[a-zA-Z0-9_.-]{1,100}$/;
var branch3 = /^[a-zA-Z0-9_./-]{1,200}$/;
var tokenMaxBytes = 65536;
function token3(value) {
  return typeof value === "string" && value.length >= 20 && new TextEncoder().encode(value).length <= tokenMaxBytes && !/[\r\n\s]/.test(value);
}
function optionalTime(value) {
  if (value === null) return null;
  if (typeof value !== "string" || !Number.isFinite(Date.parse(value))) throw new Error();
  return value;
}
function assertConnection(value) {
  if (typeof window !== "undefined") throw new Error("GitHub OAuth custody scope changed.");
  const connection = assertInfrastructureConnection(value);
  if (connection.provider !== "github" || !connection.targetId || !numeric2.test(connection.accountId) || !numeric2.test(connection.targetId) || !["connected", "setup-incomplete", "deployment-failed", "ready"].includes(connection.status)) {
    throw new Error("GitHub OAuth custody scope changed.");
  }
  return connection;
}
async function readWebsiteGitHubOAuthCustody(input) {
  const connection = assertConnection(input.connection);
  if (!await input.isCurrentOwner()) throw new Error("GitHub OAuth custody scope changed.");
  const { data, error } = await input.client.rpc("website_read_github_oauth_custody", {
    p_connection_id: connection.id,
    p_project_id: connection.projectId,
    p_owner_id: connection.ownerId,
    p_expected_connection_version: connection.version
  });
  try {
    if (error || !data || !await input.isCurrentOwner() || !Number.isSafeInteger(data.version) || data.version < 1 || data.accountId !== connection.accountId || data.repositoryId !== connection.targetId || data.environment !== connection.environment || !numeric2.test(data.installationId) || !repoName2.test(data.repositoryFullName) || !branch3.test(data.defaultBranch) || data.defaultBranch.includes("..") || data.defaultBranch.startsWith("/") || data.defaultBranch.endsWith("/") || !token3(data.grant?.accessToken) || !(data.grant?.refreshToken === null || token3(data.grant?.refreshToken))) throw new Error();
    const accessExpiresAt = optionalTime(data.accessExpiresAt);
    const refreshExpiresAt = optionalTime(data.refreshExpiresAt);
    if (accessExpiresAt === null !== (data.grant.refreshToken === null) || refreshExpiresAt === null !== (data.grant.refreshToken === null) || typeof data.custodyExpiresAt !== "string" || !Number.isFinite(Date.parse(data.custodyExpiresAt)) || Date.parse(data.custodyExpiresAt) <= Date.now() || refreshExpiresAt !== null && Date.parse(refreshExpiresAt) <= Date.parse(accessExpiresAt)) throw new Error();
    return {
      version: data.version,
      installationId: data.installationId,
      repositoryId: data.repositoryId,
      repositoryFullName: data.repositoryFullName,
      defaultBranch: data.defaultBranch,
      accessToken: data.grant.accessToken,
      refreshToken: data.grant.refreshToken,
      accessExpiresAt,
      refreshExpiresAt,
      custodyExpiresAt: data.custodyExpiresAt
    };
  } catch {
    throw new Error("GitHub OAuth custody unavailable.");
  }
}
async function resolveWebsiteGitHubRepositoryGrant(input) {
  const connection = assertConnection(input.connection);
  if (!await input.isCurrentOwner()) throw new Error("GitHub repository access is unavailable.");
  const custody = await readWebsiteGitHubOAuthCustody({ client: input.client, connection, isCurrentOwner: input.isCurrentOwner });
  const now = (input.now ?? Date.now)();
  if (!Number.isFinite(now) || !await input.isCurrentOwner()) throw new Error("GitHub repository access is unavailable.");
  if (custody.accessExpiresAt === null || Date.parse(custody.accessExpiresAt) > now + 12e4) {
    return {
      accessToken: custody.accessToken,
      repositoryFullName: custody.repositoryFullName,
      defaultBranch: custody.defaultBranch
    };
  }
  if (!custody.refreshToken || !custody.refreshExpiresAt || Date.parse(custody.refreshExpiresAt) <= now + 12e4) {
    throw new Error("GitHub repository access is unavailable.");
  }
  try {
    const grant = await refreshGitHubAppUserGrant({
      clientId: input.clientId,
      clientSecret: input.clientSecret,
      refreshToken: custody.refreshToken,
      fetcher: input.fetcher,
      now: () => now
    });
    const expiries = githubGrantExpiries(grant);
    if (!grant.refreshToken || !expiries.accessExpiresAt || !expiries.refreshExpiresAt || !await input.isCurrentOwner()) throw new Error();
    const observed = await verifyGitHubInstallationRepository({
      userToken: grant.accessToken,
      installationId: custody.installationId,
      repositoryId: custody.repositoryId,
      fetcher: input.fetcher
    });
    if (!await input.isCurrentOwner() || observed.accountId !== connection.accountId || observed.repositoryId !== connection.targetId || observed.repositoryFullName !== custody.repositoryFullName || observed.defaultBranch !== custody.defaultBranch) throw new Error();
    const operationId = crypto.randomUUID();
    if (!uuid9.test(operationId)) throw new Error();
    const base = {
      p_connection_id: connection.id,
      p_project_id: connection.projectId,
      p_owner_id: connection.ownerId,
      p_expected_connection_version: connection.version,
      p_expected_version: custody.version,
      p_operation_id: operationId
    };
    const expected = custody.version + 1;
    const args = {
      ...base,
      p_access_token: grant.accessToken,
      p_refresh_token: grant.refreshToken,
      p_access_expires_at: expiries.accessExpiresAt,
      p_refresh_expires_at: expiries.refreshExpiresAt,
      p_custody_expires_at: expiries.custodyExpiresAt
    };
    const result = await input.client.rpc("website_refresh_github_oauth_custody", args);
    if (result.error || result.data !== expected) {
      const reconcile = await input.client.rpc("website_reconcile_github_oauth_refresh", base);
      if (reconcile.error || reconcile.data !== expected) throw new Error();
    }
    if (!await input.isCurrentOwner()) throw new Error();
    return {
      accessToken: grant.accessToken,
      repositoryFullName: custody.repositoryFullName,
      defaultBranch: custody.defaultBranch
    };
  } catch {
    throw new Error("GitHub repository access is unavailable.");
  }
}

// server/website-vercel-github-target.ts
var numeric3 = /^[1-9][0-9]{0,19}$/;
function createWebsiteVercelGithubTargetLoader(input) {
  return async (scope) => {
    try {
      if (!await scope.isCurrentOwner()) return null;
      const connections = await readWebsiteInfrastructureConnections({
        client: input.ownerClient,
        ownerId: scope.ownerId,
        projectId: scope.projectId,
        isCurrent: () => true
      });
      if (!await scope.isCurrentOwner()) return null;
      const candidates = connections.filter((connection) => connection.provider === "github" && connection.environment === "preview" && ["connected", "ready"].includes(connection.status) && connection.targetId && numeric3.test(connection.targetId) && numeric3.test(connection.accountId) && connection.permissions.length === 1 && connection.permissions[0] === "contents:write");
      if (candidates.length !== 1) return null;
      const candidate = candidates[0];
      const exact = await createWebsiteOwnedSourceReader(input.serviceClient).readConnection(candidate.id, scope.projectId, scope.ownerId);
      if (!exact || exact.provider !== "github" || exact.environment !== "preview" || exact.status !== candidate.status || exact.version !== candidate.version || exact.accountId !== candidate.accountId || exact.targetId !== candidate.targetId || exact.operationId !== null || exact.permissions.length !== 1 || exact.permissions[0] !== "contents:write" || !exact.verifiedAt || !await scope.isCurrentOwner()) return null;
      const verified = await resolveWebsiteGitHubRepositoryGrant({
        client: input.serviceClient,
        connection: exact,
        clientId: input.githubClientId,
        clientSecret: input.githubClientSecret,
        isCurrentOwner: scope.isCurrentOwner,
        fetcher: input.fetcher
      });
      if (!await scope.isCurrentOwner()) return null;
      const parts = verified.repositoryFullName.split("/");
      if (parts.length !== 2) return null;
      return {
        repositoryId: exact.targetId,
        repositoryOwner: parts[0],
        repositoryName: parts[1],
        productionBranch: verified.defaultBranch
      };
    } catch {
      return null;
    }
  };
}

// server/website-vercel-connection-edge.ts
var provider2 = /^[A-Za-z0-9_-]{3,128}$/;
var slug = /^[a-z0-9][a-z0-9-]{1,99}$/;
var githubClient = /^[A-Za-z0-9_]{5,100}$/;
var publicSecret = /^(?:NEXT_PUBLIC_|VITE_|PUBLIC_).*?(?:SECRET|SERVICE_ROLE|PRIVATE_KEY)/i;
var keys = {
  url: "SUPABASE_URL",
  secret: "SUPABASE_SERVICE_ROLE_KEY",
  integrationSlug: "WEBSITE_VERCEL_INTEGRATION_SLUG",
  clientId: "WEBSITE_VERCEL_CLIENT_ID",
  clientSecret: "WEBSITE_VERCEL_CLIENT_SECRET",
  callback: "WEBSITE_VERCEL_CALLBACK_URL",
  returnUrl: "WEBSITE_VERCEL_RETURN_URL",
  platformAccount: "TAYAR_PLATFORM_VERCEL_ACCOUNT_ID",
  githubClient: "WEBSITE_GITHUB_APP_CLIENT_ID",
  githubSecret: "WEBSITE_GITHUB_APP_CLIENT_SECRET"
};
var fixedHeaders = {
  "cache-control": "no-store",
  "referrer-policy": "no-referrer",
  "content-security-policy": "default-src 'none'",
  "x-content-type-options": "nosniff"
};
function required(environment, key, max) {
  const value = environment[key];
  if (typeof value !== "string" || !value || value.length > max || value.trim() !== value || value.includes(String.fromCharCode(0))) throw new Error();
  return value;
}
function optional(environment, key, max) {
  const value = environment[key] ?? "";
  if (typeof value !== "string" || value.length > max || value.trim() !== value || value.includes(String.fromCharCode(0))) throw new Error();
  return value;
}
function platformUrl(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== value || url.pathname !== "/" || url.port || url.username || url.password || url.search || url.hash || !/^[a-z0-9]{20}[.]supabase[.]co$/.test(url.hostname)) throw new Error();
  return url.origin;
}
function callbackUrl2(value, platformOrigin) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.origin !== platformOrigin || url.username || url.password || url.hash || url.search !== "?action=callback" || !url.pathname.endsWith("/functions/v1/website-vercel-connection")) throw new Error();
  return url.toString();
}
function browserReturn(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.username || url.password || url.hash || url.search) throw new Error();
  return { value: url.toString(), origin: url.origin };
}
function legacyServiceRole(value) {
  try {
    const parts = value.split(".");
    if (parts.length !== 3 || parts.some((part) => !part)) return false;
    const base = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const payload = JSON.parse(atob(base.padEnd(Math.ceil(base.length / 4) * 4, "=")));
    return !!payload && typeof payload === "object" && payload.role === "service_role";
  } catch {
    return false;
  }
}
function serviceKey(value) {
  if (/[\s\r\n]/.test(value) || value.length > 4096 || !/^sb_secret_[A-Za-z0-9_-]{20,}$/.test(value) && !legacyServiceRole(value)) throw new Error();
  return value;
}
function json2(status, error) {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { ...fixedHeaders, "content-type": "application/json" }
  });
}
function createWebsiteVercelConnectionEdge(input) {
  try {
    if (input.fetcher !== void 0 && typeof input.fetcher !== "function") throw new Error();
    for (const [key, value] of Object.entries(input.environment)) if (value && publicSecret.test(key)) throw new Error();
    const url = platformUrl(required(input.environment, keys.url, 2048));
    const secret2 = serviceKey(required(input.environment, keys.secret, 4096));
    const callback = callbackUrl2(required(input.environment, keys.callback, 2048), url);
    const destination = browserReturn(required(input.environment, keys.returnUrl, 2048));
    const integrationSlug = optional(input.environment, keys.integrationSlug, 100);
    const clientId = optional(input.environment, keys.clientId, 128);
    const clientSecret = optional(input.environment, keys.clientSecret, 4096);
    const platformAccountId = optional(input.environment, keys.platformAccount, 128);
    const githubClientId = optional(input.environment, keys.githubClient, 100);
    const githubClientSecret = optional(input.environment, keys.githubSecret, 4096);
    if (integrationSlug && !slug.test(integrationSlug) || clientId && !provider2.test(clientId) || clientSecret && (clientSecret.length < 20 || /[\r\n]/.test(clientSecret)) || platformAccountId && !provider2.test(platformAccountId) || githubClientId && !githubClient.test(githubClientId) || githubClientSecret && (githubClientSecret.length < 20 || /[\r\n]/.test(githubClientSecret))) throw new Error();
    const factory = input.clientFactory ?? createClient2;
    const options = {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
      ...input.fetcher ? { global: { fetch: input.fetcher } } : {}
    };
    const platform = factory(url, secret2, options);
    return async (request) => {
      const origin = request.headers.get("origin");
      const headers = new Headers(fixedHeaders);
      headers.set("vary", "Origin");
      if (origin && origin !== destination.origin) return json2(403, "Origin not allowed.");
      if (origin) headers.set("access-control-allow-origin", origin);
      headers.set("access-control-allow-methods", "POST, GET, OPTIONS");
      headers.set("access-control-allow-headers", "authorization, apikey, content-type, x-client-info");
      if (request.method === "OPTIONS") return new Response(null, { status: 204, headers });
      try {
        const response = await handleWebsiteVercelConnection(request, {
          platform,
          integrationSlug,
          clientId,
          clientSecret,
          callback,
          returnUrl: destination.value,
          platformAccountId,
          loadGithubTarget: async (scope) => {
            const authorization = request.headers.get("authorization") ?? "";
            const ownerClient = factory(url, secret2, {
              ...options,
              global: { ...options.global ?? {}, headers: { Authorization: authorization } }
            });
            return createWebsiteVercelGithubTargetLoader({
              ownerClient,
              serviceClient: platform,
              githubClientId,
              githubClientSecret,
              fetcher: input.fetcher
            })(scope);
          },
          fetcher: input.fetcher
        });
        const combined = new Headers(response.headers);
        headers.forEach((value, key) => combined.set(key, value));
        return new Response(response.body, { status: response.status, headers: combined });
      } catch {
        return json2(503, "Vercel connection is unavailable.");
      }
    };
  } catch {
    throw new Error("Vercel connection deployment unavailable.");
  }
}
function createWebsiteVercelConnectionDeployment(input) {
  try {
    return createWebsiteVercelConnectionEdge(input);
  } catch {
    return async () => json2(503, "Vercel connection is unavailable.");
  }
}
export {
  createWebsiteVercelConnectionDeployment,
  createWebsiteVercelConnectionEdge
};
Deno.serve(createWebsiteVercelConnectionDeployment({environment:{"SUPABASE_URL":Deno.env.get("SUPABASE_URL"),"SUPABASE_SERVICE_ROLE_KEY":Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),"WEBSITE_VERCEL_INTEGRATION_SLUG":Deno.env.get("WEBSITE_VERCEL_INTEGRATION_SLUG"),"WEBSITE_VERCEL_CLIENT_ID":Deno.env.get("WEBSITE_VERCEL_CLIENT_ID"),"WEBSITE_VERCEL_CLIENT_SECRET":Deno.env.get("WEBSITE_VERCEL_CLIENT_SECRET"),"WEBSITE_VERCEL_CALLBACK_URL":Deno.env.get("WEBSITE_VERCEL_CALLBACK_URL"),"WEBSITE_VERCEL_RETURN_URL":Deno.env.get("WEBSITE_VERCEL_RETURN_URL"),"TAYAR_PLATFORM_VERCEL_ACCOUNT_ID":Deno.env.get("TAYAR_PLATFORM_VERCEL_ACCOUNT_ID"),"WEBSITE_GITHUB_APP_CLIENT_ID":Deno.env.get("WEBSITE_GITHUB_APP_CLIENT_ID"),"WEBSITE_GITHUB_APP_CLIENT_SECRET":Deno.env.get("WEBSITE_GITHUB_APP_CLIENT_SECRET")}}));
