create table if not exists public.tool_access_rules (
  tool_id text primary key,
  minimum_plan text not null default 'free' check (minimum_plan in ('free','pro','business')),
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);
alter table public.tool_access_rules enable row level security;

drop policy if exists tool_access_rules_select on public.tool_access_rules;
create policy tool_access_rules_select on public.tool_access_rules for select to authenticated using (true);
drop policy if exists tool_access_rules_admin_insert on public.tool_access_rules;
create policy tool_access_rules_admin_insert on public.tool_access_rules for insert to authenticated with check ((select public.is_admin()));
drop policy if exists tool_access_rules_admin_update on public.tool_access_rules;
create policy tool_access_rules_admin_update on public.tool_access_rules for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

grant select on public.tool_access_rules to authenticated;
grant insert, update on public.tool_access_rules to authenticated;
grant all on public.tool_access_rules to service_role;

create table if not exists public.tool_plan_limits (
  tool_id text primary key references public.tool_access_rules(tool_id) on delete cascade,
  free_limit integer,
  pro_limit integer,
  business_limit integer,
  period text not null default 'monthly' check (period in ('daily','monthly','lifetime')),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);
alter table public.tool_plan_limits enable row level security;
drop policy if exists tool_plan_limits_select on public.tool_plan_limits;
create policy tool_plan_limits_select on public.tool_plan_limits for select to authenticated using (true);
drop policy if exists tool_plan_limits_admin_insert on public.tool_plan_limits;
create policy tool_plan_limits_admin_insert on public.tool_plan_limits for insert to authenticated with check ((select public.is_admin()));
drop policy if exists tool_plan_limits_admin_update on public.tool_plan_limits;
create policy tool_plan_limits_admin_update on public.tool_plan_limits for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
grant select on public.tool_plan_limits to authenticated;
grant insert, update on public.tool_plan_limits to authenticated;
grant all on public.tool_plan_limits to service_role;

create table if not exists public.tool_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_id text not null,
  created_at timestamptz not null default now()
);
create index if not exists tool_usage_events_user_tool_created_idx on public.tool_usage_events(user_id, tool_id, created_at desc);
alter table public.tool_usage_events enable row level security;
drop policy if exists tool_usage_events_select_own on public.tool_usage_events;
create policy tool_usage_events_select_own on public.tool_usage_events for select to authenticated using ((select auth.uid()) = user_id or (select public.is_admin()));
revoke all on public.tool_usage_events from anon;
grant select on public.tool_usage_events to authenticated;
grant all on public.tool_usage_events to service_role;

insert into public.tool_access_rules (tool_id, minimum_plan, enabled, updated_at)
values
('cv-builder','free',true,now()),('cover-letter','free',true,now()),('ai-writer','free',true,now()),('translator','free',true,now()),('document-ai','pro',true,now()),('study-assistant','free',true,now()),('pdf-tools','free',true,now()),('email-writer','free',true,now()),('contract-writer','pro',true,now()),('analytics-ai','pro',true,now()),('code-assistant','pro',true,now()),('website-builder','free',true,now()),('team-workspace','business',true,now()),('invoice-generator','free',true,now()),('image-tools','free',true,now()),('csv-cleaner','free',true,now()),('templates-hub','free',true,now()),('name-generator','free',true,now()),('letter-generator','free',true,now()),('prompt-library','free',true,now()),('batch-image-tools','free',true,now()),('image-cropper','free',true,now()),('background-remover','free',true,now()),('image-to-pdf','free',true,now())
on conflict (tool_id) do nothing;

insert into public.tool_plan_limits(tool_id, free_limit, pro_limit, business_limit, period, updated_at)
select r.tool_id, case when r.minimum_plan='free' then 25 else 0 end, case when r.minimum_plan in ('free','pro') then 250 else 0 end, 1000, 'monthly', now()
from public.tool_access_rules r on conflict (tool_id) do nothing;

create or replace function public.tool_access_state(p_tool_id text)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_id text:=trim(coalesce(p_tool_id,'')); v_req text:='free'; v_enabled boolean:=true; v_plan text:='free'; v_allowed boolean:=false;
begin
 if v_uid is null then raise exception 'Authentication required'; end if;
 if v_id='' then raise exception 'Tool id is required'; end if;
 select r.minimum_plan,r.enabled into v_req,v_enabled from public.tool_access_rules r where r.tool_id=v_id;
 v_req:=coalesce(v_req,'free'); v_enabled:=coalesce(v_enabled,true); v_plan:=public.team_effective_plan(v_uid);
 v_allowed:=v_enabled and (v_req='free' or (v_req='pro' and v_plan in ('pro','business')) or (v_req='business' and v_plan='business'));
 return jsonb_build_object('tool_id',v_id,'enabled',v_enabled,'required_plan',v_req,'effective_plan',v_plan,'allowed',v_allowed);
end; $$;
revoke all on function public.tool_access_state(text) from public,anon;
grant execute on function public.tool_access_state(text) to authenticated,service_role;

create or replace function public.check_tool_usage(p_tool_id text)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_id text:=trim(coalesce(p_tool_id,'')); v_access jsonb; v_plan text; v_limit integer; v_period text; v_start timestamptz; v_used bigint:=0; v_ai boolean:=false;
begin
 if v_uid is null then raise exception 'Authentication required'; end if;
 if v_id='' then raise exception 'Tool id is required'; end if;
 v_access:=public.tool_access_state(v_id);
 if coalesce((v_access->>'allowed')::boolean,false)=false then return v_access||jsonb_build_object('usage_allowed',false,'reason','plan_or_tool_access'); end if;
 v_plan:=coalesce(v_access->>'effective_plan','free');
 select l.period,case v_plan when 'business' then l.business_limit when 'pro' then l.pro_limit else l.free_limit end into v_period,v_limit from public.tool_plan_limits l where l.tool_id=v_id;
 if not found or v_limit is null then return v_access||jsonb_build_object('usage_allowed',true,'limit',null,'used',null,'remaining',null,'period',coalesce(v_period,'monthly')); end if;
 if v_period='daily' then v_start:=date_trunc('day',now()); elsif v_period='monthly' then v_start:=date_trunc('month',now()); else v_start:=to_timestamp(0); end if;
 v_ai:=v_id in ('cv-builder','cover-letter','ai-writer','document-ai','study-assistant','translator','ai-chat','website-builder','code-assistant','image-tools');
 if v_ai then select count(*) into v_used from public.ai_usage u where u.user_id=v_uid and u.tool=v_id and u.status='success' and u.created_at>=v_start;
 else select count(*) into v_used from public.tool_usage_events e where e.user_id=v_uid and e.tool_id=v_id and e.created_at>=v_start; end if;
 return v_access||jsonb_build_object('usage_allowed',v_used<v_limit,'limit',v_limit,'used',v_used,'remaining',greatest(v_limit-v_used,0),'period',v_period,'reason',case when v_used>=v_limit then 'quota_exhausted' else null end);
end; $$;
revoke all on function public.check_tool_usage(text) from public,anon;
grant execute on function public.check_tool_usage(text) to authenticated,service_role;
